apiVersion: v1
kind: Namespace
metadata:
  name: vcp
  labels:
    name: vcp
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: vcp
  labels:
    app: core
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: core
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core
  namespace: vcp
  labels:
    app: core
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core
  template:
    metadata:
      labels:
        app: core
    spec:
      serviceAccountName: vcp-service-account
      containers:
        - name: core
          image: core
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
          env:
            - name: CORE_API_PORT
              value: "8080"
            - name: CORE_API_HOST
              value: "0.0.0.0"
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: testpass
            - name: DB_NAME
              value: vcp
            - name: DB_ADMIN_USER
              value: postgres
            - name: DB_ADMIN_PASSWORD
              value: testpass
            - name: RUN_MIGRATION_ON_START
              value: "true"
            - name: VCP_DB_RETRY_MAX
              value: "10"
            - name: VCP_DB_RETRY_DELAY_MS
              value: "250"
            - name: TEMPORAL_ADDRESS
              value: "local-temporal-frontend.default.svc.cluster.local:7233"
            - name: TEMPORAL_NAMESPACE
              value: "default"
            - name: ENV
              value: "local"
            - name: LOCAL_REGION
              value: "australia-southeast1"
            - name: SETUP_NW_HEARTBEAT_TIMEOUT_SEC
              value: "300"
            - name: VSA_NODE_PASSWORD
              value: <vsa_node_password_here>
            - name: VSA_NODE_USERNAME
              value: <vsa_node_username_here>
            - name: ERROR_FILE_PATH
              value: "/app/errors.json"
            - name: TEMPORAL_HOST_PORT
              value: local-temporal-frontend.default.svc.cluster.local:7233
            - name: REGION_NUMBER_MAP
              value: '{"africa-south1":"01","asia-east1":"02","asia-east2":"03","asia-northeast1":"04","asia-northeast2":"05","asia-northeast3":"06","asia-south1":"07","asia-south2":"08","asia-southeast1":"09","asia-southeast2":"10","australia-southeast1":"11","australia-southeast2":"12","europe-central2":"13","europe-north1":"14","europe-north2":"15","europe-southwest1":"16","europe-west1":"17","europe-west10":"18","europe-west12":"19","europe-west2":"20","europe-west3":"21","europe-west4":"22","europe-west6":"23","europe-west8":"24","europe-west9":"25","me-central1":"26","me-central2":"27","me-west1":"28","northamerica-northeast1":"29","northamerica-northeast2":"30","northamerica-south1":"31","southamerica-east1":"32","southamerica-west1":"33","us-central1":"34","us-east1":"35","us-east4":"36","us-east5":"37","us-south1":"38","us-west1":"39","us-west2":"40","us-west3":"41","us-west4":"42"}'
            - name: ENABLE_BACKGROUND_TASKS
              value: "true"
            - name: ONTAP_VERSION_DETAILS
              value: "9.17.1P2"
            - name: REQUIRED_TAKEOVER_REASONS
              value: "disabled,Storage failover mailbox disks are in a degraded state,Local node has encountered errors while reading the storage failover partner's mailbox disks,Storage failover interconnect error,Partner node halted after disabling takeover,Mailbox disks are not healthy,Local node missing partner disks,Default"
            - name: JOB_POLLING_MAX_DURATION
              value: "25"
            - name: JOB_POLLING_INTERVAL
              value: "3"
          resources:
            limits:
              cpu: "1"
              memory: "1Gi"
            requests:
              cpu: "100m"
              memory: "128Mi"
      imagePullSecrets:
        - name: ghcr-secret
