apiVersion: v1
kind: Namespace
metadata:
  name: vcp
  labels:
    name: vcp
---
apiVersion: v1
kind: Service
metadata:
  name: google-proxy-service
  namespace: vcp
  labels:
    app: google-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: google-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-proxy
  namespace: vcp
  labels:
    app: google-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-proxy
  template:
    metadata:
      labels:
        app: google-proxy
    spec:
      serviceAccountName: vcp-service-account
      containers:
        - name: google-proxy
          image: google-proxy
          imagePullPolicy: IfNotPresent
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: testpass
            - name: DB_NAME
              value: vcp
            - name: DB_ADMIN_USER
              value: postgres
            - name: DB_ADMIN_PASSWORD
              value: testpass
            - name: RUN_MIGRATION_ON_START
              value: "true"
            - name: VCP_DB_RETRY_MAX
              value: "10"
            - name: VCP_DB_RETRY_DELAY_MS
              value: "250"
            - name: TEMPORAL_ADDRESS
              value: "local-temporal-frontend.default.svc.cluster.local:7233"
            - name: TEMPORAL_NAMESPACE
              value: "default"
            - name: ENV
              value: "local"
            - name: LOCAL_REGION
              value: "australia-southeast1"
            - name: SETUP_NW_HEARTBEAT_TIMEOUT_SEC
              value: "300"
            - name: VSA_NODE_PASSWORD
              value: <vsa_node_password_here>
            - name: VSA_NODE_USERNAME
              value: <vsa_node_username_here>
            - name: ERROR_FILE_PATH
              value: "/app/errors.json"
            - name: METRICS_DB_CLEANUP_ENABLED
              value: "false"
            - name: FILES_PROTOCOL_SUPPORT
              value: "false"
            - name: FILE_PROTOCOL_ALLOWLISTED_ACCOUNTS
              value: ""
            - name: IS_ALL_SQUASH_ENABLED
              value: "true"
            - name: NUMBER_OF_HA_PAIRS_LARGE_CAPACITY
              value: "6"
            - name: MIN_CONSTITUENT_VOLUME_SIZE_BYTES
              value: "107374182400"