---
# Google Proxy NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: google-proxy-nodeport
  namespace: vcp
  labels:
    app: google-proxy
    service-type: nodeport
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30900
      name: http
  selector:
    app: google-proxy
---
# Local Temporal Web NodePort Service
apiVersion: v1
kind: Service
metadata:
  name: local-temporal-web-nodeport
  namespace: default
  labels:
    app: temporal-web
    service-type: nodeport
spec:
  type: NodePort
  ports:
    - port: 8080
      targetPort: 8080
      nodePort: 30808
      name: http
  selector:
    app.kubernetes.io/name: temporal
    app.kubernetes.io/component: web

---
# postgres NodePort Service
apiVersion: v1
kind: Service
metadata:
    name: postgres-nodeport
    namespace: default
    labels:
        app: postgres
        service-type: nodeport
spec:
    type: NodePort
    ports:
        - port: 5432
          targetPort: 5432
          nodePort: 30901
          name: postgres
    selector:
        app: postgres

