apiVersion: v1
kind: Service
metadata:
  name: ontap-proxy-service
  namespace: vcp
  labels:
    app: ontap-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: ontap-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontap-proxy
  namespace: vcp
  labels:
    app: ontap-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ontap-proxy
  template:
    metadata:
      labels:
        app: ontap-proxy
    spec:
      serviceAccountName: vcp-service-account
      containers:
        - name: ontap-proxy
          image: ontap-proxy
          ports:
            - containerPort: 8080
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
          env:
            - name: ONTAP_API_ADDRESS
              value: "35.221.37.74"
            - name: ONTAP_API_USERNAME
              value: "admin"
            - name: ONTAP_API_PASSWORD
              value: "waltham1!"
            - name: ONTAP_API_PORT
              value: "443"
            - name: ENV
              value: "local"
          resources:
            limits:
              cpu: 500m
              memory: 256Mi
            requests:
              cpu: 100m
              memory: 128Mi 