apiVersion: v1
kind: Namespace
metadata:
  name: vcp
  labels:
    name: vcp
---
apiVersion: v1
kind: Service
metadata:
  name: metrics-processer-service
  namespace: vcp
  labels:
    app: metrics-processer
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: metrics-processer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: metrics-processer
  namespace: vcp
  labels:
    app: metrics-processer
spec:
  replicas: 1
  selector:
    matchLabels:
      app: metrics-processer
  template:
    metadata:
      labels:
        app: metrics-processer
    spec:
      containers:
        - name: metrics-processer
          image: telemetry
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: ENV
              value: local
            - name: GCP_PROXY_PORT
              value: "8090"
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: "testpass"
            - name: DB_NAME
              value: vcp
            - name: DB_SSL_MODE
              value: disable
            - name: DB_TIMEZONE
              value: UTC
            - name: DB_MAX_OPEN_CONNS
              value: "25"
            - name: DB_MAX_IDLE_CONNS
              value: "25"
            - name: DB_CONN_MAX_LIFETIME
              value: 1h
            - name: MIGRATION_PATH
              value: migrations/core
            - name: DB_ADMIN_USER
              value: postgres
            - name: DB_ADMIN_PASSWORD
              value: "testpass"
            - name: RUN_MIGRATION_ON_START
              value: "true"
            - name: GCE_METADATA_HOST
              value: 35.189.45.145:9090
            - name: ROOT_URL
              value: "https://servicecontrol.googleapis.com"
            - name: OPERATION_BATCH_SIZE
              value: "200"
            - name: PUSHER_SERVICE_NAME
              value: "autopush-netapp.sandbox.googleapis.com"
            - name: PUSHER_SERVICE_PROJECT
              value: "netapp-au-se1-autopush-sde-tst"
            - name: LOCAL_REGION
              value: "us-west2"

