apiVersion: v1
kind: Namespace
metadata:
  name: vcp
  labels:
    name: vcp
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: vcp-worker
  namespace: vcp
  labels:
    app: vcp-worker
spec:
  replicas: 1
  selector:
    matchLabels:
      app: vcp-worker
  template:
    metadata:
      labels:
        app: vcp-worker
    spec:
      containers:
        - name: vcp-worker
          image: vcp-worker
          imagePullPolicy: Never
          ports:
            - containerPort: 8080
              name: http
          env:
            - name: TEMPORAL_ADDRESS
              value: local-temporal-frontend.default.svc.cluster.local:7233
            - name: ENV
              value: local
            - name: GCP_PROXY_PORT
              value: "8090"
            - name: DB_TYPE
              value: postgres
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: DB_PORT
              value: "5432"
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: "testpass"
            - name: DB_NAME
              value: vcp
            - name: DB_SSL_MODE
              value: disable
            - name: DB_TIMEZONE
              value: UTC
            - name: DB_MAX_OPEN_CONNS
              value: "25"
            - name: DB_MAX_IDLE_CONNS
              value: "25"
            - name: DB_CONN_MAX_LIFETIME
              value: 1h
            - name: MIGRATION_PATH
              value: migrations/core
            - name: DB_ADMIN_USER
              value: postgres
            - name: DB_ADMIN_PASSWORD
              value: "testpass"
            - name: RUN_MIGRATION_ON_START
              value: "true"
            - name: GCE_METADATA_HOST
              value: "{{ .ENV.GCE_METADATA_HOST }}"
            - name: GCP_CONSUMER_MGMT_ENDPOINT_URL
              value: autopush-netapp.sandbox.googleapis.com
            - name: GCP_SERVICE_NETWORKING_ENDPOINT_URL
              value: netapp-tst-autopush-endpoint.appspot.com
            - name: LOCAL_REGION
              value: australia-southeast1
            - name: VSA_NODE_PASSWORD
              value: <vsa_node_password_here>
            - name: VSA_NODE_USERNAME
              value: admin
            - name: OBJECT_STORE_PROVIDER
              value: "googlecloud"
            - name: OBJECT_STORES_SERVER
              value: "storage.googleapis.com"
            - name: OBJECT_STORE_AUTH_TYPE
              value: "GCP_SA"
            - name: GCP_HYDRATE_ENABLED
              value: "true"
            - name: GCP_HYDRATE_BATCH_SIZE
              value: "10"
            - name: VMRS_CONFIG_PATH
              value: "/app/vmrs_gcp.yaml"
            - name: VLM_CONFIG_FILE_PATH
              value: "/app/vlm-config.json"
            - name: ERROR_FILE_PATH
              value: "/app/errors.json"
            - name: VSA_LIFECYCLE_MANAGER_QUEUE_PREFIX
              value: "vsa-lifecycle-manager"
            - name: ONTAP_VERSION
              value: "9.18.1"
            - name: TOTAL_IP_PER_HA_PAIR
              value: "6"
            - name: DATA_SUBNET_CIDR_BLOCK
              value: "28"
            - name: ENFORCE_MIN_SP_CONFIG
              value: "true"
            - name: HARVEST_TEMPLATE_PATH
              value: "/app/harvest-template.yaml"
            - name: MAX_NODES_PER_GROUP
              value: "200"
            - name: LEASE_NAMESPACE
              value: "vcp"
            - name: HARVEST_HOST
              value: "harvest-farm-service.vcp.svc.cluster.local:3000"
            - name: ENABLE_METRICS
              value: "false"
            - name: HARVEST_REST_PROTOCOL
              value: "http"
            - name: FIREWALL_SOURCE_RANGES
              value: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,34.0.0.0/8,46.149.16.0/20,52.94.203.152/29,52.94.203.160/29,185.35.244.0/22,202.3.112.0/20,216.240.16.0/20,217.70.208.0/20,198.18.0.0/15"
            - name: CERTIFICATE_LIFETIME
              value: "25920000s"  # 300 days
            - name: CA_NAME
              value: "20250718-pn6-boa"
            - name: CA_POOL_NAME
              value: "vsa-pool-ca"
            - name: CA_POOL_DEPLOYED_PROJECT_ID
              value: "266893635349"
            - name: SECRET_MANAGER_PROJECT_ID
              value: "266893635349"
            - name: VSA_DEPLOYED_DNS_NAME
              value: "au-se1.vsa"
            - name: VSA_MANAGED_ZONE
              value: "au-se1-vsa"
            - name: VSA_SECRET_CACHE_CLEANUP_INTERVAL_HOURS
              value: "24"
            - name: VSA_SECRET_AUTH_CACHE_EXPIRATION_HOURS
              value: "24"
            - name: CLOUD_DNS_CACHE_TTL
              value: "300"
            - name: METRICS_PORT
              value: "9090"

---
apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harvest-farm-lease-create
  namespace: vcp
rules:
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "list", "watch", "create", "update", "patch", "delete" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harvest-farm-lease-create-binding
  namespace: vcp
subjects:
  - kind: ServiceAccount
    name: default
    namespace: vcp
roleRef:
  kind: Role
  name: harvest-farm-lease-create
  apiGroup: rbac.authorization.k8s.io
---