// Code generated by go-swagger; DO NOT EDIT.

package quota_rules

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp/models"
)

// V1betaDescribeQuotaRuleReader is a Reader for the V1betaDescribeQuotaRule structure.
type V1betaDescribeQuotaRuleReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1betaDescribeQuotaRuleReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1betaDescribeQuotaRuleOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1betaDescribeQuotaRuleBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewV1betaDescribeQuotaRuleUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV1betaDescribeQuotaRuleForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1betaDescribeQuotaRuleNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV1betaDescribeQuotaRuleUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewV1betaDescribeQuotaRuleTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV1betaDescribeQuotaRuleInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewV1betaDescribeQuotaRuleDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV1betaDescribeQuotaRuleOK creates a V1betaDescribeQuotaRuleOK with default headers values
func NewV1betaDescribeQuotaRuleOK() *V1betaDescribeQuotaRuleOK {
	return &V1betaDescribeQuotaRuleOK{}
}

/*
V1betaDescribeQuotaRuleOK handles this case with default header values.

OK
*/
type V1betaDescribeQuotaRuleOK struct {
	Payload *models.QuotaRulesV1beta
}

func (o *V1betaDescribeQuotaRuleOK) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1betaDescribeQuotaRuleOK  %+v", 200, o.Payload)
}

func (o *V1betaDescribeQuotaRuleOK) GetPayload() *models.QuotaRulesV1beta {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.QuotaRulesV1beta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaDescribeQuotaRuleBadRequest creates a V1betaDescribeQuotaRuleBadRequest with default headers values
func NewV1betaDescribeQuotaRuleBadRequest() *V1betaDescribeQuotaRuleBadRequest {
	return &V1betaDescribeQuotaRuleBadRequest{}
}

/*
V1betaDescribeQuotaRuleBadRequest handles this case with default header values.

Bad request
*/
type V1betaDescribeQuotaRuleBadRequest struct {
	Payload *models.Error
}

func (o *V1betaDescribeQuotaRuleBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1betaDescribeQuotaRuleBadRequest  %+v", 400, o.Payload)
}

func (o *V1betaDescribeQuotaRuleBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaDescribeQuotaRuleUnauthorized creates a V1betaDescribeQuotaRuleUnauthorized with default headers values
func NewV1betaDescribeQuotaRuleUnauthorized() *V1betaDescribeQuotaRuleUnauthorized {
	return &V1betaDescribeQuotaRuleUnauthorized{}
}

/*
V1betaDescribeQuotaRuleUnauthorized handles this case with default header values.

Unauthorized
*/
type V1betaDescribeQuotaRuleUnauthorized struct {
	Payload *models.Error
}

func (o *V1betaDescribeQuotaRuleUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1betaDescribeQuotaRuleUnauthorized  %+v", 401, o.Payload)
}

func (o *V1betaDescribeQuotaRuleUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaDescribeQuotaRuleForbidden creates a V1betaDescribeQuotaRuleForbidden with default headers values
func NewV1betaDescribeQuotaRuleForbidden() *V1betaDescribeQuotaRuleForbidden {
	return &V1betaDescribeQuotaRuleForbidden{}
}

/*
V1betaDescribeQuotaRuleForbidden handles this case with default header values.

Forbidden
*/
type V1betaDescribeQuotaRuleForbidden struct {
	Payload *models.Error
}

func (o *V1betaDescribeQuotaRuleForbidden) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1betaDescribeQuotaRuleForbidden  %+v", 403, o.Payload)
}

func (o *V1betaDescribeQuotaRuleForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaDescribeQuotaRuleNotFound creates a V1betaDescribeQuotaRuleNotFound with default headers values
func NewV1betaDescribeQuotaRuleNotFound() *V1betaDescribeQuotaRuleNotFound {
	return &V1betaDescribeQuotaRuleNotFound{}
}

/*
V1betaDescribeQuotaRuleNotFound handles this case with default header values.

Not found
*/
type V1betaDescribeQuotaRuleNotFound struct {
	Payload *models.Error
}

func (o *V1betaDescribeQuotaRuleNotFound) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1betaDescribeQuotaRuleNotFound  %+v", 404, o.Payload)
}

func (o *V1betaDescribeQuotaRuleNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaDescribeQuotaRuleUnprocessableEntity creates a V1betaDescribeQuotaRuleUnprocessableEntity with default headers values
func NewV1betaDescribeQuotaRuleUnprocessableEntity() *V1betaDescribeQuotaRuleUnprocessableEntity {
	return &V1betaDescribeQuotaRuleUnprocessableEntity{}
}

/*
V1betaDescribeQuotaRuleUnprocessableEntity handles this case with default header values.

Unprocessable entity
*/
type V1betaDescribeQuotaRuleUnprocessableEntity struct {
	Payload *models.Error
}

func (o *V1betaDescribeQuotaRuleUnprocessableEntity) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1betaDescribeQuotaRuleUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *V1betaDescribeQuotaRuleUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaDescribeQuotaRuleTooManyRequests creates a V1betaDescribeQuotaRuleTooManyRequests with default headers values
func NewV1betaDescribeQuotaRuleTooManyRequests() *V1betaDescribeQuotaRuleTooManyRequests {
	return &V1betaDescribeQuotaRuleTooManyRequests{}
}

/*
V1betaDescribeQuotaRuleTooManyRequests handles this case with default header values.

Too many requests
*/
type V1betaDescribeQuotaRuleTooManyRequests struct {
	Payload *models.Error
}

func (o *V1betaDescribeQuotaRuleTooManyRequests) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1betaDescribeQuotaRuleTooManyRequests  %+v", 429, o.Payload)
}

func (o *V1betaDescribeQuotaRuleTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaDescribeQuotaRuleInternalServerError creates a V1betaDescribeQuotaRuleInternalServerError with default headers values
func NewV1betaDescribeQuotaRuleInternalServerError() *V1betaDescribeQuotaRuleInternalServerError {
	return &V1betaDescribeQuotaRuleInternalServerError{}
}

/*
V1betaDescribeQuotaRuleInternalServerError handles this case with default header values.

Internal server error
*/
type V1betaDescribeQuotaRuleInternalServerError struct {
	Payload *models.Error
}

func (o *V1betaDescribeQuotaRuleInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1betaDescribeQuotaRuleInternalServerError  %+v", 500, o.Payload)
}

func (o *V1betaDescribeQuotaRuleInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaDescribeQuotaRuleDefault creates a V1betaDescribeQuotaRuleDefault with default headers values
func NewV1betaDescribeQuotaRuleDefault(code int) *V1betaDescribeQuotaRuleDefault {
	return &V1betaDescribeQuotaRuleDefault{
		_statusCode: code,
	}
}

/*
V1betaDescribeQuotaRuleDefault handles this case with default header values.

Unexpected error
*/
type V1betaDescribeQuotaRuleDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the v1beta describe quota rule default response
func (o *V1betaDescribeQuotaRuleDefault) Code() int {
	return o._statusCode
}

func (o *V1betaDescribeQuotaRuleDefault) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/quotaRules/{quotaRuleId}][%d] v1beta_describeQuotaRule default  %+v", o._statusCode, o.Payload)
}

func (o *V1betaDescribeQuotaRuleDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaDescribeQuotaRuleDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
