ARG BASE
FROM $BASE

COPY app/oci-proxy /app
COPY common/vsa_config /common/vsa_config

# Copy Air config for live reload
COPY oci-proxy/air.toml /app/air.toml

ENV GOTRACEBACK=all
ENTRYPOINT ["air", "-c", "/app/air.toml"]

# Set ownership and permissions
# USER nonroot:nonroot
