apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  labels:
    app: harvest-pvc
  name: harvest-pvc
  namespace: {{ $.Values.global.namespace }}
spec:
  storageClassName: "standard"
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 25Gi

