{{- if and (eq .Values.mode "deployment") (.Values.configMap.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontap-opentelemetry-collector.fullname" . }}
  labels:
    {{- include "ontap-opentelemetry-collector.labels" . | nindent 4 }}
data:
  relay: |
    exporters:
        debug:
            verbosity: normal
        googlecloud:
            project: {{ .Values.otel.project }}
            metric:
                prefix: custom.googleapis.com
                skip_create_descriptor: true
            sending_queue:
                enabled: false
                queue_size: 40000
    extensions:
        health_check:
            endpoint: "0.0.0.0:13133"
    processors:
        batch:
            send_batch_size: 200
            send_batch_max_size: 200
            timeout: 200ms
        memory_limiter:
            check_interval: 5s
            limit_percentage: 80
            spike_limit_percentage: 30
        resourcedetection:
            detectors: [gcp]
            timeout: 10s
        filter/cv:
          metrics:
            include:
              match_type: strict
              metric_names:
                - aggr_disk_busy
                - aggr_disk_max_busy
                - aggr_disk_max_total_data
                - aggr_disk_max_total_transfers
                - aggr_disk_max_user_read_chain
                - aggr_disk_max_user_write_chain
                - aggr_inode_files_total
                - aggr_inode_files_used
                - aggr_inode_inodefile_private_capacity
                - aggr_inode_inodefile_public_capacity
                - aggr_inode_used_percent
                - aggr_labels
                - aggr_logical_used_wo_snapshots
                - aggr_logical_used_wo_snapshots_flexclones
                - aggr_new_status
                - aggr_object_store_logical_used
                - aggr_object_store_physical_used
                - aggr_physical_used_wo_snapshots
                - aggr_physical_used_wo_snapshots_flexclones
                - aggr_raid_disk_count
                - aggr_snapshot_files_total
                - aggr_snapshot_files_used
                - aggr_snapshot_inode_used_percent
                - aggr_snapshot_maxfiles_available
                - aggr_snapshot_maxfiles_possible
                - aggr_snapshot_maxfiles_used
                - aggr_snapshot_reserve_percent
                - aggr_snapshot_size_available
                - aggr_snapshot_size_used
                - aggr_snapshot_used_percent
                - aggr_space_available
                - aggr_space_capacity_tier_used
                - aggr_space_data_compaction_saved
                - aggr_space_performance_tier_inactive_user_data
                - aggr_space_physical_used
                - aggr_space_physical_used_percent
                - aggr_space_sis_saved
                - aggr_space_total
                - aggr_space_used
                - aggr_space_used_percent
                - aggr_total_logical_used
                - aggr_volume_count
                - bucket_bytes
                - cluster_new_status
                - cluster_software_update
                - cluster_subsystem_suppressed_alerts
                - disk_bytes_per_sector
                - disk_labels
                - disk_sectors
                - ems_events
                - environment_sensor_max_fan_speed
                - environment_sensor_max_temperature
                - environment_sensor_power
                - environment_sensor_threshold_value
                - fcp_nvmf_read_data
                - fcp_nvmf_write_data
                - fcp_read_data
                - fcp_util_percent
                - fcp_write_data
                - health_disk_alerts
                - health_ems_alerts
                - health_ha_alerts
                - health_license_alerts
                - health_lif_alerts
                - health_network_ethernet_port_alerts
                - health_network_fc_port_alerts
                - health_node_alerts
                - health_shelf_alerts
                - health_support_alerts
                - health_volume_move_alerts
                - health_volume_ransomware_alerts
                - hostadapter_bytes_read
                - hostadapter_bytes_written
                - lif_labels
                - lun_avg_read_latency
                - lun_avg_write_latency
                - lun_labels
                - lun_read_align_histo
                - lun_read_data
                - lun_read_ops
                - lun_remote_ops
                - lun_size_used_percent
                - lun_write_align_histo
                - lun_write_data
                - lun_write_ops
                - metadata_collector_api_time
                - metadata_collector_calc_time
                - metadata_collector_instances
                - metadata_collector_metrics
                - metadata_collector_parse_time
                - metadata_collector_poll_time
                - metadata_component_count
                - metadata_component_status
                - metadata_exporter_count
                - metadata_exporter_time
                - metadata_target_ping
                - metadata_target_status
                - nic_rx_bytes
                - nic_tx_bytes
                - nic_util_percent
                - node_avg_processor_busy
                - node_cifs_connections
                - node_cifs_established_sessions
                - node_cifs_latency
                - node_cifs_op_count
                - node_cifs_open_files
                - node_cifs_ops
                - node_cifs_signed_sessions
                - node_cpu_busy
                - node_cpu_busytime
                - node_cpu_domain_busy
                - node_disk_busy
                - node_disk_data_read
                - node_disk_data_written
                - node_disk_max_busy
                - node_fcp_ops
                - node_iscsi_ops
                - node_labels
                - node_new_status
                - node_nfs_latency
                - node_nfs_ops
                - node_nfs_read_avg_latency
                - node_nfs_read_ops
                - node_nfs_read_throughput
                - node_nfs_throughput
                - node_nfs_total_ops
                - node_nfs_write_avg_latency
                - node_nfs_write_ops
                - node_nfs_write_throughput
                - node_nvmf_ops
                - node_total_data
                - node_total_ops
                - node_uptime
                - node_vol_write_latency
                - node_volume_avg_latency
                - node_volume_other_latency
                - node_volume_other_ops
                - node_volume_read_data
                - node_volume_read_latency
                - node_volume_read_ops
                - node_volume_total_data
                - node_volume_total_ops
                - node_volume_write_data
                - node_volume_write_latency
                - node_volume_write_ops
                - ontap_cluster_flexgroup_volume_count_usage
                - ontap_cluster_svm_count_usage
                - poller_cpu_percent
                - poller_memory
                - poller_memory_percent
                - poller_status
                - qos_detail_resource_latency
                - raid_disk_busy
                - raid_disk_total_transfers
                - raid_disk_user_read_latency
                - raid_disk_user_write_latency
                - security_certificate_expiry_time
                - security_certificate_labels
                - shelf_labels
                - shelf_max_fan_speed
                - shelf_max_temperature
                - shelf_power
                - snapmirror_labels
                - snapshot_policy_total_schedules
                - storagegrid_private_load_balancer_storage_request_count
                - storagegrid_private_load_balancer_storage_rx_bytes
                - storagegrid_private_load_balancer_storage_tx_bytes
                - svm_labels
                - svm_vol_avg_latency
                - svm_vol_other_latency
                - svm_vol_other_ops
                - svm_vol_read_data
                - svm_vol_read_latency
                - svm_vol_read_ops
                - svm_vol_total_ops
                - svm_vol_write_data
                - svm_vol_write_latency
                - svm_vol_write_ops
                - volume_aggr_labels
                - volume_avg_latency
                - volume_labels
                - volume_other_latency
                - volume_other_ops
                - volume_read_data
                - volume_read_latency
                - volume_read_ops
                - volume_sis_compress_saved
                - volume_sis_compress_saved_percent
                - volume_sis_dedup_saved
                - volume_sis_dedup_saved_percent
                - volume_sis_total_saved
                - volume_size
                - volume_size_available
                - volume_size_total
                - volume_size_used
                - volume_size_used_percent
                - volume_snapshot_count
                - volume_snapshot_reserve_available
                - volume_snapshot_reserve_percent
                - volume_snapshot_reserve_size
                - volume_snapshot_reserve_used
                - volume_snapshot_reserve_used_percent
                - volume_snapshots_size_available
                - volume_snapshots_size_used
                - volume_space_logical_used
                - volume_space_logical_used_by_afs
                - volume_space_logical_used_by_snapshots
                - volume_space_logical_used_percent
                - volume_space_physical_used
                - volume_space_physical_used_percent
                - volume_total_data
                - volume_total_ops
                - volume_write_data
                - volume_write_latency
                - volume_write_ops
                - wafl_cp_count
                - wafl_cp_phase_times
                - wafl_read_io_type
    receivers:
        prometheus:
            config:
                scrape_configs:
                - job_name: "otel-scrape-job"
                  scrape_interval: 300s
                  http_sd_configs:
                  - url: http://localhost:3000/pollers/prometheus-targets
                    refresh_interval: 30s
    service:
        extensions:
            - health_check
        pipelines:
            metrics:
                receivers: [prometheus]
                processors: [filter/cv, resourcedetection]
{{/*                exporters: [googlecloud, debug]*/}}
                exporters: [debug]
{{- end }}
