apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vcp-worker.configMapName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    app: {{ .Values.app.name }}
data:
  TEMPORAL_ADDRESS: {{ .Values.workerConfig.temporalAddress | quote }}
  ENV: {{ .Values.workerConfig.env | quote }}
  GCP_PROXY_PORT: {{ .Values.workerConfig.gcpProxyPort | quote }}
  DB_TYPE: {{ .Values.workerConfig.database.type | quote }}
  DB_HOST: {{ .Values.workerConfig.database.host | quote }}
  DB_PORT: {{ .Values.workerConfig.database.port | quote }}
  DB_USER: {{ .Values.workerConfig.database.user | quote }}
  DB_NAME: {{ .Values.workerConfig.database.dbname | quote }}
  DB_ADMIN_USER: {{ .Values.workerConfig.database.adminUser | quote }}
  DB_SSL_MODE: {{ .Values.workerConfig.database.sslMode | quote }}
  DB_TIMEZONE: {{ .Values.workerConfig.database.timezone | quote }}
  DB_MAX_OPEN_CONNS: {{ .Values.workerConfig.database.maxConns | quote }}
  DB_MAX_IDLE_CONNS: {{ .Values.workerConfig.database.maxIdleConns | quote }}
  DB_CONN_MAX_LIFETIME: {{ .Values.workerConfig.database.maxConnLifetime | quote }}
  RUN_MIGRATION_ON_START: {{ .Values.workerConfig.database.runMigrationOnStart | quote }}
  GCE_METADATA_HOST: {{ .Values.workerConfig.gceMetadataHost | quote }}
  GCP_CONSUMER_MGMT_ENDPOINT_URL: {{ .Values.workerConfig.gcpConsumerMgmtEndpointUrl | quote }}
  GCP_SERVICE_NETWORKING_ENDPOINT_URL: {{ .Values.workerConfig.gcpServiceNetworkingEndpointUrl | quote }}
  LOCAL_REGION: {{ .Values.workerConfig.localRegion | quote }}
  VSA_NODE_USERNAME: {{ .Values.workerConfig.vsaNodeUsername | quote }}
  GCP_HYDRATE_AUTH_SERVICE_ACCOUNT: {{ .Values.workerConfig.gcpServiceNetworkingEndpointUrl | quote }}
  GCP_HYDRATE_BASE_URL: {{ .Values.workerConfig.gcpHydrateBaseUrl | quote }}
  PROXY_CLIENT_TRANSPORT_SCHEMA: {{ .Values.workerConfig.proxyClientTransportSchema | quote }}
  VCP_PAIRED_REGIONS: {{ .Values.workerConfig.vcpPairedRegions | quote }}
  GCP_AUTH_SERVICE_ACCOUNT: {{ .Values.workerConfig.gcpAuthServiceAccount | quote }}
  GCP_SERVICE_URL: {{ .Values.workerConfig.gcpServiceUrl | quote }}
  LOGGER_LEVEL: {{ .Values.workerConfig.loggerLevel | quote }}
  SMC_GCP_PROJECT_ID: {{ .Values.workerConfig.smcProjectId | quote }}
  GCP_SMC_SECRET_NAME: {{ .Values.workerConfig.gcpSmcSecretName | quote }}
  GCP_SMC_SECRET_VERSION_NAME: {{ .Values.workerConfig.gcpSmcSecretVersionName | quote }}
  VMRS_CONFIG_PATH: {{ .Values.workerConfig.vmrsConfigPath | quote }}
  GCP_HYDRATE_ENABLED: {{ .Values.workerConfig.gcpHydrateEnabled | quote }}
  GCP_HYDRATE_BATCH_SIZE: {{ .Values.workerConfig.gcpHydrateBatchSize | quote }}
  VSA_NODE_PASSWORD: {{ .Values.workerConfig.vsaNodePassword | quote }}
  CERTIFICATE_LIFETIME: {{ .Values.workerConfig.certificateLifetime | quote }}
  CA_POOL_NAME: {{ .Values.workerConfig.caPoolName | quote }}
  CA_NAME: {{ .Values.workerConfig.caName | quote }}
  CA_POOL_DEPLOYED_PROJECT_ID: {{ .Values.workerConfig.caPoolDeployedProjectId | quote }}
  SECRET_MANAGER_PROJECT_ID: {{ .Values.workerConfig.secretManagerProjectId | quote }}
  VSA_DEPLOYED_DNS_NAME: {{ .Values.workerConfig.vsaDeployedDnsName | quote }}
  VSA_SECRET_CACHE_CLEANUP_INTERVAL_HOURS: {{ .Values.workerConfig.vsaSecretCacheCleanupIntervalHours | quote }}
  VSA_SECRET_AUTH_CACHE_EXPIRATION_HOURS: {{ .Values.workerConfig.vsaSecretAuthCacheExpirationHours | quote }}
  TOTAL_IP_PER_HA_PAIR: {{ .Values.workerConfig.totalIpPerHaPair | quote }}
  DATA_SUBNET_CIDR_BLOCK: {{ .Values.workerConfig.dataSubnetCidrBlock | quote }}
  VSA_MANAGED_ZONE: {{ .Values.workerConfig.vsaManagedZone | quote }}
  CLOUD_DNS_CACHE_TTL: {{ .Values.workerConfig.cloudDnsCacheTtl | quote }}
  VSA_LIFECYCLE_MANAGER_QUEUE_PREFIX: {{ .Values.workerConfig.vsaLifecycleManagerQueuePrefix | quote }}
  ONTAP_VERSION: {{ .Values.workerConfig.ontapVersion | quote }}
  ENFORCE_MIN_SP_CONFIG: {{ .Values.workerConfig.enforceMinSpConfig | quote }}
  MAX_NODES_PER_GROUP: {{ .Values.workerConfig.maxNodesPerGroup | quote }}
  SERVICE_CONTROL_URL: {{ .Values.workerConfig.serviceControlUrl | quote }}
  SERVICE_NAME: {{ .Values.workerConfig.serviceName | quote }}
  DATACENTER: {{ .Values.workerConfig.datacenter | quote }}
  HARVEST_PORT_START: {{ .Values.workerConfig.harvestPortStart | quote }}
  HARVEST_PORT_END: {{ .Values.workerConfig.harvestPortEnd | quote }}
  LEASE_NAMESPACE: {{.Values.workerConfig.leaseNameSpace | quote}}
  HARVEST_HOST: {{.Values.workerConfig.harvestHost | quote}}
  ENABLE_METRICS: {{.Values.workerConfig.enableMetrics | quote}}
  HARVEST_REST_PROTOCOL: {{.Values.workerConfig.harvestRestProtocol | quote}}
  FIREWALL_SOURCE_RANGES: {{ .Values.workerConfig.firewallSourceRanges | quote }}
  CVP_HOST: {{ .Values.workerConfig.cvpHost | quote }}
  WORKFLOW_GLOBAL_TIMEOUT_MINUTES: {{ .Values.workerConfig.workflowGlobalTimeoutMinutes | quote }}
  FILES_PROTOCOL_SUPPORT: {{ .Values.workerConfig.filesProtocolSupport | quote }}
  FILE_PROTOCOL_ALLOWLISTED_ACCOUNTS: {{ .Values.workerConfig.fileProtocolAllowlistedAccounts | quote }}
  VSA_IMAGE_NAME: {{ .Values.workerConfig.vsaImageName | quote }}
  VSA_FILES_IMAGE_NAME: {{ .Values.workerConfig.vsaFilesImageName | quote }}
