{{- range .Values.app }}
  {{- $name := .name }}
  {{- $replicas := .replicas }}
  {{- $workerAdditionalConfig := .workerAdditionalConfig }}
  {{- range $ver := $.Values.versionsSupported }}
    {{ $versionName := $.Chart.Version -}}
    {{ if not $.Values.workerConfig.nkdevTest -}}
      {{ $versionName = $ver.name -}}
    {{ end -}}
    {{ $version := ($versionName | lower | replace "." "-") -}}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ $name }}-{{ $version }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ $name }}-{{ $version }}
spec:
  replicas: {{ $replicas }}
  selector:
    matchLabels:
      app: {{ $name }}-{{ $version }}
  template:
    metadata:
      labels:
        app: {{ $name }}-{{ $version }}
    spec:
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      {{- if $.Values.global.cloudSqlIamAuthEnabled }}
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      {{- end }}
      {{- if and $.Values.podAffinity.enabled (eq $.Values.global.environment "gcp") }}
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: {{ $name }}-{{ $version }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              app: {{ $name }}-{{ $version }}
      {{- end }}
      containers:
        - name: {{ $name }}
          {{- if $.Values.images.vcpWorker.secondary }}
          image: "{{- include "containerImage" (list $ (dict "name" "vcpWorker" "secondary" true "version" $versionName "sha" $ver.sha )) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list $ (dict "name" "vcpWorker" "secondary" false "version" $versionName "sha" $ver.sha )) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ $.Values.images.vcpWorker.pullPolicy }}
          resources:
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
          envFrom:
            - configMapRef:
                name: {{ include "vcp-worker.configMapName" (printf "%s-%s" $name $version) }}
            - secretRef:
                name: {{ include "vcp-worker.secretName" $name }}
{{- include "worker.databaseProxyContainer" $ | nindent 8 }}
---
  {{- end }}
{{- end }}
