apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      containers:
        - name: {{ .Values.app.name }}
          {{- if .Values.images.vcpWorker.secondary }}
          image: "{{- include "containerImage" (list . (dict "name" "vcpWorker" "secondary" true)) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list . (dict "name" "vcpWorker" "secondary" false)) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.images.vcpWorker.pullPolicy }}
          envFrom:
            - configMapRef:
                name: {{ include "vcp-worker.configMapName" . }}
            - secretRef:
                name: {{ include "vcp-worker.secretName" . }}
