{{- range .Values.app }}
apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .name }}
  namespace: {{ $.Release.Namespace }}
  labels:
    app: {{ .name }}
spec:
  replicas: {{ .replicas }}
  selector:
    matchLabels:
      app: {{ .name }}
  template:
    metadata:
      labels:
        app: {{ .name }}
    spec:
      serviceAccountName: {{ $.Values.serviceAccount.name }}
      containers:
        - name: {{ .name }}
          {{- if $.Values.images.vcpWorker.secondary }}
          image: "{{- include "containerImage" (list $ (dict "name" "vcpWorker" "secondary" true)) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list $ (dict "name" "vcpWorker" "secondary" false)) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ $.Values.images.vcpWorker.pullPolicy }}
          resources:
            limits:
              cpu: {{ $.Values.resources.limits.cpu }}
              memory: {{ $.Values.resources.limits.memory }}
            requests:
              cpu: {{ $.Values.resources.requests.cpu }}
              memory: {{ $.Values.resources.requests.memory }}
          envFrom:
            - configMapRef:
                name: {{ include "vcp-worker.configMapName" .name }}
            - secretRef:
                name: {{ include "vcp-worker.secretName" .name }}
---
{{- end }}