apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vcp-worker.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
data:
  DB_PASSWORD: {{ .Values.workerConfig.database.password | b64enc | quote }}
  DB_ADMIN_PASSWORD: {{ .Values.workerConfig.database.adminPassword | b64enc | quote }}
  VSA_NODE_PASSWORD: {{ .Values.workerConfig.vsaNodePassword | b64enc | quote }}
