apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- range $key, $value := .Values.serviceAccount.annotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.imagePullSecrets }}
  {{- if . }}
  - name: {{ .name | quote }}
  {{- end}}
  {{- end }}
{{- end }}

