apiVersion: v1
kind: Service
metadata:
  name: {{ .Values.app.name }}-service
  namespace: vcp
  labels:
    app: {{ .Values.app.name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: metrics
      port: {{ .Values.workerConfig.metricsPort }}
      targetPort: {{ .Values.workerConfig.metricsPort }}
  selector:
    app: {{ .Values.app.name }}
