apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- include "google_proxy.kubernetes.annotations" . | nindent 4 }}
    {{- include "google_proxy.helmchart.annotations" . | nindent 4 }}
  labels:
    {{- include "google_proxy.kubernetes.labels" . | nindent 4 }}
    {{- include "google_proxy.helmchart.labels" . | nindent 4 }}
{{- if or ( .Values.global.primaryImageRegistryPasswordAuth ) ( .Values.global.secondaryImageRegistryPasswordAuth ) }}
imagePullSecrets:
  {{- if .Values.global.primaryImageRegistryPasswordAuth }}
  - name: {{ .Values.chartPrimaryImageRegistry | default .Values.global.primaryImageRegistry }}
  {{- end }}
  {{- if .Values.global.secondaryImageRegistryPasswordAuth }}
  - name: {{ .Values.chartSecondaryImageRegistry | default .Values.global.secondaryImageRegistry }}
  {{- end }}
{{- end }}

