{{- if .Values.enabled }}
{{- if not .Values.externalSecretManager }}
{{- $currentAdcSecretDict := (lookup "v1" "Secret" .Release.Namespace "adc-secret") | default dict }}
{{- $currentAdcSecretData := (get $currentAdcSecretDict "data") | default dict }}
{{- $currentAdcSecretForGCP := (get $currentAdcSecretData "google-com-chain.pem") | default "" }}
{{- $newAdcSecretForGCP := .Values.secret.googlecomchain | default "" }}
apiVersion: v1
kind: Secret
metadata:
  name: adc-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "adc.kubernetes.annotations" . | nindent 4 }}
    {{- include "adc.helmchart.annotations" . | nindent 4 }}
    {{- include "adc.netapp.annotations" . | nindent 4 }}
    {{- include "adc.secretAnnotations" . | nindent 4 }}
    {{- include "adc.commonAnnotations" . | nindent 4 }}
  labels:
    {{- include "adc.kubernetes.labels" . | nindent 4 }}
    {{- include "adc.helmchart.labels" . | nindent 4 }}
    {{- include "adc.secretLabels" . | nindent 4 }}
    {{- include "adc.commonLabels" . | nindent 4 }}
data:
    {{- if ne $newAdcSecretForGCP "" }}
      google-com-chain.pem: {{ $newAdcSecretForGCP }}
    {{- else }}
      google-com-chain.pem: {{ $currentAdcSecretForGCP }}
    {{- end }}
{{- end }}
{{- end }}