{{- if .Values.enabled }}
apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-5"
  {{- include "adc.kubernetes.annotations" . | nindent 4 }}
  {{- include "adc.helmchart.annotations" . | nindent 4 }}
  labels:
  {{- include "adc.kubernetes.labels" . | nindent 4 }}
  {{- include "adc.helmchart.labels" . | nindent 4 }}
{{- if or ( .Values.global.primaryImageRegistryPasswordAuth ) ( .Values.global.secondaryImageRegistryPasswordAuth ) }}
imagePullSecrets:
  {{- if .Values.global.primaryImageRegistryPasswordAuth }}
  - name: {{ .Values.global.chartPrimaryImageRegistry | default .Values.global.primaryImagePullSecretName }}
  {{- end }}
  {{- if .Values.global.secondaryImageRegistryPasswordAuth }}
  - name: {{ .Values.global.chartSecondaryImageRegistry | default .Values.global.secondaryImageRegistry }}
  {{- end }}
{{- end }}
{{- end }}