{{- if .Values.enabled }}
{{- if and ( .Values.externalSecretManager ) ( eq .Values.global.hyperscaler "gcp" ) }}
apiVersion: {{ .Values.secretManager.apiVersion | quote }}
kind: ExternalSecret
metadata:
  name: adc-secret
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- include "adc.kubernetes.annotations" . | nindent 4 }}
    {{- include "adc.helmchart.annotations" . | nindent 4 }}
    {{- include "adc.netapp.annotations" . | nindent 4 }}
    {{- include "adc.secretAnnotations" . | nindent 4 }}
    {{- include "adc.commonAnnotations" . | nindent 4 }}
  labels:
    {{- include "adc.kubernetes.labels" . | nindent 4 }}
    {{- include "adc.helmchart.labels" . | nindent 4 }}
    {{- include "adc.secretLabels" . | nindent 4 }}
    {{- include "adc.commonLabels" . | nindent 4 }}
spec:
  refreshInterval: {{ .Values.secretManager.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ .Values.secretManager.clusterSecretStoreName }}
  target:
    name: adc-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
  - secretKey: google-com-chain.pem
    remoteRef:
      key: {{ .Values.secretManager.googleComChain }}
{{- end }}
{{- end }}

