// Code generated by go-swagger; DO NOT EDIT.

package object_store

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/ontap-rest/models"
)

// XcS3BucketCollectionGetReader is a Reader for the XcS3BucketCollectionGet structure.
type XcS3BucketCollectionGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *XcS3BucketCollectionGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewXcS3BucketCollectionGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewXcS3BucketCollectionGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewXcS3BucketCollectionGetOK creates a XcS3BucketCollectionGetOK with default headers values
func NewXcS3BucketCollectionGetOK() *XcS3BucketCollectionGetOK {
	return &XcS3BucketCollectionGetOK{}
}

/*
XcS3BucketCollectionGetOK describes a response with status code 200, with default header values.

OK
*/
type XcS3BucketCollectionGetOK struct {
	Payload *models.XcS3BucketResponse
}

// IsSuccess returns true when this xc s3 bucket collection get o k response has a 2xx status code
func (o *XcS3BucketCollectionGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this xc s3 bucket collection get o k response has a 3xx status code
func (o *XcS3BucketCollectionGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this xc s3 bucket collection get o k response has a 4xx status code
func (o *XcS3BucketCollectionGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this xc s3 bucket collection get o k response has a 5xx status code
func (o *XcS3BucketCollectionGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this xc s3 bucket collection get o k response a status code equal to that given
func (o *XcS3BucketCollectionGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the xc s3 bucket collection get o k response
func (o *XcS3BucketCollectionGetOK) Code() int {
	return 200
}

func (o *XcS3BucketCollectionGetOK) Error() string {
	return fmt.Sprintf("[GET /svm/peers/{peer.uuid}/protocols/s3/services/{svm.uuid}/buckets][%d] xcS3BucketCollectionGetOK  %+v", 200, o.Payload)
}

func (o *XcS3BucketCollectionGetOK) String() string {
	return fmt.Sprintf("[GET /svm/peers/{peer.uuid}/protocols/s3/services/{svm.uuid}/buckets][%d] xcS3BucketCollectionGetOK  %+v", 200, o.Payload)
}

func (o *XcS3BucketCollectionGetOK) GetPayload() *models.XcS3BucketResponse {
	return o.Payload
}

func (o *XcS3BucketCollectionGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.XcS3BucketResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewXcS3BucketCollectionGetDefault creates a XcS3BucketCollectionGetDefault with default headers values
func NewXcS3BucketCollectionGetDefault(code int) *XcS3BucketCollectionGetDefault {
	return &XcS3BucketCollectionGetDefault{
		_statusCode: code,
	}
}

/*
XcS3BucketCollectionGetDefault describes a response with status code -1, with default header values.

Error
*/
type XcS3BucketCollectionGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this xc s3 bucket collection get default response has a 2xx status code
func (o *XcS3BucketCollectionGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this xc s3 bucket collection get default response has a 3xx status code
func (o *XcS3BucketCollectionGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this xc s3 bucket collection get default response has a 4xx status code
func (o *XcS3BucketCollectionGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this xc s3 bucket collection get default response has a 5xx status code
func (o *XcS3BucketCollectionGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this xc s3 bucket collection get default response a status code equal to that given
func (o *XcS3BucketCollectionGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the xc s3 bucket collection get default response
func (o *XcS3BucketCollectionGetDefault) Code() int {
	return o._statusCode
}

func (o *XcS3BucketCollectionGetDefault) Error() string {
	return fmt.Sprintf("[GET /svm/peers/{peer.uuid}/protocols/s3/services/{svm.uuid}/buckets][%d] xc_s3_bucket_collection_get default  %+v", o._statusCode, o.Payload)
}

func (o *XcS3BucketCollectionGetDefault) String() string {
	return fmt.Sprintf("[GET /svm/peers/{peer.uuid}/protocols/s3/services/{svm.uuid}/buckets][%d] xc_s3_bucket_collection_get default  %+v", o._statusCode, o.Payload)
}

func (o *XcS3BucketCollectionGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *XcS3BucketCollectionGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
