// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/ontap-rest/models"
)

// IkpKmsCreateReader is a Reader for the IkpKmsCreate structure.
type IkpKmsCreateReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *IkpKmsCreateReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 201:
		result := NewIkpKmsCreateCreated()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 202:
		result := NewIkpKmsCreateAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewIkpKmsCreateDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewIkpKmsCreateCreated creates a IkpKmsCreateCreated with default headers values
func NewIkpKmsCreateCreated() *IkpKmsCreateCreated {
	return &IkpKmsCreateCreated{}
}

/*
IkpKmsCreateCreated describes a response with status code 201, with default header values.

Created
*/
type IkpKmsCreateCreated struct {

	/* Useful for tracking the resource location
	 */
	Location string

	Payload *models.IkpKmsResponse
}

// IsSuccess returns true when this ikp kms create created response has a 2xx status code
func (o *IkpKmsCreateCreated) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ikp kms create created response has a 3xx status code
func (o *IkpKmsCreateCreated) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ikp kms create created response has a 4xx status code
func (o *IkpKmsCreateCreated) IsClientError() bool {
	return false
}

// IsServerError returns true when this ikp kms create created response has a 5xx status code
func (o *IkpKmsCreateCreated) IsServerError() bool {
	return false
}

// IsCode returns true when this ikp kms create created response a status code equal to that given
func (o *IkpKmsCreateCreated) IsCode(code int) bool {
	return code == 201
}

// Code gets the status code for the ikp kms create created response
func (o *IkpKmsCreateCreated) Code() int {
	return 201
}

func (o *IkpKmsCreateCreated) Error() string {
	return fmt.Sprintf("[POST /security/ikp-kms][%d] ikpKmsCreateCreated  %+v", 201, o.Payload)
}

func (o *IkpKmsCreateCreated) String() string {
	return fmt.Sprintf("[POST /security/ikp-kms][%d] ikpKmsCreateCreated  %+v", 201, o.Payload)
}

func (o *IkpKmsCreateCreated) GetPayload() *models.IkpKmsResponse {
	return o.Payload
}

func (o *IkpKmsCreateCreated) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		o.Location = hdrLocation
	}

	o.Payload = new(models.IkpKmsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIkpKmsCreateAccepted creates a IkpKmsCreateAccepted with default headers values
func NewIkpKmsCreateAccepted() *IkpKmsCreateAccepted {
	return &IkpKmsCreateAccepted{}
}

/*
IkpKmsCreateAccepted describes a response with status code 202, with default header values.

Accepted
*/
type IkpKmsCreateAccepted struct {

	/* Useful for tracking the resource location
	 */
	Location string

	Payload *models.IkpKmsJobLinkResponse
}

// IsSuccess returns true when this ikp kms create accepted response has a 2xx status code
func (o *IkpKmsCreateAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this ikp kms create accepted response has a 3xx status code
func (o *IkpKmsCreateAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this ikp kms create accepted response has a 4xx status code
func (o *IkpKmsCreateAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this ikp kms create accepted response has a 5xx status code
func (o *IkpKmsCreateAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this ikp kms create accepted response a status code equal to that given
func (o *IkpKmsCreateAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the ikp kms create accepted response
func (o *IkpKmsCreateAccepted) Code() int {
	return 202
}

func (o *IkpKmsCreateAccepted) Error() string {
	return fmt.Sprintf("[POST /security/ikp-kms][%d] ikpKmsCreateAccepted  %+v", 202, o.Payload)
}

func (o *IkpKmsCreateAccepted) String() string {
	return fmt.Sprintf("[POST /security/ikp-kms][%d] ikpKmsCreateAccepted  %+v", 202, o.Payload)
}

func (o *IkpKmsCreateAccepted) GetPayload() *models.IkpKmsJobLinkResponse {
	return o.Payload
}

func (o *IkpKmsCreateAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// hydrates response header Location
	hdrLocation := response.GetHeader("Location")

	if hdrLocation != "" {
		o.Location = hdrLocation
	}

	o.Payload = new(models.IkpKmsJobLinkResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewIkpKmsCreateDefault creates a IkpKmsCreateDefault with default headers values
func NewIkpKmsCreateDefault(code int) *IkpKmsCreateDefault {
	return &IkpKmsCreateDefault{
		_statusCode: code,
	}
}

/*
	IkpKmsCreateDefault describes a response with status code -1, with default header values.

	ONTAP Error Response Codes

| Error Code | Description |
| ---------- | ----------- |
| 65536600 | Not all nodes are in quorum. |
| 65536601 | Internal error. Cannot determine node count. |
| 65537518 | A LIF with Cluster role was not found. |
| 65538700 | Not all nodes are running a version that supports IKPKMS. |
| 65538701 | The IBM Key Protect Key Management Service capability is not enabled. |
| 65538702 | Internal error. The secret API key was not able to be retrieved. |
| 65538703 | MCC is enabled, and is not compatible with the IBM Key Protect Key Management Service. |
| 65538707 | The secret API key was not provided. |
| 65538709 | Key-id provided was not a UUID. |
| 65538720 | An IBM Key Protect Key Management Service instance already exists on the SVM. |
| 65538723 | The IBM Key Protect Key Management Service is not supported on the Admin SVM. |
Also see the table of common errors in the <a href="#Response_body">Response body</a> overview section of this documentation.
*/
type IkpKmsCreateDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this ikp kms create default response has a 2xx status code
func (o *IkpKmsCreateDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this ikp kms create default response has a 3xx status code
func (o *IkpKmsCreateDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this ikp kms create default response has a 4xx status code
func (o *IkpKmsCreateDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this ikp kms create default response has a 5xx status code
func (o *IkpKmsCreateDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this ikp kms create default response a status code equal to that given
func (o *IkpKmsCreateDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the ikp kms create default response
func (o *IkpKmsCreateDefault) Code() int {
	return o._statusCode
}

func (o *IkpKmsCreateDefault) Error() string {
	return fmt.Sprintf("[POST /security/ikp-kms][%d] ikp_kms_create default  %+v", o._statusCode, o.Payload)
}

func (o *IkpKmsCreateDefault) String() string {
	return fmt.Sprintf("[POST /security/ikp-kms][%d] ikp_kms_create default  %+v", o._statusCode, o.Payload)
}

func (o *IkpKmsCreateDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *IkpKmsCreateDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
