// Code generated by go-swagger; DO NOT EDIT.

package security

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/ontap-rest/models"
)

// SecurityKeystoreCertificateDeleteCollectionReader is a Reader for the SecurityKeystoreCertificateDeleteCollection structure.
type SecurityKeystoreCertificateDeleteCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SecurityKeystoreCertificateDeleteCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSecurityKeystoreCertificateDeleteCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSecurityKeystoreCertificateDeleteCollectionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSecurityKeystoreCertificateDeleteCollectionOK creates a SecurityKeystoreCertificateDeleteCollectionOK with default headers values
func NewSecurityKeystoreCertificateDeleteCollectionOK() *SecurityKeystoreCertificateDeleteCollectionOK {
	return &SecurityKeystoreCertificateDeleteCollectionOK{}
}

/*
SecurityKeystoreCertificateDeleteCollectionOK describes a response with status code 200, with default header values.

OK
*/
type SecurityKeystoreCertificateDeleteCollectionOK struct {
}

// IsSuccess returns true when this security keystore certificate delete collection o k response has a 2xx status code
func (o *SecurityKeystoreCertificateDeleteCollectionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this security keystore certificate delete collection o k response has a 3xx status code
func (o *SecurityKeystoreCertificateDeleteCollectionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this security keystore certificate delete collection o k response has a 4xx status code
func (o *SecurityKeystoreCertificateDeleteCollectionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this security keystore certificate delete collection o k response has a 5xx status code
func (o *SecurityKeystoreCertificateDeleteCollectionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this security keystore certificate delete collection o k response a status code equal to that given
func (o *SecurityKeystoreCertificateDeleteCollectionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the security keystore certificate delete collection o k response
func (o *SecurityKeystoreCertificateDeleteCollectionOK) Code() int {
	return 200
}

func (o *SecurityKeystoreCertificateDeleteCollectionOK) Error() string {
	return fmt.Sprintf("[DELETE /security/keystore-certificates][%d] securityKeystoreCertificateDeleteCollectionOK ", 200)
}

func (o *SecurityKeystoreCertificateDeleteCollectionOK) String() string {
	return fmt.Sprintf("[DELETE /security/keystore-certificates][%d] securityKeystoreCertificateDeleteCollectionOK ", 200)
}

func (o *SecurityKeystoreCertificateDeleteCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewSecurityKeystoreCertificateDeleteCollectionDefault creates a SecurityKeystoreCertificateDeleteCollectionDefault with default headers values
func NewSecurityKeystoreCertificateDeleteCollectionDefault(code int) *SecurityKeystoreCertificateDeleteCollectionDefault {
	return &SecurityKeystoreCertificateDeleteCollectionDefault{
		_statusCode: code,
	}
}

/*
SecurityKeystoreCertificateDeleteCollectionDefault describes a response with status code -1, with default header values.

ONTAP Error Response Codes
*/
type SecurityKeystoreCertificateDeleteCollectionDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this security keystore certificate delete collection default response has a 2xx status code
func (o *SecurityKeystoreCertificateDeleteCollectionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this security keystore certificate delete collection default response has a 3xx status code
func (o *SecurityKeystoreCertificateDeleteCollectionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this security keystore certificate delete collection default response has a 4xx status code
func (o *SecurityKeystoreCertificateDeleteCollectionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this security keystore certificate delete collection default response has a 5xx status code
func (o *SecurityKeystoreCertificateDeleteCollectionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this security keystore certificate delete collection default response a status code equal to that given
func (o *SecurityKeystoreCertificateDeleteCollectionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the security keystore certificate delete collection default response
func (o *SecurityKeystoreCertificateDeleteCollectionDefault) Code() int {
	return o._statusCode
}

func (o *SecurityKeystoreCertificateDeleteCollectionDefault) Error() string {
	return fmt.Sprintf("[DELETE /security/keystore-certificates][%d] security_keystore_certificate_delete_collection default  %+v", o._statusCode, o.Payload)
}

func (o *SecurityKeystoreCertificateDeleteCollectionDefault) String() string {
	return fmt.Sprintf("[DELETE /security/keystore-certificates][%d] security_keystore_certificate_delete_collection default  %+v", o._statusCode, o.Payload)
}

func (o *SecurityKeystoreCertificateDeleteCollectionDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SecurityKeystoreCertificateDeleteCollectionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
SecurityKeystoreCertificateDeleteCollectionBody security keystore certificate delete collection body
swagger:model SecurityKeystoreCertificateDeleteCollectionBody
*/
type SecurityKeystoreCertificateDeleteCollectionBody struct {

	// security keystore certificate response inline records
	SecurityKeystoreCertificateResponseInlineRecords []*models.SecurityKeystoreCertificate `json:"records,omitempty"`
}

// Validate validates this security keystore certificate delete collection body
func (o *SecurityKeystoreCertificateDeleteCollectionBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSecurityKeystoreCertificateResponseInlineRecords(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SecurityKeystoreCertificateDeleteCollectionBody) validateSecurityKeystoreCertificateResponseInlineRecords(formats strfmt.Registry) error {
	if swag.IsZero(o.SecurityKeystoreCertificateResponseInlineRecords) { // not required
		return nil
	}

	for i := 0; i < len(o.SecurityKeystoreCertificateResponseInlineRecords); i++ {
		if swag.IsZero(o.SecurityKeystoreCertificateResponseInlineRecords[i]) { // not required
			continue
		}

		if o.SecurityKeystoreCertificateResponseInlineRecords[i] != nil {
			if err := o.SecurityKeystoreCertificateResponseInlineRecords[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("info" + "." + "records" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("info" + "." + "records" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this security keystore certificate delete collection body based on the context it is used
func (o *SecurityKeystoreCertificateDeleteCollectionBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSecurityKeystoreCertificateResponseInlineRecords(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *SecurityKeystoreCertificateDeleteCollectionBody) contextValidateSecurityKeystoreCertificateResponseInlineRecords(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.SecurityKeystoreCertificateResponseInlineRecords); i++ {

		if o.SecurityKeystoreCertificateResponseInlineRecords[i] != nil {
			if err := o.SecurityKeystoreCertificateResponseInlineRecords[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("info" + "." + "records" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("info" + "." + "records" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *SecurityKeystoreCertificateDeleteCollectionBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *SecurityKeystoreCertificateDeleteCollectionBody) UnmarshalBinary(b []byte) error {
	var res SecurityKeystoreCertificateDeleteCollectionBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
