with-expecter: True
tags: mocks
filename: "{{.InterfaceNameSnake}}_mock.go"
packages:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/google-proxy/api/gcp-servergen:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Handler:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/core-api/clientgen:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Invoker:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core/core-api/core-servergen:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      Handler:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core/ontap-rest:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      ClusterClient:
      NetworkingClient:
      Poller:
      RESTClient:
      SANClient:
      SecurityClient:
      StorageClient:
      SVMClient:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core/vsa:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      Provider:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/hyperscaler:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      GoogleServices:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
  github.com/vcp-vsa-control-Plane/vsa-control-plane/workflow_engine:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      ClientConfig:
      WorkflowEngine: