with-expecter: True
tags: mocks
filename: "{{.InterfaceNameSnake}}_mock.go"
packages:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/google-proxy/api/gcp-servergen:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Handler:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/core-api:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Invoker:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core/core-api/core-servergen:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      Handler:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core/ontap-rest:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      ClusterClient:
      NetworkingClient:
      Poller:
      RESTClient:
      SANClient:
      NASClient:
      SecurityClient:
      StorageClient:
      SVMClient:
      SnapmirrorClient:
      CloudClient:
      NameServicesClient:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core/vsa:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      Provider:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core/scheduler:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      Scheduler:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/hyperscaler:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
    interfaces:
      GoogleServices:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
      recursive: True
      include-regex: "ClientService"
  github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/google-proxy-client:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Invoker:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/vlm:
    config:
      dir: "{{.InterfaceDir}}"
      inpackage: True
      replace-type:
        - "go.temporal.io/sdk/internal=go.temporal.io/sdk/workflow"
    interfaces:
      VlmWorkflowClient:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/workflow_engine:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
      replace-type:
        - "go.temporal.io/sdk/internal=go.temporal.io/sdk/client"
    interfaces:
      ClientConfig:
      WorkflowEngine:
      TemporalTestClient:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/database/vcp:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Storage:
      MigratorInterface:
      DataStore:
      Transaction:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/database/metrics:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Storage:
      MigratorInterface:
      DataStore:
      Transaction:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/utils/middleware/log:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Logger:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core/orchestrator:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      OrchestratorFactory:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/telemetry/performance:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Sink:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/telemetry/processor:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      Processor:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/telemetry/bizops/sink:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      BizOpsSink:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/telemetry/bizops:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      BizOpsProvider:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/telemetry/bizops/sink/gcs:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      BucketHandle:
      StorageClient:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/telemetry/monitoring:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
    interfaces:
      MetricsRecorder: