with-expecter: True
tags: mocks
packages:
  github.com/vcp-vsa-control-Plane/vsa-control-plane/core:
    config:
      inpackage: True
      dir: "{{.InterfaceDir}}"
      filename: "monkey_mocks_test.go"
      mockname: "monkeyMock"
      include-regex: "monkeyMethods"
      recursive: True
      replace-type:
        - "go.temporal.io/sdk/internal.Client=go.temporal.io/sdk/client.Client"
        - "go.temporal.io/sdk/internal.StartWorkflowOptions=go.temporal.io/sdk/client.StartWorkflowOptions"
        - "go.temporal.io/sdk/internal.ChildWorkflowOptions=go.temporal.io/sdk/workflow.ChildWorkflowOptions"
