apiVersion: skaffold/v4beta12
kind: Config
build:
  local:
    push: false
    concurrency: 0
  tagPolicy:
    envTemplate:
      template: "{{.IMAGES_TAG}}"
  artifacts:
    - image: base
      context: .
      docker:
        dockerfile: common/Dockerfile
        buildArgs:
          noCache: true
    - image: google-proxy
      context: .
      docker:
        dockerfile: google-proxy/Dockerfile
        buildArgs:
          GHVSA_PAT: "{{.GHVSA_PAT}}"
          noCache: true
      requires:
        - image: base
          alias: BASE
    - image: ontap-proxy
      context: .
      docker:
        dockerfile: ontap-proxy/Dockerfile
        buildArgs:
          noCache: true
          GHVSA_PAT: "{{.GHVSA_PAT}}"
      requires:
        - image: base
          alias: BASE
    - image: oci-proxy
      context: .
      docker:
        dockerfile: oci-proxy/Dockerfile
        buildArgs:
          GHVSA_PAT: "{{.GHVSA_PAT}}"
          noCache: true
      requires:
        - image: base
          alias: BASE
    - image: core
      context: .
      docker:
        dockerfile: vcp-core/Dockerfile
        buildArgs:
          noCache: true
          GHVSA_PAT: "{{.GHVSA_PAT}}"
      requires:
        - image: base
          alias: BASE          
    - image: vcp-worker
      context: .
      docker:
        dockerfile: worker/Dockerfile
        buildArgs:
          GHVSA_PAT: "{{.GHVSA_PAT}}"
      requires:
        - image: base
          alias: BASE
    - image: telemetry
      context: .
      docker:
        dockerfile: telemetry/Dockerfile
        buildArgs:
          GHVSA_PAT: "{{.GHVSA_PAT}}"
      requires:
        - image: base
          alias: BASE
manifests:
  rawYaml:
    - skaffold/*
  helm:
    releases:
      - name: local-temporal
        remoteChart: temporal/temporal
        version: 1.2.0
        namespace: default
        valuesFiles:
          - ./tools/temporal-deployment/local/values.yaml
        skipTests: true
portForward:
  - resourceType: service
    resourceName: google-proxy-service
    namespace: vcp
    port: 8080
    localPort: 9000
  - resourceType: service
    resourceName: core-service
    namespace: vcp
    port: 8080
    localPort: 9001
  - resourceType: service
    resourceName: postgres
    namespace: default
    port: 5432
    localPort: 5432
  - resourceType: service
    resourceName: local-temporal-web
    namespace: default
    port: 8080
    localPort: 8080
  - resourceType: service
    resourceName: metrics-processer-service
    namespace: vcp
    port: 8080
    localPort: 9090
  - resourceType: service
    resourceName: harvest-farm-service
    namespace: vcp
    port: 3000
    localPort: 3000
  - resourceType: service
    resourceName: ontap-proxy-service
    namespace: vcp
    port: 8080
    localPort: 9003
  - resourceType: service
    resourceName: oci-proxy-service
    namespace: vcp
    port: 8080
    localPort: 9004
profiles:
  - name: gcb
    build:
      googleCloudBuild: {}
  - name: dev
    build:
      artifacts:
        - image: base
          context: .
          docker:
            dockerfile: common/Dockerfile.dev
        - image: google-proxy
          context: .
          sync:
            manual:
              - src: artifacts/google-proxy
                dest: "/app"
          docker:
            dockerfile: google-proxy/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: core
          context: .
          sync:
            manual:
              - src: artifacts/core
                dest: "/app"
          docker:
            dockerfile: vcp-core/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: vcp-worker
          context: .
          sync:
            manual:
              - src: "artifacts/vcp-worker"
                dest: "/app"
          docker:
            dockerfile: worker/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: ontap-proxy
          context: .
          sync:
            manual:
              - src: "artifacts/ontap-proxy"
                dest: "/app"
          docker:
            dockerfile: ontap-proxy/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: oci-proxy
          context: .
          sync:
            manual:
              - src: "artifacts/oci-proxy"
                dest: "/app"
          docker:
            dockerfile: oci-proxy/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: telemetry
          context: .
          sync:
            manual:
              - src: "artifacts/telemetry"
                dest: "/app/"
          docker:
            dockerfile: telemetry/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
  - name: sks
    build:
      local:
        push: true
      tagPolicy:
        dateTime: {}
      artifacts:
        - image: base
          context: .
          docker:
            dockerfile: common/Dockerfile.dev
        - image: google-proxy
          context: .
          docker:
            dockerfile: google-proxy/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: core
          context: .
          docker:
            dockerfile: vcp-core/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: vcp-worker
          context: .
          docker:
            dockerfile: worker/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: ontap-proxy
          context: .
          docker:
            dockerfile: ontap-proxy/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: oci-proxy
          context: .
          docker:
            dockerfile: oci-proxy/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
        - image: telemetry
          context: .
          docker:
            dockerfile: telemetry/Dockerfile.dev
          requires:
            - image: base
              alias: BASE
deploy:
  kubectl:
    hooks:
      before:
        - host:
            command: [ "sh", "-c", "./skaffold/scripts/before_deploy.sh" ]
      after:
        - host:
            command: [ "sh", "-c", "./skaffold/scripts/after_deploy.sh" ]