// Code generated by go-swagger; DO NOT EDIT.

package test

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewSmnextDeleteCollectionParams creates a new SmnextDeleteCollectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewSmnextDeleteCollectionParams() *SmnextDeleteCollectionParams {
	return &SmnextDeleteCollectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewSmnextDeleteCollectionParamsWithTimeout creates a new SmnextDeleteCollectionParams object
// with the ability to set a timeout on a request.
func NewSmnextDeleteCollectionParamsWithTimeout(timeout time.Duration) *SmnextDeleteCollectionParams {
	return &SmnextDeleteCollectionParams{
		timeout: timeout,
	}
}

// NewSmnextDeleteCollectionParamsWithContext creates a new SmnextDeleteCollectionParams object
// with the ability to set a context for a request.
func NewSmnextDeleteCollectionParamsWithContext(ctx context.Context) *SmnextDeleteCollectionParams {
	return &SmnextDeleteCollectionParams{
		Context: ctx,
	}
}

// NewSmnextDeleteCollectionParamsWithHTTPClient creates a new SmnextDeleteCollectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewSmnextDeleteCollectionParamsWithHTTPClient(client *http.Client) *SmnextDeleteCollectionParams {
	return &SmnextDeleteCollectionParams{
		HTTPClient: client,
	}
}

/*
SmnextDeleteCollectionParams contains all the parameters to send to the API endpoint

	for the smnext delete collection operation.

	Typically these are written to a http.Request.
*/
type SmnextDeleteCollectionParams struct {

	/* ContinueOnFailure.

	   Continue even when the operation fails on one of the records.

	   Format: boolean
	   Default: "\"False\""
	*/
	ContinueOnFailure *string

	/* Info.

	   Info specification
	*/
	Info SmnextDeleteCollectionBody

	/* ReturnRecords.

	   The default is true for GET calls.  When set to false, only the number of records is returned.

	   Format: boolean
	   Default: "\"True\""
	*/
	ReturnRecords *string

	/* ReturnTimeout.

	   The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

	   Format: integer
	   Default: "\"15\""
	*/
	ReturnTimeout *string

	/* SerialRecords.

	   Perform the operation on the records synchronously.

	   Format: boolean
	   Default: "\"False\""
	*/
	SerialRecords *string

	/* Top1.

	   Filter by top1

	   Format: string
	*/
	Top1 *string

	/* Top10.

	   Filter by top10

	   Format: string
	*/
	Top10 *string

	/* Top2.

	   Filter by top2

	   Format: number
	*/
	Top2 *string

	/* Top3.

	   Filter by top3

	   Format: string
	*/
	Top3 *string

	/* Top4.

	   Filter by top4

	   Format: string
	*/
	Top4 *string

	/* Top5.

	   Filter by top5

	   Format: boolean
	*/
	Top5 *string

	/* Top6.

	   Filter by top6

	   Format: integer
	*/
	Top6 *string

	/* Top7.

	   Filter by top7

	   Format: string
	*/
	Top7 *string

	/* Top8.

	   Filter by top8

	   Format: string
	*/
	Top8 *string

	/* Top9.

	   Filter by top9

	   Format: integer
	*/
	Top9 *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the smnext delete collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SmnextDeleteCollectionParams) WithDefaults() *SmnextDeleteCollectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the smnext delete collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *SmnextDeleteCollectionParams) SetDefaults() {
	var (
		continueOnFailureDefault = string("\"False\"")

		returnRecordsDefault = string("\"True\"")

		returnTimeoutDefault = string("\"15\"")

		serialRecordsDefault = string("\"False\"")
	)

	val := SmnextDeleteCollectionParams{
		ContinueOnFailure: &continueOnFailureDefault,
		ReturnRecords:     &returnRecordsDefault,
		ReturnTimeout:     &returnTimeoutDefault,
		SerialRecords:     &serialRecordsDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTimeout(timeout time.Duration) *SmnextDeleteCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithContext(ctx context.Context) *SmnextDeleteCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithHTTPClient(client *http.Client) *SmnextDeleteCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithContinueOnFailure adds the continueOnFailure to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithContinueOnFailure(continueOnFailure *string) *SmnextDeleteCollectionParams {
	o.SetContinueOnFailure(continueOnFailure)
	return o
}

// SetContinueOnFailure adds the continueOnFailure to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetContinueOnFailure(continueOnFailure *string) {
	o.ContinueOnFailure = continueOnFailure
}

// WithInfo adds the info to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithInfo(info SmnextDeleteCollectionBody) *SmnextDeleteCollectionParams {
	o.SetInfo(info)
	return o
}

// SetInfo adds the info to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetInfo(info SmnextDeleteCollectionBody) {
	o.Info = info
}

// WithReturnRecords adds the returnRecords to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithReturnRecords(returnRecords *string) *SmnextDeleteCollectionParams {
	o.SetReturnRecords(returnRecords)
	return o
}

// SetReturnRecords adds the returnRecords to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetReturnRecords(returnRecords *string) {
	o.ReturnRecords = returnRecords
}

// WithReturnTimeout adds the returnTimeout to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithReturnTimeout(returnTimeout *string) *SmnextDeleteCollectionParams {
	o.SetReturnTimeout(returnTimeout)
	return o
}

// SetReturnTimeout adds the returnTimeout to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetReturnTimeout(returnTimeout *string) {
	o.ReturnTimeout = returnTimeout
}

// WithSerialRecords adds the serialRecords to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithSerialRecords(serialRecords *string) *SmnextDeleteCollectionParams {
	o.SetSerialRecords(serialRecords)
	return o
}

// SetSerialRecords adds the serialRecords to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetSerialRecords(serialRecords *string) {
	o.SerialRecords = serialRecords
}

// WithTop1 adds the top1 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop1(top1 *string) *SmnextDeleteCollectionParams {
	o.SetTop1(top1)
	return o
}

// SetTop1 adds the top1 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop1(top1 *string) {
	o.Top1 = top1
}

// WithTop10 adds the top10 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop10(top10 *string) *SmnextDeleteCollectionParams {
	o.SetTop10(top10)
	return o
}

// SetTop10 adds the top10 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop10(top10 *string) {
	o.Top10 = top10
}

// WithTop2 adds the top2 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop2(top2 *string) *SmnextDeleteCollectionParams {
	o.SetTop2(top2)
	return o
}

// SetTop2 adds the top2 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop2(top2 *string) {
	o.Top2 = top2
}

// WithTop3 adds the top3 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop3(top3 *string) *SmnextDeleteCollectionParams {
	o.SetTop3(top3)
	return o
}

// SetTop3 adds the top3 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop3(top3 *string) {
	o.Top3 = top3
}

// WithTop4 adds the top4 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop4(top4 *string) *SmnextDeleteCollectionParams {
	o.SetTop4(top4)
	return o
}

// SetTop4 adds the top4 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop4(top4 *string) {
	o.Top4 = top4
}

// WithTop5 adds the top5 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop5(top5 *string) *SmnextDeleteCollectionParams {
	o.SetTop5(top5)
	return o
}

// SetTop5 adds the top5 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop5(top5 *string) {
	o.Top5 = top5
}

// WithTop6 adds the top6 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop6(top6 *string) *SmnextDeleteCollectionParams {
	o.SetTop6(top6)
	return o
}

// SetTop6 adds the top6 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop6(top6 *string) {
	o.Top6 = top6
}

// WithTop7 adds the top7 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop7(top7 *string) *SmnextDeleteCollectionParams {
	o.SetTop7(top7)
	return o
}

// SetTop7 adds the top7 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop7(top7 *string) {
	o.Top7 = top7
}

// WithTop8 adds the top8 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop8(top8 *string) *SmnextDeleteCollectionParams {
	o.SetTop8(top8)
	return o
}

// SetTop8 adds the top8 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop8(top8 *string) {
	o.Top8 = top8
}

// WithTop9 adds the top9 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) WithTop9(top9 *string) *SmnextDeleteCollectionParams {
	o.SetTop9(top9)
	return o
}

// SetTop9 adds the top9 to the smnext delete collection params
func (o *SmnextDeleteCollectionParams) SetTop9(top9 *string) {
	o.Top9 = top9
}

// WriteToRequest writes these params to a swagger request
func (o *SmnextDeleteCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ContinueOnFailure != nil {

		// query param continue_on_failure
		var qrContinueOnFailure string

		if o.ContinueOnFailure != nil {
			qrContinueOnFailure = *o.ContinueOnFailure
		}
		qContinueOnFailure := qrContinueOnFailure
		if qContinueOnFailure != "" {

			if err := r.SetQueryParam("continue_on_failure", qContinueOnFailure); err != nil {
				return err
			}
		}
	}
	if err := r.SetBodyParam(o.Info); err != nil {
		return err
	}

	if o.ReturnRecords != nil {

		// query param return_records
		var qrReturnRecords string

		if o.ReturnRecords != nil {
			qrReturnRecords = *o.ReturnRecords
		}
		qReturnRecords := qrReturnRecords
		if qReturnRecords != "" {

			if err := r.SetQueryParam("return_records", qReturnRecords); err != nil {
				return err
			}
		}
	}

	if o.ReturnTimeout != nil {

		// query param return_timeout
		var qrReturnTimeout string

		if o.ReturnTimeout != nil {
			qrReturnTimeout = *o.ReturnTimeout
		}
		qReturnTimeout := qrReturnTimeout
		if qReturnTimeout != "" {

			if err := r.SetQueryParam("return_timeout", qReturnTimeout); err != nil {
				return err
			}
		}
	}

	if o.SerialRecords != nil {

		// query param serial_records
		var qrSerialRecords string

		if o.SerialRecords != nil {
			qrSerialRecords = *o.SerialRecords
		}
		qSerialRecords := qrSerialRecords
		if qSerialRecords != "" {

			if err := r.SetQueryParam("serial_records", qSerialRecords); err != nil {
				return err
			}
		}
	}

	if o.Top1 != nil {

		// query param top1
		var qrTop1 string

		if o.Top1 != nil {
			qrTop1 = *o.Top1
		}
		qTop1 := qrTop1
		if qTop1 != "" {

			if err := r.SetQueryParam("top1", qTop1); err != nil {
				return err
			}
		}
	}

	if o.Top10 != nil {

		// query param top10
		var qrTop10 string

		if o.Top10 != nil {
			qrTop10 = *o.Top10
		}
		qTop10 := qrTop10
		if qTop10 != "" {

			if err := r.SetQueryParam("top10", qTop10); err != nil {
				return err
			}
		}
	}

	if o.Top2 != nil {

		// query param top2
		var qrTop2 string

		if o.Top2 != nil {
			qrTop2 = *o.Top2
		}
		qTop2 := qrTop2
		if qTop2 != "" {

			if err := r.SetQueryParam("top2", qTop2); err != nil {
				return err
			}
		}
	}

	if o.Top3 != nil {

		// query param top3
		var qrTop3 string

		if o.Top3 != nil {
			qrTop3 = *o.Top3
		}
		qTop3 := qrTop3
		if qTop3 != "" {

			if err := r.SetQueryParam("top3", qTop3); err != nil {
				return err
			}
		}
	}

	if o.Top4 != nil {

		// query param top4
		var qrTop4 string

		if o.Top4 != nil {
			qrTop4 = *o.Top4
		}
		qTop4 := qrTop4
		if qTop4 != "" {

			if err := r.SetQueryParam("top4", qTop4); err != nil {
				return err
			}
		}
	}

	if o.Top5 != nil {

		// query param top5
		var qrTop5 string

		if o.Top5 != nil {
			qrTop5 = *o.Top5
		}
		qTop5 := qrTop5
		if qTop5 != "" {

			if err := r.SetQueryParam("top5", qTop5); err != nil {
				return err
			}
		}
	}

	if o.Top6 != nil {

		// query param top6
		var qrTop6 string

		if o.Top6 != nil {
			qrTop6 = *o.Top6
		}
		qTop6 := qrTop6
		if qTop6 != "" {

			if err := r.SetQueryParam("top6", qTop6); err != nil {
				return err
			}
		}
	}

	if o.Top7 != nil {

		// query param top7
		var qrTop7 string

		if o.Top7 != nil {
			qrTop7 = *o.Top7
		}
		qTop7 := qrTop7
		if qTop7 != "" {

			if err := r.SetQueryParam("top7", qTop7); err != nil {
				return err
			}
		}
	}

	if o.Top8 != nil {

		// query param top8
		var qrTop8 string

		if o.Top8 != nil {
			qrTop8 = *o.Top8
		}
		qTop8 := qrTop8
		if qTop8 != "" {

			if err := r.SetQueryParam("top8", qTop8); err != nil {
				return err
			}
		}
	}

	if o.Top9 != nil {

		// query param top9
		var qrTop9 string

		if o.Top9 != nil {
			qrTop9 = *o.Top9
		}
		qTop9 := qrTop9
		if qTop9 != "" {

			if err := r.SetQueryParam("top9", qTop9); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
