apiVersion: v1
kind: ConfigMap
metadata:
  name: ontap-proxy-config
  labels:
    app: {{ .Chart.Name }}
data:
  PORT: {{ .Values.config.port | quote }}
  ENV: {{ .Values.config.env | default "production" | quote }}
  CORE_API_HOST: {{ .Values.coreApi.host | quote }}
  AUTH_DATA_CACHE_CLEANUP_INTERVAL_MINUTES: {{ .Values.cache.authData.cleanupIntervalMinutes | default "10080" | quote }}
  AUTH_DATA_CACHE_EXPIRATION_MINUTES: {{ .Values.cache.authData.expirationMinutes | default "10080" | quote }}
  CA_POOL_DEPLOYED_PROJECT_ID: {{ .Values.gcp.caPool.deployedProjectId | quote }}
  SECRET_MANAGER_PROJECT_ID: {{ .Values.gcp.secretManager.projectId | quote }}
  REGION: {{ .Values.gcp.region | quote }}
  CA_POOL_NAME: {{ .Values.gcp.caPool.name | quote }}
  GCP_AUTH_ACCEPTED_SERVICE_ACCOUNTS: {{ .Values.gcp.auth.acceptedServiceAccounts | quote }}
  GCP_SERVICE_URL: {{ .Values.gcp.serviceUrl | quote }}
  JWK_KIDS_URL: {{ .Values.gcp.jwkUrl | default "https://www.googleapis.com/service_accounts/v1/metadata/x509/" | quote }}
  CERT_CACHE_EXPIRATION_MINUTES: {{ .Values.gcp.certCache.expirationMinutes | default "120" | quote }}
  CERT_CACHE_SLEEP_RETRY_INTERVAL_SECONDS: {{ .Values.gcp.certCache.sleepRetryIntervalSeconds | default "5" | quote }}
  JWK_TIMEOUT_SECONDS: {{ .Values.gcp.jwkTimeoutSeconds | default "10" | quote }}
