apiVersion: apps/v1
kind: Deployment
metadata:
  name: ontap-proxy
  labels:
    app: {{ .Chart.Name }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- if and .Values.podAffinity.enabled (eq .Values.global.environment "gcp") }}
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: {{ .Values.podAffinity.minDomains | default 3 }}
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "ontap-proxy.podSelectorLabels" . | nindent 14 }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "ontap-proxy.podSelectorLabels" . | nindent 14 }}
      {{- end }}
      containers:
        - name: ontap-proxy
          {{- if .Values.images.ontapProxy.secondary }}
          image: "{{- include "containerImage" (list . (dict "name" "ontapProxy" "secondary" true)) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list . (dict "name" "ontapProxy" "secondary" false)) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.images.ontapProxy.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.service.appPort }}
          livenessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: {{ .Values.service.appPort }}
              scheme: HTTP
            initialDelaySeconds: 60
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          readinessProbe:
            failureThreshold: 3
            httpGet:
              path: /health
              port: {{ .Values.service.appPort }}
              scheme: HTTP
            initialDelaySeconds: 10
            periodSeconds: 15
            successThreshold: 1
            timeoutSeconds: 1
          envFrom:
            - configMapRef:
                name: ontap-proxy-service-env-config
