apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ontap-proxy-ingress
  annotations:
    nginx.ingress.kubernetes.io/rewrite-target: /
    nginx.ingress.kubernetes.io/ssl-redirect: "true"
  labels:
    app: {{ .Chart.Name }}
spec:
  rules:
    - host: ontapproxy.svc.cluster.local
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: ontap-proxy
                port:
                  number: {{ .Values.service.appPort }}
