{{- if .Values.istioEnabled | default true }}
---
apiVersion: security.istio.io/v1beta1
kind: AuthorizationPolicy
metadata:
  name: allow-to-ontap-proxy
  namespace: {{ .Release.Namespace }}
  annotations:
    kubernetes.io/description: "Authorization policy for ontap-proxy to allow access from all sources (including CCFE)"
  labels:
    app: {{ .Chart.Name }}
spec:
  action: ALLOW
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  rules:
    - {}   # Matches all sources (internal and external, including CCFE)
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-peer-authentication-ontap-proxy
  namespace: {{ .Release.Namespace }}
spec:
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  mtls:
    mode: PERMISSIVE # CCFE should be able to invoke ontap-proxy api hence mode is set as PERMISSIVE here.
{{- end }}
