apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- range $key, $value := .Values.serviceAccountAnnotations }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
{{- if or ( .Values.global.primaryImageRegistryPasswordAuth ) ( .Values.global.secondaryImageRegistryPasswordAuth ) }}
imagePullSecrets:
  {{- if .Values.global.primaryImageRegistryPasswordAuth }}
  - name: {{ .Values.global.chartPrimaryImageRegistry | default .Values.global.primaryImagePullSecretName }}
  {{- end }}
  {{- if .Values.global.secondaryImageRegistryPasswordAuth }}
  - name: {{ .Values.global.chartSecondaryImageRegistry | default .Values.global.secondaryImageRegistry }}
  {{- end }}
{{- end }}