apiVersion: v1
kind: Service
metadata:
  name: ontap-proxy-service
  annotations:
    description: "Service for ONTAP Proxy"
  labels:
    app: {{ .Chart.Name }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.appPort }}
      targetPort: {{ .Values.service.appPort }}
      protocol: TCP
      name: http
  selector:
    app: {{ .Chart.Name }}
