// Code generated by ogen, DO NOT EDIT.

package ociserver

// OperationName is the ogen operation name
type OperationName = string

const (
	CreatePoolOperation  OperationName = "CreatePool"
	DeletePoolOperation  OperationName = "DeletePool"
	GetHealthOperation   OperationName = "GetHealth"
	GetWorkflowOperation OperationName = "GetWorkflow"
)
