// Code generated by ogen, DO NOT EDIT.

package ociserver

import (
	"github.com/go-faster/errors"
)

// Ref: #/components/schemas/CreatePoolAcceptedResponse
type CreatePoolAcceptedResponse struct {
	// Current workflow status for the create operation.
	Status string `json:"status"`
	// Workflow identifier used to poll operation status.
	WorkflowId string `json:"workflowId"`
	// Pool OCID for the requested pool.
	PoolOCID string `json:"poolOCID"`
}

// GetStatus returns the value of Status.
func (s *CreatePoolAcceptedResponse) GetStatus() string {
	return s.Status
}

// GetWorkflowId returns the value of WorkflowId.
func (s *CreatePoolAcceptedResponse) GetWorkflowId() string {
	return s.WorkflowId
}

// GetPoolOCID returns the value of PoolOCID.
func (s *CreatePoolAcceptedResponse) GetPoolOCID() string {
	return s.PoolOCID
}

// SetStatus sets the value of Status.
func (s *CreatePoolAcceptedResponse) SetStatus(val string) {
	s.Status = val
}

// SetWorkflowId sets the value of WorkflowId.
func (s *CreatePoolAcceptedResponse) SetWorkflowId(val string) {
	s.WorkflowId = val
}

// SetPoolOCID sets the value of PoolOCID.
func (s *CreatePoolAcceptedResponse) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// CreatePoolAcceptedResponseHeaders wraps CreatePoolAcceptedResponse with response headers.
type CreatePoolAcceptedResponseHeaders struct {
	OpcRequestID string
	Response     CreatePoolAcceptedResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *CreatePoolAcceptedResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *CreatePoolAcceptedResponseHeaders) GetResponse() CreatePoolAcceptedResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *CreatePoolAcceptedResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *CreatePoolAcceptedResponseHeaders) SetResponse(val CreatePoolAcceptedResponse) {
	s.Response = val
}

func (*CreatePoolAcceptedResponseHeaders) createPoolRes() {}

type CreatePoolBadRequest PoolOperationErrorResponseHeaders

func (*CreatePoolBadRequest) createPoolRes() {}

type CreatePoolConflict PoolOperationErrorResponseHeaders

func (*CreatePoolConflict) createPoolRes() {}

// CreatePoolDefaultErrorStatusCodeWithHeaders wraps PoolOperationErrorResponse with status code and response headers.
type CreatePoolDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     PoolOperationErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *CreatePoolDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *CreatePoolDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *CreatePoolDefaultErrorStatusCodeWithHeaders) GetResponse() PoolOperationErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *CreatePoolDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *CreatePoolDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *CreatePoolDefaultErrorStatusCodeWithHeaders) SetResponse(val PoolOperationErrorResponse) {
	s.Response = val
}

func (*CreatePoolDefaultErrorStatusCodeWithHeaders) createPoolRes() {}

type CreatePoolForbidden PoolOperationErrorResponseHeaders

func (*CreatePoolForbidden) createPoolRes() {}

type CreatePoolInternalServerError PoolOperationErrorResponseHeaders

func (*CreatePoolInternalServerError) createPoolRes() {}

type CreatePoolNotFound PoolOperationErrorResponseHeaders

func (*CreatePoolNotFound) createPoolRes() {}

// Ref: #/components/schemas/CreatePoolRequest
type CreatePoolRequest struct {
	// OCI pool resource OCID for the pool being created.
	PoolOCID string `json:"poolOCID"`
	// OCI compartment OCID (scope for the pool).
	CompartmentOCID string `json:"compartmentOCID"`
	// Human-readable pool name. Must be unique within the compartment.
	DisplayName string `json:"displayName"`
	// OCI subnet OCID for the pool. This is the service subnet in your VCN where pool resources will be
	// placed.
	SubnetId string `json:"subnetId"`
	// Total pool capacity in GiB across all HA pairs. The service distributes this
	// capacity across the underlying nodes. Typically a multiple of 1 TiB.
	SizeInGiB int64 `json:"sizeInGiB"`
	// Total target throughput for the pool in GBps across all HA pairs.
	ThroughputGBps float64 `json:"throughputGBps"`
	// Number of data endpoints to provision for the pool. Must be >= 2
	// and a multiple of 2.
	DataEndpointCount int64 `json:"dataEndpointCount"`
	// Availability domain for the primary HA node (e.g. IMtu:EU-FRANKFURT-1-AD-1).
	PrimaryAvailabilityDomain string `json:"primaryAvailabilityDomain"`
	// Availability domain for the secondary HA node. Required for HA deployments.
	SecondaryAvailabilityDomain OptString `json:"secondaryAvailabilityDomain"`
	// Availability domain for the mediator VM. Required for HA deployments.
	MediatorAvailabilityDomain OptString `json:"mediatorAvailabilityDomain"`
	// OCI secret reference for admin password.
	OciAdminPassword OCIOCIDVersionRef `json:"ociAdminPassword"`
	// Optional description for the pool.
	Description OptString `json:"description"`
	// OCI subnet OCID for the data NIC.
	DataNicSubnetId string `json:"dataNicSubnetId"`
	// Optional cloud tiering configuration. When provided, cold pool data is
	// tiered to the specified OCI Object Storage bucket via the S3-compatible
	// endpoint. Omit to disable tiering.
	TieringConfig OptTieringConfig `json:"tieringConfig"`
	// Optional OCI Vault Master Encryption Key OCID used to encrypt pool data
	// at rest. When omitted, the service default encryption is used.
	KmsKeyId OptString `json:"kmsKeyId"`
	// Optional list of OCI Network Security Group OCIDs to attach to the pool's
	// VNICs. When omitted or empty, no NSGs are attached and only subnet-level
	// security rules apply.
	NsgIds []string `json:"nsgIds"`
	// Optional OCI Zero Trust Packet Routing (ZPR) security attributes to
	// apply to the pool's VNICs at deploy time. Namespaces and attribute
	// keys referenced here must already exist in the tenancy.
	SecurityAttributes OptSecurityAttributes `json:"securityAttributes"`
}

// GetPoolOCID returns the value of PoolOCID.
func (s *CreatePoolRequest) GetPoolOCID() string {
	return s.PoolOCID
}

// GetCompartmentOCID returns the value of CompartmentOCID.
func (s *CreatePoolRequest) GetCompartmentOCID() string {
	return s.CompartmentOCID
}

// GetDisplayName returns the value of DisplayName.
func (s *CreatePoolRequest) GetDisplayName() string {
	return s.DisplayName
}

// GetSubnetId returns the value of SubnetId.
func (s *CreatePoolRequest) GetSubnetId() string {
	return s.SubnetId
}

// GetSizeInGiB returns the value of SizeInGiB.
func (s *CreatePoolRequest) GetSizeInGiB() int64 {
	return s.SizeInGiB
}

// GetThroughputGBps returns the value of ThroughputGBps.
func (s *CreatePoolRequest) GetThroughputGBps() float64 {
	return s.ThroughputGBps
}

// GetDataEndpointCount returns the value of DataEndpointCount.
func (s *CreatePoolRequest) GetDataEndpointCount() int64 {
	return s.DataEndpointCount
}

// GetPrimaryAvailabilityDomain returns the value of PrimaryAvailabilityDomain.
func (s *CreatePoolRequest) GetPrimaryAvailabilityDomain() string {
	return s.PrimaryAvailabilityDomain
}

// GetSecondaryAvailabilityDomain returns the value of SecondaryAvailabilityDomain.
func (s *CreatePoolRequest) GetSecondaryAvailabilityDomain() OptString {
	return s.SecondaryAvailabilityDomain
}

// GetMediatorAvailabilityDomain returns the value of MediatorAvailabilityDomain.
func (s *CreatePoolRequest) GetMediatorAvailabilityDomain() OptString {
	return s.MediatorAvailabilityDomain
}

// GetOciAdminPassword returns the value of OciAdminPassword.
func (s *CreatePoolRequest) GetOciAdminPassword() OCIOCIDVersionRef {
	return s.OciAdminPassword
}

// GetDescription returns the value of Description.
func (s *CreatePoolRequest) GetDescription() OptString {
	return s.Description
}

// GetDataNicSubnetId returns the value of DataNicSubnetId.
func (s *CreatePoolRequest) GetDataNicSubnetId() string {
	return s.DataNicSubnetId
}

// GetTieringConfig returns the value of TieringConfig.
func (s *CreatePoolRequest) GetTieringConfig() OptTieringConfig {
	return s.TieringConfig
}

// GetKmsKeyId returns the value of KmsKeyId.
func (s *CreatePoolRequest) GetKmsKeyId() OptString {
	return s.KmsKeyId
}

// GetNsgIds returns the value of NsgIds.
func (s *CreatePoolRequest) GetNsgIds() []string {
	return s.NsgIds
}

// GetSecurityAttributes returns the value of SecurityAttributes.
func (s *CreatePoolRequest) GetSecurityAttributes() OptSecurityAttributes {
	return s.SecurityAttributes
}

// SetPoolOCID sets the value of PoolOCID.
func (s *CreatePoolRequest) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// SetCompartmentOCID sets the value of CompartmentOCID.
func (s *CreatePoolRequest) SetCompartmentOCID(val string) {
	s.CompartmentOCID = val
}

// SetDisplayName sets the value of DisplayName.
func (s *CreatePoolRequest) SetDisplayName(val string) {
	s.DisplayName = val
}

// SetSubnetId sets the value of SubnetId.
func (s *CreatePoolRequest) SetSubnetId(val string) {
	s.SubnetId = val
}

// SetSizeInGiB sets the value of SizeInGiB.
func (s *CreatePoolRequest) SetSizeInGiB(val int64) {
	s.SizeInGiB = val
}

// SetThroughputGBps sets the value of ThroughputGBps.
func (s *CreatePoolRequest) SetThroughputGBps(val float64) {
	s.ThroughputGBps = val
}

// SetDataEndpointCount sets the value of DataEndpointCount.
func (s *CreatePoolRequest) SetDataEndpointCount(val int64) {
	s.DataEndpointCount = val
}

// SetPrimaryAvailabilityDomain sets the value of PrimaryAvailabilityDomain.
func (s *CreatePoolRequest) SetPrimaryAvailabilityDomain(val string) {
	s.PrimaryAvailabilityDomain = val
}

// SetSecondaryAvailabilityDomain sets the value of SecondaryAvailabilityDomain.
func (s *CreatePoolRequest) SetSecondaryAvailabilityDomain(val OptString) {
	s.SecondaryAvailabilityDomain = val
}

// SetMediatorAvailabilityDomain sets the value of MediatorAvailabilityDomain.
func (s *CreatePoolRequest) SetMediatorAvailabilityDomain(val OptString) {
	s.MediatorAvailabilityDomain = val
}

// SetOciAdminPassword sets the value of OciAdminPassword.
func (s *CreatePoolRequest) SetOciAdminPassword(val OCIOCIDVersionRef) {
	s.OciAdminPassword = val
}

// SetDescription sets the value of Description.
func (s *CreatePoolRequest) SetDescription(val OptString) {
	s.Description = val
}

// SetDataNicSubnetId sets the value of DataNicSubnetId.
func (s *CreatePoolRequest) SetDataNicSubnetId(val string) {
	s.DataNicSubnetId = val
}

// SetTieringConfig sets the value of TieringConfig.
func (s *CreatePoolRequest) SetTieringConfig(val OptTieringConfig) {
	s.TieringConfig = val
}

// SetKmsKeyId sets the value of KmsKeyId.
func (s *CreatePoolRequest) SetKmsKeyId(val OptString) {
	s.KmsKeyId = val
}

// SetNsgIds sets the value of NsgIds.
func (s *CreatePoolRequest) SetNsgIds(val []string) {
	s.NsgIds = val
}

// SetSecurityAttributes sets the value of SecurityAttributes.
func (s *CreatePoolRequest) SetSecurityAttributes(val OptSecurityAttributes) {
	s.SecurityAttributes = val
}

type CreatePoolTooManyRequests PoolOperationErrorResponseHeaders

func (*CreatePoolTooManyRequests) createPoolRes() {}

type CreatePoolUnauthorized PoolOperationErrorResponseHeaders

func (*CreatePoolUnauthorized) createPoolRes() {}

type CreatePoolUnprocessableEntity PoolOperationErrorResponseHeaders

func (*CreatePoolUnprocessableEntity) createPoolRes() {}

// Ref: #/components/schemas/CreateSvmAcceptedResponse
type CreateSvmAcceptedResponse struct {
	// Current workflow status for the create operation.
	Status string `json:"status"`
	// Workflow identifier used to poll operation status.
	WorkflowId string `json:"workflowId"`
	// SVM OCID for the requested SVM.
	SvmOCID string `json:"svmOCID"`
}

// GetStatus returns the value of Status.
func (s *CreateSvmAcceptedResponse) GetStatus() string {
	return s.Status
}

// GetWorkflowId returns the value of WorkflowId.
func (s *CreateSvmAcceptedResponse) GetWorkflowId() string {
	return s.WorkflowId
}

// GetSvmOCID returns the value of SvmOCID.
func (s *CreateSvmAcceptedResponse) GetSvmOCID() string {
	return s.SvmOCID
}

// SetStatus sets the value of Status.
func (s *CreateSvmAcceptedResponse) SetStatus(val string) {
	s.Status = val
}

// SetWorkflowId sets the value of WorkflowId.
func (s *CreateSvmAcceptedResponse) SetWorkflowId(val string) {
	s.WorkflowId = val
}

// SetSvmOCID sets the value of SvmOCID.
func (s *CreateSvmAcceptedResponse) SetSvmOCID(val string) {
	s.SvmOCID = val
}

// CreateSvmAcceptedResponseHeaders wraps CreateSvmAcceptedResponse with response headers.
type CreateSvmAcceptedResponseHeaders struct {
	OpcRequestID string
	Response     CreateSvmAcceptedResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *CreateSvmAcceptedResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *CreateSvmAcceptedResponseHeaders) GetResponse() CreateSvmAcceptedResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *CreateSvmAcceptedResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *CreateSvmAcceptedResponseHeaders) SetResponse(val CreateSvmAcceptedResponse) {
	s.Response = val
}

func (*CreateSvmAcceptedResponseHeaders) createSvmByPoolRes() {}

type CreateSvmByPoolBadRequest SvmOperationErrorResponseHeaders

func (*CreateSvmByPoolBadRequest) createSvmByPoolRes() {}

type CreateSvmByPoolConflict SvmOperationErrorResponseHeaders

func (*CreateSvmByPoolConflict) createSvmByPoolRes() {}

type CreateSvmByPoolForbidden SvmOperationErrorResponseHeaders

func (*CreateSvmByPoolForbidden) createSvmByPoolRes() {}

type CreateSvmByPoolInternalServerError SvmOperationErrorResponseHeaders

func (*CreateSvmByPoolInternalServerError) createSvmByPoolRes() {}

type CreateSvmByPoolNotFound SvmOperationErrorResponseHeaders

func (*CreateSvmByPoolNotFound) createSvmByPoolRes() {}

type CreateSvmByPoolTooManyRequests SvmOperationErrorResponseHeaders

func (*CreateSvmByPoolTooManyRequests) createSvmByPoolRes() {}

type CreateSvmByPoolUnauthorized SvmOperationErrorResponseHeaders

func (*CreateSvmByPoolUnauthorized) createSvmByPoolRes() {}

type CreateSvmByPoolUnprocessableEntity SvmOperationErrorResponseHeaders

func (*CreateSvmByPoolUnprocessableEntity) createSvmByPoolRes() {}

// CreateSvmDefaultErrorStatusCodeWithHeaders wraps SvmOperationErrorResponse with status code and response headers.
type CreateSvmDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     SvmOperationErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *CreateSvmDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *CreateSvmDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *CreateSvmDefaultErrorStatusCodeWithHeaders) GetResponse() SvmOperationErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *CreateSvmDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *CreateSvmDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *CreateSvmDefaultErrorStatusCodeWithHeaders) SetResponse(val SvmOperationErrorResponse) {
	s.Response = val
}

func (*CreateSvmDefaultErrorStatusCodeWithHeaders) createSvmByPoolRes() {}

// Ref: #/components/schemas/CreateSvmRequest
type CreateSvmRequest struct {
	// OCI SVM resource OCID for the SVM being created.
	SvmOCID string `json:"svmOCID"`
	// Requested SVM name.
	Name string `json:"Name"`
	// OCI secret reference for the SVM admin password.
	SvmAdminPassword OCIOCIDVersionRef `json:"svmAdminPassword"`
	// Optional list of IP addresses for the SVM.
	Ips []string `json:"Ips"`
}

// GetSvmOCID returns the value of SvmOCID.
func (s *CreateSvmRequest) GetSvmOCID() string {
	return s.SvmOCID
}

// GetName returns the value of Name.
func (s *CreateSvmRequest) GetName() string {
	return s.Name
}

// GetSvmAdminPassword returns the value of SvmAdminPassword.
func (s *CreateSvmRequest) GetSvmAdminPassword() OCIOCIDVersionRef {
	return s.SvmAdminPassword
}

// GetIps returns the value of Ips.
func (s *CreateSvmRequest) GetIps() []string {
	return s.Ips
}

// SetSvmOCID sets the value of SvmOCID.
func (s *CreateSvmRequest) SetSvmOCID(val string) {
	s.SvmOCID = val
}

// SetName sets the value of Name.
func (s *CreateSvmRequest) SetName(val string) {
	s.Name = val
}

// SetSvmAdminPassword sets the value of SvmAdminPassword.
func (s *CreateSvmRequest) SetSvmAdminPassword(val OCIOCIDVersionRef) {
	s.SvmAdminPassword = val
}

// SetIps sets the value of Ips.
func (s *CreateSvmRequest) SetIps(val []string) {
	s.Ips = val
}

// Ref: #/components/schemas/DeletePoolAcceptedResponse
type DeletePoolAcceptedResponse struct {
	// Current workflow status for the delete operation.
	Status string `json:"status"`
	// Workflow identifier used to poll operation status.
	WorkflowId string `json:"workflowId"`
	// Pool OCID for the requested pool.
	PoolOCID string `json:"poolOCID"`
}

// GetStatus returns the value of Status.
func (s *DeletePoolAcceptedResponse) GetStatus() string {
	return s.Status
}

// GetWorkflowId returns the value of WorkflowId.
func (s *DeletePoolAcceptedResponse) GetWorkflowId() string {
	return s.WorkflowId
}

// GetPoolOCID returns the value of PoolOCID.
func (s *DeletePoolAcceptedResponse) GetPoolOCID() string {
	return s.PoolOCID
}

// SetStatus sets the value of Status.
func (s *DeletePoolAcceptedResponse) SetStatus(val string) {
	s.Status = val
}

// SetWorkflowId sets the value of WorkflowId.
func (s *DeletePoolAcceptedResponse) SetWorkflowId(val string) {
	s.WorkflowId = val
}

// SetPoolOCID sets the value of PoolOCID.
func (s *DeletePoolAcceptedResponse) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// DeletePoolAcceptedResponseHeaders wraps DeletePoolAcceptedResponse with response headers.
type DeletePoolAcceptedResponseHeaders struct {
	OpcRequestID string
	Response     DeletePoolAcceptedResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *DeletePoolAcceptedResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *DeletePoolAcceptedResponseHeaders) GetResponse() DeletePoolAcceptedResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *DeletePoolAcceptedResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *DeletePoolAcceptedResponseHeaders) SetResponse(val DeletePoolAcceptedResponse) {
	s.Response = val
}

func (*DeletePoolAcceptedResponseHeaders) deletePoolRes() {}

type DeletePoolBadRequest PoolOperationErrorResponseHeaders

func (*DeletePoolBadRequest) deletePoolRes() {}

type DeletePoolConflict PoolOperationErrorResponseHeaders

func (*DeletePoolConflict) deletePoolRes() {}

// DeletePoolDefaultErrorStatusCodeWithHeaders wraps PoolOperationErrorResponse with status code and response headers.
type DeletePoolDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     PoolOperationErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *DeletePoolDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *DeletePoolDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *DeletePoolDefaultErrorStatusCodeWithHeaders) GetResponse() PoolOperationErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *DeletePoolDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *DeletePoolDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *DeletePoolDefaultErrorStatusCodeWithHeaders) SetResponse(val PoolOperationErrorResponse) {
	s.Response = val
}

func (*DeletePoolDefaultErrorStatusCodeWithHeaders) deletePoolRes() {}

type DeletePoolForbidden PoolOperationErrorResponseHeaders

func (*DeletePoolForbidden) deletePoolRes() {}

type DeletePoolInternalServerError PoolOperationErrorResponseHeaders

func (*DeletePoolInternalServerError) deletePoolRes() {}

// DeletePoolNoContent is response for DeletePool operation.
type DeletePoolNoContent struct {
	OpcRequestID string
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *DeletePoolNoContent) GetOpcRequestID() string {
	return s.OpcRequestID
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *DeletePoolNoContent) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

func (*DeletePoolNoContent) deletePoolRes() {}

type DeletePoolNotFound PoolOperationErrorResponseHeaders

func (*DeletePoolNotFound) deletePoolRes() {}

type DeletePoolTooManyRequests PoolOperationErrorResponseHeaders

func (*DeletePoolTooManyRequests) deletePoolRes() {}

type DeletePoolUnauthorized PoolOperationErrorResponseHeaders

func (*DeletePoolUnauthorized) deletePoolRes() {}

// Ref: #/components/schemas/DeleteSvmAcceptedResponse
type DeleteSvmAcceptedResponse struct {
	// Current workflow status for the delete operation.
	Status string `json:"status"`
	// Workflow identifier used to poll operation status.
	WorkflowId string `json:"workflowId"`
	// SVM OCID for the requested SVM.
	SvmOCID string `json:"svmOCID"`
}

// GetStatus returns the value of Status.
func (s *DeleteSvmAcceptedResponse) GetStatus() string {
	return s.Status
}

// GetWorkflowId returns the value of WorkflowId.
func (s *DeleteSvmAcceptedResponse) GetWorkflowId() string {
	return s.WorkflowId
}

// GetSvmOCID returns the value of SvmOCID.
func (s *DeleteSvmAcceptedResponse) GetSvmOCID() string {
	return s.SvmOCID
}

// SetStatus sets the value of Status.
func (s *DeleteSvmAcceptedResponse) SetStatus(val string) {
	s.Status = val
}

// SetWorkflowId sets the value of WorkflowId.
func (s *DeleteSvmAcceptedResponse) SetWorkflowId(val string) {
	s.WorkflowId = val
}

// SetSvmOCID sets the value of SvmOCID.
func (s *DeleteSvmAcceptedResponse) SetSvmOCID(val string) {
	s.SvmOCID = val
}

// DeleteSvmAcceptedResponseHeaders wraps DeleteSvmAcceptedResponse with response headers.
type DeleteSvmAcceptedResponseHeaders struct {
	OpcRequestID string
	Response     DeleteSvmAcceptedResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *DeleteSvmAcceptedResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *DeleteSvmAcceptedResponseHeaders) GetResponse() DeleteSvmAcceptedResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *DeleteSvmAcceptedResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *DeleteSvmAcceptedResponseHeaders) SetResponse(val DeleteSvmAcceptedResponse) {
	s.Response = val
}

func (*DeleteSvmAcceptedResponseHeaders) deleteSvmRes() {}

type DeleteSvmBadRequest SvmOperationErrorResponseHeaders

func (*DeleteSvmBadRequest) deleteSvmRes() {}

type DeleteSvmConflict SvmOperationErrorResponseHeaders

func (*DeleteSvmConflict) deleteSvmRes() {}

// DeleteSvmDefaultErrorStatusCodeWithHeaders wraps SvmOperationErrorResponse with status code and response headers.
type DeleteSvmDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     SvmOperationErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *DeleteSvmDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *DeleteSvmDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *DeleteSvmDefaultErrorStatusCodeWithHeaders) GetResponse() SvmOperationErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *DeleteSvmDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *DeleteSvmDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *DeleteSvmDefaultErrorStatusCodeWithHeaders) SetResponse(val SvmOperationErrorResponse) {
	s.Response = val
}

func (*DeleteSvmDefaultErrorStatusCodeWithHeaders) deleteSvmRes() {}

type DeleteSvmForbidden SvmOperationErrorResponseHeaders

func (*DeleteSvmForbidden) deleteSvmRes() {}

type DeleteSvmInternalServerError SvmOperationErrorResponseHeaders

func (*DeleteSvmInternalServerError) deleteSvmRes() {}

type DeleteSvmNotFound SvmOperationErrorResponseHeaders

func (*DeleteSvmNotFound) deleteSvmRes() {}

type DeleteSvmReq struct {
	// Force-delete even if dependent resources exist.
	Force OptBool `json:"force"`
}

// GetForce returns the value of Force.
func (s *DeleteSvmReq) GetForce() OptBool {
	return s.Force
}

// SetForce sets the value of Force.
func (s *DeleteSvmReq) SetForce(val OptBool) {
	s.Force = val
}

type DeleteSvmTooManyRequests SvmOperationErrorResponseHeaders

func (*DeleteSvmTooManyRequests) deleteSvmRes() {}

type DeleteSvmUnauthorized SvmOperationErrorResponseHeaders

func (*DeleteSvmUnauthorized) deleteSvmRes() {}

// Ref: #/components/schemas/Error
type Error struct {
	// OCI error code or HTTP status.
	Code float64 `json:"code"`
	// Human-readable error message.
	Message string `json:"message"`
}

// GetCode returns the value of Code.
func (s *Error) GetCode() float64 {
	return s.Code
}

// GetMessage returns the value of Message.
func (s *Error) GetMessage() string {
	return s.Message
}

// SetCode sets the value of Code.
func (s *Error) SetCode(val float64) {
	s.Code = val
}

// SetMessage sets the value of Message.
func (s *Error) SetMessage(val string) {
	s.Message = val
}

// ErrorStatusCode wraps Error with StatusCode.
type ErrorStatusCode struct {
	StatusCode int
	Response   Error
}

// GetStatusCode returns the value of StatusCode.
func (s *ErrorStatusCode) GetStatusCode() int {
	return s.StatusCode
}

// GetResponse returns the value of Response.
func (s *ErrorStatusCode) GetResponse() Error {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *ErrorStatusCode) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetResponse sets the value of Response.
func (s *ErrorStatusCode) SetResponse(val Error) {
	s.Response = val
}

func (*ErrorStatusCode) getHealthRes() {}

type GetWorkflowBadRequest GetWorkflowErrorResponseHeaders

func (*GetWorkflowBadRequest) getWorkflowRes() {}

type GetWorkflowConflict GetWorkflowErrorResponseHeaders

func (*GetWorkflowConflict) getWorkflowRes() {}

// GetWorkflowDefaultErrorStatusCodeWithHeaders wraps GetWorkflowErrorResponse with status code and response headers.
type GetWorkflowDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     GetWorkflowErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *GetWorkflowDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *GetWorkflowDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *GetWorkflowDefaultErrorStatusCodeWithHeaders) GetResponse() GetWorkflowErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *GetWorkflowDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *GetWorkflowDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *GetWorkflowDefaultErrorStatusCodeWithHeaders) SetResponse(val GetWorkflowErrorResponse) {
	s.Response = val
}

func (*GetWorkflowDefaultErrorStatusCodeWithHeaders) getWorkflowRes() {}

// Ref: #/components/schemas/GetWorkflowErrorResponse
type GetWorkflowErrorResponse struct {
	// Error message for failed request.
	ErrorMessage string `json:"errorMessage"`
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *GetWorkflowErrorResponse) GetErrorMessage() string {
	return s.ErrorMessage
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *GetWorkflowErrorResponse) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

// GetWorkflowErrorResponseHeaders wraps GetWorkflowErrorResponse with response headers.
type GetWorkflowErrorResponseHeaders struct {
	OpcRequestID string
	Response     GetWorkflowErrorResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *GetWorkflowErrorResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *GetWorkflowErrorResponseHeaders) GetResponse() GetWorkflowErrorResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *GetWorkflowErrorResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *GetWorkflowErrorResponseHeaders) SetResponse(val GetWorkflowErrorResponse) {
	s.Response = val
}

type GetWorkflowForbidden GetWorkflowErrorResponseHeaders

func (*GetWorkflowForbidden) getWorkflowRes() {}

type GetWorkflowInternalServerError GetWorkflowErrorResponseHeaders

func (*GetWorkflowInternalServerError) getWorkflowRes() {}

type GetWorkflowNotFound GetWorkflowErrorResponseHeaders

func (*GetWorkflowNotFound) getWorkflowRes() {}

// Ref: #/components/schemas/GetWorkflowStatusResponse
type GetWorkflowStatusResponse struct {
	// Workflow type name.
	WorkflowType string `json:"workflow_type"`
	// Current workflow status.
	Status string `json:"status"`
	// Present when workflow execution has failure details (for example failed or timed out).
	Error OptWorkflowStatusError `json:"error"`
	// Present only when `workflow_type` is `OCICreatePoolWorkflow` and `status` is `completed`.
	// Omitted for all other workflow types and statuses.
	PoolMetadata OptOCICreatePoolWorkflowMetadata `json:"poolMetadata"`
	// Present only when `workflow_type` is `OCICreateSVMWorkflow` and `status` is `completed`.
	// Omitted for all other workflow types and statuses.
	SvmMetadata OptOCICreateSVMWorkflowMetadata `json:"svmMetadata"`
}

// GetWorkflowType returns the value of WorkflowType.
func (s *GetWorkflowStatusResponse) GetWorkflowType() string {
	return s.WorkflowType
}

// GetStatus returns the value of Status.
func (s *GetWorkflowStatusResponse) GetStatus() string {
	return s.Status
}

// GetError returns the value of Error.
func (s *GetWorkflowStatusResponse) GetError() OptWorkflowStatusError {
	return s.Error
}

// GetPoolMetadata returns the value of PoolMetadata.
func (s *GetWorkflowStatusResponse) GetPoolMetadata() OptOCICreatePoolWorkflowMetadata {
	return s.PoolMetadata
}

// GetSvmMetadata returns the value of SvmMetadata.
func (s *GetWorkflowStatusResponse) GetSvmMetadata() OptOCICreateSVMWorkflowMetadata {
	return s.SvmMetadata
}

// SetWorkflowType sets the value of WorkflowType.
func (s *GetWorkflowStatusResponse) SetWorkflowType(val string) {
	s.WorkflowType = val
}

// SetStatus sets the value of Status.
func (s *GetWorkflowStatusResponse) SetStatus(val string) {
	s.Status = val
}

// SetError sets the value of Error.
func (s *GetWorkflowStatusResponse) SetError(val OptWorkflowStatusError) {
	s.Error = val
}

// SetPoolMetadata sets the value of PoolMetadata.
func (s *GetWorkflowStatusResponse) SetPoolMetadata(val OptOCICreatePoolWorkflowMetadata) {
	s.PoolMetadata = val
}

// SetSvmMetadata sets the value of SvmMetadata.
func (s *GetWorkflowStatusResponse) SetSvmMetadata(val OptOCICreateSVMWorkflowMetadata) {
	s.SvmMetadata = val
}

// GetWorkflowStatusResponseHeaders wraps GetWorkflowStatusResponse with response headers.
type GetWorkflowStatusResponseHeaders struct {
	OpcRequestID string
	Response     GetWorkflowStatusResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *GetWorkflowStatusResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *GetWorkflowStatusResponseHeaders) GetResponse() GetWorkflowStatusResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *GetWorkflowStatusResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *GetWorkflowStatusResponseHeaders) SetResponse(val GetWorkflowStatusResponse) {
	s.Response = val
}

func (*GetWorkflowStatusResponseHeaders) getWorkflowRes() {}

type GetWorkflowTooManyRequests GetWorkflowErrorResponseHeaders

func (*GetWorkflowTooManyRequests) getWorkflowRes() {}

type GetWorkflowUnauthorized GetWorkflowErrorResponseHeaders

func (*GetWorkflowUnauthorized) getWorkflowRes() {}

type GetWorkflowUnprocessableEntity GetWorkflowErrorResponseHeaders

func (*GetWorkflowUnprocessableEntity) getWorkflowRes() {}

// Server health status.
// Ref: #/components/schemas/Health
type Health struct {
	// Server health status (e.g. healthy).
	Status OptString `json:"status"`
}

// GetStatus returns the value of Status.
func (s *Health) GetStatus() OptString {
	return s.Status
}

// SetStatus sets the value of Status.
func (s *Health) SetStatus(val OptString) {
	s.Status = val
}

func (*Health) getHealthRes() {}

// Capacity target for one VM (endpoint) in the pool. Used in `UpdatePoolRequest.nodeCapacities`
// to resize existing nodes; there is no pool-level `sizeInGiB` on the update request.
// Ref: #/components/schemas/NodeCapacity
type NodeCapacity struct {
	// Display name of the VM in the pool, matching the node name returned at pool
	// create (for example from work-request metadata).
	Name string `json:"name"`
	// UUID of the node to update. Must be unique within the request and must
	// match an existing node in the pool.
	NodeUUID string `json:"nodeUUID"`
	// Target capacity for this node in GiB. Both VMs in the same HA pair must
	// request the same value (intra-pair homogeneity); the pair shares one
	// mirrored aggregate. Different HA pairs may use different values
	// (inter-pair heterogeneity). Post-update pool capacity equals the sum of
	// per-HA-pair sizes (one size per pair), not the sum of all node entries.
	SizeInGiB int64 `json:"sizeInGiB"`
}

// GetName returns the value of Name.
func (s *NodeCapacity) GetName() string {
	return s.Name
}

// GetNodeUUID returns the value of NodeUUID.
func (s *NodeCapacity) GetNodeUUID() string {
	return s.NodeUUID
}

// GetSizeInGiB returns the value of SizeInGiB.
func (s *NodeCapacity) GetSizeInGiB() int64 {
	return s.SizeInGiB
}

// SetName sets the value of Name.
func (s *NodeCapacity) SetName(val string) {
	s.Name = val
}

// SetNodeUUID sets the value of NodeUUID.
func (s *NodeCapacity) SetNodeUUID(val string) {
	s.NodeUUID = val
}

// SetSizeInGiB sets the value of SizeInGiB.
func (s *NodeCapacity) SetSizeInGiB(val int64) {
	s.SizeInGiB = val
}

// Ref: #/components/schemas/OCICreatePoolWorkflowCredentials
type OCICreatePoolWorkflowCredentials struct {
	Secret      OCIOCIDVersionRef `json:"secret"`
	Certificate OCIOCIDVersionRef `json:"certificate"`
}

// GetSecret returns the value of Secret.
func (s *OCICreatePoolWorkflowCredentials) GetSecret() OCIOCIDVersionRef {
	return s.Secret
}

// GetCertificate returns the value of Certificate.
func (s *OCICreatePoolWorkflowCredentials) GetCertificate() OCIOCIDVersionRef {
	return s.Certificate
}

// SetSecret sets the value of Secret.
func (s *OCICreatePoolWorkflowCredentials) SetSecret(val OCIOCIDVersionRef) {
	s.Secret = val
}

// SetCertificate sets the value of Certificate.
func (s *OCICreatePoolWorkflowCredentials) SetCertificate(val OCIOCIDVersionRef) {
	s.Certificate = val
}

// Ref: #/components/schemas/OCICreatePoolWorkflowMetadata
type OCICreatePoolWorkflowMetadata struct {
	// OCI pool resource OCID.
	PoolOCID string `json:"poolOCID"`
	// RBAC LIF IP for the cluster.
	ClusterIP OptString `json:"clusterIP"`
	// VM metadata for OCI pool nodes.
	Vms         []OCICreatePoolWorkflowVM        `json:"vms"`
	Credentials OCICreatePoolWorkflowCredentials `json:"credentials"`
}

// GetPoolOCID returns the value of PoolOCID.
func (s *OCICreatePoolWorkflowMetadata) GetPoolOCID() string {
	return s.PoolOCID
}

// GetClusterIP returns the value of ClusterIP.
func (s *OCICreatePoolWorkflowMetadata) GetClusterIP() OptString {
	return s.ClusterIP
}

// GetVms returns the value of Vms.
func (s *OCICreatePoolWorkflowMetadata) GetVms() []OCICreatePoolWorkflowVM {
	return s.Vms
}

// GetCredentials returns the value of Credentials.
func (s *OCICreatePoolWorkflowMetadata) GetCredentials() OCICreatePoolWorkflowCredentials {
	return s.Credentials
}

// SetPoolOCID sets the value of PoolOCID.
func (s *OCICreatePoolWorkflowMetadata) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// SetClusterIP sets the value of ClusterIP.
func (s *OCICreatePoolWorkflowMetadata) SetClusterIP(val OptString) {
	s.ClusterIP = val
}

// SetVms sets the value of Vms.
func (s *OCICreatePoolWorkflowMetadata) SetVms(val []OCICreatePoolWorkflowVM) {
	s.Vms = val
}

// SetCredentials sets the value of Credentials.
func (s *OCICreatePoolWorkflowMetadata) SetCredentials(val OCICreatePoolWorkflowCredentials) {
	s.Credentials = val
}

// Ref: #/components/schemas/OCICreatePoolWorkflowVM
type OCICreatePoolWorkflowVM struct {
	// VM name from VLM config.
	Name string `json:"name"`
	// VM serial number from VLM config.
	SerialNumber string `json:"serialNumber"`
	// VSA management IP for this VM.
	VsaManagementIP string `json:"vsaManagementIP"`
	// Intercluster IP address for this VM.
	InterclusterIP string `json:"interclusterIP"`
	// UUID of the corresponding node.
	NodeUUID string `json:"nodeUUID"`
	// Identifier of the HA pair this VM belongs to within the pool,
	// formatted as `ha_pair-<index>` where `<index>` is **1-based**
	// (e.g. `ha_pair-1`, `ha_pair-2`). The first HA pair is
	// `ha_pair-1`. Both VMs in the same HA pair share this label.
	HaPair string `json:"haPair"`
	// Aggregated capacity for this VM in GiB, computed as the sum of
	// `size` across all entries in the VM's `data_disks` from VLM config.
	SizeInGiB int64 `json:"sizeInGiB"`
	// Aggregated IOPS for this VM, computed as the sum of `disk_iops`
	// across all entries in the VM's `data_disks` from VLM config.
	Iops int64 `json:"iops"`
	// Aggregated throughput for this VM in GBps, computed as the sum of
	// `disk_throughput` (MiBps) across all entries in the VM's `data_disks`
	// from VLM config and converted from MiBps to GBps.
	ThroughputGBps float64 `json:"throughputGBps"`
}

// GetName returns the value of Name.
func (s *OCICreatePoolWorkflowVM) GetName() string {
	return s.Name
}

// GetSerialNumber returns the value of SerialNumber.
func (s *OCICreatePoolWorkflowVM) GetSerialNumber() string {
	return s.SerialNumber
}

// GetVsaManagementIP returns the value of VsaManagementIP.
func (s *OCICreatePoolWorkflowVM) GetVsaManagementIP() string {
	return s.VsaManagementIP
}

// GetInterclusterIP returns the value of InterclusterIP.
func (s *OCICreatePoolWorkflowVM) GetInterclusterIP() string {
	return s.InterclusterIP
}

// GetNodeUUID returns the value of NodeUUID.
func (s *OCICreatePoolWorkflowVM) GetNodeUUID() string {
	return s.NodeUUID
}

// GetHaPair returns the value of HaPair.
func (s *OCICreatePoolWorkflowVM) GetHaPair() string {
	return s.HaPair
}

// GetSizeInGiB returns the value of SizeInGiB.
func (s *OCICreatePoolWorkflowVM) GetSizeInGiB() int64 {
	return s.SizeInGiB
}

// GetIops returns the value of Iops.
func (s *OCICreatePoolWorkflowVM) GetIops() int64 {
	return s.Iops
}

// GetThroughputGBps returns the value of ThroughputGBps.
func (s *OCICreatePoolWorkflowVM) GetThroughputGBps() float64 {
	return s.ThroughputGBps
}

// SetName sets the value of Name.
func (s *OCICreatePoolWorkflowVM) SetName(val string) {
	s.Name = val
}

// SetSerialNumber sets the value of SerialNumber.
func (s *OCICreatePoolWorkflowVM) SetSerialNumber(val string) {
	s.SerialNumber = val
}

// SetVsaManagementIP sets the value of VsaManagementIP.
func (s *OCICreatePoolWorkflowVM) SetVsaManagementIP(val string) {
	s.VsaManagementIP = val
}

// SetInterclusterIP sets the value of InterclusterIP.
func (s *OCICreatePoolWorkflowVM) SetInterclusterIP(val string) {
	s.InterclusterIP = val
}

// SetNodeUUID sets the value of NodeUUID.
func (s *OCICreatePoolWorkflowVM) SetNodeUUID(val string) {
	s.NodeUUID = val
}

// SetHaPair sets the value of HaPair.
func (s *OCICreatePoolWorkflowVM) SetHaPair(val string) {
	s.HaPair = val
}

// SetSizeInGiB sets the value of SizeInGiB.
func (s *OCICreatePoolWorkflowVM) SetSizeInGiB(val int64) {
	s.SizeInGiB = val
}

// SetIops sets the value of Iops.
func (s *OCICreatePoolWorkflowVM) SetIops(val int64) {
	s.Iops = val
}

// SetThroughputGBps sets the value of ThroughputGBps.
func (s *OCICreatePoolWorkflowVM) SetThroughputGBps(val float64) {
	s.ThroughputGBps = val
}

// SVM metadata returned when an OCICreateSVMWorkflow completes successfully.
// Ref: #/components/schemas/OCICreateSVMWorkflowMetadata
type OCICreateSVMWorkflowMetadata struct {
	// SVM name as registered in ONTAP.
	Name OptString `json:"name"`
	// SVM OCID.
	SvmOCID OptString `json:"svmOCID"`
	// Logical interfaces created for the SVM.
	Lifs []SvmLif `json:"lifs"`
}

// GetName returns the value of Name.
func (s *OCICreateSVMWorkflowMetadata) GetName() OptString {
	return s.Name
}

// GetSvmOCID returns the value of SvmOCID.
func (s *OCICreateSVMWorkflowMetadata) GetSvmOCID() OptString {
	return s.SvmOCID
}

// GetLifs returns the value of Lifs.
func (s *OCICreateSVMWorkflowMetadata) GetLifs() []SvmLif {
	return s.Lifs
}

// SetName sets the value of Name.
func (s *OCICreateSVMWorkflowMetadata) SetName(val OptString) {
	s.Name = val
}

// SetSvmOCID sets the value of SvmOCID.
func (s *OCICreateSVMWorkflowMetadata) SetSvmOCID(val OptString) {
	s.SvmOCID = val
}

// SetLifs sets the value of Lifs.
func (s *OCICreateSVMWorkflowMetadata) SetLifs(val []SvmLif) {
	s.Lifs = val
}

// Ref: #/components/schemas/OCIOCIDVersionRef
type OCIOCIDVersionRef struct {
	// OCI resource OCID.
	Ocid string `json:"ocid"`
	// Resource version identifier.
	Version string `json:"version"`
}

// GetOcid returns the value of Ocid.
func (s *OCIOCIDVersionRef) GetOcid() string {
	return s.Ocid
}

// GetVersion returns the value of Version.
func (s *OCIOCIDVersionRef) GetVersion() string {
	return s.Version
}

// SetOcid sets the value of Ocid.
func (s *OCIOCIDVersionRef) SetOcid(val string) {
	s.Ocid = val
}

// SetVersion sets the value of Version.
func (s *OCIOCIDVersionRef) SetVersion(val string) {
	s.Version = val
}

// NewOptBool returns new OptBool with value set to v.
func NewOptBool(v bool) OptBool {
	return OptBool{
		Value: v,
		Set:   true,
	}
}

// OptBool is optional bool.
type OptBool struct {
	Value bool
	Set   bool
}

// IsSet returns true if OptBool was set.
func (o OptBool) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptBool) Reset() {
	var v bool
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptBool) SetTo(v bool) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptBool) Get() (v bool, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptBool) Or(d bool) bool {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptDeleteSvmReq returns new OptDeleteSvmReq with value set to v.
func NewOptDeleteSvmReq(v DeleteSvmReq) OptDeleteSvmReq {
	return OptDeleteSvmReq{
		Value: v,
		Set:   true,
	}
}

// OptDeleteSvmReq is optional DeleteSvmReq.
type OptDeleteSvmReq struct {
	Value DeleteSvmReq
	Set   bool
}

// IsSet returns true if OptDeleteSvmReq was set.
func (o OptDeleteSvmReq) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptDeleteSvmReq) Reset() {
	var v DeleteSvmReq
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptDeleteSvmReq) SetTo(v DeleteSvmReq) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptDeleteSvmReq) Get() (v DeleteSvmReq, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptDeleteSvmReq) Or(d DeleteSvmReq) DeleteSvmReq {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptFloat64 returns new OptFloat64 with value set to v.
func NewOptFloat64(v float64) OptFloat64 {
	return OptFloat64{
		Value: v,
		Set:   true,
	}
}

// OptFloat64 is optional float64.
type OptFloat64 struct {
	Value float64
	Set   bool
}

// IsSet returns true if OptFloat64 was set.
func (o OptFloat64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptFloat64) Reset() {
	var v float64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptFloat64) SetTo(v float64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptFloat64) Get() (v float64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptFloat64) Or(d float64) float64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptInt64 returns new OptInt64 with value set to v.
func NewOptInt64(v int64) OptInt64 {
	return OptInt64{
		Value: v,
		Set:   true,
	}
}

// OptInt64 is optional int64.
type OptInt64 struct {
	Value int64
	Set   bool
}

// IsSet returns true if OptInt64 was set.
func (o OptInt64) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptInt64) Reset() {
	var v int64
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptInt64) SetTo(v int64) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptInt64) Get() (v int64, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptInt64) Or(d int64) int64 {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOCICreatePoolWorkflowMetadata returns new OptOCICreatePoolWorkflowMetadata with value set to v.
func NewOptOCICreatePoolWorkflowMetadata(v OCICreatePoolWorkflowMetadata) OptOCICreatePoolWorkflowMetadata {
	return OptOCICreatePoolWorkflowMetadata{
		Value: v,
		Set:   true,
	}
}

// OptOCICreatePoolWorkflowMetadata is optional OCICreatePoolWorkflowMetadata.
type OptOCICreatePoolWorkflowMetadata struct {
	Value OCICreatePoolWorkflowMetadata
	Set   bool
}

// IsSet returns true if OptOCICreatePoolWorkflowMetadata was set.
func (o OptOCICreatePoolWorkflowMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOCICreatePoolWorkflowMetadata) Reset() {
	var v OCICreatePoolWorkflowMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOCICreatePoolWorkflowMetadata) SetTo(v OCICreatePoolWorkflowMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOCICreatePoolWorkflowMetadata) Get() (v OCICreatePoolWorkflowMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOCICreatePoolWorkflowMetadata) Or(d OCICreatePoolWorkflowMetadata) OCICreatePoolWorkflowMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOCICreateSVMWorkflowMetadata returns new OptOCICreateSVMWorkflowMetadata with value set to v.
func NewOptOCICreateSVMWorkflowMetadata(v OCICreateSVMWorkflowMetadata) OptOCICreateSVMWorkflowMetadata {
	return OptOCICreateSVMWorkflowMetadata{
		Value: v,
		Set:   true,
	}
}

// OptOCICreateSVMWorkflowMetadata is optional OCICreateSVMWorkflowMetadata.
type OptOCICreateSVMWorkflowMetadata struct {
	Value OCICreateSVMWorkflowMetadata
	Set   bool
}

// IsSet returns true if OptOCICreateSVMWorkflowMetadata was set.
func (o OptOCICreateSVMWorkflowMetadata) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOCICreateSVMWorkflowMetadata) Reset() {
	var v OCICreateSVMWorkflowMetadata
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOCICreateSVMWorkflowMetadata) SetTo(v OCICreateSVMWorkflowMetadata) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOCICreateSVMWorkflowMetadata) Get() (v OCICreateSVMWorkflowMetadata, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOCICreateSVMWorkflowMetadata) Or(d OCICreateSVMWorkflowMetadata) OCICreateSVMWorkflowMetadata {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptOCIOCIDVersionRef returns new OptOCIOCIDVersionRef with value set to v.
func NewOptOCIOCIDVersionRef(v OCIOCIDVersionRef) OptOCIOCIDVersionRef {
	return OptOCIOCIDVersionRef{
		Value: v,
		Set:   true,
	}
}

// OptOCIOCIDVersionRef is optional OCIOCIDVersionRef.
type OptOCIOCIDVersionRef struct {
	Value OCIOCIDVersionRef
	Set   bool
}

// IsSet returns true if OptOCIOCIDVersionRef was set.
func (o OptOCIOCIDVersionRef) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptOCIOCIDVersionRef) Reset() {
	var v OCIOCIDVersionRef
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptOCIOCIDVersionRef) SetTo(v OCIOCIDVersionRef) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptOCIOCIDVersionRef) Get() (v OCIOCIDVersionRef, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptOCIOCIDVersionRef) Or(d OCIOCIDVersionRef) OCIOCIDVersionRef {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptRbacRefreshRequest returns new OptRbacRefreshRequest with value set to v.
func NewOptRbacRefreshRequest(v RbacRefreshRequest) OptRbacRefreshRequest {
	return OptRbacRefreshRequest{
		Value: v,
		Set:   true,
	}
}

// OptRbacRefreshRequest is optional RbacRefreshRequest.
type OptRbacRefreshRequest struct {
	Value RbacRefreshRequest
	Set   bool
}

// IsSet returns true if OptRbacRefreshRequest was set.
func (o OptRbacRefreshRequest) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptRbacRefreshRequest) Reset() {
	var v RbacRefreshRequest
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptRbacRefreshRequest) SetTo(v RbacRefreshRequest) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptRbacRefreshRequest) Get() (v RbacRefreshRequest, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptRbacRefreshRequest) Or(d RbacRefreshRequest) RbacRefreshRequest {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptSecurityAttributes returns new OptSecurityAttributes with value set to v.
func NewOptSecurityAttributes(v SecurityAttributes) OptSecurityAttributes {
	return OptSecurityAttributes{
		Value: v,
		Set:   true,
	}
}

// OptSecurityAttributes is optional SecurityAttributes.
type OptSecurityAttributes struct {
	Value SecurityAttributes
	Set   bool
}

// IsSet returns true if OptSecurityAttributes was set.
func (o OptSecurityAttributes) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptSecurityAttributes) Reset() {
	var v SecurityAttributes
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptSecurityAttributes) SetTo(v SecurityAttributes) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptSecurityAttributes) Get() (v SecurityAttributes, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptSecurityAttributes) Or(d SecurityAttributes) SecurityAttributes {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptString returns new OptString with value set to v.
func NewOptString(v string) OptString {
	return OptString{
		Value: v,
		Set:   true,
	}
}

// OptString is optional string.
type OptString struct {
	Value string
	Set   bool
}

// IsSet returns true if OptString was set.
func (o OptString) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptString) Reset() {
	var v string
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptString) SetTo(v string) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptString) Get() (v string, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptString) Or(d string) string {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptTieringConfig returns new OptTieringConfig with value set to v.
func NewOptTieringConfig(v TieringConfig) OptTieringConfig {
	return OptTieringConfig{
		Value: v,
		Set:   true,
	}
}

// OptTieringConfig is optional TieringConfig.
type OptTieringConfig struct {
	Value TieringConfig
	Set   bool
}

// IsSet returns true if OptTieringConfig was set.
func (o OptTieringConfig) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptTieringConfig) Reset() {
	var v TieringConfig
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptTieringConfig) SetTo(v TieringConfig) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptTieringConfig) Get() (v TieringConfig, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptTieringConfig) Or(d TieringConfig) TieringConfig {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// NewOptWorkflowStatusError returns new OptWorkflowStatusError with value set to v.
func NewOptWorkflowStatusError(v WorkflowStatusError) OptWorkflowStatusError {
	return OptWorkflowStatusError{
		Value: v,
		Set:   true,
	}
}

// OptWorkflowStatusError is optional WorkflowStatusError.
type OptWorkflowStatusError struct {
	Value WorkflowStatusError
	Set   bool
}

// IsSet returns true if OptWorkflowStatusError was set.
func (o OptWorkflowStatusError) IsSet() bool { return o.Set }

// Reset unsets value.
func (o *OptWorkflowStatusError) Reset() {
	var v WorkflowStatusError
	o.Value = v
	o.Set = false
}

// SetTo sets value to v.
func (o *OptWorkflowStatusError) SetTo(v WorkflowStatusError) {
	o.Set = true
	o.Value = v
}

// Get returns value and boolean that denotes whether value was set.
func (o OptWorkflowStatusError) Get() (v WorkflowStatusError, ok bool) {
	if !o.Set {
		return v, false
	}
	return o.Value, true
}

// Or returns value if set, or given parameter if does not.
func (o OptWorkflowStatusError) Or(d WorkflowStatusError) WorkflowStatusError {
	if v, ok := o.Get(); ok {
		return v
	}
	return d
}

// Ref: #/components/schemas/PoolOperationErrorResponse
type PoolOperationErrorResponse struct {
	// Operation status.
	Status string `json:"status"`
	// Pool OCID for the request.
	PoolOCID string `json:"poolOCID"`
	// Error message for the failed operation.
	ErrorMessage string `json:"errorMessage"`
}

// GetStatus returns the value of Status.
func (s *PoolOperationErrorResponse) GetStatus() string {
	return s.Status
}

// GetPoolOCID returns the value of PoolOCID.
func (s *PoolOperationErrorResponse) GetPoolOCID() string {
	return s.PoolOCID
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *PoolOperationErrorResponse) GetErrorMessage() string {
	return s.ErrorMessage
}

// SetStatus sets the value of Status.
func (s *PoolOperationErrorResponse) SetStatus(val string) {
	s.Status = val
}

// SetPoolOCID sets the value of PoolOCID.
func (s *PoolOperationErrorResponse) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *PoolOperationErrorResponse) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

// PoolOperationErrorResponseHeaders wraps PoolOperationErrorResponse with response headers.
type PoolOperationErrorResponseHeaders struct {
	OpcRequestID string
	Response     PoolOperationErrorResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *PoolOperationErrorResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *PoolOperationErrorResponseHeaders) GetResponse() PoolOperationErrorResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *PoolOperationErrorResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *PoolOperationErrorResponseHeaders) SetResponse(val PoolOperationErrorResponse) {
	s.Response = val
}

// Ref: #/components/schemas/RbacRefreshAcceptedResponse
type RbacRefreshAcceptedResponse struct {
	// Current workflow status for the RBAC refresh operation.
	Status string `json:"status"`
	// Workflow identifier used to poll operation status.
	WorkflowId string `json:"workflowId"`
	// Pool OCID for the requested pool.
	PoolOCID string `json:"poolOCID"`
}

// GetStatus returns the value of Status.
func (s *RbacRefreshAcceptedResponse) GetStatus() string {
	return s.Status
}

// GetWorkflowId returns the value of WorkflowId.
func (s *RbacRefreshAcceptedResponse) GetWorkflowId() string {
	return s.WorkflowId
}

// GetPoolOCID returns the value of PoolOCID.
func (s *RbacRefreshAcceptedResponse) GetPoolOCID() string {
	return s.PoolOCID
}

// SetStatus sets the value of Status.
func (s *RbacRefreshAcceptedResponse) SetStatus(val string) {
	s.Status = val
}

// SetWorkflowId sets the value of WorkflowId.
func (s *RbacRefreshAcceptedResponse) SetWorkflowId(val string) {
	s.WorkflowId = val
}

// SetPoolOCID sets the value of PoolOCID.
func (s *RbacRefreshAcceptedResponse) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// RbacRefreshAcceptedResponseHeaders wraps RbacRefreshAcceptedResponse with response headers.
type RbacRefreshAcceptedResponseHeaders struct {
	OpcRequestID string
	Response     RbacRefreshAcceptedResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *RbacRefreshAcceptedResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *RbacRefreshAcceptedResponseHeaders) GetResponse() RbacRefreshAcceptedResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *RbacRefreshAcceptedResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *RbacRefreshAcceptedResponseHeaders) SetResponse(val RbacRefreshAcceptedResponse) {
	s.Response = val
}

func (*RbacRefreshAcceptedResponseHeaders) rbacRefreshPoolRes() {}

type RbacRefreshPoolBadRequest PoolOperationErrorResponseHeaders

func (*RbacRefreshPoolBadRequest) rbacRefreshPoolRes() {}

// RbacRefreshPoolDefaultErrorStatusCodeWithHeaders wraps PoolOperationErrorResponse with status code and response headers.
type RbacRefreshPoolDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     PoolOperationErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *RbacRefreshPoolDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *RbacRefreshPoolDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *RbacRefreshPoolDefaultErrorStatusCodeWithHeaders) GetResponse() PoolOperationErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *RbacRefreshPoolDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *RbacRefreshPoolDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *RbacRefreshPoolDefaultErrorStatusCodeWithHeaders) SetResponse(val PoolOperationErrorResponse) {
	s.Response = val
}

func (*RbacRefreshPoolDefaultErrorStatusCodeWithHeaders) rbacRefreshPoolRes() {}

type RbacRefreshPoolInternalServerError PoolOperationErrorResponseHeaders

func (*RbacRefreshPoolInternalServerError) rbacRefreshPoolRes() {}

type RbacRefreshPoolNotFound PoolOperationErrorResponseHeaders

func (*RbacRefreshPoolNotFound) rbacRefreshPoolRes() {}

// Ref: #/components/schemas/RbacRefreshRequest
type RbacRefreshRequest struct {
	// When provided, the service uses this path to fetch the RBAC file.
	// When omitted or null, the service fetch the path from the environment variable if set.
	RbacFilePath OptString `json:"rbacFilePath"`
}

// GetRbacFilePath returns the value of RbacFilePath.
func (s *RbacRefreshRequest) GetRbacFilePath() OptString {
	return s.RbacFilePath
}

// SetRbacFilePath sets the value of RbacFilePath.
func (s *RbacRefreshRequest) SetRbacFilePath(val OptString) {
	s.RbacFilePath = val
}

// Ref: #/components/schemas/RotateFabricPoolKeysAcceptedResponse
type RotateFabricPoolKeysAcceptedResponse struct {
	// Outcome of the rotate request.
	Status RotateFabricPoolKeysAcceptedResponseStatus `json:"status"`
	// Workflow identifier used to poll operation status.
	WorkflowId OptString `json:"workflowId"`
	// Pool OCID for the requested pool.
	PoolOCID string `json:"poolOCID"`
}

// GetStatus returns the value of Status.
func (s *RotateFabricPoolKeysAcceptedResponse) GetStatus() RotateFabricPoolKeysAcceptedResponseStatus {
	return s.Status
}

// GetWorkflowId returns the value of WorkflowId.
func (s *RotateFabricPoolKeysAcceptedResponse) GetWorkflowId() OptString {
	return s.WorkflowId
}

// GetPoolOCID returns the value of PoolOCID.
func (s *RotateFabricPoolKeysAcceptedResponse) GetPoolOCID() string {
	return s.PoolOCID
}

// SetStatus sets the value of Status.
func (s *RotateFabricPoolKeysAcceptedResponse) SetStatus(val RotateFabricPoolKeysAcceptedResponseStatus) {
	s.Status = val
}

// SetWorkflowId sets the value of WorkflowId.
func (s *RotateFabricPoolKeysAcceptedResponse) SetWorkflowId(val OptString) {
	s.WorkflowId = val
}

// SetPoolOCID sets the value of PoolOCID.
func (s *RotateFabricPoolKeysAcceptedResponse) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// RotateFabricPoolKeysAcceptedResponseHeaders wraps RotateFabricPoolKeysAcceptedResponse with response headers.
type RotateFabricPoolKeysAcceptedResponseHeaders struct {
	OpcRequestID string
	Response     RotateFabricPoolKeysAcceptedResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *RotateFabricPoolKeysAcceptedResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *RotateFabricPoolKeysAcceptedResponseHeaders) GetResponse() RotateFabricPoolKeysAcceptedResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *RotateFabricPoolKeysAcceptedResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *RotateFabricPoolKeysAcceptedResponseHeaders) SetResponse(val RotateFabricPoolKeysAcceptedResponse) {
	s.Response = val
}

func (*RotateFabricPoolKeysAcceptedResponseHeaders) rotateFabricPoolKeysRes() {}

// Outcome of the rotate request.
type RotateFabricPoolKeysAcceptedResponseStatus string

const (
	RotateFabricPoolKeysAcceptedResponseStatusInProgress RotateFabricPoolKeysAcceptedResponseStatus = "in_progress"
	RotateFabricPoolKeysAcceptedResponseStatusNoChange   RotateFabricPoolKeysAcceptedResponseStatus = "no_change"
)

// AllValues returns all RotateFabricPoolKeysAcceptedResponseStatus values.
func (RotateFabricPoolKeysAcceptedResponseStatus) AllValues() []RotateFabricPoolKeysAcceptedResponseStatus {
	return []RotateFabricPoolKeysAcceptedResponseStatus{
		RotateFabricPoolKeysAcceptedResponseStatusInProgress,
		RotateFabricPoolKeysAcceptedResponseStatusNoChange,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s RotateFabricPoolKeysAcceptedResponseStatus) MarshalText() ([]byte, error) {
	switch s {
	case RotateFabricPoolKeysAcceptedResponseStatusInProgress:
		return []byte(s), nil
	case RotateFabricPoolKeysAcceptedResponseStatusNoChange:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *RotateFabricPoolKeysAcceptedResponseStatus) UnmarshalText(data []byte) error {
	switch RotateFabricPoolKeysAcceptedResponseStatus(data) {
	case RotateFabricPoolKeysAcceptedResponseStatusInProgress:
		*s = RotateFabricPoolKeysAcceptedResponseStatusInProgress
		return nil
	case RotateFabricPoolKeysAcceptedResponseStatusNoChange:
		*s = RotateFabricPoolKeysAcceptedResponseStatusNoChange
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

type RotateFabricPoolKeysBadRequest PoolOperationErrorResponseHeaders

func (*RotateFabricPoolKeysBadRequest) rotateFabricPoolKeysRes() {}

type RotateFabricPoolKeysConflict PoolOperationErrorResponseHeaders

func (*RotateFabricPoolKeysConflict) rotateFabricPoolKeysRes() {}

// RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders wraps PoolOperationErrorResponse with status code and response headers.
type RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     PoolOperationErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders) GetResponse() PoolOperationErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders) SetResponse(val PoolOperationErrorResponse) {
	s.Response = val
}

func (*RotateFabricPoolKeysDefaultErrorStatusCodeWithHeaders) rotateFabricPoolKeysRes() {}

type RotateFabricPoolKeysForbidden PoolOperationErrorResponseHeaders

func (*RotateFabricPoolKeysForbidden) rotateFabricPoolKeysRes() {}

type RotateFabricPoolKeysInternalServerError PoolOperationErrorResponseHeaders

func (*RotateFabricPoolKeysInternalServerError) rotateFabricPoolKeysRes() {}

type RotateFabricPoolKeysNotFound PoolOperationErrorResponseHeaders

func (*RotateFabricPoolKeysNotFound) rotateFabricPoolKeysRes() {}

// Ref: #/components/schemas/RotateFabricPoolKeysRequest
type RotateFabricPoolKeysRequest struct {
	// OCID of the OCI Vault Secret.
	SecretOCID string `json:"secretOCID"`
}

// GetSecretOCID returns the value of SecretOCID.
func (s *RotateFabricPoolKeysRequest) GetSecretOCID() string {
	return s.SecretOCID
}

// SetSecretOCID sets the value of SecretOCID.
func (s *RotateFabricPoolKeysRequest) SetSecretOCID(val string) {
	s.SecretOCID = val
}

type RotateFabricPoolKeysTooManyRequests PoolOperationErrorResponseHeaders

func (*RotateFabricPoolKeysTooManyRequests) rotateFabricPoolKeysRes() {}

type RotateFabricPoolKeysUnauthorized PoolOperationErrorResponseHeaders

func (*RotateFabricPoolKeysUnauthorized) rotateFabricPoolKeysRes() {}

// Ref: #/components/schemas/SecurityAttributeValue
type SecurityAttributeValue struct {
	// Attribute value. Must satisfy the validator (if any) configured on
	// the security-attribute key in the tenancy.
	Value string `json:"value"`
	// Enforcement mode for this attribute.
	Mode SecurityAttributeValueMode `json:"mode"`
}

// GetValue returns the value of Value.
func (s *SecurityAttributeValue) GetValue() string {
	return s.Value
}

// GetMode returns the value of Mode.
func (s *SecurityAttributeValue) GetMode() SecurityAttributeValueMode {
	return s.Mode
}

// SetValue sets the value of Value.
func (s *SecurityAttributeValue) SetValue(val string) {
	s.Value = val
}

// SetMode sets the value of Mode.
func (s *SecurityAttributeValue) SetMode(val SecurityAttributeValueMode) {
	s.Mode = val
}

// Enforcement mode for this attribute.
type SecurityAttributeValueMode string

const (
	SecurityAttributeValueModeEnforce SecurityAttributeValueMode = "enforce"
	SecurityAttributeValueModeAudit   SecurityAttributeValueMode = "audit"
)

// AllValues returns all SecurityAttributeValueMode values.
func (SecurityAttributeValueMode) AllValues() []SecurityAttributeValueMode {
	return []SecurityAttributeValueMode{
		SecurityAttributeValueModeEnforce,
		SecurityAttributeValueModeAudit,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SecurityAttributeValueMode) MarshalText() ([]byte, error) {
	switch s {
	case SecurityAttributeValueModeEnforce:
		return []byte(s), nil
	case SecurityAttributeValueModeAudit:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SecurityAttributeValueMode) UnmarshalText(data []byte) error {
	switch SecurityAttributeValueMode(data) {
	case SecurityAttributeValueModeEnforce:
		*s = SecurityAttributeValueModeEnforce
		return nil
	case SecurityAttributeValueModeAudit:
		*s = SecurityAttributeValueModeAudit
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// OCI Zero Trust Packet Routing (ZPR) security attributes
// Example payload:
// ```
// "vcp_zpr": {
// "ns1": {
// "value": "{\"app\": {\"value\": \"app1\", \"mode\": \"enforce\"}}",
// "mode": "enforce"
// }
// }
// ```.
// Ref: #/components/schemas/SecurityAttributes
type SecurityAttributes map[string]SecurityAttributesItem

func (s *SecurityAttributes) init() SecurityAttributes {
	m := *s
	if m == nil {
		m = map[string]SecurityAttributesItem{}
		*s = m
	}
	return m
}

// Map of attribute name to attribute value+mode for one namespace.
type SecurityAttributesItem map[string]SecurityAttributeValue

func (s *SecurityAttributesItem) init() SecurityAttributesItem {
	m := *s
	if m == nil {
		m = map[string]SecurityAttributeValue{}
		*s = m
	}
	return m
}

// StandardError400Headers wraps Error with response headers.
type StandardError400Headers struct {
	OpcRequestID string
	Response     Error
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *StandardError400Headers) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *StandardError400Headers) GetResponse() Error {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *StandardError400Headers) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *StandardError400Headers) SetResponse(val Error) {
	s.Response = val
}

func (*StandardError400Headers) getHealthRes() {}

// StandardError401Headers wraps Error with response headers.
type StandardError401Headers struct {
	OpcRequestID string
	Response     Error
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *StandardError401Headers) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *StandardError401Headers) GetResponse() Error {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *StandardError401Headers) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *StandardError401Headers) SetResponse(val Error) {
	s.Response = val
}

func (*StandardError401Headers) getHealthRes() {}

// StandardError403Headers wraps Error with response headers.
type StandardError403Headers struct {
	OpcRequestID string
	Response     Error
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *StandardError403Headers) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *StandardError403Headers) GetResponse() Error {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *StandardError403Headers) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *StandardError403Headers) SetResponse(val Error) {
	s.Response = val
}

func (*StandardError403Headers) getHealthRes() {}

// StandardError404Headers wraps Error with response headers.
type StandardError404Headers struct {
	OpcRequestID string
	Response     Error
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *StandardError404Headers) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *StandardError404Headers) GetResponse() Error {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *StandardError404Headers) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *StandardError404Headers) SetResponse(val Error) {
	s.Response = val
}

func (*StandardError404Headers) getHealthRes() {}

// StandardError429Headers wraps Error with response headers.
type StandardError429Headers struct {
	OpcRequestID string
	Response     Error
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *StandardError429Headers) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *StandardError429Headers) GetResponse() Error {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *StandardError429Headers) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *StandardError429Headers) SetResponse(val Error) {
	s.Response = val
}

func (*StandardError429Headers) getHealthRes() {}

// StandardError500Headers wraps Error with response headers.
type StandardError500Headers struct {
	OpcRequestID string
	Response     Error
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *StandardError500Headers) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *StandardError500Headers) GetResponse() Error {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *StandardError500Headers) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *StandardError500Headers) SetResponse(val Error) {
	s.Response = val
}

func (*StandardError500Headers) getHealthRes() {}

// Ref: #/components/schemas/SvmLif
type SvmLif struct {
	Name      OptString `json:"name"`
	IpAddress OptString `json:"ipAddress"`
	Node      OptString `json:"node"`
	// UUID of the corresponding node.
	NodeUUID OptString `json:"nodeUUID"`
	// HA pair label in cloud.ha_pair for the LIF home node, formatted as ha_pair-<index>.
	HaPair    OptString             `json:"haPair"`
	Protocols []SvmLifProtocolsItem `json:"protocols"`
}

// GetName returns the value of Name.
func (s *SvmLif) GetName() OptString {
	return s.Name
}

// GetIpAddress returns the value of IpAddress.
func (s *SvmLif) GetIpAddress() OptString {
	return s.IpAddress
}

// GetNode returns the value of Node.
func (s *SvmLif) GetNode() OptString {
	return s.Node
}

// GetNodeUUID returns the value of NodeUUID.
func (s *SvmLif) GetNodeUUID() OptString {
	return s.NodeUUID
}

// GetHaPair returns the value of HaPair.
func (s *SvmLif) GetHaPair() OptString {
	return s.HaPair
}

// GetProtocols returns the value of Protocols.
func (s *SvmLif) GetProtocols() []SvmLifProtocolsItem {
	return s.Protocols
}

// SetName sets the value of Name.
func (s *SvmLif) SetName(val OptString) {
	s.Name = val
}

// SetIpAddress sets the value of IpAddress.
func (s *SvmLif) SetIpAddress(val OptString) {
	s.IpAddress = val
}

// SetNode sets the value of Node.
func (s *SvmLif) SetNode(val OptString) {
	s.Node = val
}

// SetNodeUUID sets the value of NodeUUID.
func (s *SvmLif) SetNodeUUID(val OptString) {
	s.NodeUUID = val
}

// SetHaPair sets the value of HaPair.
func (s *SvmLif) SetHaPair(val OptString) {
	s.HaPair = val
}

// SetProtocols sets the value of Protocols.
func (s *SvmLif) SetProtocols(val []SvmLifProtocolsItem) {
	s.Protocols = val
}

type SvmLifProtocolsItem string

const (
	SvmLifProtocolsItemIscsi SvmLifProtocolsItem = "iscsi"
	SvmLifProtocolsItemNvme  SvmLifProtocolsItem = "nvme"
	SvmLifProtocolsItemNfs   SvmLifProtocolsItem = "nfs"
	SvmLifProtocolsItemCifs  SvmLifProtocolsItem = "cifs"
	SvmLifProtocolsItemS3    SvmLifProtocolsItem = "s3"
)

// AllValues returns all SvmLifProtocolsItem values.
func (SvmLifProtocolsItem) AllValues() []SvmLifProtocolsItem {
	return []SvmLifProtocolsItem{
		SvmLifProtocolsItemIscsi,
		SvmLifProtocolsItemNvme,
		SvmLifProtocolsItemNfs,
		SvmLifProtocolsItemCifs,
		SvmLifProtocolsItemS3,
	}
}

// MarshalText implements encoding.TextMarshaler.
func (s SvmLifProtocolsItem) MarshalText() ([]byte, error) {
	switch s {
	case SvmLifProtocolsItemIscsi:
		return []byte(s), nil
	case SvmLifProtocolsItemNvme:
		return []byte(s), nil
	case SvmLifProtocolsItemNfs:
		return []byte(s), nil
	case SvmLifProtocolsItemCifs:
		return []byte(s), nil
	case SvmLifProtocolsItemS3:
		return []byte(s), nil
	default:
		return nil, errors.Errorf("invalid value: %q", s)
	}
}

// UnmarshalText implements encoding.TextUnmarshaler.
func (s *SvmLifProtocolsItem) UnmarshalText(data []byte) error {
	switch SvmLifProtocolsItem(data) {
	case SvmLifProtocolsItemIscsi:
		*s = SvmLifProtocolsItemIscsi
		return nil
	case SvmLifProtocolsItemNvme:
		*s = SvmLifProtocolsItemNvme
		return nil
	case SvmLifProtocolsItemNfs:
		*s = SvmLifProtocolsItemNfs
		return nil
	case SvmLifProtocolsItemCifs:
		*s = SvmLifProtocolsItemCifs
		return nil
	case SvmLifProtocolsItemS3:
		*s = SvmLifProtocolsItemS3
		return nil
	default:
		return errors.Errorf("invalid value: %q", data)
	}
}

// Ref: #/components/schemas/SvmOperationErrorResponse
type SvmOperationErrorResponse struct {
	// Operation status.
	Status string `json:"status"`
	// SVM OCID for the request.
	SvmOCID string `json:"svmOCID"`
	// Error message for the failed operation.
	ErrorMessage string `json:"errorMessage"`
}

// GetStatus returns the value of Status.
func (s *SvmOperationErrorResponse) GetStatus() string {
	return s.Status
}

// GetSvmOCID returns the value of SvmOCID.
func (s *SvmOperationErrorResponse) GetSvmOCID() string {
	return s.SvmOCID
}

// GetErrorMessage returns the value of ErrorMessage.
func (s *SvmOperationErrorResponse) GetErrorMessage() string {
	return s.ErrorMessage
}

// SetStatus sets the value of Status.
func (s *SvmOperationErrorResponse) SetStatus(val string) {
	s.Status = val
}

// SetSvmOCID sets the value of SvmOCID.
func (s *SvmOperationErrorResponse) SetSvmOCID(val string) {
	s.SvmOCID = val
}

// SetErrorMessage sets the value of ErrorMessage.
func (s *SvmOperationErrorResponse) SetErrorMessage(val string) {
	s.ErrorMessage = val
}

// SvmOperationErrorResponseHeaders wraps SvmOperationErrorResponse with response headers.
type SvmOperationErrorResponseHeaders struct {
	OpcRequestID string
	Response     SvmOperationErrorResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *SvmOperationErrorResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *SvmOperationErrorResponseHeaders) GetResponse() SvmOperationErrorResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *SvmOperationErrorResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *SvmOperationErrorResponseHeaders) SetResponse(val SvmOperationErrorResponse) {
	s.Response = val
}

// Cloud tiering configuration pointing at an OCI Object Storage bucket reached
// via its S3-compatible endpoint. All four fields are required when the parent
// request supplies a tieringConfig object.
// Ref: #/components/schemas/TieringConfig
type TieringConfig struct {
	// OCI Vault secret OCID holding the S3-compatible Customer Secret Key
	// used to authenticate against the bucket.
	SecretId string `json:"secretId"`
	// OCI Object Storage namespace that owns the bucket.
	Namespace string `json:"namespace"`
	// Name of the OCI Object Storage bucket to tier cold data into.
	BucketName string `json:"bucketName"`
	// Hostname of the S3-compatible endpoint for the bucket.
	ServerName string `json:"serverName"`
}

// GetSecretId returns the value of SecretId.
func (s *TieringConfig) GetSecretId() string {
	return s.SecretId
}

// GetNamespace returns the value of Namespace.
func (s *TieringConfig) GetNamespace() string {
	return s.Namespace
}

// GetBucketName returns the value of BucketName.
func (s *TieringConfig) GetBucketName() string {
	return s.BucketName
}

// GetServerName returns the value of ServerName.
func (s *TieringConfig) GetServerName() string {
	return s.ServerName
}

// SetSecretId sets the value of SecretId.
func (s *TieringConfig) SetSecretId(val string) {
	s.SecretId = val
}

// SetNamespace sets the value of Namespace.
func (s *TieringConfig) SetNamespace(val string) {
	s.Namespace = val
}

// SetBucketName sets the value of BucketName.
func (s *TieringConfig) SetBucketName(val string) {
	s.BucketName = val
}

// SetServerName sets the value of ServerName.
func (s *TieringConfig) SetServerName(val string) {
	s.ServerName = val
}

// Ref: #/components/schemas/UpdatePoolAcceptedResponse
type UpdatePoolAcceptedResponse struct {
	// Current workflow status for the update operation.
	Status string `json:"status"`
	// Workflow identifier used to poll operation status.
	WorkflowId string `json:"workflowId"`
	// OCID of the pool being updated.
	PoolOCID string `json:"poolOCID"`
}

// GetStatus returns the value of Status.
func (s *UpdatePoolAcceptedResponse) GetStatus() string {
	return s.Status
}

// GetWorkflowId returns the value of WorkflowId.
func (s *UpdatePoolAcceptedResponse) GetWorkflowId() string {
	return s.WorkflowId
}

// GetPoolOCID returns the value of PoolOCID.
func (s *UpdatePoolAcceptedResponse) GetPoolOCID() string {
	return s.PoolOCID
}

// SetStatus sets the value of Status.
func (s *UpdatePoolAcceptedResponse) SetStatus(val string) {
	s.Status = val
}

// SetWorkflowId sets the value of WorkflowId.
func (s *UpdatePoolAcceptedResponse) SetWorkflowId(val string) {
	s.WorkflowId = val
}

// SetPoolOCID sets the value of PoolOCID.
func (s *UpdatePoolAcceptedResponse) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// UpdatePoolAcceptedResponseHeaders wraps UpdatePoolAcceptedResponse with response headers.
type UpdatePoolAcceptedResponseHeaders struct {
	OpcRequestID string
	Response     UpdatePoolAcceptedResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *UpdatePoolAcceptedResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *UpdatePoolAcceptedResponseHeaders) GetResponse() UpdatePoolAcceptedResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *UpdatePoolAcceptedResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *UpdatePoolAcceptedResponseHeaders) SetResponse(val UpdatePoolAcceptedResponse) {
	s.Response = val
}

func (*UpdatePoolAcceptedResponseHeaders) updatePoolRes() {}

type UpdatePoolBadRequest PoolOperationErrorResponseHeaders

func (*UpdatePoolBadRequest) updatePoolRes() {}

type UpdatePoolConflict PoolOperationErrorResponseHeaders

func (*UpdatePoolConflict) updatePoolRes() {}

// UpdatePoolDefaultErrorStatusCodeWithHeaders wraps PoolOperationErrorResponse with status code and response headers.
type UpdatePoolDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     PoolOperationErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *UpdatePoolDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *UpdatePoolDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *UpdatePoolDefaultErrorStatusCodeWithHeaders) GetResponse() PoolOperationErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *UpdatePoolDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *UpdatePoolDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *UpdatePoolDefaultErrorStatusCodeWithHeaders) SetResponse(val PoolOperationErrorResponse) {
	s.Response = val
}

func (*UpdatePoolDefaultErrorStatusCodeWithHeaders) updatePoolRes() {}

type UpdatePoolForbidden PoolOperationErrorResponseHeaders

func (*UpdatePoolForbidden) updatePoolRes() {}

type UpdatePoolInternalServerError PoolOperationErrorResponseHeaders

func (*UpdatePoolInternalServerError) updatePoolRes() {}

type UpdatePoolNotFound PoolOperationErrorResponseHeaders

func (*UpdatePoolNotFound) updatePoolRes() {}

// Update pool request body. All fields are optional; include only the fields
// you intend to change. Metadata-only updates (for example kmsKeyId, nsgIds,
// or securityAttributes) are supported without resizing or changing throughput.
// When provided, nodeCapacities and dataEndpointCount are mutually exclusive.
// Ref: #/components/schemas/UpdatePoolRequest
type UpdatePoolRequest struct {
	// Optional total target throughput for the pool in GBps. When provided, must be > 0.
	ThroughputGBps OptFloat64 `json:"throughputGBps"`
	// Absolute number of endpoints that should exist in the cluster. Must be >= 2 and even.
	// Mutually exclusive with nodeCapacities. Allowed only for Single AD clusters.
	DataEndpointCount OptInt64 `json:"dataEndpointCount"`
	// Per-node capacity targets for the update. Mutually exclusive with
	// `dataEndpointCount`. Each element identifies one VM and its desired
	// `sizeInGiB`; see `#/components/schemas/NodeCapacity` for field semantics
	// and capacity accounting rules.
	NodeCapacities []NodeCapacity `json:"nodeCapacities"`
	// OCI secret reference for admin password.
	OciAdminPassword OptOCIOCIDVersionRef `json:"ociAdminPassword"`
	// Updated KMS key OCID for data encryption.
	KmsKeyId OptString `json:"kmsKeyId"`
	// Updated list of Network Security Group OCIDs.
	NsgIds []string `json:"nsgIds"`
	// Updated OCI Zero Trust Packet Routing (ZPR) security attributes.
	SecurityAttributes OptSecurityAttributes `json:"securityAttributes"`
}

// GetThroughputGBps returns the value of ThroughputGBps.
func (s *UpdatePoolRequest) GetThroughputGBps() OptFloat64 {
	return s.ThroughputGBps
}

// GetDataEndpointCount returns the value of DataEndpointCount.
func (s *UpdatePoolRequest) GetDataEndpointCount() OptInt64 {
	return s.DataEndpointCount
}

// GetNodeCapacities returns the value of NodeCapacities.
func (s *UpdatePoolRequest) GetNodeCapacities() []NodeCapacity {
	return s.NodeCapacities
}

// GetOciAdminPassword returns the value of OciAdminPassword.
func (s *UpdatePoolRequest) GetOciAdminPassword() OptOCIOCIDVersionRef {
	return s.OciAdminPassword
}

// GetKmsKeyId returns the value of KmsKeyId.
func (s *UpdatePoolRequest) GetKmsKeyId() OptString {
	return s.KmsKeyId
}

// GetNsgIds returns the value of NsgIds.
func (s *UpdatePoolRequest) GetNsgIds() []string {
	return s.NsgIds
}

// GetSecurityAttributes returns the value of SecurityAttributes.
func (s *UpdatePoolRequest) GetSecurityAttributes() OptSecurityAttributes {
	return s.SecurityAttributes
}

// SetThroughputGBps sets the value of ThroughputGBps.
func (s *UpdatePoolRequest) SetThroughputGBps(val OptFloat64) {
	s.ThroughputGBps = val
}

// SetDataEndpointCount sets the value of DataEndpointCount.
func (s *UpdatePoolRequest) SetDataEndpointCount(val OptInt64) {
	s.DataEndpointCount = val
}

// SetNodeCapacities sets the value of NodeCapacities.
func (s *UpdatePoolRequest) SetNodeCapacities(val []NodeCapacity) {
	s.NodeCapacities = val
}

// SetOciAdminPassword sets the value of OciAdminPassword.
func (s *UpdatePoolRequest) SetOciAdminPassword(val OptOCIOCIDVersionRef) {
	s.OciAdminPassword = val
}

// SetKmsKeyId sets the value of KmsKeyId.
func (s *UpdatePoolRequest) SetKmsKeyId(val OptString) {
	s.KmsKeyId = val
}

// SetNsgIds sets the value of NsgIds.
func (s *UpdatePoolRequest) SetNsgIds(val []string) {
	s.NsgIds = val
}

// SetSecurityAttributes sets the value of SecurityAttributes.
func (s *UpdatePoolRequest) SetSecurityAttributes(val OptSecurityAttributes) {
	s.SecurityAttributes = val
}

type UpdatePoolUnauthorized PoolOperationErrorResponseHeaders

func (*UpdatePoolUnauthorized) updatePoolRes() {}

// Ref: #/components/schemas/UpgradePoolAcceptedResponse
type UpgradePoolAcceptedResponse struct {
	// Current workflow status for the upgrade operation.
	Status string `json:"status"`
	// Workflow identifier used to poll operation status.
	WorkflowId string `json:"workflowId"`
	// Pool OCID for the requested pool.
	PoolOCID string `json:"poolOCID"`
}

// GetStatus returns the value of Status.
func (s *UpgradePoolAcceptedResponse) GetStatus() string {
	return s.Status
}

// GetWorkflowId returns the value of WorkflowId.
func (s *UpgradePoolAcceptedResponse) GetWorkflowId() string {
	return s.WorkflowId
}

// GetPoolOCID returns the value of PoolOCID.
func (s *UpgradePoolAcceptedResponse) GetPoolOCID() string {
	return s.PoolOCID
}

// SetStatus sets the value of Status.
func (s *UpgradePoolAcceptedResponse) SetStatus(val string) {
	s.Status = val
}

// SetWorkflowId sets the value of WorkflowId.
func (s *UpgradePoolAcceptedResponse) SetWorkflowId(val string) {
	s.WorkflowId = val
}

// SetPoolOCID sets the value of PoolOCID.
func (s *UpgradePoolAcceptedResponse) SetPoolOCID(val string) {
	s.PoolOCID = val
}

// UpgradePoolAcceptedResponseHeaders wraps UpgradePoolAcceptedResponse with response headers.
type UpgradePoolAcceptedResponseHeaders struct {
	OpcRequestID string
	Response     UpgradePoolAcceptedResponse
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *UpgradePoolAcceptedResponseHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *UpgradePoolAcceptedResponseHeaders) GetResponse() UpgradePoolAcceptedResponse {
	return s.Response
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *UpgradePoolAcceptedResponseHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *UpgradePoolAcceptedResponseHeaders) SetResponse(val UpgradePoolAcceptedResponse) {
	s.Response = val
}

func (*UpgradePoolAcceptedResponseHeaders) upgradePoolRes() {}

type UpgradePoolBadRequest PoolOperationErrorResponseHeaders

func (*UpgradePoolBadRequest) upgradePoolRes() {}

type UpgradePoolConflict PoolOperationErrorResponseHeaders

func (*UpgradePoolConflict) upgradePoolRes() {}

// UpgradePoolDefaultErrorStatusCodeWithHeaders wraps PoolOperationErrorResponse with status code and response headers.
type UpgradePoolDefaultErrorStatusCodeWithHeaders struct {
	StatusCode   int
	OpcRequestID string
	Response     PoolOperationErrorResponse
}

// GetStatusCode returns the value of StatusCode.
func (s *UpgradePoolDefaultErrorStatusCodeWithHeaders) GetStatusCode() int {
	return s.StatusCode
}

// GetOpcRequestID returns the value of OpcRequestID.
func (s *UpgradePoolDefaultErrorStatusCodeWithHeaders) GetOpcRequestID() string {
	return s.OpcRequestID
}

// GetResponse returns the value of Response.
func (s *UpgradePoolDefaultErrorStatusCodeWithHeaders) GetResponse() PoolOperationErrorResponse {
	return s.Response
}

// SetStatusCode sets the value of StatusCode.
func (s *UpgradePoolDefaultErrorStatusCodeWithHeaders) SetStatusCode(val int) {
	s.StatusCode = val
}

// SetOpcRequestID sets the value of OpcRequestID.
func (s *UpgradePoolDefaultErrorStatusCodeWithHeaders) SetOpcRequestID(val string) {
	s.OpcRequestID = val
}

// SetResponse sets the value of Response.
func (s *UpgradePoolDefaultErrorStatusCodeWithHeaders) SetResponse(val PoolOperationErrorResponse) {
	s.Response = val
}

func (*UpgradePoolDefaultErrorStatusCodeWithHeaders) upgradePoolRes() {}

type UpgradePoolInternalServerError PoolOperationErrorResponseHeaders

func (*UpgradePoolInternalServerError) upgradePoolRes() {}

type UpgradePoolNotFound PoolOperationErrorResponseHeaders

func (*UpgradePoolNotFound) upgradePoolRes() {}

// Ref: #/components/schemas/UpgradePoolRequest
type UpgradePoolRequest struct {
	// Target ONTAP version (e.g. "9.20.0").
	TargetOntapVersion string `json:"targetOntapVersion"`
	// Full OCI Object Storage path to the ONTAP .tgz upgrade image
	// in the format /n/{namespace}/b/{bucket}/o/{objectName}
	// (e.g. "/n/controlplane-nb/b/vsaimage/o/image-9-20-1P2.tgz").
	VsaImagePath string `json:"vsaImagePath"`
	// When true, proceed with the upgrade even if the pool's current
	// build info already matches the target images. Default false.
	ForceUpgrade OptBool `json:"forceUpgrade"`
	// When true, skip the RBAC refresh after the upgrade completes.
	// Default false (RBAC refresh runs by default).
	SkipUpdateRBAC OptBool `json:"skipUpdateRBAC"`
}

// GetTargetOntapVersion returns the value of TargetOntapVersion.
func (s *UpgradePoolRequest) GetTargetOntapVersion() string {
	return s.TargetOntapVersion
}

// GetVsaImagePath returns the value of VsaImagePath.
func (s *UpgradePoolRequest) GetVsaImagePath() string {
	return s.VsaImagePath
}

// GetForceUpgrade returns the value of ForceUpgrade.
func (s *UpgradePoolRequest) GetForceUpgrade() OptBool {
	return s.ForceUpgrade
}

// GetSkipUpdateRBAC returns the value of SkipUpdateRBAC.
func (s *UpgradePoolRequest) GetSkipUpdateRBAC() OptBool {
	return s.SkipUpdateRBAC
}

// SetTargetOntapVersion sets the value of TargetOntapVersion.
func (s *UpgradePoolRequest) SetTargetOntapVersion(val string) {
	s.TargetOntapVersion = val
}

// SetVsaImagePath sets the value of VsaImagePath.
func (s *UpgradePoolRequest) SetVsaImagePath(val string) {
	s.VsaImagePath = val
}

// SetForceUpgrade sets the value of ForceUpgrade.
func (s *UpgradePoolRequest) SetForceUpgrade(val OptBool) {
	s.ForceUpgrade = val
}

// SetSkipUpdateRBAC sets the value of SkipUpdateRBAC.
func (s *UpgradePoolRequest) SetSkipUpdateRBAC(val OptBool) {
	s.SkipUpdateRBAC = val
}

// Present when the workflow failed or timed out.
// Ref: #/components/schemas/WorkflowStatusError
type WorkflowStatusError struct {
	// Primary error message.
	Message OptString `json:"message"`
	// Root cause of the failure, if available.
	Cause OptString `json:"cause"`
}

// GetMessage returns the value of Message.
func (s *WorkflowStatusError) GetMessage() OptString {
	return s.Message
}

// GetCause returns the value of Cause.
func (s *WorkflowStatusError) GetCause() OptString {
	return s.Cause
}

// SetMessage sets the value of Message.
func (s *WorkflowStatusError) SetMessage(val OptString) {
	s.Message = val
}

// SetCause sets the value of Cause.
func (s *WorkflowStatusError) SetCause(val OptString) {
	s.Cause = val
}
