apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvest.configMapName" . }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{ include "harvest.kubernetes.labels" . | nindent 6 }}
data:
  ENABLE_VOLUME_ONLINE: {{ .Values.harvestConfig.enableVolumeOnline | quote }}
  ENABLE_VOLUME_METRICS: {{ .Values.harvestConfig.enableVolumeMetrics | quote }}
  ENABLE_BACKUP_METRICS: {{ .Values.harvestConfig.enableBackupMetrics | quote }}