apiVersion: v1
kind: Service
metadata:
  name: {{$.Values.service.name}}
  namespace: {{ $.Values.global.namespace }}
  labels:
    app: {{ .Chart.Name }}
  annotations:
    {{ include "harvest.kubernetes.annotations" $ | nindent 8 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: 3000
      targetPort: {{ .Values.service.port }}
      name: http
  selector:
    app: {{ .Chart.Name }}