apiVersion: v1
kind: PersistentVolume
metadata:
  name: harvest-gcs-fuse-csi-pv
spec:
  accessModes:
    - ReadWriteMany
  capacity:
    storage: {{ $.Values.persistentVolumes.storage }}
  storageClassName: ""
  mountOptions:
    - implicit-dirs
  csi:
    driver: gcsfuse.csi.storage.gke.io
    volumeHandle: {{ $.Values.persistentVolumes.persistentVolumeBucket }}