apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "harvest.configMapName" . }}
  namespace: {{ $.Values.global.namespace }}
  labels:
    {{ include "harvest.kubernetes.labels" . | nindent 6 }}
data:
  ENABLE_VOLUME_ONLINE: {{ .Values.harvestConfig.enableVolumeOnline | quote }}
  ENABLE_VOLUME_METRICS: {{ .Values.harvestConfig.enableVolumeMetrics | quote }}
  ENABLE_POOL_METRICS: {{ .Values.harvestConfig.enablePoolMetrics | quote }}
  ENABLE_BACKUP_METRICS: {{ .Values.harvestConfig.enableBackupMetrics | quote }}
  ENABLE_BACKUP_VAULT_METRICS: {{ .Values.harvestConfig.enableBackupVaultMetrics | quote }}
  ENABLE_REPLICATION_METRICS: {{ .Values.harvestConfig.enableReplicationMetrics | quote }}
  CORE_API_BASE_URL: {{ .Values.harvestConfig.coreApiBaseUrl | quote }}
  CORE_API_PORT: {{ .Values.harvestConfig.coreApiPort | quote }}
  CORE_API_BATCH_SIZE: {{ .Values.harvestConfig.coreApiBatchSize | quote }}
  GCP_AUTH_SERVICE_ACCOUNT: {{ .Values.harvestConfig.gcpAuthServiceAccount | quote }}
  GCP_SERVICE_URL: {{ .Values.harvestConfig.gcpServiceUrl | quote }}
  ENVIRONMENT: {{ .Values.global.environment | quote }}
