{{- if (.Values.horizontalPodAutoscaling.enable) -}}
apiVersion: autoscaling/v2
kind: HorizontalPodAutoscaler
metadata:
  name: {{ include "harvest.name" . }}-hpa
  namespace: {{ .Values.global.namespace }}
spec:
  scaleTargetRef:
    apiVersion: apps/v1
    kind: Deployment
    name: {{ include "harvest.name" . }}
  minReplicas: {{ .Values.horizontalPodAutoscaling.minReplicas }}
  maxReplicas: {{ .Values.horizontalPodAutoscaling.maxReplicas }}
  metrics:
    - external:
        metric:
          name: custom.googleapis.com|harvest_leases_total
          selector: {}
        target:
          averageValue: "1"
          type: AverageValue
      type: External
  behavior:
    scaleDown:
      policies:
      - periodSeconds: 60
        type: Percent
        value: 50
      selectPolicy: Max
      stabilizationWindowSeconds: 900
    scaleUp:
      policies:
      - periodSeconds: 15
        type: Pods
        value: 4
      - periodSeconds: 15
        type: Percent
        value: 100
      selectPolicy: Max
      stabilizationWindowSeconds: 0
{{- end }}