apiVersion: rbac.authorization.k8s.io/v1
kind: Role
metadata:
  name: harvest-farm-lease-reader
  namespace: {{ .Values.global.namespace }}
rules:
  - apiGroups: [ "coordination.k8s.io" ]
    resources: [ "leases" ]
    verbs: [ "get", "list", "watch", "update" ]
---
apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: harvest-farm-lease-reader-binding
  namespace: {{ .Values.global.namespace }}
subjects:
  - kind: ServiceAccount
    name: {{ .Values.serviceAccount.name }}
    namespace: {{ .Values.global.namespace }}
roleRef:
  kind: Role
  name: harvest-farm-lease-reader
  apiGroup: rbac.authorization.k8s.io