{{- if and (eq .Values.mode "deployment") (.Values.configMap.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontap-opentelemetry-collector.fullname" . }}
  labels:
    {{- include "ontap-opentelemetry-collector.labels" . | nindent 4 }}
  namespace: {{ $.Values.global.namespace }}
data:
  relay: |
    exporters:
        debug:
            verbosity: normal
        googlecloud:
            project: {{ .Values.otel.project }}
            metric:
                prefix: custom.googleapis.com
                skip_create_descriptor: true
            sending_queue:
                enabled: false
                queue_size: 40000
    extensions:
        health_check:
            endpoint: "0.0.0.0:13133"
    processors:
        batch:
            send_batch_size: 200
            send_batch_max_size: 200
            timeout: 200ms
        memory_limiter:
            check_interval: 5s
            limit_percentage: 80
            spike_limit_percentage: 30
        resourcedetection:
            detectors: [gcp]
            timeout: 10s
    receivers:
        prometheus:
            config:
                scrape_configs:
                - job_name: "otel-scrape-job"
                  scrape_interval: 300s
                  http_sd_configs:
                  - url: http://localhost:3000/pollers/prometheus-targets
                    refresh_interval: 30s
                  metric_relabel_configs:
                  - source_labels: [metadata_collector_api_time, metadata_collector_bytesRx, metadata_collector_calc_time, metadata_collector_instances]
                    action: drop
                  - source_labels: [metadata_collector_metrics, metadata_collector_numCalls, metadata_collector_numPartials, metadata_collector_parse_time]
                    action: drop
                  - source_labels: [metadata_collector_pluginInstances, metadata_collector_plugin_time, metadata_collector_poll_time, metadata_collector_skips]
                    action: drop
                  - source_labels: [metadata_collector_task_time, metadata_component_count, metadata_component_status, metadata_exporter_count]
                    action: drop
                  - source_labels: [metadata_exporter_time, metadata_target_goroutines, metadata_target_ping, metadata_target_status]
                    action: drop
    service:
        extensions:
            - health_check
        pipelines:
            metrics:
                receivers: [prometheus]
                processors: [resourcedetection]
                exporters: [googlecloud, debug]
{{- end }}
