{{- if and (eq .Values.mode "deployment") (.Values.configMap.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontap-opentelemetry-collector.fullname" . }}
  labels:
    {{- include "ontap-opentelemetry-collector.labels" . | nindent 4 }}
  namespace: {{ $.Values.global.namespace }}
data:
  relay: |
    exporters:
        debug:
            verbosity: {{ .Values.otel.logLevel }}
        googlecloud:
            project: {{ .Values.otel.project }}
            metric:
                prefix: custom.googleapis.com
                skip_create_descriptor: true
            sending_queue:
                enabled: {{.Values.harvestConfig.sendingQueueEnabled}}
                queue_size: 40000
        googlecloud/scaling:
            project: {{ .Values.otel.autoScaleProject }}
            metric:
                prefix: custom.googleapis.com
                skip_create_descriptor: true
            sending_queue:
                enabled: {{.Values.harvestConfig.sendingQueueEnabled}}
                queue_size: 40000
    extensions:
        health_check:
            endpoint: "0.0.0.0:13133"
    processors:
        batch:
            send_batch_size: 200
            send_batch_max_size: 200
            timeout: 200ms
        groupbyattrs:
            keys:
            - tenant_project
            - cluster
        memory_limiter:
            check_interval: 5s
            limit_percentage: 80
            spike_limit_percentage: 30
        resourcedetection:
            detectors: [gcp]
            timeout: 10s
        transform/monitoring:
            error_mode: ignore
            metric_statements:
              - context: resource
                statements:
                  - set(attributes["k8s.cluster.name"],attributes["deployment_name"])
        transform/tenant:
            error_mode: ignore
            metric_statements:
              - context: resource
                statements:
                  - set(attributes["gcp.project.id"],attributes["tenant_project"])
                  - set(attributes["k8s.cluster.name"],attributes["cluster"])
                  - delete_key(attributes, "tenant_project")
    receivers:
        prometheus:
            config:
                scrape_configs:
                - job_name: "otel-scrape-job"
                  scrape_interval: 300s
                  http_sd_configs:
                  - url: http://{{ .Values.otel.metricsHost }}{{ .Values.otel.pollerMetricsEndPoint }}
                    refresh_interval: {{ .Values.otel.refresh_interval }}
                  metric_relabel_configs:
                  - source_labels: ['__name__']
                    action: drop
                    regex: 'metadata_collector_bytesRx|metadata_collector_calc_time|metadata_collector_instances|metadata_collector_metrics|metadata_collector_numPartials|metadata_collector_parse_time|metadata_collector_pluginInstances|metadata_collector_plugin_time|metadata_collector_poll_time|metadata_collector_skips|metadata_collector_task_time|metadata_component_count|metadata_component_status|metadata_exporter_count|metadata_exporter_time|metadata_target_goroutines|metadata_target_ping|metadata_target_status|metadata_collector_api_time|metadata_collector_numCalls'
                  - source_labels: ['__name__']
                    action: drop
                    regex: 'poller_memory|poller_memory_percent'
                  - source_labels: ['__name__']
                    action: drop
                    regex: 'instrumentation_source|instrumentation_version|service_name|service_instance_id|plex'
        prometheus/scaling:
            config:
                scrape_configs:
                  - job_name: "otel-scaling-metrics-job"
                    scrape_interval: 30s
                    static_configs:
                      - targets: ["{{ .Values.otel.metricsHost }}"]
                    metrics_path: {{ .Values.otel.harvestMetricEndPoint }}


    service:
        extensions:
            - health_check
        pipelines:
            metrics:
                receivers: [prometheus]
                processors: [batch,resourcedetection,transform/monitoring]
                exporters: [googlecloud, debug]
            metrics/tenants:
                receivers: [prometheus]
                processors: [resourcedetection, groupbyattrs,transform/tenant, batch]
                exporters: [googlecloud, debug]
            metrics/scaling:
                receivers: [prometheus/scaling]
                processors: [resourcedetection]
                exporters: [googlecloud/scaling, debug]
{{- end }}
