{{- if and (eq .Values.mode "deployment") (.Values.configMap.create) -}}
apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "ontap-opentelemetry-collector.fullname" . }}
  labels:
    {{- include "ontap-opentelemetry-collector.labels" . | nindent 4 }}
  namespace: {{ $.Values.global.namespace }}
data:
  relay: |
    exporters:
        debug:
            verbosity: {{ .Values.otel.logLevel }}
        googlecloud:
            project: {{ .Values.otel.project }}
            metric:
                prefix: custom.googleapis.com
                skip_create_descriptor: true
                service_resource_labels: false
                instrumentation_library_labels: false
            sending_queue:
                enabled: {{.Values.harvestConfig.sendingQueueEnabled}}
                queue_size: 40000
        googlecloud/scaling:
            project: {{ .Values.otel.autoScaleProject }}
            metric:
                prefix: custom.googleapis.com
                skip_create_descriptor: true
            sending_queue:
                enabled: {{.Values.harvestConfig.sendingQueueEnabled}}
                queue_size: 40000
    extensions:
        health_check:
            endpoint: "0.0.0.0:20001"
    processors:
        transform/monitoring:
            error_mode: ignore
            metric_statements:
              - context: resource
                statements:
                  - set(attributes["k8s.cluster.name"],attributes["cluster"])
        transform/tenant:
            error_mode: ignore
            metric_statements:
              - context: resource
                statements:
                  - set(attributes["gcp.project.id"],attributes["tenant_project"])
                  - set(attributes["k8s.cluster.name"],attributes["cluster"])
                  - delete_key(attributes, "tenant_project")
        resourcedetection:
            detectors: [gcp]
            timeout: 10s
        batch:
            send_batch_size: 200
            send_batch_max_size: 200
            timeout: 200ms
        groupbyattrs:
            keys:
            - tenant_project
            - cluster
        memory_limiter:
            check_interval: 5s
            limit_percentage: 80
            spike_limit_percentage: 30
    receivers:
        prometheus:
            config:
                scrape_configs:
                - job_name: "otel-scrape-job"
                  scrape_interval: 300s
                  http_sd_configs:
                  - url: http://{{ .Values.otel.metricsHost }}{{ .Values.otel.pollerMetricsEndPoint }}
                    refresh_interval: {{ .Values.otel.refresh_interval }}
                  metric_relabel_configs:
                  - source_labels: ['__name__']
                    action: drop
                    regex: 'metadata_collector_bytesRx|metadata_collector_calc_time|metadata_collector_instances|metadata_collector_metrics|metadata_collector_numPartials|metadata_collector_parse_time|metadata_collector_pluginInstances|metadata_collector_plugin_time|metadata_collector_poll_time|metadata_collector_skips|metadata_collector_task_time|metadata_component_count|metadata_component_status|metadata_exporter_count|metadata_exporter_time|metadata_target_goroutines|metadata_target_ping|metadata_target_status|metadata_collector_api_time|metadata_collector_numCalls'
                  - source_labels: ['__name__']
                    action: drop
                    regex: 'poller_memory|poller_memory_percent'
                  - source_labels: [source_cluster, source_location, source_volume, source_vserver]
                    separator: '_'
                    target_label: source_details
                    replacement: '$${1}_$${2}_$${3}_$${4}'
                  - source_labels: [destination_location, destination_node, destination_volume, destination_vserver]
                    separator: '_'
                    target_label: destination_details
                    replacement: '$${1}_$${2}_$${3}_$${4}'
                  - source_labels: [aggr, partition, plex]
                    separator: '_'
                    target_label: aggr_details
                    replacement: '$${1}_$${2}_$${3}'
                  - action: labeldrop
                    regex: 'source_cluster|source_location|source_volume|source_vserver|destination_location|destination_node|destination_volume|destination_vserver'
                  - action: labeldrop
                    regex: 'aggr|partition|plex|node'
        prometheus/scaling:
            config:
                scrape_configs:
                  - job_name: "otel-scaling-metrics-job"
                    scrape_interval: 30s
                    static_configs:
                      - targets: ["{{ .Values.otel.metricsHost }}"]
                    metrics_path: {{ .Values.otel.harvestMetricEndPoint }}
        prometheus/tenant:
            config:
                scrape_configs:
                - job_name: "otel-tenant-scrape-job"
                  scrape_interval: 300s
                  http_sd_configs:
                  - url: http://{{ .Values.otel.metricsHost }}{{ .Values.otel.pollerMetricsEndPoint }}
                    refresh_interval: {{ .Values.otel.refresh_interval }}
                  metric_relabel_configs:
                  - source_labels: ['__name__']
                    action: keep
                    regex: 'volume_space_logical_used|volume_capacity|snapmirror_total_transfer_bytes|volume_read_latency|volume_write_latency|volume_other_latency|volume_read_data|volume_write_data|volume_other_data|wafl_volume_client_protocol_reads|wafl_volume_cloud_bin_operation_size|pool_client_protocol_reads|pool_cloud_bin_operation_size|pool_client_protocol_reads_raw|pool_cloud_bin_operation_size_raw|wafl_volume_client_protocol_reads_raw|wafl_volume_cloud_bin_operation_size_raw|pool_capacity_tier_logical_footprint'
                  - source_labels: [source_cluster, source_location, source_volume, source_vserver]
                    separator: '_'
                    target_label: source_details
                    replacement: '$${1}_$${2}_$${3}_$${4}'
                  - source_labels: [destination_location, destination_node, destination_volume, destination_vserver]
                    separator: '_'
                    target_label: destination_details
                    replacement: '$${1}_$${2}_$${3}_$${4}'
                  - source_labels: [aggr, partition, plex]
                    separator: '_'
                    target_label: aggr_details
                    replacement: '$${1}_$${2}_$${3}'
                  - action: labeldrop
                    regex: 'source_cluster|source_location|source_volume|source_vserver'
                  - action: labeldrop
                    regex: 'destination_location|destination_node|destination_volume|destination_vserver'
                  - action: labeldrop
                    regex: 'aggr|partition|plex'
    service:
        telemetry:
            logs:
                level: info
                encoding: json
                output_paths:
                    - stderr
                error_output_paths:
                    - stderr
        extensions:
            - health_check
        pipelines:
            metrics:
                receivers: [prometheus]
                processors: [resourcedetection,groupbyattrs,transform/monitoring,batch]
                exporters: [googlecloud,debug]
            metrics/tenants:
                receivers: [prometheus/tenant]
                processors: [resourcedetection,groupbyattrs,transform/tenant,batch]
                exporters: [googlecloud,debug]
            metrics/scaling:
                receivers: [prometheus/scaling]
                processors: [resourcedetection]
                exporters: [googlecloud/scaling,debug]
{{- end }}
