apiVersion: v1
kind: ServiceAccount
metadata:
  annotations:
    {{ include "harvest.serviceaccount.annotations" . | nindent 4 }}
  name: custom-metrics-stackdriver-adapter
  namespace: {{ $.Values.global.namespace }}