apiVersion: {{ required "apiVersion" .Values.secretManager.apiVersion | quote }}
kind: ExternalSecret
metadata:
  name: {{ .Values.global.secondaryImageRegistry | default .Values.global.secondImageRegistry }}
  namespace: {{ $.Values.global.namespace }}
spec:
  refreshInterval: {{ required "refreshInterval missing" .Values.secretManager.refreshInterval | quote }}
  secretStoreRef:
    kind: ClusterSecretStore
    name: {{ required "clusterSecretStoreName missing" .Values.secretManager.clusterSecretStoreName }}
  target:
    name: {{ .Values.global.secondaryImageRegistry | default .Values.global.secondImageRegistry }}
    creationPolicy: Owner
    template:
      type: kubernetes.io/dockerconfigjson
  data:
    - secretKey: ".dockerconfigjson"
      remoteRef:
        key: {{ required "secondRegistryCredentials missing" .Values.secretManager.registryCredentials }}