ARG BASE
FROM $BASE

COPY app/google-proxy /app
COPY core/errors/errors.json /app/errors.json
COPY common/vsa_config /app/vsa_config

# Copy Air config for live reload
COPY google-proxy/air.toml /app/air.toml

ENV GOTRACEBACK=all
ENTRYPOINT ["air", "-c", "/app/air.toml"]

# Set ownership and permissions
# USER nonroot:nonroot
