serviceAccountName: workflow-server

replicaCount: 1

images:
  workflowServer:
    name: workflow-server
    tag: v25044.0.0-dev.6
    secondary: false
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  appPort: 50051