generator:
  ignore_not_implemented: ["complex defaults"]
  features:
    enable:
      - 'paths/server'
      - 'ogen/otel'
      - 'ogen/unimplemented'
      - 'debug/example_tests'
    disable_all: true
