enabled: true
serviceAccountName: google-proxy
replicaCount: 1

images:
  googleProxy:
    name: google-proxy
    tag: 0.0.0
    secondary: true
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  appPort: 8080

database:
  host: postgres
  user: postgres
  password: testpass
  name: vcp
  adminUser: postgres
  adminPassword: testpass

google-proxy:
  env: ""  # To be kept empty for GKE
  acceptedSAs: "" # Comma-separated list of service account emails that are allowed to access the Google Proxy APIs.
  gcpConsumerMgmtEndpointUrl: ""
  gcpServiceNetworkingEndpointUrl: ""
  gcpServiceUrl: ""
  localRegion: ""
  otelGoogleProjectId: ""
  runMigrationOnStart: true
  temporalAddress: "temporal-frontend.temporal.svc.cluster.local:7233"
  vsaNodeUsername: ""
  vsaNodePassword: ""

# Annotations
serviceAccountAnnotations:
  "iam.gke.io/gcp-service-account": vcp-ci@gcnv-artifact-registry-nonprod.iam.gserviceaccount.com

