# Global configuration
environment: gcp

# Pod affinity configuration
podAffinity:
  enabled: true

enabled: true
serviceAccountName: google-proxy
replicaCount: 1

acceptedSAs: "" # Comma-separated list of service account emails that are allowed to access the Google Proxy APIs.
gcpConsumerMgmtEndpointUrl: ""
gcpServiceNetworkingEndpointUrl: ""
gcpServiceUrl: "https://cloudvolumesgcp-api.netapp.com"
localRegion: ""
otelGoogleProjectId: ""
runMigrationOnStart: true
temporalAddress: "temporal-frontend.temporal.svc.cluster.local:7233"
vsaNodeUsername: ""
vsaNodePassword: ""
vsaAuthType: 0 # 0 : username/password, 1 : username/password in secret manager and 2 : certificate authentication
smcProjectId: ""
gcpSmcSecretName: ""
gcpSmcSecretVersionName: ""
gcpHydrateEnabled: true
gcpHydrateAuthServiceAccount: ""
gcpAuthServiceAccount: ""
gcpHydrateBaseUrl: ""
proxyClientTransportSchema: "https"
vcpPairedRegions: ""
loggerLevel: "info"
cvpHost: ""
coreApi:
  host: "core-service.vcp.svc.cluster.local:8080"
crrEnabled: false
cpcrrEnabled: false
czcrrEnabled: false
refreshAdminJobSpecs: true
flexCacheEnabled: false
hybridReplicationEnabled: false
autoTieringEnabled: false
blockUpdatePoolToATPool: true # Block updating existing pools to Auto-Tiering pools
regionalSupportEnabled: true
filesProtocolSupport: false
fileProtocolAllowlistedAccounts: "" # Comma-separated list of account IDs that are allowlisted for file protocol support
backupEnabled: false
sfrEnabled: false
qaEnabled: false
immutableBackupEnabled: false
crossRegionBackupEnabled: false
restoreVolumeBufferEnabled: false
minQuotaInBytesPool: "1099511627776" # 1TiB in bytes
maxQuotaInBytesPool: "467292441804800" # 425TiB in bytes
minQuotaInBytesVolume: "1073741824" # 1GiB in bytes
maxQuotaInBytesVolume: "140737488355328" # 128TiB in bytes
minQuotaInBytesLargeVolume: "13194139533312" # 12TiB in bytes
maxQuotaInBytesLargeVolume: "22517998136852480" # 20PiB in bytes
maxConstituentsPerAggregate: "1000" # 1000 constituents per aggregate
maxConstituentsPerVolumePerAggregate: "200" # 200 constituents per aggregate per volume
minSizeGranularity: "1073741824" # 1GiB in bytes
jwkKidsUrl: "https://www.googleapis.com/service_accounts/v1/metadata/x509/"
workflowGlobalTimeoutMinutes: "60" # Global timeout for workflows in minutes
maxHostsPerHostgroup: "128"
cmekWorkflowGlobalTimeoutMinutes: "14" # Global timeout for CMEK workflows in minutes
cmekBackupEnabled: false
workflowGlobalTimeoutForReplicationMinutes: 10
gcpKmsKeyRotationEnabled: "false" # Flag to enable GCP KMS key rotation
minCustomIops: "1024"
minCustomThroughput: "64"
maxCustomIops: "160000"
maxCustomThroughput: "5120"
iopsPerMibps: "16"
deleteResourcesCronExpression: "0 0 * * *" # DELETE_RESOURCES job configuration
waitForTemporalEnabled: false
metricsDbCleanupEnabled: false
volumeRefreshIntervalMinutes: "5"
thinCloneGASupport: false
enableCloneInfoRefresh: false
maxThinClonesPerPool: 100
enableAutoPoolScaling: true
snapshotAPISyncMode: false
syncSnapshotOntapJobPollTimeoutMilliseconds: 40000
syncSnapshotOntapJobPollIntervalMilliseconds: 2000
caName: "20250718-pn6-boa"
caPoolName: "vsa-pool-ca"
caPoolDeployedProjectId: "266893635349"
vsaDeployedDnsName: "au-se1.vsa"
vsaManagedZone: "au-se1-vsa"
privateKeyBits: 4096
vsaSecretCacheCleanupIntervalHours: 24
vsaSecretAuthCacheExpirationHours: 24
hardDeleteResources: true
scheduleHardDelete: false
createCommonResourcesInVCP: true
numberOfHaPairsLargeCapacity: 6
minConstituentVolumeSizeInBytes: 107374182400
secretManagerProjectId: "402007546452"
enableLdap: false
enableMultiAd: true
maxNumberOfAdPerAccount: 5
autoPoolScalingLimits:
  c3-standard-4-lssd:
    min_volume_count: 0
    max_volume_count: 245
  c3-standard-8-lssd:
    min_volume_count: 0
    max_volume_count: 495
  c3-standard-22-lssd:
    min_volume_count: 0
    max_volume_count: 995

# Mock gcp access token for testing purposes
mockAccessToken: ""
integrationTest: false
nkdevTest: false

# Add values here in overrideCoreConfig to override the common configuration
overrideCoreConfig: {}

images:
  googleProxy:
    name: google-proxy
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "1"
    memory: 1Gi 
  requests:
    cpu: 250m
    memory: 150Mi

service:
  type: ClusterIP
  appPort: 8080

database:
  host: postgres
  user: postgres
  password: testpass
  name: vcp
  adminUser: postgres
  adminPassword: testpass
  sslMode: "disable"

# Annotations
serviceAccountAnnotations:
  "iam.gke.io/gcp-service-account": vcp-ci@gcnv-artifact-registry-nonprod.iam.gserviceaccount.com

temporal:
  timeouts:
    heartbeat:
      setupNwSecond: 300
#Enabling for secrets manager
#flag for enabling/disabling secret manager
secretManagerEnabled: false # Default is false
externalSecrets:
  dbUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-username-key"
    secretKey: "dbUsername"
  dbPassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-password-key"
    secretKey: "dbPassword"
  dbAdminUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-adminUsername-key"
    secretKey: "dbAdminUsername"
  dbAdminPassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-adminPassword-key"
    secretKey: "dbAdminPassword"
  vsaNodeUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-node-username"
    secretKey: "vsaNodeUsername"
  vsaNodePassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-node-password"
    secretKey: "vsaNodePassword"

proberProjectList: ""
enableUniqueSerialNumberGeneration: false
clusterSerialNumberPrefix: "935"
