enabled: true
serviceAccountName: google-proxy
replicaCount: 1

acceptedSAs: "" # Comma-separated list of service account emails that are allowed to access the Google Proxy APIs.
gcpConsumerMgmtEndpointUrl: ""
gcpServiceNetworkingEndpointUrl: ""
gcpServiceUrl: "https://cloudvolumesgcp-api.netapp.com"
localRegion: ""
otelGoogleProjectId: ""
runMigrationOnStart: true
temporalAddress: "temporal-frontend.temporal.svc.cluster.local:7233"
vsaNodeUsername: ""
vsaNodePassword: ""
vsaAuthType: 0 # 0 : username/password, 1 : username/password in secret manager and 2 : certificate authentication
smcProjectId: ""
gcpSmcSecretName: ""
gcpSmcSecretVersionName: ""
gcpHydrateEnabled: false
gcpHydrateAuthServiceAccount: ""
gcpAuthServiceAccount: ""
gcpHydrateBaseUrl: ""
proxyClientTransportSchema: "https"
vcpPairedRegions: ""
loggerLevel: "info"
cvpHost: ""
crrEnabled: false
refreshAdminJobSpecs: false
autoTieringEnabled: false
regionalSupportEnabled: true
filesProtocolSupport: false
fileProtocolAllowlistedAccounts: "" # Comma-separated list of account IDs that are allowlisted for file protocol support
backupEnabled: false
minQuotaInBytesPool: "1099511627776" # 1TB in bytes
minQuotaInBytesVolume: "1073741824" # 1GB in bytes
maxQuotaInBytesVolume: "140737488355328" # 128TB in bytes
jwkKidsUrl: "https://www.googleapis.com/service_accounts/v1/metadata/x509/"
workflowGlobalTimeoutMinutes: "60" # Global timeout for workflows in minutes
maxHostsPerHostgroup: "64"

# Add values here in overrideCoreConfig to override the common configuration
overrideCoreConfig: {}

images:
  googleProxy:
    name: google-proxy
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent

service:
  type: ClusterIP
  appPort: 8080

database:
  host: postgres
  user: postgres
  password: testpass
  name: vcp
  adminUser: postgres
  adminPassword: testpass

# Annotations
serviceAccountAnnotations:
  "iam.gke.io/gcp-service-account": vcp-ci@gcnv-artifact-registry-nonprod.iam.gserviceaccount.com

temporal:
  timeouts:
    heartbeat:
      setupNwSecond: 300
#Enabling for secrets manager
#flag for enabling/disabling secret manager
secretManagerEnabled: false # Default is false
externalSecrets:
  dbUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-username-key"
    secretKey: "dbUsername"
  dbPassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-password-key"
    secretKey: "dbPassword"
  dbAdminUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-adminUsername-key"
    secretKey: "dbAdminUsername"
  dbAdminPassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-adminPassword-key"
    secretKey: "dbAdminPassword"
  vsaNodeUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-node-username"
    secretKey: "vsaNodeUsername"
  vsaNodePassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-node-password"
    secretKey: "vsaNodePassword"
