global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  primaryImageRegistryPasswordAuth: true
  primaryImagePullSecretName: ghcr.io
  secondaryImageRegistry: "europe-north1-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vcp-container-images-us"
  use-tags: false
  secondaryImageRegistryPasswordAuth: false
  nodeSelector:
    nodeType: vsacp-nodes
  chartPrimaryImageRegistry: "" # example value: ghcr.io/vcp-vsa-control-plane
  chartSecondaryImageRegistry: "" # example value: europe-north1-docker.pkg.dev/gcnv-artifact-registry-nonprod/vcp-container-images
  environment: gcp
  hyperscaler: gcp
  workloadIdentityEnabled: false

google-proxy:
  enabled: true
  serviceAccountName: google-proxy
  replicaCount: 1

  env: ""  # To be kept empty for GKE
  acceptedSAs: "" # Comma-separated list of service account emails that are allowed to access the Google Proxy APIs.
  gcpConsumerMgmtEndpointUrl: ""
  gcpServiceNetworkingEndpointUrl: ""
  gcpServiceUrl: ""
  localRegion: ""
  otelGoogleProjectId: ""
  runMigrationOnStart: true
  temporalAddress: "temporal-frontend.temporal.svc.cluster.local:7233"
  vsaNodeUsername: ""
  vsaNodePassword: ""
  secretManagerEnabled: false
  certificateLifetime: "25920000s"
  caName: ""
  caPoolName: ""
  caPoolDeployedProjectId: ""
  vsaDeployedDnsName: ""
  vsaSecretCacheCleanupIntervalMinutes: 5
  vsaSecretAuthCacheExpirationMinutes: 5

  images:
    googleProxy:
      name: google-proxy
      tag: 0.0.0
      digest: ""
      secondary: true
      pullPolicy: IfNotPresent

  service:
    type: ClusterIP
    appPort: 8080

  database:
    host: postgres
    user: postgres
    password: testpass
    name: vcp
    adminUser: postgres
    adminPassword: testpass

  # Annotations
  serviceAccountAnnotations:
    "iam.gke.io/gcp-service-account": vcp-ci@gcnv-artifact-registry-nonprod.iam.gserviceaccount.com

  temporal:
    timeouts:
      heartbeat:
        setupNwSecond: 300

core:
  enabled: true
  enableDbMigration: true
  ttlSecondsAfterFinished: 3600
  dbAdminUser: dbAdminUser
  dbAdminPassword: dbAdminPassword
  msiEnabled: false
  msiUser: db-msi-user
  serviceAccountName: vcp-core

  replicaCount: 1

  images:
    core:
      name: core
      tag: 0.0.0
      digest: ""
      secondary: true
      pullPolicy: IfNotPresent
    vcpDbMigrate:
      name: vcp-db-migrate
      tag: 0.0.0
      digest: ""
      secondary: true
      pullPolicy: IfNotPresent


  service:
    type: ClusterIP
    appPort: 8081

  database:
    host: postgres-service
    user: vcp-db-user
    password: vcp-db-pass
    name: vcp
    port: 5432
    type: postgres

  resources:
    limits:
      cpu: 1000m
      memory: 512Mi
    requests:
      cpu: 200m
      memory: 256Mi

  # Annotations
  serviceAccountAnnotations:
    "iam.gke.io/gcp-service-account": vcp-ci@gcnv-artifact-registry-nonprod.iam.gserviceaccount.com

adc:
  externalSecretManager: false
  hyperscaler: "gcp"

  images:
    cloudBackupAdcGCP:
      name: cloud-backup-adc
      tag: "2.7" #NOTE: Please also update the tag for "cloud-backup-adc" in the blackduck scan CI job in release.yaml in case of a tag update here if useTags is set to true in global values.yaml
      digest: "sha256:86e301917e86880e5b65bfecc7a97e44abd13d970db775e91a6a13b6d52fa88a" #Update digest here if useTags is set to false in global values.yaml
      secondary: true
      pullPolicy: IfNotPresent

  # Enabled
  enabled: true

  # Naming
  serviceAccount: adc
  nameOverride: adc

  # Configuration
  replicas: 2
  adcport: 8085
  threshold: 50

  # Secret configuration
  secret:
    googlecomchain: ""

  adc_info:
    adcMountBackupSleepInterval: "6"
    adcProvider: ""
    adcMountDir: ""
    adcEndPoint: ""
    adcCertName: ""
    adcCertDir: ""
    adcLogDir: "/home/vsa/adcLogPath"
    adcNumOfCpus: "1"
    adcNumOfFuseDevices: "1"
    adcConfigMemory: "256M"
    adcBrowseMemory: "4G"
    adcNodeSelector: "vsacp-nodes"
    adcCertSecretName: "adc-secret"
    adcPodPollMaxRetryCount: "15"
    adcPodPollSleepInterval: "1"
    adcPodPollDeleteRetryCount: "12"
    adcPodPollDeleteSleepInterval: "5"

  # Add support to turn off separate nodes for VSA (tolerations + labels)
  nodes:
    tolerations: true
    nodeSelector: false

  # Secret Manager config (used with external-secrets chart)
  secretManager:
    apiVersion: external-secrets.io/v1beta1
    clusterSecretStoreName: "main-cluster-secret-store"
    refreshInterval: 24h
    # Name of secret(s) in external Secret Manager
    googleComChain: "vsa-google-chain"

  workloadIdentity:
    azureClientId: ""
    gcpServiceAccount: ""

  # Annotations
  statefulSetAnnotations: {}
  podAnnotations:
    container.apparmor.security.beta.kubernetes.io/adc: unconfined
  serviceAnnotations: {}
  configmapAnnotations: {}
  secretAnnotations: {}
  serviceAccountAnnotations:
    "iam.gke.io/gcp-service-account": ""
  commonAnnotations: {}

  # Labels
  statefulSetLabels: {}
  podLabels: {}
  serviceLabels: {}
  configmapLabels: {}
  secretLabels: { }
  serviceAccountLabels: {}
  commonLabels: {}
