// Code generated by go-swagger; DO NOT EDIT.

package n_v_m_e

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
)

// NewNvmeNamespaceCollectionGetParams creates a new NvmeNamespaceCollectionGetParams object,
// with the default timeout for this client.
func NewNvmeNamespaceCollectionGetParams() *NvmeNamespaceCollectionGetParams {
	return &NvmeNamespaceCollectionGetParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewNvmeNamespaceCollectionGetParamsWithTimeout creates a new NvmeNamespaceCollectionGetParams object
// with the ability to set a timeout on a request.
func NewNvmeNamespaceCollectionGetParamsWithTimeout(timeout time.Duration) *NvmeNamespaceCollectionGetParams {
	return &NvmeNamespaceCollectionGetParams{
		timeout: timeout,
	}
}

// NewNvmeNamespaceCollectionGetParamsWithContext creates a new NvmeNamespaceCollectionGetParams object
// with the ability to set a context for a request.
func NewNvmeNamespaceCollectionGetParamsWithContext(ctx context.Context) *NvmeNamespaceCollectionGetParams {
	return &NvmeNamespaceCollectionGetParams{
		Context: ctx,
	}
}

// NewNvmeNamespaceCollectionGetParamsWithHTTPClient creates a new NvmeNamespaceCollectionGetParams object
// with the ability to set a custom HTTPClient for a request.
func NewNvmeNamespaceCollectionGetParamsWithHTTPClient(client *http.Client) *NvmeNamespaceCollectionGetParams {
	return &NvmeNamespaceCollectionGetParams{
		HTTPClient: client,
	}
}

/*
NvmeNamespaceCollectionGetParams contains all the parameters to send to the API endpoint

	for the nvme namespace collection get operation.

	Typically these are written to a http.Request.
*/
type NvmeNamespaceCollectionGetParams struct {

	/* Fields.

	   Specify the fields to return.
	*/
	Fields []string

	/* LocationVolumeName.

	   Filter by location.volume.name

	   Format: string
	*/
	LocationVolumeName *string

	/* MaxRecords.

	   Limit the number of records returned.

	   Format: integer
	*/
	MaxRecords *string

	/* Name.

	   Filter by name

	   Format: string
	*/
	Name *string

	/* SvmName.

	   Filter by svm.name

	   Format: string
	*/
	SvmName *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the nvme namespace collection get params (not the query body).
func (o *NvmeNamespaceCollectionGetParams) WithDefaults() *NvmeNamespaceCollectionGetParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the nvme namespace collection get params (not the query body).
func (o *NvmeNamespaceCollectionGetParams) SetDefaults() {
}

// WithTimeout adds the timeout to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) WithTimeout(timeout time.Duration) *NvmeNamespaceCollectionGetParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) WithContext(ctx context.Context) *NvmeNamespaceCollectionGetParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) WithHTTPClient(client *http.Client) *NvmeNamespaceCollectionGetParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithFields adds the fields to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) WithFields(fields []string) *NvmeNamespaceCollectionGetParams {
	o.SetFields(fields)
	return o
}

// SetFields adds the fields to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) SetFields(fields []string) {
	o.Fields = fields
}

// WithLocationVolumeName adds the locationVolumeName to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) WithLocationVolumeName(locationVolumeName *string) *NvmeNamespaceCollectionGetParams {
	o.SetLocationVolumeName(locationVolumeName)
	return o
}

// SetLocationVolumeName adds the locationVolumeName to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) SetLocationVolumeName(locationVolumeName *string) {
	o.LocationVolumeName = locationVolumeName
}

// WithMaxRecords adds the maxRecords to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) WithMaxRecords(maxRecords *string) *NvmeNamespaceCollectionGetParams {
	o.SetMaxRecords(maxRecords)
	return o
}

// SetMaxRecords adds the maxRecords to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) SetMaxRecords(maxRecords *string) {
	o.MaxRecords = maxRecords
}

// WithName adds the name to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) WithName(name *string) *NvmeNamespaceCollectionGetParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) SetName(name *string) {
	o.Name = name
}

// WithSvmName adds the svmName to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) WithSvmName(svmName *string) *NvmeNamespaceCollectionGetParams {
	o.SetSvmName(svmName)
	return o
}

// SetSvmName adds the svmName to the nvme namespace collection get params
func (o *NvmeNamespaceCollectionGetParams) SetSvmName(svmName *string) {
	o.SvmName = svmName
}

// WriteToRequest writes these params to a swagger request
func (o *NvmeNamespaceCollectionGetParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.Fields != nil {
		// binding items for fields
		joinedFields := o.bindParamFields(reg)
		if err := r.SetQueryParam("fields", joinedFields...); err != nil {
			return err
		}
	}

	if o.LocationVolumeName != nil {
		var qrLocationVolumeName string
		if o.LocationVolumeName != nil {
			qrLocationVolumeName = *o.LocationVolumeName
		}
		qLocationVolumeName := qrLocationVolumeName
		if qLocationVolumeName != "" {
			if err := r.SetQueryParam("location.volume.name", qLocationVolumeName); err != nil {
				return err
			}
		}
	}

	if o.MaxRecords != nil {
		var qrMaxRecords string
		if o.MaxRecords != nil {
			qrMaxRecords = *o.MaxRecords
		}
		qMaxRecords := qrMaxRecords
		if qMaxRecords != "" {
			if err := r.SetQueryParam("max_records", qMaxRecords); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {
		var qrName string
		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {
			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.SvmName != nil {
		var qrSvmName string
		if o.SvmName != nil {
			qrSvmName = *o.SvmName
		}
		qSvmName := qrSvmName
		if qSvmName != "" {
			if err := r.SetQueryParam("svm.name", qSvmName); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

// bindParamFields binds the parameter fields
func (o *NvmeNamespaceCollectionGetParams) bindParamFields(formats strfmt.Registry) []string {
	fieldsIR := o.Fields

	var fieldsIC []string
	for _, fieldsIIR := range fieldsIR {
		fieldsIIV := fieldsIIR
		fieldsIC = append(fieldsIC, fieldsIIV)
	}

	return swag.JoinByFormat(fieldsIC, "csv")
}
