// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"encoding/json"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// HostEms host ems
//
// swagger:model host_ems
type HostEms struct {

	// links
	Links *HostEmsInlineLinks `json:"_links,omitempty"`

	// UUID of the endpoint for which this error is being reported.
	EndpointUUID *string `json:"endpoint_uuid,omitempty"`

	// The endpoint for which this error is being reported.
	// Enum: [application application_component host]
	ErrorEndpoint *string `json:"error_endpoint,omitempty"`

	// Default message reported on the host.
	ErrorMessage *string `json:"error_message,omitempty"`

	// Default number reported on the host.
	ErrorNumber *int64 `json:"error_number,omitempty"`

	// The software product that is reporting this error to the system.
	// Enum: [MAX_Data]
	SoftwareProduct *string `json:"software_product,omitempty"`

	// Host UUID.
	UUID *string `json:"uuid,omitempty"`
}

// Validate validates this host ems
func (m *HostEms) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateErrorEndpoint(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSoftwareProduct(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HostEms) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(m.Links) { // not required
		return nil
	}

	if m.Links != nil {
		if err := m.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

var hostEmsTypeErrorEndpointPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["application","application_component","host"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostEmsTypeErrorEndpointPropEnum = append(hostEmsTypeErrorEndpointPropEnum, v)
	}
}

const (

	// HostEmsErrorEndpointApplication captures enum value "application"
	HostEmsErrorEndpointApplication string = "application"

	// HostEmsErrorEndpointApplicationComponent captures enum value "application_component"
	HostEmsErrorEndpointApplicationComponent string = "application_component"

	// HostEmsErrorEndpointHost captures enum value "host"
	HostEmsErrorEndpointHost string = "host"
)

// prop value enum
func (m *HostEms) validateErrorEndpointEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, hostEmsTypeErrorEndpointPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *HostEms) validateErrorEndpoint(formats strfmt.Registry) error {
	if swag.IsZero(m.ErrorEndpoint) { // not required
		return nil
	}

	// value enum
	if err := m.validateErrorEndpointEnum("error_endpoint", "body", *m.ErrorEndpoint); err != nil {
		return err
	}

	return nil
}

var hostEmsTypeSoftwareProductPropEnum []interface{}

func init() {
	var res []string
	if err := json.Unmarshal([]byte(`["MAX_Data"]`), &res); err != nil {
		panic(err)
	}
	for _, v := range res {
		hostEmsTypeSoftwareProductPropEnum = append(hostEmsTypeSoftwareProductPropEnum, v)
	}
}

const (

	// HostEmsSoftwareProductMAXData captures enum value "MAX_Data"
	HostEmsSoftwareProductMAXData string = "MAX_Data"
)

// prop value enum
func (m *HostEms) validateSoftwareProductEnum(path, location string, value string) error {
	if err := validate.EnumCase(path, location, value, hostEmsTypeSoftwareProductPropEnum, true); err != nil {
		return err
	}
	return nil
}

func (m *HostEms) validateSoftwareProduct(formats strfmt.Registry) error {
	if swag.IsZero(m.SoftwareProduct) { // not required
		return nil
	}

	// value enum
	if err := m.validateSoftwareProductEnum("software_product", "body", *m.SoftwareProduct); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this host ems based on the context it is used
func (m *HostEms) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HostEms) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if m.Links != nil {
		if err := m.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HostEms) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HostEms) UnmarshalBinary(b []byte) error {
	var res HostEms
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}

// HostEmsInlineLinks host ems inline links
//
// swagger:model host_ems_inline__links
type HostEmsInlineLinks struct {

	// self
	Self *Href `json:"self,omitempty"`
}

// Validate validates this host ems inline links
func (m *HostEmsInlineLinks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HostEmsInlineLinks) validateSelf(formats strfmt.Registry) error {
	if swag.IsZero(m.Self) { // not required
		return nil
	}

	if m.Self != nil {
		if err := m.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this host ems inline links based on the context it is used
func (m *HostEmsInlineLinks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := m.contextValidateSelf(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *HostEmsInlineLinks) contextValidateSelf(ctx context.Context, formats strfmt.Registry) error {

	if m.Self != nil {
		if err := m.Self.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (m *HostEmsInlineLinks) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *HostEmsInlineLinks) UnmarshalBinary(b []byte) error {
	var res HostEmsInlineLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
