openapi: 3.0.4
info:
  title: ONTAP Proxy API
  version: "${major_version}.${minor_version}.${patch_version}"
servers:
  - url: http://ontap-proxy.netapp.com/
  - url: https://ontap-proxy.netapp.com/
tags:
  - name: health
    description: Health check operations
paths:
  /health:
    get:
      operationId: getHealth
      summary: Get the server health status
      description: Returns the server health status
      tags:
        - health
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Health'
        '400':
          $ref: '#/components/responses/StandardError-400'
        '401':
          $ref: '#/components/responses/StandardError-401'
        '403':
          $ref: '#/components/responses/StandardError-403'
        '404':
          $ref: '#/components/responses/StandardError-404'
        '429':
          $ref: '#/components/responses/StandardError-429'
        '500':
          $ref: '#/components/responses/StandardError-500'
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Health:
      type: object
      title: Health
      properties:
        status:
          title: healthStatus
          type: string
          readOnly: true
          description: Server health status
          example: healthy
    Error:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: integer
          description: Error code
        message:
          type: string
          description: Error message
  responses:
    StandardError-400:
      description: Bad request
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 400
            message: Bad Request or Input
    StandardError-401:
      description: Unauthorized
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 401
            message: Unauthorized access attempt
    StandardError-403:
      description: Forbidden
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 403
            message: Forbidden
    StandardError-404:
      description: Not Found
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 404
            message: Resource not found
    StandardError-429:
      description: Too Many Requests
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 429
            message: Too many requests
    StandardError-500:
      description: Internal Server Error
      content:
        application/json:
          schema:
            $ref: '#/components/schemas/Error'
          example:
            code: 500
            message: Internal server error

