// Code generated by go-swagger; DO NOT EDIT.

package kms_configurations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
)

// New creates a new kms configurations API client.
func New(transport runtime.ClientTransport, formats strfmt.Registry) ClientService {
	return &Client{transport: transport, formats: formats}
}

/*
Client for kms configurations API
*/
type Client struct {
	transport runtime.ClientTransport
	formats   strfmt.Registry
}

// ClientService is the interface for Client methods
type ClientService interface {
	V1betaCreateKmsConfiguration(params *V1betaCreateKmsConfigurationParams) (*V1betaCreateKmsConfigurationAccepted, error)

	V1betaCheckKmsConfig(params *V1betaCheckKmsConfigParams) (*V1betaCheckKmsConfigOK, error)

	V1betaDeleteKmsConfiguration(params *V1betaDeleteKmsConfigurationParams) (*V1betaDeleteKmsConfigurationAccepted, *V1betaDeleteKmsConfigurationNoContent, error)

	V1betaDescribeKmsConfiguration(params *V1betaDescribeKmsConfigurationParams) (*V1betaDescribeKmsConfigurationOK, error)

	V1betaEncryptVolumes(params *V1betaEncryptVolumesParams) (*V1betaEncryptVolumesAccepted, error)

	V1betaGetMultipleKmsConfigs(params *V1betaGetMultipleKmsConfigsParams) (*V1betaGetMultipleKmsConfigsOK, error)

	V1betaListKmsConfigurations(params *V1betaListKmsConfigurationsParams) (*V1betaListKmsConfigurationsOK, error)

	V1betaUpdateKmsConfiguration(params *V1betaUpdateKmsConfigurationParams) (*V1betaUpdateKmsConfigurationOK, error)

	SetTransport(transport runtime.ClientTransport)
}

/*
V1betaCreateKmsConfiguration creates a k m s configuration

Create new KMS configuration for the active user
*/
func (a *Client) V1betaCreateKmsConfiguration(params *V1betaCreateKmsConfigurationParams) (*V1betaCreateKmsConfigurationAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1betaCreateKmsConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "v1beta_CreateKmsConfiguration",
		Method:             "POST",
		PathPattern:        "/v1beta/projects/{projectNumber}/locations/{locationId}/storage/kmsConfig",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1betaCreateKmsConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1betaCreateKmsConfigurationAccepted)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1betaCreateKmsConfigurationDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
V1betaCheckKmsConfig verifies k m s configuration reachability

Verifies whether service account can access the configured key
*/
func (a *Client) V1betaCheckKmsConfig(params *V1betaCheckKmsConfigParams) (*V1betaCheckKmsConfigOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1betaCheckKmsConfigParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "v1beta_checkKmsConfig",
		Method:             "GET",
		PathPattern:        "/v1beta/projects/{projectNumber}/locations/{locationId}/storage/kmsConfig/{kmsConfigId}/check",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1betaCheckKmsConfigReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1betaCheckKmsConfigOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1betaCheckKmsConfigDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
V1betaDeleteKmsConfiguration deletes a k m s configuration

Deletes KMS configuration for the active user
*/
func (a *Client) V1betaDeleteKmsConfiguration(params *V1betaDeleteKmsConfigurationParams) (*V1betaDeleteKmsConfigurationAccepted, *V1betaDeleteKmsConfigurationNoContent, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1betaDeleteKmsConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "v1beta_deleteKmsConfiguration",
		Method:             "DELETE",
		PathPattern:        "/v1beta/projects/{projectNumber}/locations/{locationId}/storage/kmsConfig/{kmsConfigId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1betaDeleteKmsConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, nil, err
	}
	switch value := result.(type) {
	case *V1betaDeleteKmsConfigurationAccepted:
		return value, nil, nil
	case *V1betaDeleteKmsConfigurationNoContent:
		return nil, value, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1betaDeleteKmsConfigurationDefault)
	return nil, nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
V1betaDescribeKmsConfiguration describes a k m s configuration

Returns the description of a KMS configuration specified by KMS configuration ID.
*/
func (a *Client) V1betaDescribeKmsConfiguration(params *V1betaDescribeKmsConfigurationParams) (*V1betaDescribeKmsConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1betaDescribeKmsConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "v1beta_describeKmsConfiguration",
		Method:             "GET",
		PathPattern:        "/v1beta/projects/{projectNumber}/locations/{locationId}/storage/kmsConfig/{kmsConfigId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1betaDescribeKmsConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1betaDescribeKmsConfigurationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1betaDescribeKmsConfigurationDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
V1betaEncryptVolumes migrates volumes to g c p c m e k encryption

Migrates all volumes to GCP CMEK encryption.
*/
func (a *Client) V1betaEncryptVolumes(params *V1betaEncryptVolumesParams) (*V1betaEncryptVolumesAccepted, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1betaEncryptVolumesParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "v1beta_encryptVolumes",
		Method:             "POST",
		PathPattern:        "/v1beta/projects/{projectNumber}/locations/{locationId}/storage/kmsConfig/{kmsConfigId}/encryptVolumes",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1betaEncryptVolumesReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1betaEncryptVolumesAccepted)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1betaEncryptVolumesDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
V1betaGetMultipleKmsConfigs lists specified k m s configurations

Returns descriptions of KMS configurations that are listed in request body.
*/
func (a *Client) V1betaGetMultipleKmsConfigs(params *V1betaGetMultipleKmsConfigsParams) (*V1betaGetMultipleKmsConfigsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1betaGetMultipleKmsConfigsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "v1beta_getMultipleKmsConfigs",
		Method:             "POST",
		PathPattern:        "/v1beta/projects/{projectNumber}/locations/{locationId}/storage/kmsConfig/getMultipleKmsConfigs",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1betaGetMultipleKmsConfigsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1betaGetMultipleKmsConfigsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1betaGetMultipleKmsConfigsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
V1betaListKmsConfigurations lists all k m s configurations

Returns descriptions of all KMS configurations owned by the caller.
*/
func (a *Client) V1betaListKmsConfigurations(params *V1betaListKmsConfigurationsParams) (*V1betaListKmsConfigurationsOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1betaListKmsConfigurationsParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "v1beta_listKmsConfigurations",
		Method:             "GET",
		PathPattern:        "/v1beta/projects/{projectNumber}/locations/{locationId}/storage/kmsConfig",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1betaListKmsConfigurationsReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1betaListKmsConfigurationsOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1betaListKmsConfigurationsDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

/*
V1betaUpdateKmsConfiguration updates a k m s configuration

Update the KMS configuration
*/
func (a *Client) V1betaUpdateKmsConfiguration(params *V1betaUpdateKmsConfigurationParams) (*V1betaUpdateKmsConfigurationOK, error) {
	// TODO: Validate the params before sending
	if params == nil {
		params = NewV1betaUpdateKmsConfigurationParams()
	}

	result, err := a.transport.Submit(&runtime.ClientOperation{
		ID:                 "v1beta_updateKmsConfiguration",
		Method:             "PUT",
		PathPattern:        "/v1beta/projects/{projectNumber}/locations/{locationId}/storage/kmsConfig/{kmsConfigId}",
		ProducesMediaTypes: []string{"application/json"},
		ConsumesMediaTypes: []string{"application/json"},
		Schemes:            []string{"http", "https"},
		Params:             params,
		Reader:             &V1betaUpdateKmsConfigurationReader{formats: a.formats},
		Context:            params.Context,
		Client:             params.HTTPClient,
	})
	if err != nil {
		return nil, err
	}
	success, ok := result.(*V1betaUpdateKmsConfigurationOK)
	if ok {
		return success, nil
	}
	// unexpected success response
	unexpectedSuccess := result.(*V1betaUpdateKmsConfigurationDefault)
	return nil, runtime.NewAPIError("unexpected success response: content available as default response in error", unexpectedSuccess, unexpectedSuccess.Code())
}

// SetTransport changes the transport on the client
func (a *Client) SetTransport(transport runtime.ClientTransport) {
	a.transport = transport
}
