ARG BASE
FROM $BASE

# Copy the binary to the production image from the builder stage.
COPY artifacts/telemetry /app

# Copy Air config for live reload
COPY telemetry/air.toml /app/air.toml

ENV GOTRACEBACK=all
ENTRYPOINT ["air", "-c", "/app/air.toml"]

# Document the port the container listens on.
EXPOSE 8080
