apiVersion: v1
kind: Namespace
metadata:
  name: vcp
  labels:
    name: vcp
---
apiVersion: v1
kind: Service
metadata:
  name: core-service
  namespace: vcp
  labels:
    app: core-service
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: core
  selector:
    app: core-service
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  namespace: vcp
  labels:
    app: core-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-service
  template:
    metadata:
      labels:
        app: core-service
    spec:
      containers:
      - name: core
        image: core
        env:
          - name: FIRESTORE_EMULATOR_HOST
            value: firestore_emulator:8200
          - name: FIRESTORE_PROJECT_ID
            value: dummy-project-id
        ports:
        - containerPort: 50051
          name: http
