version: 2
linters:
  enable:
    - govet
    - staticcheck
    - ineffassign
    - errcheck
    - importas

  disable:
    - gocyclo
    - dupl
    - depguard
    - gosec

run:
  timeout: 5m
  skip-dirs:
    - vendor
    - clients/core-api
    - clients/cvp
    - clients/ontap-rest
    - clients/cvp
    - core/core-api/core-servergen
    - google-proxy/api/gcp-servergen
    - cicd/cmd/lint
  skip-files:
    - workflow_engine/workflow_engine_mock.go
    - workflow_engine/client_config_mock.go
    - workflow_engine/temporal_test_client_mock.go
    - database/storage_mock.go
    - core/orchestrator/orchestrator_factory_mock.go
    - clients/hyperscaler/google_services_mock.go
    - database/data_store_mock.go