// Code generated by go-swagger; DO NOT EDIT.

package backups

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp/models"
)

// V1betaListBackupsReader is a Reader for the V1betaListBackups structure.
type V1betaListBackupsReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1betaListBackupsReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1betaListBackupsOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1betaListBackupsBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewV1betaListBackupsUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV1betaListBackupsForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1betaListBackupsNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV1betaListBackupsInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewV1betaListBackupsNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewV1betaListBackupsDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV1betaListBackupsOK creates a V1betaListBackupsOK with default headers values
func NewV1betaListBackupsOK() *V1betaListBackupsOK {
	return &V1betaListBackupsOK{}
}

/*
V1betaListBackupsOK handles this case with default header values.

OK
*/
type V1betaListBackupsOK struct {
	Payload *V1betaListBackupsOKBody
}

func (o *V1betaListBackupsOK) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/backupVaults/{backupVaultId}/backups][%d] v1betaListBackupsOK  %+v", 200, o.Payload)
}

func (o *V1betaListBackupsOK) GetPayload() *V1betaListBackupsOKBody {
	return o.Payload
}

func (o *V1betaListBackupsOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(V1betaListBackupsOKBody)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaListBackupsBadRequest creates a V1betaListBackupsBadRequest with default headers values
func NewV1betaListBackupsBadRequest() *V1betaListBackupsBadRequest {
	return &V1betaListBackupsBadRequest{}
}

/*
V1betaListBackupsBadRequest handles this case with default header values.

Bad request
*/
type V1betaListBackupsBadRequest struct {
	Payload *models.Error
}

func (o *V1betaListBackupsBadRequest) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/backupVaults/{backupVaultId}/backups][%d] v1betaListBackupsBadRequest  %+v", 400, o.Payload)
}

func (o *V1betaListBackupsBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaListBackupsBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaListBackupsUnauthorized creates a V1betaListBackupsUnauthorized with default headers values
func NewV1betaListBackupsUnauthorized() *V1betaListBackupsUnauthorized {
	return &V1betaListBackupsUnauthorized{}
}

/*
V1betaListBackupsUnauthorized handles this case with default header values.

Unauthorized
*/
type V1betaListBackupsUnauthorized struct {
	Payload *models.Error
}

func (o *V1betaListBackupsUnauthorized) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/backupVaults/{backupVaultId}/backups][%d] v1betaListBackupsUnauthorized  %+v", 401, o.Payload)
}

func (o *V1betaListBackupsUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaListBackupsUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaListBackupsForbidden creates a V1betaListBackupsForbidden with default headers values
func NewV1betaListBackupsForbidden() *V1betaListBackupsForbidden {
	return &V1betaListBackupsForbidden{}
}

/*
V1betaListBackupsForbidden handles this case with default header values.

Forbidden
*/
type V1betaListBackupsForbidden struct {
	Payload *models.Error
}

func (o *V1betaListBackupsForbidden) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/backupVaults/{backupVaultId}/backups][%d] v1betaListBackupsForbidden  %+v", 403, o.Payload)
}

func (o *V1betaListBackupsForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaListBackupsForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaListBackupsNotFound creates a V1betaListBackupsNotFound with default headers values
func NewV1betaListBackupsNotFound() *V1betaListBackupsNotFound {
	return &V1betaListBackupsNotFound{}
}

/*
V1betaListBackupsNotFound handles this case with default header values.

Not found
*/
type V1betaListBackupsNotFound struct {
	Payload *models.Error
}

func (o *V1betaListBackupsNotFound) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/backupVaults/{backupVaultId}/backups][%d] v1betaListBackupsNotFound  %+v", 404, o.Payload)
}

func (o *V1betaListBackupsNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaListBackupsNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaListBackupsInternalServerError creates a V1betaListBackupsInternalServerError with default headers values
func NewV1betaListBackupsInternalServerError() *V1betaListBackupsInternalServerError {
	return &V1betaListBackupsInternalServerError{}
}

/*
V1betaListBackupsInternalServerError handles this case with default header values.

Internal server error
*/
type V1betaListBackupsInternalServerError struct {
	Payload *models.Error
}

func (o *V1betaListBackupsInternalServerError) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/backupVaults/{backupVaultId}/backups][%d] v1betaListBackupsInternalServerError  %+v", 500, o.Payload)
}

func (o *V1betaListBackupsInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaListBackupsInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaListBackupsNotImplemented creates a V1betaListBackupsNotImplemented with default headers values
func NewV1betaListBackupsNotImplemented() *V1betaListBackupsNotImplemented {
	return &V1betaListBackupsNotImplemented{}
}

/*
V1betaListBackupsNotImplemented handles this case with default header values.

Not implemented
*/
type V1betaListBackupsNotImplemented struct {
	Payload *models.Error
}

func (o *V1betaListBackupsNotImplemented) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/backupVaults/{backupVaultId}/backups][%d] v1betaListBackupsNotImplemented  %+v", 501, o.Payload)
}

func (o *V1betaListBackupsNotImplemented) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaListBackupsNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaListBackupsDefault creates a V1betaListBackupsDefault with default headers values
func NewV1betaListBackupsDefault(code int) *V1betaListBackupsDefault {
	return &V1betaListBackupsDefault{
		_statusCode: code,
	}
}

/*
V1betaListBackupsDefault handles this case with default header values.

Unexpected error
*/
type V1betaListBackupsDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the v1beta list backups default response
func (o *V1betaListBackupsDefault) Code() int {
	return o._statusCode
}

func (o *V1betaListBackupsDefault) Error() string {
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/backupVaults/{backupVaultId}/backups][%d] v1beta_listBackups default  %+v", o._statusCode, o.Payload)
}

func (o *V1betaListBackupsDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaListBackupsDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
V1betaListBackupsOKBody v1beta list backups o k body
swagger:model V1betaListBackupsOKBody
*/
type V1betaListBackupsOKBody struct {

	// backups
	Backups []*models.BackupV1beta `json:"backups"`
}

// UnmarshalJSON unmarshals this object from a JSON structure
func (o *V1betaListBackupsOKBody) UnmarshalJSON(raw []byte) error {
	// V1betaListBackupsOKBodyAO0
	var dataV1betaListBackupsOKBodyAO0 struct {
		Backups []*models.BackupV1beta `json:"backups"`
	}
	if err := swag.ReadJSON(raw, &dataV1betaListBackupsOKBodyAO0); err != nil {
		return err
	}

	o.Backups = dataV1betaListBackupsOKBodyAO0.Backups

	return nil
}

// MarshalJSON marshals this object to a JSON structure
func (o V1betaListBackupsOKBody) MarshalJSON() ([]byte, error) {
	_parts := make([][]byte, 0, 1)

	var dataV1betaListBackupsOKBodyAO0 struct {
		Backups []*models.BackupV1beta `json:"backups"`
	}

	dataV1betaListBackupsOKBodyAO0.Backups = o.Backups

	jsonDataV1betaListBackupsOKBodyAO0, errV1betaListBackupsOKBodyAO0 := swag.WriteJSON(dataV1betaListBackupsOKBodyAO0)
	if errV1betaListBackupsOKBodyAO0 != nil {
		return nil, errV1betaListBackupsOKBodyAO0
	}
	_parts = append(_parts, jsonDataV1betaListBackupsOKBodyAO0)
	return swag.ConcatJSON(_parts...), nil
}

// Validate validates this v1beta list backups o k body
func (o *V1betaListBackupsOKBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateBackups(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *V1betaListBackupsOKBody) validateBackups(formats strfmt.Registry) error {

	if swag.IsZero(o.Backups) { // not required
		return nil
	}

	for i := 0; i < len(o.Backups); i++ {
		if swag.IsZero(o.Backups[i]) { // not required
			continue
		}

		if o.Backups[i] != nil {
			if err := o.Backups[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("v1betaListBackupsOK" + "." + "backups" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (o *V1betaListBackupsOKBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *V1betaListBackupsOKBody) UnmarshalBinary(b []byte) error {
	var res V1betaListBackupsOKBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
