ARG BASE
FROM $BASE

COPY app/core /app
COPY common/vsa_config /common/vsa_config
COPY utils/harvest-template.yaml /app/harvest-template.yaml

# Copy Air config for live reload
COPY core/air.toml /app/air.toml

ENV GOTRACEBACK=all
ENTRYPOINT ["air", "-c", "/app/air.toml"]

# Set ownership and permissions - commented out for dev compatibility
# USER nonroot:nonroot
