// Code generated by go-swagger; DO NOT EDIT.

package n_a_s

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewAuditLogRedirectDeleteParams creates a new AuditLogRedirectDeleteParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewAuditLogRedirectDeleteParams() *AuditLogRedirectDeleteParams {
	return &AuditLogRedirectDeleteParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewAuditLogRedirectDeleteParamsWithTimeout creates a new AuditLogRedirectDeleteParams object
// with the ability to set a timeout on a request.
func NewAuditLogRedirectDeleteParamsWithTimeout(timeout time.Duration) *AuditLogRedirectDeleteParams {
	return &AuditLogRedirectDeleteParams{
		timeout: timeout,
	}
}

// NewAuditLogRedirectDeleteParamsWithContext creates a new AuditLogRedirectDeleteParams object
// with the ability to set a context for a request.
func NewAuditLogRedirectDeleteParamsWithContext(ctx context.Context) *AuditLogRedirectDeleteParams {
	return &AuditLogRedirectDeleteParams{
		Context: ctx,
	}
}

// NewAuditLogRedirectDeleteParamsWithHTTPClient creates a new AuditLogRedirectDeleteParams object
// with the ability to set a custom HTTPClient for a request.
func NewAuditLogRedirectDeleteParamsWithHTTPClient(client *http.Client) *AuditLogRedirectDeleteParams {
	return &AuditLogRedirectDeleteParams{
		HTTPClient: client,
	}
}

/*
AuditLogRedirectDeleteParams contains all the parameters to send to the API endpoint

	for the audit log redirect delete operation.

	Typically these are written to a http.Request.
*/
type AuditLogRedirectDeleteParams struct {
	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the audit log redirect delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuditLogRedirectDeleteParams) WithDefaults() *AuditLogRedirectDeleteParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the audit log redirect delete params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *AuditLogRedirectDeleteParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the audit log redirect delete params
func (o *AuditLogRedirectDeleteParams) WithTimeout(timeout time.Duration) *AuditLogRedirectDeleteParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the audit log redirect delete params
func (o *AuditLogRedirectDeleteParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the audit log redirect delete params
func (o *AuditLogRedirectDeleteParams) WithContext(ctx context.Context) *AuditLogRedirectDeleteParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the audit log redirect delete params
func (o *AuditLogRedirectDeleteParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the audit log redirect delete params
func (o *AuditLogRedirectDeleteParams) WithHTTPClient(client *http.Client) *AuditLogRedirectDeleteParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the audit log redirect delete params
func (o *AuditLogRedirectDeleteParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WriteToRequest writes these params to a swagger request
func (o *AuditLogRedirectDeleteParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
