global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  primaryImageRegistryPasswordAuth: true
  primaryImagePullSecretName: ghcr.io
  secondaryImageRegistry: "europe-north1-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vcp-container-images-us"
  useTags: false
  secondaryImageRegistryPasswordAuth: false
  nodeSelector:
    nodeType: vsacp-nodes
  chartPrimaryImageRegistry: ""
  chartSecondaryImageRegistry: ""
  environment: gcp
  hyperscaler: gcp
  workloadIdentityEnabled: false