// Code generated by go-swagger; DO NOT EDIT.

package san

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"fmt"
	"io"
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/ontap-rest/models"
)

// XcIgroupInitiatorModifyCollectionReader is a Reader for the XcIgroupInitiatorModifyCollection structure.
type XcIgroupInitiatorModifyCollectionReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *XcIgroupInitiatorModifyCollectionReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewXcIgroupInitiatorModifyCollectionOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewXcIgroupInitiatorModifyCollectionDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewXcIgroupInitiatorModifyCollectionOK creates a XcIgroupInitiatorModifyCollectionOK with default headers values
func NewXcIgroupInitiatorModifyCollectionOK() *XcIgroupInitiatorModifyCollectionOK {
	return &XcIgroupInitiatorModifyCollectionOK{}
}

/*
XcIgroupInitiatorModifyCollectionOK describes a response with status code 200, with default header values.

OK
*/
type XcIgroupInitiatorModifyCollectionOK struct {
}

// IsSuccess returns true when this xc igroup initiator modify collection o k response has a 2xx status code
func (o *XcIgroupInitiatorModifyCollectionOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this xc igroup initiator modify collection o k response has a 3xx status code
func (o *XcIgroupInitiatorModifyCollectionOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this xc igroup initiator modify collection o k response has a 4xx status code
func (o *XcIgroupInitiatorModifyCollectionOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this xc igroup initiator modify collection o k response has a 5xx status code
func (o *XcIgroupInitiatorModifyCollectionOK) IsServerError() bool {
	return false
}

// IsCode returns true when this xc igroup initiator modify collection o k response a status code equal to that given
func (o *XcIgroupInitiatorModifyCollectionOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the xc igroup initiator modify collection o k response
func (o *XcIgroupInitiatorModifyCollectionOK) Code() int {
	return 200
}

func (o *XcIgroupInitiatorModifyCollectionOK) Error() string {
	return fmt.Sprintf("[PATCH /cluster/peers/{peer.uuid}/protocols/san/igroups/{igroup.uuid}/initiators][%d] xcIgroupInitiatorModifyCollectionOK ", 200)
}

func (o *XcIgroupInitiatorModifyCollectionOK) String() string {
	return fmt.Sprintf("[PATCH /cluster/peers/{peer.uuid}/protocols/san/igroups/{igroup.uuid}/initiators][%d] xcIgroupInitiatorModifyCollectionOK ", 200)
}

func (o *XcIgroupInitiatorModifyCollectionOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	return nil
}

// NewXcIgroupInitiatorModifyCollectionDefault creates a XcIgroupInitiatorModifyCollectionDefault with default headers values
func NewXcIgroupInitiatorModifyCollectionDefault(code int) *XcIgroupInitiatorModifyCollectionDefault {
	return &XcIgroupInitiatorModifyCollectionDefault{
		_statusCode: code,
	}
}

/*
XcIgroupInitiatorModifyCollectionDefault describes a response with status code -1, with default header values.

Error
*/
type XcIgroupInitiatorModifyCollectionDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this xc igroup initiator modify collection default response has a 2xx status code
func (o *XcIgroupInitiatorModifyCollectionDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this xc igroup initiator modify collection default response has a 3xx status code
func (o *XcIgroupInitiatorModifyCollectionDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this xc igroup initiator modify collection default response has a 4xx status code
func (o *XcIgroupInitiatorModifyCollectionDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this xc igroup initiator modify collection default response has a 5xx status code
func (o *XcIgroupInitiatorModifyCollectionDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this xc igroup initiator modify collection default response a status code equal to that given
func (o *XcIgroupInitiatorModifyCollectionDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the xc igroup initiator modify collection default response
func (o *XcIgroupInitiatorModifyCollectionDefault) Code() int {
	return o._statusCode
}

func (o *XcIgroupInitiatorModifyCollectionDefault) Error() string {
	return fmt.Sprintf("[PATCH /cluster/peers/{peer.uuid}/protocols/san/igroups/{igroup.uuid}/initiators][%d] xc_igroup_initiator_modify_collection default  %+v", o._statusCode, o.Payload)
}

func (o *XcIgroupInitiatorModifyCollectionDefault) String() string {
	return fmt.Sprintf("[PATCH /cluster/peers/{peer.uuid}/protocols/san/igroups/{igroup.uuid}/initiators][%d] xc_igroup_initiator_modify_collection default  %+v", o._statusCode, o.Payload)
}

func (o *XcIgroupInitiatorModifyCollectionDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *XcIgroupInitiatorModifyCollectionDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

/*
XcIgroupInitiatorModifyCollectionBody igroup_initiator_response clone for cluster peer.
swagger:model XcIgroupInitiatorModifyCollectionBody
*/
type XcIgroupInitiatorModifyCollectionBody struct {

	// links
	Links *IgroupInitiatorInlineLinks `json:"_links,omitempty"`

	// A comment available for use by the administrator. Valid in POST and PATCH.
	//
	// Max Length: 254
	// Min Length: 0
	Comment *string `json:"comment,omitempty"`

	// connectivity tracking
	ConnectivityTracking *IgroupInitiatorInlineConnectivityTracking `json:"connectivity_tracking,omitempty"`

	// igroup
	Igroup *IgroupInitiatorInlineIgroup `json:"igroup,omitempty"`

	// An array of initiators specified to add multiple initiators to an initiator group in a single API call. Not allowed when the `name` property is used.
	//
	IgroupInitiatorInlineRecords []*IgroupInitiatorInlineRecordsInlineArrayItem `json:"records,omitempty"`

	// The FC WWPN, iSCSI IQN, or iSCSI EUI that identifies the host initiator. Valid in POST only and not allowed when the `records` property is used.<br/>
	// An FC WWPN consists of 16 hexadecimal digits grouped as 8 pairs separated by colons. The format for an iSCSI IQN is _iqn.yyyy-mm.reverse_domain_name:any_. The iSCSI EUI format consists of the _eui._ prefix followed by 16 hexadecimal characters.
	//
	// Example: iqn.1998-01.com.corp.iscsi:name1
	// Max Length: 96
	// Min Length: 1
	Name *string `json:"name,omitempty"`

	// proximity
	Proximity *IgroupInitiatorInlineProximity `json:"proximity,omitempty"`
}

// Validate validates this xc igroup initiator modify collection body
func (o *XcIgroupInitiatorModifyCollectionBody) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateComment(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateConnectivityTracking(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIgroup(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIgroupInitiatorInlineRecords(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateName(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateProximity(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("info" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) validateComment(formats strfmt.Registry) error {
	if swag.IsZero(o.Comment) { // not required
		return nil
	}

	if err := validate.MinLength("info"+"."+"comment", "body", *o.Comment, 0); err != nil {
		return err
	}

	if err := validate.MaxLength("info"+"."+"comment", "body", *o.Comment, 254); err != nil {
		return err
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) validateConnectivityTracking(formats strfmt.Registry) error {
	if swag.IsZero(o.ConnectivityTracking) { // not required
		return nil
	}

	if o.ConnectivityTracking != nil {
		if err := o.ConnectivityTracking.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "connectivity_tracking")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("info" + "." + "connectivity_tracking")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) validateIgroup(formats strfmt.Registry) error {
	if swag.IsZero(o.Igroup) { // not required
		return nil
	}

	if o.Igroup != nil {
		if err := o.Igroup.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "igroup")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("info" + "." + "igroup")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) validateIgroupInitiatorInlineRecords(formats strfmt.Registry) error {
	if swag.IsZero(o.IgroupInitiatorInlineRecords) { // not required
		return nil
	}

	for i := 0; i < len(o.IgroupInitiatorInlineRecords); i++ {
		if swag.IsZero(o.IgroupInitiatorInlineRecords[i]) { // not required
			continue
		}

		if o.IgroupInitiatorInlineRecords[i] != nil {
			if err := o.IgroupInitiatorInlineRecords[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("info" + "." + "records" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("info" + "." + "records" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) validateName(formats strfmt.Registry) error {
	if swag.IsZero(o.Name) { // not required
		return nil
	}

	if err := validate.MinLength("info"+"."+"name", "body", *o.Name, 1); err != nil {
		return err
	}

	if err := validate.MaxLength("info"+"."+"name", "body", *o.Name, 96); err != nil {
		return err
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) validateProximity(formats strfmt.Registry) error {
	if swag.IsZero(o.Proximity) { // not required
		return nil
	}

	if o.Proximity != nil {
		if err := o.Proximity.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "proximity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("info" + "." + "proximity")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection body based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionBody) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateConnectivityTracking(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateIgroup(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateIgroupInitiatorInlineRecords(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateProximity(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if o.Links != nil {
		if err := o.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("info" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) contextValidateConnectivityTracking(ctx context.Context, formats strfmt.Registry) error {

	if o.ConnectivityTracking != nil {
		if err := o.ConnectivityTracking.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "connectivity_tracking")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("info" + "." + "connectivity_tracking")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) contextValidateIgroup(ctx context.Context, formats strfmt.Registry) error {

	if o.Igroup != nil {
		if err := o.Igroup.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "igroup")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("info" + "." + "igroup")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) contextValidateIgroupInitiatorInlineRecords(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.IgroupInitiatorInlineRecords); i++ {

		if o.IgroupInitiatorInlineRecords[i] != nil {
			if err := o.IgroupInitiatorInlineRecords[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("info" + "." + "records" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("info" + "." + "records" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionBody) contextValidateProximity(ctx context.Context, formats strfmt.Registry) error {

	if o.Proximity != nil {
		if err := o.Proximity.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("info" + "." + "proximity")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("info" + "." + "proximity")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionBody) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionBody) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionBody
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0 xc igroup initiator modify collection params body connectivity tracking alerts items0
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0 struct {

	// summary
	Summary *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary `json:"summary,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking alerts items0
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSummary(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0) validateSummary(formats strfmt.Registry) error {
	if swag.IsZero(o.Summary) { // not required
		return nil
	}

	if o.Summary != nil {
		if err := o.Summary.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("summary")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("summary")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking alerts items0 based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSummary(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0) contextValidateSummary(ctx context.Context, formats strfmt.Registry) error {

	if o.Summary != nil {
		if err := o.Summary.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("summary")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("summary")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary A user friendly message describing the connection state.
//
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary struct {

	// Message arguments
	// Read Only: true
	Arguments []*models.ErrorArguments `json:"arguments"`

	// Error code
	// Example: 4
	// Read Only: true
	Code *string `json:"code,omitempty"`

	// Error message
	// Example: entry doesn't exist
	// Read Only: true
	Message *string `json:"message,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking alerts items0 summary
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateArguments(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary) validateArguments(formats strfmt.Registry) error {
	if swag.IsZero(o.Arguments) { // not required
		return nil
	}

	for i := 0; i < len(o.Arguments); i++ {
		if swag.IsZero(o.Arguments[i]) { // not required
			continue
		}

		if o.Arguments[i] != nil {
			if err := o.Arguments[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("summary" + "." + "arguments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("summary" + "." + "arguments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking alerts items0 summary based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateArguments(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateCode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateMessage(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary) contextValidateArguments(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "summary"+"."+"arguments", "body", []*models.ErrorArguments(o.Arguments)); err != nil {
		return err
	}

	for i := 0; i < len(o.Arguments); i++ {

		if o.Arguments[i] != nil {
			if err := o.Arguments[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("summary" + "." + "arguments" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("summary" + "." + "arguments" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary) contextValidateCode(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "summary"+"."+"code", "body", o.Code); err != nil {
		return err
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary) contextValidateMessage(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "summary"+"."+"message", "body", o.Message); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingAlertsItems0Summary
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0 xc igroup initiator modify collection params body connectivity tracking connections items0
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0 struct {

	// logins
	Logins []*XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0 `json:"logins"`

	// node
	Node *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node `json:"node,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLogins(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateNode(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0) validateLogins(formats strfmt.Registry) error {
	if swag.IsZero(o.Logins) { // not required
		return nil
	}

	for i := 0; i < len(o.Logins); i++ {
		if swag.IsZero(o.Logins[i]) { // not required
			continue
		}

		if o.Logins[i] != nil {
			if err := o.Logins[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("logins" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("logins" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0) validateNode(formats strfmt.Registry) error {
	if swag.IsZero(o.Node) { // not required
		return nil
	}

	if o.Node != nil {
		if err := o.Node.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("node")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLogins(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateNode(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0) contextValidateLogins(ctx context.Context, formats strfmt.Registry) error {

	for i := 0; i < len(o.Logins); i++ {

		if o.Logins[i] != nil {
			if err := o.Logins[i].ContextValidate(ctx, formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("logins" + "." + strconv.Itoa(i))
				} else if ce, ok := err.(*errors.CompositeError); ok {
					return ce.ValidateName("logins" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0) contextValidateNode(ctx context.Context, formats strfmt.Registry) error {

	if o.Node != nil {
		if err := o.Node.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("node")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0 xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0 struct {

	// True if the initiator is currently logged in to this connection's interface.
	//
	// Read Only: true
	Connected *bool `json:"connected,omitempty"`

	// interface
	Interface *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface `json:"interface,omitempty"`

	// The last time this initiator logged in. Logins not seen for 48 hours are cleared and not reported.
	//
	// Example: 2021-03-14 05:19:00
	// Read Only: true
	// Format: date-time
	LastSeenTime *strfmt.DateTime `json:"last_seen_time,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateInterface(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateLastSeenTime(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) validateInterface(formats strfmt.Registry) error {
	if swag.IsZero(o.Interface) { // not required
		return nil
	}

	if o.Interface != nil {
		if err := o.Interface.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) validateLastSeenTime(formats strfmt.Registry) error {
	if swag.IsZero(o.LastSeenTime) { // not required
		return nil
	}

	if err := validate.FormatOf("last_seen_time", "body", "date-time", o.LastSeenTime.String(), formats); err != nil {
		return err
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateConnected(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateInterface(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateLastSeenTime(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) contextValidateConnected(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "connected", "body", o.Connected); err != nil {
		return err
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) contextValidateInterface(ctx context.Context, formats strfmt.Registry) error {

	if o.Interface != nil {
		if err := o.Interface.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) contextValidateLastSeenTime(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "last_seen_time", "body", o.LastSeenTime); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface struct {

	// fc
	Fc *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc `json:"fc,omitempty"`

	// ip
	IP *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP `json:"ip,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateFc(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface) validateFc(formats strfmt.Registry) error {
	if swag.IsZero(o.Fc) { // not required
		return nil
	}

	if o.Fc != nil {
		if err := o.Fc.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "fc")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "fc")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface) validateIP(formats strfmt.Registry) error {
	if swag.IsZero(o.IP) { // not required
		return nil
	}

	if o.IP != nil {
		if err := o.IP.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateFc(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateIP(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface) contextValidateFc(ctx context.Context, formats strfmt.Registry) error {

	if o.Fc != nil {
		if err := o.Fc.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "fc")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "fc")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface) contextValidateIP(ctx context.Context, formats strfmt.Registry) error {

	if o.IP != nil {
		if err := o.IP.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0Interface
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc An FC interface.
//
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc struct {

	// links
	Links *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks `json:"_links,omitempty"`

	// The name of the FC interface.
	//
	// Example: fc_lif1
	Name *string `json:"name,omitempty"`

	// The unique identifier of the FC interface.
	//
	// Example: 3a09ab42-4da1-32cf-9d35-3385a6101a0b
	UUID *string `json:"uuid,omitempty"`

	// The WWPN of the FC interface.
	//
	// Example: 20:00:00:50:56:b4:13:a8
	// Read Only: true
	Wwpn *string `json:"wwpn,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface fc
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "fc" + "." + "_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "fc" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface fc based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateWwpn(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if o.Links != nil {
		if err := o.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "fc" + "." + "_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "fc" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc) contextValidateWwpn(ctx context.Context, formats strfmt.Registry) error {

	if err := validate.ReadOnly(ctx, "interface"+"."+"fc"+"."+"wwpn", "body", o.Wwpn); err != nil {
		return err
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFc
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface fc links
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks struct {

	// self
	Self *models.Href `json:"self,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface fc links
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks) validateSelf(formats strfmt.Registry) error {
	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "fc" + "." + "_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "fc" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface fc links based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSelf(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks) contextValidateSelf(ctx context.Context, formats strfmt.Registry) error {

	if o.Self != nil {
		if err := o.Self.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "fc" + "." + "_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "fc" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceFcLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP A network interface. Either UUID or name may be supplied on input.
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP struct {

	// links
	Links *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks `json:"_links,omitempty"`

	// ip
	IP *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP `json:"ip,omitempty"`

	// The name of the interface. If only the name is provided, the SVM scope
	// must be provided by the object this object is embedded in.
	//
	// Example: lif1
	Name *string `json:"name,omitempty"`

	// The UUID that uniquely identifies the interface.
	// Example: 1cd8a442-86d1-11e0-ae1c-123478563412
	UUID *string `json:"uuid,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface IP
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if err := o.validateIP(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip" + "." + "_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP) validateIP(formats strfmt.Registry) error {
	if swag.IsZero(o.IP) { // not required
		return nil
	}

	if o.IP != nil {
		if err := o.IP.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip" + "." + "ip")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip" + "." + "ip")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface IP based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if err := o.contextValidateIP(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if o.Links != nil {
		if err := o.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip" + "." + "_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP) contextValidateIP(ctx context.Context, formats strfmt.Registry) error {

	if o.IP != nil {
		if err := o.IP.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip" + "." + "ip")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip" + "." + "ip")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP IP information
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP struct {

	// address
	Address *models.IPAddressReadonly `json:"address,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface IP IP
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateAddress(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP) validateAddress(formats strfmt.Registry) error {
	if swag.IsZero(o.Address) { // not required
		return nil
	}

	if o.Address != nil {
		if err := o.Address.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip" + "." + "ip" + "." + "address")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip" + "." + "ip" + "." + "address")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface IP IP based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateAddress(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP) contextValidateAddress(ctx context.Context, formats strfmt.Registry) error {

	if o.Address != nil {
		if err := o.Address.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip" + "." + "ip" + "." + "address")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip" + "." + "ip" + "." + "address")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPIP
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface IP links
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks struct {

	// self
	Self *models.Href `json:"self,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface IP links
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks) validateSelf(formats strfmt.Registry) error {
	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip" + "." + "_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 logins items0 interface IP links based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSelf(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks) contextValidateSelf(ctx context.Context, formats strfmt.Registry) error {

	if o.Self != nil {
		if err := o.Self.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("interface" + "." + "ip" + "." + "_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("interface" + "." + "ip" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0LoginsItems0InterfaceIPLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node xc igroup initiator modify collection params body connectivity tracking connections items0 node
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node struct {

	// links
	Links *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks `json:"_links,omitempty"`

	// name
	// Example: node1
	Name *string `json:"name,omitempty"`

	// uuid
	// Example: 1cd8a442-86d1-11e0-ae1c-123478563412
	UUID *string `json:"uuid,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 node
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node" + "." + "_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("node" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 node based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if o.Links != nil {
		if err := o.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node" + "." + "_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("node" + "." + "_links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0Node
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks xc igroup initiator modify collection params body connectivity tracking connections items0 node links
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks
*/
type XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks struct {

	// self
	Self *models.Href `json:"self,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body connectivity tracking connections items0 node links
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks) validateSelf(formats strfmt.Registry) error {
	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node" + "." + "_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("node" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body connectivity tracking connections items0 node links based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSelf(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks) contextValidateSelf(ctx context.Context, formats strfmt.Registry) error {

	if o.Self != nil {
		if err := o.Self.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("node" + "." + "_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("node" + "." + "_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyConnectivityTrackingConnectionsItems0NodeLinks
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0 A reference to an SVM peer relationship.
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0
*/
type XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0 struct {

	// links
	Links *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links `json:"_links,omitempty"`

	// The local name of the peer SVM. This name is unique among all local and peer SVMs.
	//
	// Example: peer1
	Name *string `json:"name,omitempty"`

	// The unique identifier of the SVM peer relationship. This is the UUID of the relationship, not the UUID of the peer SVM itself.
	//
	// Example: 4204cf77-4c82-9bdb-5644-b5a841c097a9
	UUID *string `json:"uuid,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body proximity peer svms items0
func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body proximity peer svms items0 based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if o.Links != nil {
		if err := o.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links xc igroup initiator modify collection params body proximity peer svms items0 links
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links
*/
type XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links struct {

	// self
	Self *models.Href `json:"self,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body proximity peer svms items0 links
func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links) validateSelf(formats strfmt.Registry) error {
	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body proximity peer svms items0 links based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSelf(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links) contextValidateSelf(ctx context.Context, formats strfmt.Registry) error {

	if o.Self != nil {
		if err := o.Self.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyProximityPeerSvmsItems0Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0 A reference to an SVM peer relationship.
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0
*/
type XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0 struct {

	// links
	Links *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links `json:"_links,omitempty"`

	// The local name of the peer SVM. This name is unique among all local and peer SVMs.
	//
	// Example: peer1
	Name *string `json:"name,omitempty"`

	// The unique identifier of the SVM peer relationship. This is the UUID of the relationship, not the UUID of the peer SVM itself.
	//
	// Example: 4204cf77-4c82-9bdb-5644-b5a841c097a9
	UUID *string `json:"uuid,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body records items0 proximity peer svms items0
func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateLinks(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0) validateLinks(formats strfmt.Registry) error {
	if swag.IsZero(o.Links) { // not required
		return nil
	}

	if o.Links != nil {
		if err := o.Links.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body records items0 proximity peer svms items0 based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateLinks(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0) contextValidateLinks(ctx context.Context, formats strfmt.Registry) error {

	if o.Links != nil {
		if err := o.Links.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}

/*
XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links xc igroup initiator modify collection params body records items0 proximity peer svms items0 links
swagger:model XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links
*/
type XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links struct {

	// self
	Self *models.Href `json:"self,omitempty"`
}

// Validate validates this xc igroup initiator modify collection params body records items0 proximity peer svms items0 links
func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links) Validate(formats strfmt.Registry) error {
	var res []error

	if err := o.validateSelf(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links) validateSelf(formats strfmt.Registry) error {
	if swag.IsZero(o.Self) { // not required
		return nil
	}

	if o.Self != nil {
		if err := o.Self.Validate(formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// ContextValidate validate this xc igroup initiator modify collection params body records items0 proximity peer svms items0 links based on the context it is used
func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	var res []error

	if err := o.contextValidateSelf(ctx, formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links) contextValidateSelf(ctx context.Context, formats strfmt.Registry) error {

	if o.Self != nil {
		if err := o.Self.ContextValidate(ctx, formats); err != nil {
			if ve, ok := err.(*errors.Validation); ok {
				return ve.ValidateName("_links" + "." + "self")
			} else if ce, ok := err.(*errors.CompositeError); ok {
				return ce.ValidateName("_links" + "." + "self")
			}
			return err
		}
	}

	return nil
}

// MarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links) MarshalBinary() ([]byte, error) {
	if o == nil {
		return nil, nil
	}
	return swag.WriteJSON(o)
}

// UnmarshalBinary interface implementation
func (o *XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links) UnmarshalBinary(b []byte) error {
	var res XcIgroupInitiatorModifyCollectionParamsBodyRecordsItems0ProximityPeerSvmsItems0Links
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*o = res
	return nil
}
