apiVersion: v1
kind: Service
metadata:
  name: workflow-server
  labels:
    app: workflow-server
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: workflow-server
  selector:
    app: workflow-server
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: workflow-server
  labels:
    app: workflow-server
spec:
  replicas: 1
  selector:
    matchLabels:
      app: workflow-server
  template:
    metadata:
      labels:
        app: workflow-server
    spec:
      containers:
      - name: workflow-server
        image: workflow-server
        ports:
        - containerPort: 50051
          name: http
