apiVersion: v2
appVersion: v0.27.0
description: The Alertmanager handles alerts sent by client applications such as the Prometheus server.
keywords:
  - monitoring
kubeVersion: '>=1.19.0-0'
name: alertmanager
type: application
version: 1.11.0
