openapi: 3.0.4
info:
  title: Google Cloud NetApp Files API
  description: '## Google Cloud NetApp Files This is the documentation and examples
    for the "Google Cloud NetApp Files" or GNF for short'
  version: "${major_version}.${minor_version}.${patch_version}"
  x-logo:
    url: nfsaas-logo.png
    backgroundColor: '#FFFFFF'
tags:
  - name: billing and metrics
    description: Billing and Metrics operations
paths:
  /v1/performance:
    post:
      tags:
        - performance metrics
      summary: Trigger Performance Metrics Collection.
      description: Trigger Performance Metrics Collection
      operationId: v1_performance
      parameters:
        - name: X-Correlation-Id
          in: header
          description: Correlation ID for request tracing
          required: false
          schema:
            type: string
      responses:
        "202":
          description: Metrics collection triggered
        "400":
          description: Bad request
        "500":
          description: Internal server error
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/usage:
    post:
      tags:
        - usage metrics
      summary: Trigger Usage Metrics Collection.
      description: Trigger Usage Metrics Collection
      operationId: v1_usage
      parameters:
        - name: X-Correlation-Id
          in: header
          description: Correlation ID for request tracing
          required: false
          schema:
            type: string
      responses:
        "202":
          description: Metrics collection triggered
        "400":
          description: Bad request
        "500":
          description: Internal server error
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
  /v1/generateReport:
    post:
      tags:
        - generate report
      requestBody:
        description: The required parameters to create a new pool.
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/GenerateReport_v1beta'
        required: false
      summary: Trigger BizOps Report Generation.
      description: Trigger BizOps Report Generation
      operationId: v1_generateReport
      responses:
        "202":
          description: Report generation triggered
        "400":
          description: Bad request
        "500":
          description: Internal server error
        default:
          description: Unexpected error
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/Error'
components:
  schemas:
    Error:
      required:
        - code
        - message
      type: object
      properties:
        code:
          type: number
          format: double
          nullable: false
        message:
          type: string
          nullable: false
      description: Error response
      example:
        code: 1994.0
        message: Out of cheese error! Please reboot the Universe
    GenerateReport_v1beta:
        title: GenerateReport
        type: object
        properties:
            startDate:
              type: string
              format: date
              description: Start time for the report
              nullable: true
              example: 2025-01-31
            timeZone:
              type: string
              description: Time zone for the report.
              Allowed values: UTC, PST.
              enum:
                - UTC
                - PST
              example: UTC
            sinkType:
              type: string
              description: Sink type for the report.
              Allowed values: gcs, terminal.
              enum:
                - gcs
                - terminal
              example: gcs
        description: Request body for generating a BizOps report.