global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  primaryImageRegistryPasswordAuth: true
  primaryImagePullSecretName: ghcr.io
  secondaryImageRegistry: "us-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vlm"
  secondaryImageRegistryPasswordAuth: false
  useTags: false
  nodeSelector:
    nodeType: vsacp-nodes
  chartPrimaryImageRegistry: ""
  chartSecondaryImageRegistry: ""
  environment: gcp

# Application configuration
app:
  name: "vlm-worker"
  replicas: 1

serviceAccount:
  name: "vlm-worker-ksa"

# Image configuration
images:
  vlmWorker:
    name: temporal-vlm
    tag: "R9.17.1xN_non_promo_7745405"
    digest: "sha256:81badcebc85ff5f78ffebda3d10626d4f5288f24448bc8bc969df7c1400873b7"
    secondary: true
    pullPolicy: IfNotPresent

# Ontap Version
ontapVersion: "0.0.0"

podAnnotations: {}

initContainers: []

# Worker configuration
workerConfig:
  provider: "gcp"
  temporalHost: "temporal-frontend.temporal.svc.cluster.local"
  temporalPort: "7233"
  taskQueuePrefix: "vsa-lifecycle-manager"
  debug: "false"
  maxConcurrentActivities: "1000"
  maxConcurrentWorkflow: "1000"
  maxConcurrentWorkflowTaskPollers: "2"
  # Encryption key must be a 32-byte (256-bit) string for AES-256.
  vsaVlmEncryptionKey: "" # Should be the same as in the vcp-worker values.yaml.

#Enabling or Disabling Secret Manager for Microservice Secrets
secretManagerEnabled: false
