global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  primaryImageRegistryPasswordAuth: true
  primaryImagePullSecretName: ghcr.io
  secondaryImageRegistry: "us-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vcp-container-images-us"
  secondaryImageRegistryPasswordAuth: false
  useTags: false
  chartPrimaryImageRegistry: ""
  chartSecondaryImageRegistry: ""
  environment: gcp

# Application configuration
app:
  name: "vlm-worker"
  replicas: 1

serviceAccount:
  name: "vlm-worker-ksa"

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 350m
    memory: 500Mi

# Ontap Version mapping with VLM. To support more ontap versions, similar block needs to be added below.
# We should support previous versions as well, for backward compatibility.
ontapVersionVlmImageMappings:
    # VLM worker to support ONTAP patch version 9.17.1P2
  - ontapVersion: "9.17.1P2"
    vlmImageName: "vlm-worker"
    vlmImageTag: "R9.17.1x_7882520"
    vlmImageDigest: "sha256:0b0a7f4063ba4e848af6f5d43c120c830ab1bcadf4f13e11710a3f15f066bf27"
    secondary: true
    pullPolicy: IfNotPresent
  # VLM worker to support ONTAP patch version 9.17.1P1
  - ontapVersion: "9.17.1P1"
    vlmImageName: "vlm-worker"
    vlmImageTag: "R9.17.1x_7855269"
    vlmImageDigest: "sha256:07d042905f40dfc4c566919ebc539b617d9a1fc38773ab9a26e7749fd85c8405"
    secondary: true
    pullPolicy: IfNotPresent
    # VLM worker to support ONTAP test patch versions like 9.17.1X50 or any other test patch version
  - ontapVersion: "9.17.1"
    vlmImageName: "vlm-worker"
    vlmImageTag: "R9.17.1x_7882520"
    vlmImageDigest: "sha256:0b0a7f4063ba4e848af6f5d43c120c830ab1bcadf4f13e11710a3f15f066bf27"
    secondary: true
    pullPolicy: IfNotPresent
  - ontapVersion: "9.18.1"
    vlmImageName: "vlm-worker"
    vlmImageTag: "R9.18.1x_7966003"
    vlmImageDigest: "sha256:9f341969850af4444f59126bcc50a44b50044e17f1c1a53181f8ef343627630e"
    secondary: true
    pullPolicy: IfNotPresent

podAnnotations: {}

initContainers: []

# Worker configuration
workerConfig:
  provider: "gcp"
  temporalHost: "temporal-frontend.temporal.svc.cluster.local"
  temporalPort: "7233"
  taskQueuePrefix: "vsa-lifecycle-manager"
  debug: "false"
  maxConcurrentActivities: "1000"
  maxConcurrentWorkflow: "1000"
  maxConcurrentWorkflowTaskPollers: "2"
  # Encryption key must be a 32-byte (256-bit) string for AES-256.
  vsaVlmEncryptionKey: "" # Should be the same as in the vcp-worker values.yaml.
  gceMetadataHost: ""
  enableGlobalGcpClients: "true"
  useVmReservations: "true"

#Enabling or Disabling Secret Manager for Microservice Secrets
secretManagerEnabled: false

# Pod affinity configuration  
podAffinity:  
  enabled: true
