apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccount.name }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- with .Values.serviceAccount.annotations }}
    {{- range $key, $value := . }}
    {{ $key | quote }}: {{ $value | quote }}
    {{- end }}
    {{- end }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.imagePullSecrets }}
  {{- if .name }}
  - name: {{ .name | quote }}
  {{- end }}
  {{- end }}
{{- end }}
