# This file describes VMRS (VM Right Sizing) module related configuration.
# It merges facts provided by our perf team and hyperscaler documented limits into a single source of truth.
#
# We nest all these details under a parent `vmrs` tag to avoid namespace clashes.
#
# The structure of this config is as follows:
#
# vmrs: # top level namespace disambiguator
#   max_num_ha_pairs: 12 # The max. number of HA pairs that we are allowed. This field constraints the max. performance/capacity that a single storage pool can be provisioned for.
#   ontap_overheads: # This data is provided by the perf team. The data in this section should be hyperscaler agnostic.
#     amplification_factors:
#     # We expect a multiplication factor.
#     # For example, if we want to allocate a 10% overhead, please input 1.1
#       iops: 1.1 # Overhead to overprovision by to guarantee that customer observes the IOPs they requested.
#       throughput: 1.1 # Overhead to overprovision by to guarantee that customer observes the throughput they requested.
#       capacity: 1.1 # WAFL overhead.
#     num_disks_per_zone: 8 # The number of disks that will be attached to each HA-pair (shared zonal mode), or VM (non-shared regional mode) to form an aggregate.
#     workload_headroom: # If the headroom values are 0, do not include this field at all.
#       - workload: backup # The name of the feature which is enabled.
#         headroom: # Additional headroom to provision in case this feature is enabled.
#           iops : 0.05
#           throughput: 0.05
#     hotspot_prevention_factors: # Additional overhead to provision to prevent hot-spotting.
#     # We expect a multiplication factor.
#     # For example, if we want to allocate a 10% overhead, please input 1.1
#       iops: 1.1
#       throughput: 1.1
#   - disk_type: hyperdisk_balanced # for this specific disk type, this element will contain a list of VMs that were qualified by the perf team.
#     qualified_vms:  # we consolidate by vm_type to prevent operator errors.
#     - vm_type: c4-standard-4 # data for a specific vm/instance type.
#       ontap_perf: # facts provided by the ontap perf team.
#         # For each VM/instance type, define the max. IOPS, capacity and throughput that ONTAP can support per HA-pair (i.e., per two nodes).
#         # This data is provided by the perf team.
#         iops: I
#         throughput_in_mibs: T
#         capacity_in_gib: C
#       disk_perf: # facts provided by the hyperscaler (GCP in this case).
#         # For each VM/instance type, define the max. capacity, IOPS and throughput that the hyperscaler allows.
#         iops: I
#         throughput_in_mibs: T
#         capacity_in_gib: C
#       relative_cost: 4 # cost of this VM relative to the smallest instance type that is available from the hyperscaler.
#                          The relative cost is *USUALLY* linear w.r.t the number of vCPUs/GPUs that the VM makes available for use.
#                          It is recommended to always provide this cost as a ratio (this_vm_cost/smallest_vm_cost). This will allow for
#                          qualifying smaller instances at a later point in time.
vmrs:
  selection_strategy: "least_cost_single_vm"
  max_num_ha_pairs: 1 # for preview.
  max_disk_overprovisioning_factors:
    iops: 1.1
    throughput: 1.1
  ontap_overheads:
    amplification_factors:
      iops: 3.3
      throughput: 2.538
      capacity: 1.2
    workload_headroom:
      - workload: all
        headroom:
          iops: 0.3
          throughput: 0.3
    num_disks_per_zone: 8
    hotspot_prevention_factors:
      iops: 1.1
      throughput: 1.1
  # GCP specific configuration.
  # GCP organizes hyperdisk limits as follows (https://cloud.google.com/compute/docs/disks/hyperdisk-perf-limits#per-vm-limits-summary):
  #   1. Overall throughput limits irrespective of hyperdisk type: https://cloud.google.com/compute/docs/disks/hyperdisk-perf-limits#machine-type-limits
  #      These limits are applicable to all hyperdisk types (balanced, extreme, etc.) and persistent disks.
  #      These limits are (or, should always be) higher than what are defined for specific hyperdisk types (see section 2 below). This was verified to be true as of June 3rd, 2025.
  #      If multiple hyperdisk types are used, the total IOPS and throughput across all hyperdisk types must not exceed these limits.
  #   2. Hyperdisk type specific throughput limits: https://cloud.google.com/compute/docs/disks/hyperdisk-perf-limits#hdb-perf
  #      These limits are applicable to each hyperdisk type and define the max. IOPS and throughput for that specific hyperdisk type.
  #   3. Hyperdisk size limits: https://cloud.google.com/compute/docs/disks/hyperdisk-perf-limits#limits-instance
  #      These limits define the max. capacity that can be attached to a VM/instance.
  #   4. Max. number of hyperdisks per vm: https://cloud.google.com/compute/docs/disks/hyperdisk-perf-limits#max-total-disks-per-vm
  #      These limits define the max. number of hyperdisks that can be attached to a VM/instance.
  #
  # Each ontap_perf entry is structured as follows. Ideally, the numbers from this section are the same as those in disk_perf, which means ONTAP has 0 overhead overall,
  # and is able to fully utilize the underlying hardware.
  # ontap_perf:
  #   iops: 6559 # Max. IOPS supported by ONTAP for this VM/instance type, per HA-pair.
  #   throughput_in_mibs: 168 # Max. throughput in Mibs supported by ONTAP for this VM/instance type, per HA-pair.
  #   capacity_in_gib: 213000 # Max. capacity in GiB supported by ONTAP for this VM/instance type, per HA-pair.
  #
  # Each disk_perf entry's data is pulled from the hyperscaler documentation, as shown below.
  # disk_perf:
  #   iops: 50000 # Max. IOPS allowed for this VM/instance type, with an I/O size of 4 KiB. From section 2 above.
  #   throughput_in_mibs: 400 # Max. throughput allowed for this VM/instance type, with an I/O size of at-least 256 KiB. From section 2 above.
  #   capacity_in_gib: 257000 # Max. capacity allowed for this VM/instance type. From section 3 above.
  disk_limits:
    - disk_type: hyperdisk-balanced
      qualified_vms:
      - vm_type: c3-standard-4-lssd
        ontap_perf:
          iops: 8286
          throughput_in_mibs: 105
          capacity_in_gib: 213000
        disk_perf:
          iops: 25000
          throughput_in_mibs: 400
          capacity_in_gib: 257000
        relative_cost: 4
      - vm_type: c3-standard-8-lssd
        ontap_perf:
          iops: 19139
          throughput_in_mibs: 321
          capacity_in_gib: 213000
        disk_perf:
          iops: 50000
          throughput_in_mibs: 800
          capacity_in_gib: 257000
        relative_cost: 8
      - vm_type: c3-standard-22-lssd
        ontap_perf:
          iops: 34115
          throughput_in_mibs: 662
          capacity_in_gib: 213000
        disk_perf:
          iops: 120000
          throughput_in_mibs: 1800
          capacity_in_gib: 257000
        relative_cost: 22
      - vm_type: c3-standard-44-lssd
        ontap_perf:
          iops: 64768
          throughput_in_mibs: 1111
          capacity_in_gib: 426000
        disk_perf:
          iops: 160000
          throughput_in_mibs: 2400
          capacity_in_gib: 512000
        relative_cost: 44
      - vm_type: c3-standard-88-lssd
        ontap_perf:
          # We don't want to derate the largest instance type.
          # One way to do that would be to add more conditional code in the VMRS go module.
          # Another, more flexible way is to account for derating within the numbers provided by the perf team.
          # We arrived at the numbers for IOPS and throughput by taking the max. we want to allow (from the VM),
          # dividing by 0.7 (because we derate the VM perf. by multiplying with 0.7 in the go module - at 30%),
          # and finally rounding them up to an event number.
          # Example:
          # IOPS: 160000/0.7 = 228571.xy
          # Throughput: 5120 (what we want to allow over the entire cluster made up of large VMs) / 0.7 = 7314.xy
          iops: 230000
          throughput_in_mibs: 7500
          capacity_in_gib: 426000
        disk_perf:
          iops: 160000
          throughput_in_mibs: 4800
          capacity_in_gib: 512000
        relative_cost: 88
