apiVersion: v1
kind: ConfigMap
metadata:
  name: google-proxy-service-env-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- include "google_proxy.kubernetes.annotations" . | nindent 4 }}
    {{- include "google_proxy.helmchart.annotations" . | nindent 4 }}
  labels:
    {{- include "google_proxy.kubernetes.labels" . | nindent 4 }}
    {{- include "google_proxy.helmchart.labels" . | nindent 4 }}
    app: google-proxy-service
data:
  # TODO: Remove these fields after application code fix
  DB_HOST: "{{ index .Values "database" "host" }}"
  DB_USER: "{{ index .Values "database" "user" }}"
  DB_NAME: "{{ index .Values "database" "name" }}"
  DB_ADMIN_USER: "{{ index .Values "database" "adminUser" }}"
  ENV: "{{ index .Values "env" }}"
  GCP_AUTH_ACCEPTED_SERVICE_ACCOUNTS: "{{ index .Values "acceptedSAs" }}"
  GCP_CONSUMER_MGMT_ENDPOINT_URL: "{{ index .Values "gcpConsumerMgmtEndpointUrl" }}"
  GCP_SERVICE_NETWORKING_ENDPOINT_URL: "{{ index .Values "gcpServiceNetworkingEndpointUrl" }}"
  GCP_SERVICE_URL: "{{ index .Values "gcpServiceUrl" }}"
  LOCAL_REGION: "{{ index .Values "localRegion" }}"
  OTEL_GOOGLE_PROJECT_ID: "{{ index .Values "otelGoogleProjectId" }}"
  RUN_MIGRATION_ON_START: "{{ index .Values "runMigrationOnStart" }}"
  TEMPORAL_ADDRESS: "{{ index .Values "temporalAddress" }}"
  VSA_NODE_USERNAME: "{{ index .Values "vsaNodeUsername" }}"
  OBJECT_STORE_PROVIDER: "{{ index .Values "objectStoreProvider" }}"
  OBJECT_STORES_SERVER: "{{ index .Values "objectStoresServer" }}"
  OBJECT_STORE_AUTH_TYPE: "{{ index .Values "objectStoreAuthType" }}"
  SMC_GCP_PROJECT_ID: "{{ index .Values "smcProjectId" }}"
  GCP_SMC_SECRET_NAME: "{{ index .Values "gcpSmcSecretName" }}"
  GCP_SMC_SECRET_VERSION_NAME: "{{ index .Values "gcpSmcSecretVersionName" }}"
  GCP_HYDRATE_ENABLED: "{{ index .Values "gcpHydrateEnabled" }}"
  GCP_HYDRATE_AUTH_SERVICE_ACCOUNT: "{{ index .Values "gcpHydrateAuthServiceAccount" }}"
  GCP_AUTH_SERVICE_ACCOUNT: "{{ index .Values "gcpAuthServiceAccount" }}"
  GCP_HYDRATE_BASE_URL: "{{ index .Values "gcpHydrateBaseUrl" }}"
  PROXY_CLIENT_TRANSPORT_SCHEMA: "{{ index .Values "proxyClientTransportSchema" }}"
  VCP_PAIRED_REGIONS: "{{ index .Values "vcpPairedRegions" }}"
  LOGGER_LEVEL: "{{ index .Values "loggerLevel" }}"
  CVP_HOST: "{{ index .Values "cvpHost" }}"
  CRR_ENABLED: "{{ index .Values "crrEnabled" }}"
  config.yaml: |
    DB_HOST: {{ index .Values "database" "host" }}
    DB_USER: {{ index .Values "database" "user"  }}
    DB_PASSWORD: {{ index .Values "database" "password" }}
    DB_NAME: {{ index .Values "database" "name"  }}
    DB_ADMIN_USER: {{ index .Values "database" "adminUser"  }}
    DB_ADMIN_PASSWORD: {{ index .Values "database" "adminPassword" }}
    SETUP_NW_HEARTBEAT_TIMEOUT_SEC: {{ index .Values "temporal" "timeouts" "heartbeat" "setupNwSecond"}}
