apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-proxy
  labels:
    app: {{ .Chart.Name }}
    annotations:
      {{- include "google_proxy.kubernetes.annotations" . | nindent 4 }}
      {{- include "google_proxy.helmchart.annotations" . | nindent 4 }}
    labels:
      {{- include "google_proxy.kubernetes.labels" . | nindent 4 }}
      {{- include "google_proxy.helmchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 0
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
        {{- include "google_proxy.kubernetes.labels" . | nindent 8 }}
        {{- include "google_proxy.helmchart.labels" . | nindent 8 }}
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- if and .Values.podAffinity.enabled (eq .Values.environment "gcp") }}
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "google-proxy.podSelectorLabels" . | nindent 16 }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "google-proxy.podSelectorLabels" . | nindent 16 }}
      {{- end }}
      terminationGracePeriodSeconds: 60
      containers:
        - name: google-proxy
          {{- if .Values.images.googleProxy.secondary }}
          image: "{{- include "containerImage" (list . (dict "name" "googleProxy" "secondary" true)) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list . (dict "name" "googleProxy" "secondary" false)) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.images.googleProxy.pullPolicy }}
          securityContext:
            runAsNonRoot: true
            runAsUser: 65532
            allowPrivilegeEscalation: false
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          ports:
            - containerPort: {{ .Values.service.appPort }}
          {{- if .Values.istio.enabled }}
          startupProbe:
            httpGet:
              path: {{ .Values.startupProbe.path }}
              port: {{ .Values.startupProbe.port }}
              scheme: {{ .Values.startupProbe.scheme }}
            periodSeconds: {{ .Values.startupProbe.periodSeconds }}
            failureThreshold: {{ .Values.startupProbe.failureThreshold }}
          {{- end }}
          livenessProbe:
            failureThreshold: {{ .Values.livenessProbe.failureThreshold }}
            httpGet:
              path: /health
              port: {{ .Values.service.appPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.livenessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.livenessProbe.periodSeconds }}
            successThreshold: 1
            timeoutSeconds: {{ .Values.livenessProbe.timeoutSeconds }}
          readinessProbe:
            failureThreshold: {{ .Values.readinessProbe.failureThreshold }}
            httpGet:
              path: /health
              port: {{ .Values.service.appPort }}
              scheme: HTTP
            initialDelaySeconds: {{ .Values.readinessProbe.initialDelaySeconds }}
            periodSeconds: {{ .Values.readinessProbe.periodSeconds }}
            successThreshold: 1
            timeoutSeconds: {{ .Values.readinessProbe.timeoutSeconds }}
          envFrom:
            - configMapRef:
                name: google-proxy-service-env-config
            - secretRef:
                name: google-proxy-service-env-secret
          volumeMounts:
            - name: env-config-volume
              mountPath: /etc/config
              readOnly: true
{{- include "google-proxy.databaseProxyContainer" . | nindent 8 }}
      volumes:
        - name: env-config-volume
          configMap:
            name: google-proxy-service-env-config
