apiVersion: v1
kind: Secret
metadata:
  name: google-proxy-service-env-secret
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- include "google_proxy.kubernetes.annotations" . | nindent 4 }}
    {{- include "google_proxy.helmchart.annotations" . | nindent 4 }}
  labels:
    {{- include "google_proxy.kubernetes.labels" . | nindent 4 }}
    {{- include "google_proxy.helmchart.labels" . | nindent 4 }}
    app: google-proxy-service
type: Opaque
data:
  DB_PASSWORD: "{{ index .Values "database" "password" | b64enc  }}"
  DB_ADMIN_PASSWORD: "{{ index .Values "database" "adminPassword" | b64enc  }}"
  VSA_NODE_PASSWORD: "{{ index .Values "google-proxy" "vsaNodePassword" | b64enc  }}"
