apiVersion: v1
kind: Service
metadata:
  name: core-api
  labels:
    app: core-api
spec:
  clusterIP: None
  ports:
    - port: 50051
      name: core-api
  selector:
    app: core-api
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-api
  labels:
    app: core-api
spec:
  replicas: 1
  selector:
    matchLabels:
      app: core-api
  template:
    metadata:
      labels:
        app: core-api
    spec:
      containers:
      - name: core-api
        image: core-api
        ports:
        - containerPort: 50051
          name: http
