// Code generated by go-swagger; DO NOT EDIT.

package operations

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/ontap-rest/priv/models"
)

// SrvLookupReader is a Reader for the SrvLookup structure.
type SrvLookupReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *SrvLookupReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewSrvLookupOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewSrvLookupDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewSrvLookupOK creates a SrvLookupOK with default headers values
func NewSrvLookupOK() *SrvLookupOK {
	return &SrvLookupOK{}
}

/*
SrvLookupOK describes a response with status code 200, with default header values.

Ok
*/
type SrvLookupOK struct {
	Payload *models.SrvLookupResponse
}

// IsSuccess returns true when this srv lookup o k response has a 2xx status code
func (o *SrvLookupOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this srv lookup o k response has a 3xx status code
func (o *SrvLookupOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this srv lookup o k response has a 4xx status code
func (o *SrvLookupOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this srv lookup o k response has a 5xx status code
func (o *SrvLookupOK) IsServerError() bool {
	return false
}

// IsCode returns true when this srv lookup o k response a status code equal to that given
func (o *SrvLookupOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the srv lookup o k response
func (o *SrvLookupOK) Code() int {
	return 200
}

func (o *SrvLookupOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /private/cli/diag/secd/dns/srv-lookup][%d] srvLookupOK %s", 200, payload)
}

func (o *SrvLookupOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /private/cli/diag/secd/dns/srv-lookup][%d] srvLookupOK %s", 200, payload)
}

func (o *SrvLookupOK) GetPayload() *models.SrvLookupResponse {
	return o.Payload
}

func (o *SrvLookupOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.SrvLookupResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewSrvLookupDefault creates a SrvLookupDefault with default headers values
func NewSrvLookupDefault(code int) *SrvLookupDefault {
	return &SrvLookupDefault{
		_statusCode: code,
	}
}

/*
SrvLookupDefault describes a response with status code -1, with default header values.

Error
*/
type SrvLookupDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this srv lookup default response has a 2xx status code
func (o *SrvLookupDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this srv lookup default response has a 3xx status code
func (o *SrvLookupDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this srv lookup default response has a 4xx status code
func (o *SrvLookupDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this srv lookup default response has a 5xx status code
func (o *SrvLookupDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this srv lookup default response a status code equal to that given
func (o *SrvLookupDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the srv lookup default response
func (o *SrvLookupDefault) Code() int {
	return o._statusCode
}

func (o *SrvLookupDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /private/cli/diag/secd/dns/srv-lookup][%d] srv_lookup default %s", o._statusCode, payload)
}

func (o *SrvLookupDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /private/cli/diag/secd/dns/srv-lookup][%d] srv_lookup default %s", o._statusCode, payload)
}

func (o *SrvLookupDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *SrvLookupDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
