FROM golang:1.24.1 AS base
# Define GOTRACEBACK to mark this container as using the Go language runtime
# for `skaffold debug` (https://skaffold.dev/docs/workflows/debug/).
# Install Air for live reload
RUN go install github.com/air-verse/air@v1.62.0

RUN mkdir /app
WORKDIR /app


