enabled: true
serviceAccountName: ontap-proxy
replicaCount: 1

# Global configuration (required for image registry helpers)
global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  secondaryImageRegistry: "europe-north1-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vcp-container-images-us"
  useTags: false
  chartPrimaryImageRegistry: ""
  chartSecondaryImageRegistry: ""
  environment: gcp
  hyperscaler: gcp
  primaryImageRegistryPasswordAuth: true
  secondaryImageRegistryPasswordAuth: false
  primaryImagePullSecretName: ghcr.io

# Logging configuration
loggerLevel: "info"

# Resource configuration
resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 250m
    memory: 150Mi

# Service configuration
service:
  type: ClusterIP
  appPort: 8080

# Images configuration
images:
  ontapProxy:
    name: ontap-proxy
    tag: 0.0.0
    digest: ""
    secondary: false
    pullPolicy: IfNotPresent


coreApi:
  host: "core-service.vcp.svc.cluster.local:8080"

cache:
  authData:
    cleanupIntervalMinutes: 30
    expirationMinutes: 30

# Pod affinity configuration
podAffinity:
  enabled: true

config:
  env: "production"
  port: "8080"

# GCP Authentication Configuration
gcp:
  region: ""
  caPool:
    name: "vsa-pool-ca"
    deployedProjectId: "266893635349"
  secretManager:
    projectId: "266893635349"
  auth:
    acceptedServiceAccounts: ""
  serviceUrl: "https://cloudvolumesgcp-api.netapp.com"
  jwkUrl: "https://www.googleapis.com/service_accounts/v1/metadata/x509/"
  jwkTimeoutSeconds: 10
  certCache:
      expirationMinutes: 120
      sleepRetryIntervalSeconds: 5

serviceAccountAnnotations:
  "iam.gke.io/gcp-service-account": "" # FIXME: update with correct service account
