global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  primaryImageRegistryPasswordAuth: true
  primaryImagePullSecretName: ghcr.io
  secondaryImageRegistry: "europe-north1-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vcp-container-images-us"
  secondaryImageRegistryPasswordAuth: false
  useTags: false
  nodeSelector:
    nodeType: vsacp-nodes
  chartPrimaryImageRegistry: ""
  chartSecondaryImageRegistry: ""
  environment: gcp

# Application configuration
app:
  name: "vcp-worker"
  replicas: 1

serviceAccount:
  name: "vcp-worker-ksa"

# Image configuration
images:
  vcpWorker:
    name: vcp-worker
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent

# Worker configuration
workerConfig:
  temporalAddress: "temporal-frontend.temporal.svc.cluster.local:7233"
  env: ""
  gcpProxyPort: "8090"
  gceMetadataHost: ""
  gcpConsumerMgmtEndpointUrl: "autopush-netapp.sandbox.googleapis.com"
  gcpServiceNetworkingEndpointUrl: "netapp-tst-autopush-endpoint.appspot.com"
  localRegion: "australia-southeast1"
  vsaNodeUsername: "admin"
  vsaNodePassword: ""
  smAccessToken: ""
  objectStoreProvider: "gcp"
  objectStoresServer: "storage.googleapis.com"
  objectStoreAuthType: "GCP_SA"
  gcpHydrateAuthServiceAccount: ""
  gcpHydrateBaseUrl: ""
  proxyClientTransportSchema: "https"
  vcpPairedRegions: ""
  gcpAuthServiceAccount: ""
  gcpServiceUrl: "https://cloudvolumesgcp-api.netapp.com"
  loggerLevel: "info"
  vmrsConfigPath: "config/vmrs_gcp.yaml"

  # Database configuration
  database:
    type: "postgres"
    sslMode: "disable"
    timezone: "UTC"
    runMigrationOnStart: "true"
    migrationPath: "migrations/core"
    host: cloud-sql-proxy.sde.svc.cluster.local
    port: 5432
    user: postgres
    password: testpass
    adminUser: adminUser
    adminPassword: adminPassword
    dbname: vcp
    maxConns: 20
    maxIdleConns: 20
    maxConnLifetime: "1h"
