# Harvest port range configuration
global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  primaryImageRegistryPasswordAuth: true
  primaryImagePullSecretName: ghcr.io
  secondaryImageRegistry: "europe-north1-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vcp-container-images-us"
  secondaryImageRegistryPasswordAuth: false
  useTags: false
  nodeSelector:
    nodeType: vsacp-nodes
  chartPrimaryImageRegistry: ""
  chartSecondaryImageRegistry: ""
  environment: gcp

# Application configuration
app:
  name: "vcp-worker"
  replicas: 1

serviceAccount:
  name: "vcp-worker-ksa"

# Image configuration
images:
  vcpWorker:
    name: vcp-worker
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent

# Worker configuration
workerConfig:
  temporalAddress: "temporal-frontend.temporal.svc.cluster.local:7233"
  env: ""
  gcpProxyPort: "8090"
  gceMetadataHost: ""
  gcpConsumerMgmtEndpointUrl: "autopush-netapp.sandbox.googleapis.com"
  gcpServiceNetworkingEndpointUrl: "netapp-tst-autopush-endpoint.appspot.com"
  localRegion: "australia-southeast1"
  vsaNodeUsername: "admin"
  vsaNodePassword: ""
  objectStoreProvider: "gcp"
  objectStoresServer: "storage.googleapis.com"
  objectStoreAuthType: "GCP_SA"
  gcpHydrateEnabled: "true"
  gcpHydrateBatchSize: "10"
  gcpHydrateAuthServiceAccount: ""
  gcpHydrateBaseUrl: ""
  proxyClientTransportSchema: "https"
  smcProjectId: ""
  gcpSmcSecretName: ""
  gcpSmcSecretVersionName: ""
  vcpPairedRegions: ""
  gcpAuthServiceAccount: ""
  gcpServiceUrl: "https://cloudvolumesgcp-api.netapp.com"
  loggerLevel: "info"
  vmrsConfigPath: "config/vmrs_gcp.yaml"
  certificateLifetime: "25920000s"
  caName: "20250522-ea9-684"
  caPoolName: "vsa-pool-ca"
  caPoolDeployedProjectId: "266893635349"
  secretManagerProjectId: "266893635349"
  vsaDeployedDnsName: "au-se1.vsa."
  vsaManagedZone: "au-se1-vsa"
  vsaSecretCacheCleanupIntervalHours: 24
  vsaSecretAuthCacheExpirationHours: 24
  totalIpPerHaPair: 6
  dataSubnetCidrBlock: 28
  cloudDnsCacheTtl: 300
  vsaLifecycleManagerQueuePrefix: "vsa-lifecycle-manager"
  ontapVersion: "9.18.1"
  enforceMinSpConfig: "true"
  maxNodesPerGroup: 200
  filesProtocolSupport: "false"
  fileProtocolAllowlistedAccounts: "" # Comma-separated list of account IDs that are allowlisted for file protocol support
  vsaImageName: "r9-17-1xn-250710-0000-gcnv"
  # this will be removed after AGA
  vsaFilesImageName: "r9-18-1xn-250722-0000"
  
  # Mediator VM Configuration
  vsaMediatorInstanceType: "n2-standard-4"
  vsaMediatorDiskType: "pd-ssd"
  vsaMediatorImageName: "devn-250315-0200-mediator-debian-12"

  # Harvest Configuration
  serviceControlUrl: "https://servicecontrol.googleapis.com"
  serviceName: "autopush-netapp.sandbox.googleapis.com"
  datacenter: "us-west-1"
  leaseNameSpace: "vcp"
  harvestHost: "harvest-farm-service.vcp.svc.cluster.local:3000"
  enableMetrics: "false"
  harvestRestProtocol: "http"
  harvestPortStart: 13001
  harvestPortEnd: 13500
  firewallSourceRanges: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16,34.0.0.0/8,46.149.16.0/20,52.94.203.152/29,52.94.203.160/29,185.35.244.0/22,202.3.112.0/20,216.240.16.0/20,217.70.208.0/20,198.18.0.0/15"
  cvpHost: ""
  workflowGlobalTimeoutMinutes: "60" # Global timeout for workflows in minutes

  # Database configuration
  database:
    type: "postgres"
    sslMode: "disable"
    timezone: "UTC"
    runMigrationOnStart: "true"
    host: cloud-sql-proxy.sde.svc.cluster.local
    port: 5432
    user: postgres
    password: testpass
    adminUser: adminUser
    adminPassword: adminPassword
    dbname: vcp
    maxConns: 20
    maxIdleConns: 20
    maxConnLifetime: "1h"

#Enabling or Disabling Secret Manager for Microservice Secrets
secretManagerEnabled: false
