# Harvest port range configuration
global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  primaryImageRegistryPasswordAuth: true
  primaryImagePullSecretName: ghcr.io
  secondaryImageRegistry: "europe-north1-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vcp-container-images-us"
  secondaryImageRegistryPasswordAuth: false
  useTags: false
  nodeSelector:
    nodeType: vsacp-nodes
  chartPrimaryImageRegistry: ""
  chartSecondaryImageRegistry: ""
  environment: gcp


# This will be overridden automatically in deployment repo with build versions.
versionsSupported:
  - name: v0.0.1
    sha: "abc"

# Application configuration
app:
  - name: "vcp-customer-worker"
    replicas: 1
    workerAdditionalConfig:
      workerTaskQueue: "customer-workflows"
  - name: "vcp-background-worker"
    replicas: 1
    workerAdditionalConfig:
      workerTaskQueue: "background-workflows"

serviceAccount:
  name: "vcp-worker-ksa"

# Pod affinity configuration
podAffinity:
  enabled: true

# Image configuration
images:
  vcpWorker:
    name: vcp-worker
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent

resources:
  limits:
    cpu: "1"
    memory: 1Gi
  requests:
    cpu: 500m
    memory: 250Mi

# Worker configuration
workerConfig:
  gceMetadataHost: ""
  temporalAddress: "temporal-frontend.temporal.svc.cluster.local:7233"
  gcpProxyPort: "8090"
  gcpConsumerMgmtEndpointUrl: "autopush-netapp.sandbox.googleapis.com"
  gcpServiceNetworkingEndpointUrl: "netapp-tst-autopush-endpoint.appspot.com"
  localRegion: "australia-southeast1"
  aggregateName: "aggr1"
  vsaIcLifIpspace: "Gcnv"
  vsaNodeUsername: "admin"
  vsaNodePassword: ""
  objectStoreProvider: "gcp"
  objectStoresServer: "storage.googleapis.com"
  objectStoreAuthType: "GCP_SA"
  gcpHydrateEnabled: "true"
  flexCacheEnabled: "false"
  gcpHydrateBatchSize: "10"
  thinCloneGASupport: false
  snapshotSyncMaxConcurrency: 20
  ontapSnapshotFetchConcurrencyLimit: 5
  snapshotSyncParentWorkflowBatchSize: 100
  snapshotSyncChildWorkflowTimeout: 120
  snapshotSyncChildWorkflowActivityBatchSize: 10
  snapshotSyncChildWorkflowActivityTimeoutMinutes: 10
  snapshotSyncMaxConcurrentActivitiesPerChild: 5
  gcpHydrateAuthServiceAccount: ""
  gcpHydrateBaseUrl: ""
  resourceCleanupParentWorkflowBatchSize: 100
  resourceCleanupChildWorkflowTimeout: 240
  resourceCleanupChildWorkflowActivityBatchSize: 25
  resourceCleanupChildWorkflowActivityTimeoutMinutes: 60
  resourceCleanupMaxConcurrentActivitiesPerChild: 5
  proxyClientTransportSchema: "https"
  vlmWorkflowRetryMaxAttempts: "1"
  smcProjectId: ""
  gcpSmcSecretName: ""
  gcpSmcSecretVersionName: ""
  vcpPairedRegions: ""
  gcpKmsKeyRotationEnabled: "false"
  backupLogicalSizeSyncEnabled: "true"
  enableAutoVolOfflineCronForGcpKms: "true"
  vsaOperationTimeout: "45m"
  gcpAuthServiceAccount: ""
  gcpServiceUrl: "https://cloudvolumesgcp-api.netapp.com"
  loggerLevel: "info"
  vmrsConfigPath: "/config/vmrs_gcp.yaml"
  vlmConfigFilePath: "/common/vsa_config/vlm-config.json"
  certificateLifetime: "94608000s"
  caName: "20250718-pn6-boa"
  caPoolName: "vsa-pool-ca"
  caPoolDeployedProjectId: "266893635349"
  secretManagerProjectId: "266893635349"
  immutableBackupEnabled: "false"
  crossRegionBackupEnabled: "false"
  restoreVolumeBufferEnabled: "false"
  enableLdap: "false"
  enableSmb: "false"
  vsaDeployedDnsName: "au-se1.vsa"
  vsaManagedZone: "au-se1-vsa"
  vsaSecretCacheCleanupIntervalHours: 24
  vsaSecretAuthCacheExpirationHours: 24
  privateKeyBits: 4096
  expertModeUser: "gcnvadmin"
  totalIpPerHaPair: 6
  dataSubnetCidrBlock: 28
  cloudDnsCacheTtl: 300
  vsaLifecycleManagerQueuePrefix: "vsa-lifecycle-manager"
  ontapVersionDetails: "9.17.1P1"
  enforceMinSpConfig: "false"
  maxNodesPerGroup: 200
  maxNestedCloneLimit: 499
  filesProtocolSupport: "false"
  fileProtocolAllowlistedAccounts: "" # Comma-separated list of account IDs that are allowlisted for file protocol support
  flexcacheForceEncryption: "false"
  ontapRestAsyncPollTimeoutMinutes: 15
  vsaImageName: "x-9-17-1p1-gcnv"
  # this will be removed after AGA
  vsaFilesImageName: "x-9-18-1rc1"
  vsaImageProject: ""
  vsaMediatorImageProject: ""
  # VSA Image Bucket for signed URL generation
  vsaImageBucket: "vsa-compute-images-tst"
  # VSA Signed URL duration in hours (1-24, default: 12)
  vsaSignedUrlDurationHours: 12
  vsaInstanceTypeOverride: false
  # Encryption key must be a 32-byte (256-bit) string for AES-256.
  vsaVlmEncryptionKey: "" # Should be the same as in the vlm-worker values.yaml.
  vlmCreateVSAClusterDeploymentWorkflowTimeoutMinutes: 30
  vlmCreateVSASVMWorkflowTimeoutMinutes: 10
  vlmDeleteVSAClusterDeploymentWorkflowTimeoutMinutes: 20
  vlmUpdateVSAClusterDeploymentWorkflowTimeoutMinutes: 120
  vlmValidateClusterHealthWorkflowTimeoutMinutes: 15
  vlmClusterPowerOpWorkflowTimeoutMinutes: 30
  vlmGetClusterZIZSDetailsWFTimeoutMinutes: 10
  vlmUpdateVsaMediatorWFTimeoutMinutes: 30
  # Comma-separated list of error patterns that trigger delete and retry operations
  vlmRetryErrorPatterns: ""

  # ONTAP Image Version Match Configuration
  skipOntapImageVersionMatch: false

  # Mediator VM Configuration
  vsaMediatorInstanceType: "e2-micro"
  vsaMediatorDiskType: "pd-ssd"
  vsaMediatorImageName: "cvo-mediator-x-9-17-1p1"
  vsaFilesMediatorImageName: "cvo-mediator-x-9-18-1rc1"

  metricsPort: "9090"

  # Gin Logging configuration
  ginServiceAttachment: "projects/netapp-au-se1-autopush-sde-tst/regions/australia-southeast1/serviceAttachments/fluent-bit-psc"
  gitMetrics1pPort: "5140"
  ginMetrics1pProtocol: "tcp-unencrypted"
  ginLoggingFeature: "false"
  infraSubnetIpRange: "198.18.240.0/28"

  # Harvest Configuration
  serviceControlUrl: "https://servicecontrol.googleapis.com"
  serviceName: "autopush-netapp.sandbox.googleapis.com"
  datacenter: "us-west-1"
  leaseNameSpace: "vcp"
  harvestHost: "vsa-harvest-farm-service.vcp.svc.cluster.local"
  enableMetrics: "false"
  harvestSecretManagerAuthEnabled: "false"
  harvestRestProtocol: "http"
  harvestPortStart: 13001
  harvestPortEnd: 13500
  cvpHost: ""
  proberProjectList: ""
  enableUniqueSerialNumberGeneration: false
  clusterSerialNumberPrefix: "935"
  numberOfHaPairsLargeCapacity: 6
  nonLinearScalingActivePassive: true
  vlmCreateVsaClusterDeploymentWfTimeoutMinutesLv: 45
  startToCloseWorkflowTimeoutLv: "60m"
  dataSubnetCidrBlockLv: 26
  minLvPoolCoolTierCapacity: "13194139533312"
  maxLvPoolCapacity: "22517998136852476"
  maxLvHotTierPoolCapacity: "5629499534213119"
  minLvThroughput: 64
  maxLvThroughput: 60000
  minHotTierSize: "1099511627776"
  minHotTierSizeLV: "13194139533312"
  createCommonResourcesInVCP: true
  consecutiveUpdatePoolTimeGapAllowedMinutes: 240
  autoTierHotTierAutoResizeThresholdPercent: 90
  autoTierHotTierAutoResizeIncreasePercent: 10
  autoTieringSyncActivityMaxAttempts: 1
  hardDeleteResources: "true"
  scheduleHardDelete: "false"
  replicationJobsRetryMaxAttempts: 10
  updateRemoteVolumeJobsRetryMaxAttempts: 10

  workflowGlobalTimeoutMinutes: "60" # Global timeout for workflows in minutes
  mgmtFirewallSourceRanges: "198.18.0.0/15"
  rsmFirewallSourceRanges: "198.18.0.0/15"
  icFirewallSourceRanges: "198.18.0.0/15"
  dataFirewallSourceRanges: "10.0.0.0/8,172.16.0.0/12,192.168.0.0/16"
  mgmtRegionalNatIp: "34.0.0.0/8,35.0.0.0/8,202.3.112.0/20,216.240.16.0/20,217.70.208.0/20"
  mgmtNetworkIpRange: "198.18.0.0/20"
  rsmNetworkIpRange: "198.18.16.0/20"
  icNetworkIpRange: "198.18.32.0/20"
  mgmtFirewallPortRules: "tcp,22,443"
  rsmFirewallPortRules: "tcp,udp"
  icFirewallPortRules: "tcp,udp"
  iscsiFirewallPortRules: "tcp,3260"
  nfsFirewallPortRules: "tcp,111,635,2049,4045,udp,111,4046"
  interclusterFirewallPortRules: "tcp,10566,11104,11105"
  smbFirewallAllowedPortRules: "tcp,88,135,139,389,445,464,636,udp,53,88,389,464"
  ilbHealthCheckFirewallSourceRanges: "130.211.0.0/22,35.191.0.0/16"
  ilbHealthCheckFirewallAllowedPortRules: "tcp"
  waitTimeForGcpOperationInSec: "10"
  updateVolumeTieringBatchSize: 20

  # Default Workflow Retry configuration
  startToCloseTimeout: "55m"
  retryInterval: "5s"
  retryMaxAttempts: "3"
  retryMaxInterval: "5m"
  retryBackoffCoefficient: "2.0"

  # SA Creation Retry Configuration
  saRetryStartToCloseTimeout: "25m"
  saRetryInitialInterval: "10s"
  saRetryMaximumAttempts: "12"
  saRetryMaximumInterval: "60s"
  saRetryBackoffCoefficient: "2.0"

  # Volume Refresh Configuration
  volumeRefreshWorkflowStartToCloseTimeout: "10m"
  volumeSyncChunkSize: "200"

  # To enable the sync job to update zi/zs fields for pool
  enableSyncPoolZIZS: "false"
  syncPoolZIZSBatchSize: "5"

  # Mock gcp access token for testing purposes
  mockAccessToken: ""
  integrationTest: "false"
  nkdevTest: false
  disableVsaCleanupOnVlmFailure: false
  orphanJobProcessingEnabled: true


  # NLF License configuration
  nlfLicenseSecretPath: "" # Format to be followed: <secret-name>/versions/<secret-version>

  # Database configuration
  database:
    type: "postgres"
    sslMode: "disable"
    timezone: "UTC"
    runMigrationOnStart: "true"
    host: cloud-sql-proxy.sde.svc.cluster.local
    port: 5432
    user: postgres
    password: testpass
    adminUser: adminUser
    adminPassword: adminPassword
    dbname: vcp
    maxConns: 20
    maxIdleConns: 20
    maxConnLifetime: "1h"
    metricsDbType: "postgres"
    metricsDbHost: postgres.default.svc.cluster.local
    metricsDbPort: 5432
    metricsDbUser: metrics
    metricsDbPassword: testpass
    metricsDbName: metrics
    metricsDbSslMode: "disable"
    metricsDbTimezone: "UTC"
    metricsDbMaxConns: 20
    metricsDbMaxIdleConns: 20
    metricsDbMaxConnLifetime: "1h"
    metricsDbCleanupEnabled: false
  adc:
    image: "" # path of ADC image in gcp cloud image registry
    project: "" # project in which ADC cloud run to be deployed
    region: "" # region in which ADC cloud run to be deployed
    certSecretName: "" # name of the secret containing ADC certificate

#Enabling or Disabling Secret Manager for Microservice Secrets
secretManagerEnabled: false

service:
  type: ClusterIP

# Make sure to update the regionNumberMap if new regions are added. In both Google proxy and vcp-worker-chart
regionNumberMap:
  africa-south1: "01"
  asia-east1: "02"
  asia-east2: "03"
  asia-northeast1: "04"
  asia-northeast2: "05"
  asia-northeast3: "06"
  asia-south1: "07"
  asia-south2: "08"
  asia-southeast1: "09"
  asia-southeast2: "10"
  australia-southeast1: "11"
  australia-southeast2: "12"
  europe-central2: "13"
  europe-north1: "14"
  europe-north2: "15"
  europe-southwest1: "16"
  europe-west1: "17"
  europe-west10: "18"
  europe-west12: "19"
  europe-west2: "20"
  europe-west3: "21"
  europe-west4: "22"
  europe-west6: "23"
  europe-west8: "24"
  europe-west9: "25"
  me-central1: "26"
  me-central2: "27"
  me-west1: "28"
  northamerica-northeast1: "29"
  northamerica-northeast2: "30"
  northamerica-south1: "31"
  southamerica-east1: "32"
  southamerica-west1: "33"
  us-central1: "34"
  us-east1: "35"
  us-east4: "36"
  us-east5: "37"
  us-south1: "38"
  us-west1: "39"
  us-west2: "40"
  us-west3: "41"
  us-west4: "42"
