apiVersion: v2
appVersion: 1.27.2
dependencies:
  - condition: cassandra.enabled
    name: cassandra
    repository: file://dev/null
    version: 0.14.3
  - condition: prometheus.enabled
    name: prometheus
    repository: file://dev/null
    version: 25.22.0
  - condition: elasticsearch.enabled
    name: elasticsearch
    repository: file://dev/null
    version: 7.17.3
  - condition: grafana.enabled
    name: grafana
    repository: file://dev/null
    version: 8.0.2
description: Temporal is a distributed, scalable, durable, and highly available orchestration engine to execute asynchronous long-running business logic in a scalable and resilient way.
keywords:
  - temporal
  - workflow
  - orchestration
name: temporal
type: application
version: 0.60.0
