{{- range $mapping := $.Values.ontapVersionVlmImageMappings}}
  {{- $versionName := $mapping.ontapVersion }}
  {{- $version := ($versionName | lower | replace "." "-") }}

apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "vlm-worker.configMapName" (list $ $version) }}
  namespace: {{ $.Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
  labels:
    app: {{ $.Values.app.name }}-{{ $version }}
data:
  PROVIDER: {{ $.Values.workerConfig.provider | quote }}
  SERVER_IP: {{ $.Values.workerConfig.temporalHost | quote }}
  SERVER_PORT: {{ $.Values.workerConfig.temporalPort | quote }}
  TASK_QUEUE: {{ printf "%s-%s" $.Values.workerConfig.taskQueuePrefix $versionName | quote }}
  DEBUG: {{ $.Values.workerConfig.debug | quote }}
  MAX_CONCURRENT_ACTIVITIES: {{ $.Values.workerConfig.maxConcurrentActivities | quote }}
  MAX_CONCURRENT_WORKFLOW: {{ $.Values.workerConfig.maxConcurrentWorkflow | quote }}
  MAX_CONCURRENT_WORKFLOW_TASK_POLLERS: {{ $.Values.workerConfig.maxConcurrentWorkflowTaskPollers | quote }}
---
{{- end }}
