apiVersion: apps/v1
kind: Deployment
metadata:
  name: {{ .Values.app.name }}
  namespace: {{ .Release.Namespace }}
  labels:
    app: {{ .Values.app.name }}
spec:
  replicas: {{ .Values.app.replicas }}
  selector:
    matchLabels:
      app: {{ .Values.app.name }}
  template:
    metadata:
      labels:
        app: {{ .Values.app.name }}
      {{- with .Values.podAnnotations }}
      annotations:
        {{- toYaml . | nindent 8 }}
      {{- end }}
    spec:
      serviceAccountName: {{ .Values.serviceAccount.name }}
      {{- with $.Values.initContainers }}
      initContainers:
        {{- toYaml .| nindent 8 }}
      {{- end }}
      {{- if and .Values.podAffinity.enabled (eq .Values.global.environment "gcp") }}
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "vlm-worker.podSelectorLabels" . | nindent 14 }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "vlm-worker.podSelectorLabels" . | nindent 14 }}
      {{- end }}
      containers:
        - name: {{ .Values.app.name }}
          {{- if .Values.images.vlmWorker.secondary }}
          image: "{{- include "containerImage" (list . (dict "name" "vlmWorker" "secondary" true)) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list . (dict "name" "vlmWorker" "secondary" false)) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.images.vlmWorker.pullPolicy }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
          envFrom:
            - configMapRef:
                name: {{ include "vlm-worker.configMapName" . }}
            - secretRef:
                name: {{ include "vlm-worker.secretName" . }}
