{{- $namespace := ($.Release.Namespace | default "default") }}
---
apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-peer-authentication-{{ $.Release.Namespace }}
  namespace: {{ $.Release.Namespace }}
spec:
  mtls:
    mode: STRICT

---
{{- range $mapping := $.Values.ontapVersionVlmImageMappings }}
    {{- $versionName := $mapping.ontapVersion }}
    {{- $version := ($versionName | lower | replace "." "-") }}
---
apiVersion: networking.istio.io/v1beta1
kind: DestinationRule
metadata:
  name: vlm-worker-mtls-{{ $version }}
  namespace: {{ $.Release.Namespace }}
spec:
  host: vlm-metrics-service-{{ $version }}.{{ $.Release.Namespace }}.svc.cluster.local
  trafficPolicy:
    tls:
      mode: ISTIO_MUTUAL

---
apiVersion: security.istio.io/v1
kind: AuthorizationPolicy
metadata:
  annotations:
    meta.helm.sh/release-name: {{ $.Values.app.name }}-{{ $version }}
    meta.helm.sh/release-namespace: {{ $.Release.Namespace }}
  labels:
    app.kubernetes.io/managed-by: Helm
  name: allow-to-vlm-ontap-{{ $version }}
  namespace: {{ $.Release.Namespace }}
spec:
  action: ALLOW
  rules:
    - {}
  selector:
    matchLabels:
      app: {{ $.Values.app.name }}-{{ $version }}
{{- end }}