apiVersion: security.istio.io/v1beta1
kind: PeerAuthentication
metadata:
  name: istio-peer-authentication-{{ .Release.Namespace }}
  namespace: {{ .Release.Namespace }}
spec:
  mtls:
    mode: STRICT