{{- if not .Values.secretManagerEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vlm-worker.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
stringData:
  ONTAP_CREDENTIAL_ENCRYPT_KEY: {{ .Values.workerConfig.vsaVlmEncryptionKey | quote }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vlm-worker.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main-cluster-secret-store     # Configured same everywhere
    kind: ClusterSecretStore
  target:
    name: {{ include "vlm-worker.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: ONTAP_CREDENTIAL_ENCRYPT_KEY
      remoteRef:
        key: {{ .Values.workerConfig.smVsaVlmEncryptionKey | quote }}
{{- end }}
