{{- if not .Values.secretManagerEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ include "vlm-worker.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
type: Opaque
stringData:
  ONTAP_CREDENTIAL_ENCRYPT_KEY: {{ .Values.workerConfig.vsaVlmEncryptionKey | quote }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ include "vlm-worker.secretName" . }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
spec:
  refreshInterval: 1h
  secretStoreRef:
    name: main-cluster-secret-store     # Configured same everywhere
    kind: ClusterSecretStore
  target:
    name: {{ include "vlm-worker.secretName" . }}
    creationPolicy: Owner
  data:
    - secretKey: ONTAP_CREDENTIAL_ENCRYPT_KEY
      remoteRef:
        key: {{ .Values.workerConfig.smVsaVlmEncryptionKey | quote }}
{{- end }}
{{- if .Values.vlmWorkerReconciler.enabled }}
---
{{- if not .Values.secretManagerEnabled }}
apiVersion: v1
kind: Secret
metadata:
  name: {{ .Values.vlmWorkerReconciler.database.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
type: Opaque
stringData:
  DB_USER: {{ .Values.vlmWorkerReconciler.database.user | default "" | quote }}
  DB_PASSWORD: {{ .Values.vlmWorkerReconciler.database.password | default "" | quote }}
{{- else }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: {{ .Values.vlmWorkerReconciler.database.secretName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-delete-policy": before-hook-creation
spec:
  refreshInterval: "1h"
  secretStoreRef:
    name: main-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: {{ .Values.vlmWorkerReconciler.database.secretName }}
    creationPolicy: Owner
  data:
    - secretKey: DB_USER
      remoteRef:
        key: {{ .Values.vlmWorkerReconciler.externalSecrets.dbUsername.secretName | quote }}
        {{- if .Values.vlmWorkerReconciler.externalSecrets.dbUsername.property }}
        property: {{ .Values.vlmWorkerReconciler.externalSecrets.dbUsername.property | quote }}
        {{- end }}
    - secretKey: DB_PASSWORD
      remoteRef:
        key: {{ .Values.vlmWorkerReconciler.externalSecrets.dbPassword.secretName | quote }}
        {{- if .Values.vlmWorkerReconciler.externalSecrets.dbPassword.property }}
        property: {{ .Values.vlmWorkerReconciler.externalSecrets.dbPassword.property | quote }}
        {{- end }}
{{- end }}
{{- end }}
