apiVersion: v1
kind: Namespace
metadata:
  name: vcp
  labels:
    name: vcp
---
apiVersion: v1
kind: Service
metadata:
  name: google-proxy-service
  namespace: vcp
  labels:
    app: google-proxy
spec:
  type: ClusterIP
  ports:
    - port: 8080
      targetPort: 8080
      name: http
  selector:
    app: google-proxy
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-proxy
  namespace: vcp
  labels:
    app: google-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-proxy
  template:
    metadata:
      labels:
        app: google-proxy
    spec:
      containers:
        - name: google-proxy
          image: google-proxy
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres.default.svc.cluster.local
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: testpass
            - name: DB_NAME
              value: vcp
            - name: DB_ADMIN_USER
              value: postgres
            - name: DB_ADMIN_PASSWORD
              value: testpass
            - name: RUN_MIGRATION_ON_START
              value: "true"
            - name: TEMPORAL_ADDRESS
              value: "local-temporal-frontend.default.svc.cluster.local:7233"
            - name: TEMPORAL_NAMESPACE
              value: "default"
            - name: ENV
              value: "local"
            - name: LOCAL_REGION
              value: "australia-southeast1"
