apiVersion: apps/v1
kind: Deployment
metadata:
  name: google-proxy
  labels:
    app: google-proxy
spec:
  replicas: 1
  selector:
    matchLabels:
      app: google-proxy
  template:
    metadata:
      labels:
        app: google-proxy
    spec:
      containers:
        - name: google-proxy
          image: google-proxy
          ports:
            - containerPort: 8080
          env:
            - name: DB_HOST
              value: postgres
            - name: DB_USER
              value: postgres
            - name: DB_PASSWORD
              value: testpass
            - name: DB_NAME
              value: vcp
            - name: DB_ADMIN_USER
              value: postgres
            - name: DB_ADMIN_PASSWORD
              value: testpass
            - name: RUN_MIGRATION_ON_START
              value: "true"