# Global configuration
global:
  primaryImageRegistry: ghcr.io
  primaryImageRegistryPath: vcp-vsa-control-plane
  primaryImageRegistryPasswordAuth: true
  primaryImagePullSecretName: ghcr.io
  secondaryImageRegistry: "europe-north1-docker.pkg.dev/gcnv-artifact-registry-nonprod"
  secondaryImageRegistryPath: "vcp-container-images-us"
  useTags: false
  secondaryImageRegistryPasswordAuth: false
  nodeSelector:
    nodeType: vsacp-nodes
  chartPrimaryImageRegistry: ""
  chartSecondaryImageRegistry: ""
  environment: gcp
  hyperscaler: gcp
  workloadIdentityEnabled: false
  coreConfig:
    gcp: {}
    gcpServiceUrl: "https://cloudvolumesgcp-api.netapp.com"
    gcpAuthAcceptedServiceAccounts: ""
    apiCvpMaxRetries: "3"
    apiCvpRetryDelay: "100ms"
    broadcastDomainMtu: "9000"
    certCacheExpirationMinutes: "60"
    certCacheSleepRetryIntervalSeconds: "10"
    coreApiPort: "8080"
    cvpHost: ""
    dbConnMaxLifetime: "30m"
    dbHost: ""
    dbMaxIdleConns: "10"
    dbMaxOpenConns: "100"
    dbMsiUser: "msi"
    dbName: "coredb"
    dbPort: "5432"
    dbSslMode: "disable"
    dbTimezone: "UTC"
    dbType: "postgres"
    enableTemporalDataEncryption: "true"
    idleTimeout: "120s"
    jwkKidsUrl: ""
    jwkTimeoutSeconds: "30"
    logSql: "true"
    maxQuotaInBytesVolume: "1000000000"
    migrationPath: ""
    minQuotaInBytesPool: "10000000"
    minQuotaInBytesVolume: "10000000"
    maxHostsPerHostgroup: "128"
    msiEnabled: "false"
    ontapRestIdempotentTransportEnabled: ""
    ontapRestLogVerbose: ""
    ontapRestOauthEnabled: ""
    ontapRestXDotClientApp: "core-app"
    proxyClientApiMaxRetries: "5"
    proxyClientApiRetryDelay: "500ms"
    proxyClientTransportSchema: "https"
    readHeaderTimeout: "30s"
    readTimeout: "60s"
    retryBackoffCoefficient: "2.0"
    retryInterval: "1s"
    retryMaxAttempts: "5"
    retryMaxInterval: "60s"
    runMigrationOnStart: "true"
    startToCloseWorkflowTimeout: "120s"
    svmPeerTimeout: "30s"
    temporalAddress: ""
    temporalEncryptionId: ""
    temporalNamespace: ""
    temporalTlsCert: ""
    temporalTlsKey: ""
    vcpPairedRegions: ""
    ontapVersionDetails: "9.18.1X29"
    skipOntapImageVersionMatch: "false"
    gcpKmsKeyRotationEnabled: "false"
    enableJSwapVersionCheck: "false"
    vsaDeploymentPollInterval: "15s"
    vsaDeploymentTimeout: "10m"
    vsaNodeHomePort: "443"
    vsaNodePassword: ""
    vsaNodeUsername: ""
    vsaImageName: "x-9-18-1x29"
    writeTimeout: "60s"
    finishProjectCvpMaxRetries: "10"
    finishProjectCvpRetryInterval: "30s"
    finishProjectBackoffCoefficient: "1.0"
    localRegion: ""
    coreApiClientTransportSchema: "https"
    enableDbRollback: "false"
    vcpDbPreRollbackSteps: "0"
    vcpDbPostRollbackSteps: "0"
    metricsDbPreRollbackSteps: "0"
    metricsDbPostRollbackSteps: "0"
    workflowSupervisorNotFoundGracePeriod: "5m"
    regionNumberMap:
      africa-south1: "01"
      asia-east1: "02"
      asia-east2: "03"
      asia-northeast1: "04"
      asia-northeast2: "05"
      asia-northeast3: "06"
      asia-south1: "07"
      asia-south2: "08"
      asia-southeast1: "09"
      asia-southeast2: "10"
      australia-southeast1: "11"
      australia-southeast2: "12"
      europe-central2: "13"
      europe-north1: "14"
      europe-north2: "15"
      europe-southwest1: "16"
      europe-west1: "17"
      europe-west10: "18"
      europe-west12: "19"
      europe-west2: "20"
      europe-west3: "21"
      europe-west4: "22"
      europe-west6: "23"
      europe-west8: "24"
      europe-west9: "25"
      me-central1: "26"
      me-central2: "27"
      me-west1: "28"
      northamerica-northeast1: "29"
      northamerica-northeast2: "30"
      northamerica-south1: "31"
      southamerica-east1: "32"
      southamerica-west1: "33"
      us-central1: "34"
      us-east1: "35"
      us-east4: "36"
      us-east5: "37"
      us-south1: "38"
      us-west1: "39"
      us-west2: "40"
      us-west3: "41"
      us-west4: "42"

environment: gcp
enabled: true
enableDbMigration: true
ttlSecondsAfterFinished: 3600
msiEnabled: false
msiUser: db-msi-user
serviceAccountName: vcp-core
deployerServiceAccountName: vcp-core
metricsEnabled: false
replicaCount: 1
enableBackgroundTask: true
requiredTakeoverReasons:
  - "disabled"
  - "Storage failover mailbox disks are in a degraded state"
  - "Local node has encountered errors while reading the storage failover partner's mailbox disks"
  - "Storage failover interconnect error"
  - "Partner node halted after disabling takeover"
  - "Mailbox disks are not healthy"
  - "Local node missing partner disks"
  - "Default"
jobPollingMaxDuration: 25 # seconds
jobPollingInterval: 3 # seconds
caName: "vsa-intermediate-us-e4"
caPoolName: "us-e4-vsa-npd-pool"
caPoolDeployedProjectId: "163019662857"
vsaDeployedDnsName: "us-e4.vsa"
vsaManagedZone: "us-e4-vsa"
vsaSecretCacheCleanupIntervalHours: "24"
vsaSecretAuthCacheExpirationHours: 24
privateKeyBits: 4096
secretManagerProjectId: ""

images:
  core:
    name: core
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent
  vcpDbMigrate:
    name: vcp-db-migrate
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent
  telemetryDeployer:
    name: vcp-cloudrun-deployer
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent
  telemetry:
    name: telemetry
    tag: 0.0.0
    digest: ""
    secondary: true
    pullPolicy: IfNotPresent
  otel:
    name: vcp-open-telemetry-images/opentelemetry-collector-contrib
    tag: 0.118.0
    digest: 'sha256:83ff24727f615c39056d954dd3a5d4ef227a5a9fe2c234a4489199e4351f0ab'
    secondary: true
    pullPolicy: IfNotPresent

# Add values here in overrideCoreConfig to override the common configuration
overrideCoreConfig: {}

service:
  type: ClusterIP
  appPort: 8081

database:
  host: postgres-service
  hostIP: ""
  user: vcp-db-user
  password: vcp-db-pass
  metricsUser: vcp-db-user
  metricsPassword: vcp-db-pass
  dbAdminUser: dbAdminUser
  dbAdminPassword: dbAdminPassword
  name: vcp
  port: 5432
  type: postgres
  sslMode: "disable"
  metricsHost: postgres-service
  metricsHostIP: ""
  metricsPort: 5432
  metricsDbName: metrics

resources:
  limits:
    cpu: 1
    memory: 1Gi
  requests:
    cpu: 200m
    memory: 256Mi

telemetryDeployer:
  enabled: true
  gcpProxyPort: 8090
  serviceName: telemetry-service
  image: us-docker.pkg.dev/gcnv-artifact-registry-nonprod/vcp-container-images-us/telemetry:0.0.0-DEV.15
  projectID: netapp-au-se1-autopush-sde-tst
  network: "cv-tst-au-se1-k8s-vpc"
  subnet: "cloud-run"
  serviceAccount: "vcp-metrics-producer@netapp-au-se1-autopush-sde-tst.iam.gserviceaccount.com"
  vpcConnector: "projects/netapp-au-se1-autopush-sde-tst/locations/australia-southeast1/connectors/db-connector"
  region: australia-southeast1
  # schedulerRegion: ""  # Optional: GCP region for Cloud Scheduler (defaults to region if not specified)
  minInstances: 1
  maxInstances: 3
  # CPU and Memory configuration for instance-based billing
  # Resources for telemetry container
  telemetryCPU: "2"      # CPU allocation for telemetry container (e.g., "2", "1000m", "4")
  telemetryMemory: "2Gi" # Memory allocation for telemetry container (e.g., "2Gi", "512Mi", "4Gi")
  # Resources for SQL proxy container
  sqlProxyCPU: "1"       # CPU allocation for SQL proxy container (e.g., "1", "500m", "2")
  sqlProxyMemory: "512Mi" # Memory allocation for SQL proxy container (e.g., "512Mi", "256Mi", "1Gi")
  # Resources for otel container
  otelCPU: "1"       # CPU allocation for otel container (e.g., "1", "500m", "2")
  otelMemory: "512Mi" # Memory allocation for otel container (e.g., "512Mi", "256Mi", "1Gi")
  runMigrationOnStart: false
  performanceRootUrl: "https://servicecontrol.googleapis.com"
  usageRootUrl: "https://servicecontrol.googleapis.com"
  operationBatchSize: 200
  pusherServiceName: "autopush-netapp.sandbox.googleapis.com"
  pusherServiceProject: "netapp-au-se1-autopush-sde-tst"
  enableVolumeMetrics: false
  enableBackupMetrics: false
  enableSfrMetrics: false
  enableBackupBillingMetrics: false
  enableFilesBackupBilling: false
  enableCrossRegionBackupBillingMetrics: false
  enableReplicationBillingMetrics: false
  enableAutoTieringBillingMetrics: false
  enableFilesReplicationBillingMetrics: false
  enableBatchUsageUpdates: false  # Feature flag for high-performance batch usage updates (PostgreSQL bulk operations)
  resultUpdateBatchSize: 100
  intervalBackfillLimitMinutes: 60
  counterBackfillLimitMinutes: 0
  pushBatchSize: 1000
  maxGoogleBillingPushRetry: 5
  pageSize: 1000
  googleBillingLabelsMaxEntries: 64
  poolVolumeLabelPageSize: 5000
  googleContinents: "northamerica:northamerica,latinamerica:latinamerica,southamerica:latinamerica,centralamerica:latinamerica,china:china,indonesia:indonesia,asia:asia,australia:oceania,oceania:oceania,europe:europe,middleeast:middleeast,africa:africa,antarctica:antarctica,na:northamerica,latam:latinamerica,sa:latinamerica,ca:latinamerica,cn:china,in:indonesia,apac:asia,au:oceania,oc:oceania,eu:europe,eu1:europe,eu2:europe,me:middleeast,us:northamerica,af:africa,an:antarctica,nam4:northamerica,eur4:europe,asia1:asia"
  accountPaginationLimit: 1000
  bizopsReportName : "google_vsa_analytics_report"
  bizopsBucketName: "harvest-farm-pv-au-se1"
  cloudSqlConnector: "netapp-au-se1-autopush-sde-tst:australia-southeast1:netapp-au-se1-autopush-sde-tst-db-postgres"
  cloudSqlImage: "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.15.1"
  otelImage: ""
  enableScheduler: true
  retryIntervalSeconds: 30
  numWorkersBillingRetry: 5

  numWorkersPerformance: "10"
  numWorkersUsage: "1"
  numWorkersCollection: "25"
  numWorkersBizOps: "2"
  targetMinute : "15"
  resources:
    limits:
      cpu: 1
      memory: 1Gi
    requests:
      cpu: 100m
      memory: 128Mi

# Annotations
serviceAccountAnnotations:
  "iam.gke.io/gcp-service-account": vcp-ci@gcnv-artifact-registry-nonprod.iam.gserviceaccount.com

#Enabling for secrets manager
#flag for enabling/disabling secret manager

secretManagerEnabled: false
externalSecrets:
  dbUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-username-key"
    secretKey: "dbUsername"
  dbPassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-password-key"
    secretKey: "dbPassword"
  metricsDbUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-username-key"
    secretKey: "metricsDbUsername"
  metricsDbPassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-password-key"
    secretKey: "metricsDbPassword"
  dbAdminUsername:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-adminUsername-key"
    secretKey: "dbAdminUsername"
  dbAdminPassword:
    secretName: "vcp-worker-autopush-sqa-us-e4-db-adminPassword-key"
    secretKey: "dbAdminPassword"

# Pod affinity configuration
podAffinity:
  enabled: true
