apiVersion: v1
kind: ConfigMap
metadata:
  name: core-service-env-config
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- include "core.kubernetes.annotations" . | nindent 4 }}
    {{- include "core.helmchart.annotations" . | nindent 4 }}
  labels:
    {{- include "core.kubernetes.labels" . | nindent 4 }}
    {{- include "core.helmchart.labels" . | nindent 4 }}
    app: core-service