{{- if and (.Values.enabled) (.Values.enableDbMigration) }}
kind: Job
apiVersion: batch/v1
metadata:
  name: vcp-dbmigrate
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Release.IsUpgrade }}
    "helm.sh/hook": pre-upgrade
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- else }}
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-4"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
    {{- include "vcp-dbmigrate.kubernetes.annotations" . | nindent 4 }}
    {{- include "vcp-dbmigrate.helmchart.annotations" . | nindent 4 }}
  labels:
    {{- include "vcp-dbmigrate.kubernetes.labels" . | nindent 4 }}
    {{- include "vcp-dbmigrate.helmchart.labels" . | nindent 4 }}
spec:
  backoffLimit: 0
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished | default 3600 }}
  template:
    metadata:
      annotations:
        {{- include "vcp-dbmigrate.kubernetes.annotations" . | nindent 8 }}
        {{- include "vcp-dbmigrate.helmchart.annotations" . | nindent 8 }}
      labels:
        {{- include "vcp-dbmigrate.kubernetes.labels" . | nindent 8 }}
        {{- include "vcp-dbmigrate.helmchart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- if .Release.IsInstall }}
      initContainers:
        - name: vcp-dbmigrate-create
          command: ["/vcp-db-migrate"]
          args:
            {{- if .Values.msiEnabled | default false }}
            - "--setup"
            - "--admin-msi-user=${MSI_USER}"
            {{- else }}
            - "--setup"
            - "--admin-user=${DB_ADMIN_USERNAME}"
            - "--admin-pass=${DB_ADMIN_PASSWORD}"
            {{- end }}
          {{- if .Values.images.vcpDbMigrate.secondary }}
          image: "{{- include "containerImage" (list . (dict "name" "vcpDbMigrate" "secondary" true)) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list . (dict "name" "vcpDbMigrate" "secondary" false)) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.images.vcpDbMigrate.pullPolicy }}
          env:
            # DB migration admin credentials from Secret
            - name: DB_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_ADMIN_USERNAME
            - name: DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_ADMIN_PASSWORD

            # MSI user (if enabled)
            - name: MSI_USER
              value: {{ .Values.msiUser | default "defaultUser" | quote }}

            # Regular database connection info (user/pass/host etc)
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              value: {{ .Values.database.host | default "localhost" | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | default "5432" | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | default "vcp" | quote }}
            - name: DB_TYPE
              value: {{ .Values.database.type | default "postgres" | quote }}
            - name: LOCAL_REGION
              value: {{ .Values.global.coreConfig.localRegion | default "" | quote }}
            - name: REGION_NUMBER_MAP
              value: {{ .Values.global.coreConfig.regionNumberMap | toJson | quote }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      {{- end }}
      containers:
        - name: vcp-dbmigrate-migrate
          command: ["/vcp-db-migrate"]
          args:
            {{- if .Values.msiEnabled | default false }}
            - "--migrate"
            - "--admin-msi-user=${MSI_USER}"
            {{- else }}
            - "--migrate"
            - "--admin-user=${DB_ADMIN_USERNAME}"
            - "--admin-pass=${DB_ADMIN_PASSWORD}"
            {{- end }}
          {{- if .Values.images.vcpDbMigrate.secondary }}
          image: "{{- include "containerImage" (list . (dict "name" "vcpDbMigrate" "secondary" true)) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list . (dict "name" "vcpDbMigrate" "secondary" false)) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.images.vcpDbMigrate.pullPolicy }}
          env:
            # DB migration admin credentials from Secret
            - name: DB_ADMIN_USERNAME
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_ADMIN_USERNAME
            - name: DB_ADMIN_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_ADMIN_PASSWORD

            # MSI user (if enabled)
            - name: MSI_USER
              value: {{ .Values.msiUser | default "defaultUser" | quote }}

            # Regular database connection info (user/pass/host etc)
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_USERNAME
            - name: DB_PASSWORD
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_PASSWORD
            - name: DB_HOST
              value: {{ .Values.database.host | default "localhost" | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | default "5432" | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | default "vcp" | quote }}
            - name: DB_TYPE
              value: {{ .Values.database.type | default "postgres" | quote }}
            - name: LOCAL_REGION
              value: {{ .Values.global.coreConfig.localRegion | default "" | quote }}
            - name: REGION_NUMBER_MAP
              value: {{ .Values.global.coreConfig.regionNumberMap | toJson | quote }}
          resources:
            limits:
              cpu: {{ .Values.resources.limits.cpu }}
              memory: {{ .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.resources.requests.cpu }}
              memory: {{ .Values.resources.requests.memory }}
      restartPolicy: Never
{{- end }}
