apiVersion: apps/v1
kind: Deployment
metadata:
  name: core-service
  annotations:
    {{- include "core.kubernetes.annotations" . | nindent 4 }}
    {{- include "core.helmchart.annotations" . | nindent 4 }}
  labels:
    {{- include "core.kubernetes.labels" . | nindent 4 }}
    {{- include "core.helmchart.labels" . | nindent 4 }}
spec:
  replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: {{ .Chart.Name }}
  template:
    metadata:
      labels:
        app: {{ .Chart.Name }}
    spec:
      nodeSelector:
        iam.gke.io/gke-metadata-server-enabled: "true"
      serviceAccountName: {{ .Values.serviceAccountName }}
      {{- if and .Values.podAffinity.enabled (eq .Values.environment "gcp") }}
      topologySpreadConstraints:
        - maxSkew: 1
          minDomains: 3
          topologyKey: topology.kubernetes.io/zone
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "core.podSelectorLabels" . | nindent 16 }}
        - maxSkew: 1
          topologyKey: kubernetes.io/hostname
          whenUnsatisfiable: DoNotSchedule
          labelSelector:
            matchLabels:
              {{- include "core.podSelectorLabels" . | nindent 16 }}
      {{- end }}
      containers:
        - name: vcp-core
          {{- if .Values.images.core.secondary }}
          image: "{{- include "containerImage" (list . (dict "name" "core" "secondary" true)) | trim -}}"
          {{- else }}
          image: "{{- include "containerImage" (list . (dict "name" "core" "secondary" false)) | trim -}}"
          {{- end }}
          imagePullPolicy: {{ .Values.images.core.pullPolicy }}
          ports:
            - containerPort: {{ .Values.service.appPort }}
              name: http
          envFrom:
            - configMapRef:
                name: core-service-env-config
            - secretRef:
                name: core-service-env-secret
          volumeMounts:
            - name: env-config-volume
              mountPath: /etc/config
              readOnly: true
      volumes:
        - name: env-config-volume
          configMap:
            name: core-service-env-config
