{{- $instConnName := .Values.global.coreConfig.gcp.instanceConnectionName | default .Values.telemetryDeployer.cloudSqlConnector | default .Values.global.cloudSqlProxy.instanceConnectionName }}
{{- if and (.Values.enabled) (.Values.enableDbMigration) (.Values.enableIamLifecycle) (.Values.secretManagerEnabled) (.Values.global.cloudSqlIamAuthEnabled) $instConnName }}
apiVersion: external-secrets.io/v1beta1
kind: ExternalSecret
metadata:
  name: iam-lifecycle-admin-secret
  namespace: {{ .Release.Namespace }}
  labels:
    app: vcp-iam-lifecycle
    {{- include "vcp-dbmigrate.helmchart.labels" . | nindent 4 }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    "helm.sh/hook-weight": "-10"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- include "vcp-dbmigrate.helmchart.annotations" . | nindent 4 }}
spec:
  refreshInterval: "0"
  secretStoreRef:
    name: main-cluster-secret-store
    kind: ClusterSecretStore
  target:
    name: iam-lifecycle-admin-secret
    creationPolicy: Owner
    template:
      type: Opaque
  data:
    - secretKey: DB_ADMIN_USER
      remoteRef:
        key: {{ .Values.externalSecrets.dbAdminUsername.secretName | quote }}
    - secretKey: DB_ADMIN_PASSWORD
      remoteRef:
        key: {{ .Values.externalSecrets.dbAdminPassword.secretName | quote }}
{{- end }}
