apiVersion: v1
kind: Service
metadata:
  name: core-service
  labels:
    app: {{ .Chart.Name }}
    annotations:
      {{- include "core.kubernetes.annotations" . | nindent 4 }}
      {{- include "core.helmchart.annotations" . | nindent 4 }}
    labels:
      {{- include "core.kubernetes.labels" . | nindent 4 }}
      {{- include "core.helmchart.labels" . | nindent 4 }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - name: core
      port: 8080
      targetPort: 8080
  selector:
    app: {{ .Chart.Name }}