{{- if and (.Values.enabled) (.Values.telemetryDeployer.enabled) }}
kind: Job
apiVersion: batch/v1
metadata:
  name: vcp-telemetry-deployer
  namespace: {{ .Release.Namespace }}
  annotations:
    {{- if .Release.IsUpgrade }}
    "helm.sh/hook": post-upgrade
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- else }}
    "helm.sh/hook": post-install
    "helm.sh/hook-weight": "5"
    "helm.sh/hook-delete-policy": before-hook-creation,hook-succeeded
    {{- end }}
    {{- include "vcp-telemetry-deployer.kubernetes.annotations" . | nindent 4 }}
    {{- include "vcp-telemetry-deployer.helmchart.annotations" . | nindent 4 }}
  labels:
    {{- include "vcp-telemetry-deployer.kubernetes.labels" . | nindent 4 }}
    {{- include "vcp-telemetry-deployer.helmchart.labels" . | nindent 4 }}
spec:
  backoffLimit: 2
  ttlSecondsAfterFinished: {{ .Values.ttlSecondsAfterFinished | default 3600 }}
  template:
    metadata:
      annotations:
        {{- include "vcp-telemetry-deployer.kubernetes.annotations" . | nindent 8 }}
        {{- include "vcp-telemetry-deployer.helmchart.annotations" . | nindent 8 }}
      labels:
        {{- include "vcp-telemetry-deployer.kubernetes.labels" . | nindent 8 }}
        {{- include "vcp-telemetry-deployer.helmchart.labels" . | nindent 8 }}
    spec:
      serviceAccountName: {{ .Values.deployerServiceAccountName }}
      containers:
        - name: vcp-telemetry-deployer
          command: ["/vcp-cloudrun-deployer"]
          args:
            - "--service={{ .Values.telemetryDeployer.serviceName | default "vsa-harvest-otel" }}"
            {{- if .Values.images.telemetry.secondary }}
            - "--image={{ include "containerImage" (list . (dict "name" "telemetry" "secondary" true)) | trim }}"
            {{- else }}
            - "--image={{ include "containerImage" (list . (dict "name" "telemetry" "secondary" false)) | trim }}"
            {{- end }}
            - "--project={{ .Values.telemetryDeployer.projectID | default "netapp-au-se1-autopush-sde-tst" }}"
            - "--region={{ .Values.telemetryDeployer.region | default "australia-southeast1" }}"
            {{- if .Values.telemetryDeployer.schedulerRegion }}
            - "--scheduler-region={{ .Values.telemetryDeployer.schedulerRegion }}"
            {{- end }}
            - "--network={{ .Values.telemetryDeployer.network | default "default" }}"
            - "--subnet={{ .Values.telemetryDeployer.subnet | default "default" }}"
            - "--service-account-name={{ .Values.telemetryDeployer.serviceAccount | default "svc-sde-metrics-producer@netapp-au-se1-autopush-sde-tst.iam.gserviceaccount.com" }}"
            - "--max-instances={{ .Values.telemetryDeployer.maxInstances | default "5" }}"
            - "--min-instances={{ .Values.telemetryDeployer.minInstances | default 0 }}"
            - "--telemetry-cpu={{ .Values.telemetryDeployer.telemetryCPU | default "2" }}"
            - "--telemetry-memory={{ .Values.telemetryDeployer.telemetryMemory | default "2Gi" }}"
            - "--sql-proxy-cpu={{ .Values.telemetryDeployer.sqlProxyCPU | default "1" }}"
            - "--sql-proxy-memory={{ .Values.telemetryDeployer.sqlProxyMemory | default "512Mi" }}"
            - "--enable-scheduler={{ .Values.telemetryDeployer.enableScheduler | default "true"  }}"
            - "--vpc-connector={{ .Values.telemetryDeployer.vpcConnector | default "" }}"
            - "--cloud-sql-instances={{ .Values.telemetryDeployer.cloudSqlConnector | default "" }}"
            - "--cloud-sql-image={{ .Values.telemetryDeployer.cloudSqlImage | default "gcr.io/cloud-sql-connectors/cloud-sql-proxy:2.15.1" }}"
            - "--otel-cpu={{ .Values.telemetryDeployer.otelCPU | default "1" }}"
            - "--otel-memory={{ .Values.telemetryDeployer.otelMemory | default "512Mi" }}"
            - "--monitoring-project-id={{ .Values.telemetryDeployer.monitoringProject | default "" }}"
            - "--custom-prefix={{ .Values.telemetryDeployer.customPrefix | default "" }}"
           {{- if .Values.images.otel.secondary }}
            - "--otel-image={{ include "otelContainerImage" (list . (dict "name" "otel" "secondary" true)) | trim }}"
            {{- else }}
            - "--otel-image={{ include "otelContainerImage" (list . (dict "name" "otel" "secondary" false)) | trim }}"
            {{- end }}
          {{- if .Values.images.telemetryDeployer.secondary }}
          image: "{{ include "containerImage" (list . (dict "name" "telemetryDeployer" "secondary" true)) | trim }}"
          {{- else }}
          image: "{{ include "containerImage" (list . (dict "name" "telemetryDeployer" "secondary" false)) | trim }}"
          {{- end }}
          imagePullPolicy: {{ .Values.images.telemetryDeployer.pullPolicy | default "IfNotPresent" }}
          env:
            - name: GCP_PROXY_PORT
              value: {{ .Values.telemetryDeployer.gcpProxyPort | default "8090" | quote }}
            
            # Database configuration
            - name: DB_TYPE
              value: {{ .Values.database.type | default "postgres" | quote }}
            - name: DB_HOST
              value: {{ .Values.database.hostIP | default "postgres.default.svc.cluster.local" | quote }}
            - name: DB_PORT
              value: {{ .Values.database.port | default "5432" | quote }}
            - name: DB_USER
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_USER
            - name: DB_PASSWORD
              value: {{ .Values.externalSecrets.dbPassword.secretName | default "testpass" | quote }}
            - name: DB_NAME
              value: {{ .Values.database.name | default "vcp" | quote }}
            
            # Migration configuration
            - name: DB_ADMIN_USER
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: DB_ADMIN_USER
            # Metrics database configuration
            - name: METRICS_DB_TYPE
              value: {{ .Values.database.type | default "postgres" | quote }}
            - name: METRICS_DB_HOST
              value: {{ .Values.database.metricsHostIP | default "postgres.default.svc.cluster.local" | quote }}
            - name: METRICS_DB_PORT
              value: {{ .Values.database.metricsPort | default "5432" | quote }}
            - name: METRICS_DB_USER
              valueFrom:
                secretKeyRef:
                  name: core-service-env-secret
                  key: METRICS_DB_USER
            - name: METRICS_DB_PASSWORD
              value: {{ .Values.externalSecrets.metricsDbPassword.secretName | default "testpass" | quote }}
            - name: METRICS_DB_NAME
              value: {{ .Values.database.metricsDbName | default "metrics" | quote }}
            # Runtime configuration
            - name: RUN_MIGRATION_ON_START
              value: {{ .Values.telemetryDeployer.runMigrationOnStart | default "true" | quote }}
            - name: PERFORMANCE_ROOT_URL
              value: {{ .Values.telemetryDeployer.performanceRootUrl | default "https://servicecontrol.googleapis.com" | quote }}
            - name: USAGE_ROOT_URL
              value: {{ .Values.telemetryDeployer.usageRootUrl | default "https://servicecontrol.googleapis.com" | quote }}
            - name: OPERATION_BATCH_SIZE
              value: {{ .Values.telemetryDeployer.operationBatchSize | default "200" | quote }}
            - name: PUSHER_SERVICE_NAME
              value: {{ .Values.telemetryDeployer.pusherServiceName | default "autopush-netapp.sandbox.googleapis.com" | quote }}
            - name: PUSHER_SERVICE_PROJECT
              value: {{ .Values.telemetryDeployer.pusherServiceProject | default "netapp-au-se1-autopush-sde-tst" | quote }}
            - name: LOCAL_REGION
              value: {{ .Values.global.coreConfig.localRegion | default "us-west2" | quote }}
            - name: ENABLE_VOLUME_METRICS
              value: {{ .Values.telemetryDeployer.enableVolumeMetrics | default "false" | quote }}
            - name: ENABLE_BACKUP_METRICS
              value: {{ .Values.telemetryDeployer.enableBackupMetrics | default "false" | quote }}
            - name: ENABLE_SFR_METRICS
              value: {{ .Values.telemetryDeployer.enableSfrMetrics | default "false" | quote }}
            - name: ENABLE_BACKUP_BILLING_METRICS
              value: {{ .Values.telemetryDeployer.enableBackupBillingMetrics | default "false" | quote }}
            - name: ENABLE_FILES_BACKUP_BILLING
              value: {{ .Values.telemetryDeployer.enableFilesBackupBilling | default "false" | quote }}
            - name: ENABLE_CMEK_BACKUP_BILLING
              value: {{ .Values.telemetryDeployer.enableCmekBackupBilling | default "false" | quote }}
            - name: ENABLE_REPLICATION_BILLING_METRICS
              value: {{ .Values.telemetryDeployer.enableReplicationBillingMetrics | default "false" | quote }}
            - name: ENABLE_AUTO_TIERING_BILLING_METRICS
              value: {{ .Values.telemetryDeployer.enableAutoTieringBillingMetrics | default "false" | quote }}
            - name: ENABLE_FILES_AUTO_TIERING_BILLING
              value: {{ .Values.telemetryDeployer.enableFilesAutoTieringBilling | default "false" | quote }}
            - name: ENABLE_FILES_REPLICATION_BILLING_METRICS
              value: {{ .Values.telemetryDeployer.enableFilesReplicationBillingMetrics | default "false" | quote }}
            - name: ENABLE_CROSS_REGION_BACKUP_BILLING_METRICS
              value: {{ .Values.telemetryDeployer.enableCrossRegionBackupBillingMetrics | default "false" | quote }}
            - name: ENABLE_BATCH_USAGE_UPDATES
              value: {{ .Values.telemetryDeployer.enableBatchUsageUpdates | default "false" | quote }}
            - name: RESULT_UPDATE_BATCH_SIZE
              value: {{ .Values.telemetryDeployer.resultUpdateBatchSize | default "100" | quote }}
            - name: INTERVAL_BACKFILL_LIMIT_MINUTES
              value: {{ .Values.telemetryDeployer.intervalBackfillLimitMinutes | default "60" | quote }}
            - name: COUNTER_BACKFILL_LIMIT_MINUTES
              value: {{ .Values.telemetryDeployer.counterBackfillLimitMinutes | default "0" | quote }}
            - name: PUSH_BATCH_SIZE
              value: {{ .Values.telemetryDeployer.pushBatchSize | default "1000" | quote }}
            - name: MAX_GOOGLE_BILLING_PUSH_RETRY
              value: {{ .Values.telemetryDeployer.maxGoogleBillingPushRetry | default "5" | quote }}
            - name: PAGE_SIZE
              value: {{ .Values.telemetryDeployer.pageSize | default "1000" | quote }}
            - name: GOOGLE_BILLING_LABELS_MAX_ENTRIES
              value: {{ .Values.telemetryDeployer.googleBillingLabelsMaxEntries | default "64" | quote }}
            - name: POOL_VOLUME_LABEL_PAGE_SIZE
              value: {{ .Values.telemetryDeployer.poolVolumeLabelPageSize | default "5000" | quote }}
            - name: ENVIRONMENT
              value: {{ .Values.environment | default "gcp"| quote }}
            - name: GOOGLE_CONTINENTS
              value: {{ .Values.telemetryDeployer.googleContinents | default "" | quote }}
            - name: BIZOPS_ACCOUNT_PAGINATION_LIMIT
              value: {{ .Values.telemetryDeployer.accountPaginationLimit | default "1000" | quote }}
            -  name: BIZOPS_REPORT_NAME
               value: {{ .Values.telemetryDeployer.bizopsReportName }}
            - name: BIZOPS_BUCKET_NAME
              value: {{ .Values.telemetryDeployer.bizopsBucketName }}
            - name: GOOGLE_REGION
              value: {{ .Values.telemetryDeployer.region | default "australia-southeast1" | quote }}
            - name: NUM_WORKERS_PERFORMANCE
              value: {{ .Values.telemetryDeployer.numWorkersPerformance | default "10" | quote }}
            - name: NUM_WORKERS_USAGE
              value: {{ .Values.telemetryDeployer.numWorkersUsage | default "1" | quote }}
            - name: NUM_WORKERS_COLLECTION
              value: {{ .Values.telemetryDeployer.numWorkersCollection | default "25" | quote }}
            - name: NUM_WORKERS_BIZOPS
              value: {{ .Values.telemetryDeployer.numWorkersBizOps | default "2" | quote }}
            - name: TARGET_MINUTE
              value: {{ .Values.telemetryDeployer.targetMinute | default "15" | quote }}
            - name: RETRY_INTERVAL_SECONDS
              value: {{ .Values.telemetryDeployer.retryIntervalSeconds | default "300" | quote }}
            - name: NUM_WORKERS_BILLING_RETRY
              value: {{ .Values.telemetryDeployer.numWorkersBillingRetry | default "5" | quote }}  
          resources:
            limits:
              cpu: {{ .Values.telemetryDeployer.resources.limits.cpu | default .Values.resources.limits.cpu }}
              memory: {{ .Values.telemetryDeployer.resources.limits.memory | default .Values.resources.limits.memory }}
            requests:
              cpu: {{ .Values.telemetryDeployer.resources.requests.cpu | default .Values.resources.requests.cpu }}
              memory: {{ .Values.telemetryDeployer.resources.requests.memory | default .Values.resources.requests.memory }}
      
      restartPolicy: Never
{{- end }} 