// Code generated by go-swagger; DO NOT EDIT.

package v1_beta_internal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp/models"
)

// V1betaReleaseVolumeReplicationCVPReader is a Reader for the V1betaReleaseVolumeReplicationCVP structure.
type V1betaReleaseVolumeReplicationCVPReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1betaReleaseVolumeReplicationCVPReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewV1betaReleaseVolumeReplicationCVPAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1betaReleaseVolumeReplicationCVPBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewV1betaReleaseVolumeReplicationCVPUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV1betaReleaseVolumeReplicationCVPForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1betaReleaseVolumeReplicationCVPNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewV1betaReleaseVolumeReplicationCVPConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV1betaReleaseVolumeReplicationCVPUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewV1betaReleaseVolumeReplicationCVPTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV1betaReleaseVolumeReplicationCVPInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewV1betaReleaseVolumeReplicationCVPNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 503:
		result := NewV1betaReleaseVolumeReplicationCVPServiceUnavailable()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewV1betaReleaseVolumeReplicationCVPDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV1betaReleaseVolumeReplicationCVPAccepted creates a V1betaReleaseVolumeReplicationCVPAccepted with default headers values
func NewV1betaReleaseVolumeReplicationCVPAccepted() *V1betaReleaseVolumeReplicationCVPAccepted {
	return &V1betaReleaseVolumeReplicationCVPAccepted{}
}

/*
V1betaReleaseVolumeReplicationCVPAccepted handles this case with default header values.

Released volume replication
*/
type V1betaReleaseVolumeReplicationCVPAccepted struct {
	Payload *models.VolumeReplicationCVPV1beta
}

func (o *V1betaReleaseVolumeReplicationCVPAccepted) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPAccepted  %+v", 202, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPAccepted) GetPayload() *models.VolumeReplicationCVPV1beta {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.VolumeReplicationCVPV1beta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPBadRequest creates a V1betaReleaseVolumeReplicationCVPBadRequest with default headers values
func NewV1betaReleaseVolumeReplicationCVPBadRequest() *V1betaReleaseVolumeReplicationCVPBadRequest {
	return &V1betaReleaseVolumeReplicationCVPBadRequest{}
}

/*
V1betaReleaseVolumeReplicationCVPBadRequest handles this case with default header values.

Bad request
*/
type V1betaReleaseVolumeReplicationCVPBadRequest struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPBadRequest  %+v", 400, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPUnauthorized creates a V1betaReleaseVolumeReplicationCVPUnauthorized with default headers values
func NewV1betaReleaseVolumeReplicationCVPUnauthorized() *V1betaReleaseVolumeReplicationCVPUnauthorized {
	return &V1betaReleaseVolumeReplicationCVPUnauthorized{}
}

/*
V1betaReleaseVolumeReplicationCVPUnauthorized handles this case with default header values.

Unauthorized
*/
type V1betaReleaseVolumeReplicationCVPUnauthorized struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPUnauthorized  %+v", 401, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPForbidden creates a V1betaReleaseVolumeReplicationCVPForbidden with default headers values
func NewV1betaReleaseVolumeReplicationCVPForbidden() *V1betaReleaseVolumeReplicationCVPForbidden {
	return &V1betaReleaseVolumeReplicationCVPForbidden{}
}

/*
V1betaReleaseVolumeReplicationCVPForbidden handles this case with default header values.

Forbidden
*/
type V1betaReleaseVolumeReplicationCVPForbidden struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPForbidden) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPForbidden  %+v", 403, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPNotFound creates a V1betaReleaseVolumeReplicationCVPNotFound with default headers values
func NewV1betaReleaseVolumeReplicationCVPNotFound() *V1betaReleaseVolumeReplicationCVPNotFound {
	return &V1betaReleaseVolumeReplicationCVPNotFound{}
}

/*
V1betaReleaseVolumeReplicationCVPNotFound handles this case with default header values.

Not found
*/
type V1betaReleaseVolumeReplicationCVPNotFound struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPNotFound) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPNotFound  %+v", 404, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPConflict creates a V1betaReleaseVolumeReplicationCVPConflict with default headers values
func NewV1betaReleaseVolumeReplicationCVPConflict() *V1betaReleaseVolumeReplicationCVPConflict {
	return &V1betaReleaseVolumeReplicationCVPConflict{}
}

/*
V1betaReleaseVolumeReplicationCVPConflict handles this case with default header values.

Conflict
*/
type V1betaReleaseVolumeReplicationCVPConflict struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPConflict) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPConflict  %+v", 409, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPUnprocessableEntity creates a V1betaReleaseVolumeReplicationCVPUnprocessableEntity with default headers values
func NewV1betaReleaseVolumeReplicationCVPUnprocessableEntity() *V1betaReleaseVolumeReplicationCVPUnprocessableEntity {
	return &V1betaReleaseVolumeReplicationCVPUnprocessableEntity{}
}

/*
V1betaReleaseVolumeReplicationCVPUnprocessableEntity handles this case with default header values.

Unprocessable entity
*/
type V1betaReleaseVolumeReplicationCVPUnprocessableEntity struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPTooManyRequests creates a V1betaReleaseVolumeReplicationCVPTooManyRequests with default headers values
func NewV1betaReleaseVolumeReplicationCVPTooManyRequests() *V1betaReleaseVolumeReplicationCVPTooManyRequests {
	return &V1betaReleaseVolumeReplicationCVPTooManyRequests{}
}

/*
V1betaReleaseVolumeReplicationCVPTooManyRequests handles this case with default header values.

Too many requests
*/
type V1betaReleaseVolumeReplicationCVPTooManyRequests struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPTooManyRequests  %+v", 429, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPInternalServerError creates a V1betaReleaseVolumeReplicationCVPInternalServerError with default headers values
func NewV1betaReleaseVolumeReplicationCVPInternalServerError() *V1betaReleaseVolumeReplicationCVPInternalServerError {
	return &V1betaReleaseVolumeReplicationCVPInternalServerError{}
}

/*
V1betaReleaseVolumeReplicationCVPInternalServerError handles this case with default header values.

Internal server error
*/
type V1betaReleaseVolumeReplicationCVPInternalServerError struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPInternalServerError  %+v", 500, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPNotImplemented creates a V1betaReleaseVolumeReplicationCVPNotImplemented with default headers values
func NewV1betaReleaseVolumeReplicationCVPNotImplemented() *V1betaReleaseVolumeReplicationCVPNotImplemented {
	return &V1betaReleaseVolumeReplicationCVPNotImplemented{}
}

/*
V1betaReleaseVolumeReplicationCVPNotImplemented handles this case with default header values.

Not implemented
*/
type V1betaReleaseVolumeReplicationCVPNotImplemented struct {
	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPNotImplemented) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPNotImplemented  %+v", 501, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPNotImplemented) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPServiceUnavailable creates a V1betaReleaseVolumeReplicationCVPServiceUnavailable with default headers values
func NewV1betaReleaseVolumeReplicationCVPServiceUnavailable() *V1betaReleaseVolumeReplicationCVPServiceUnavailable {
	return &V1betaReleaseVolumeReplicationCVPServiceUnavailable{}
}

/*
V1betaReleaseVolumeReplicationCVPServiceUnavailable handles this case with default header values.

Service unavailable
*/
type V1betaReleaseVolumeReplicationCVPServiceUnavailable struct {
	/*A non-negative integer indicating the seconds to delay after the response is received
	 */
	RetryAfter int64

	Payload *models.Error
}

func (o *V1betaReleaseVolumeReplicationCVPServiceUnavailable) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1betaReleaseVolumeReplicationCVPServiceUnavailable  %+v", 503, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPServiceUnavailable) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPServiceUnavailable) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	// response header Retry-After
	retryAfter, err := swag.ConvertInt64(response.GetHeader("Retry-After"))
	if err != nil {
		return errors.InvalidType("Retry-After", "header", "int64", response.GetHeader("Retry-After"))
	}
	o.RetryAfter = retryAfter

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaReleaseVolumeReplicationCVPDefault creates a V1betaReleaseVolumeReplicationCVPDefault with default headers values
func NewV1betaReleaseVolumeReplicationCVPDefault(code int) *V1betaReleaseVolumeReplicationCVPDefault {
	return &V1betaReleaseVolumeReplicationCVPDefault{
		_statusCode: code,
	}
}

/*
V1betaReleaseVolumeReplicationCVPDefault handles this case with default header values.

Unexpected error
*/
type V1betaReleaseVolumeReplicationCVPDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the v1beta release volume replication c v p default response
func (o *V1betaReleaseVolumeReplicationCVPDefault) Code() int {
	return o._statusCode
}

func (o *V1betaReleaseVolumeReplicationCVPDefault) Error() string {
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/volumeReplication/release][%d] v1beta_releaseVolumeReplicationCVP default  %+v", o._statusCode, o.Payload)
}

func (o *V1betaReleaseVolumeReplicationCVPDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaReleaseVolumeReplicationCVPDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
