# syntax=docker/dockerfile:1
FROM golang:1.24.1 AS builder
WORKDIR /src
ARG GHVSA_PAT
RUN git config --global url."https://${GHVSA_PAT}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
ENV GOTRACEBACK=all

