# syntax=docker/dockerfile:1
FROM golang:1.24.11 AS builder
WORKDIR /src
ARG GHVSA_PAT
COPY . /src
RUN git config --global url."https://${GHVSA_PAT}:x-oauth-basic@github.com/".insteadOf "https://github.com/"
ENV GOTRACEBACK=single
ENV GOEXPERIMENT=boringcrypto

