// Code generated by go-swagger; DO NOT EDIT.

package active_directories

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewV1betaListActiveDirectoriesParams creates a new V1betaListActiveDirectoriesParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewV1betaListActiveDirectoriesParams() *V1betaListActiveDirectoriesParams {
	return &V1betaListActiveDirectoriesParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewV1betaListActiveDirectoriesParamsWithTimeout creates a new V1betaListActiveDirectoriesParams object
// with the ability to set a timeout on a request.
func NewV1betaListActiveDirectoriesParamsWithTimeout(timeout time.Duration) *V1betaListActiveDirectoriesParams {
	return &V1betaListActiveDirectoriesParams{
		timeout: timeout,
	}
}

// NewV1betaListActiveDirectoriesParamsWithContext creates a new V1betaListActiveDirectoriesParams object
// with the ability to set a context for a request.
func NewV1betaListActiveDirectoriesParamsWithContext(ctx context.Context) *V1betaListActiveDirectoriesParams {
	return &V1betaListActiveDirectoriesParams{
		Context: ctx,
	}
}

// NewV1betaListActiveDirectoriesParamsWithHTTPClient creates a new V1betaListActiveDirectoriesParams object
// with the ability to set a custom HTTPClient for a request.
func NewV1betaListActiveDirectoriesParamsWithHTTPClient(client *http.Client) *V1betaListActiveDirectoriesParams {
	return &V1betaListActiveDirectoriesParams{
		HTTPClient: client,
	}
}

/*
V1betaListActiveDirectoriesParams contains all the parameters to send to the API endpoint

	for the v1beta list active directories operation.

	Typically these are written to a http.Request.
*/
type V1betaListActiveDirectoriesParams struct {

	/* LocationID.

	   The location/region to perform the operation in.
	*/
	LocationID string

	/* ProjectNumber.

	   The project number of the GCP project owning the resource being acted upon
	*/
	ProjectNumber string

	/* XCorrelationID.

	   Correlation identifier
	*/
	XCorrelationID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the v1beta list active directories params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1betaListActiveDirectoriesParams) WithDefaults() *V1betaListActiveDirectoriesParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the v1beta list active directories params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *V1betaListActiveDirectoriesParams) SetDefaults() {
	// no default values defined for this parameter
}

// WithTimeout adds the timeout to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) WithTimeout(timeout time.Duration) *V1betaListActiveDirectoriesParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) WithContext(ctx context.Context) *V1betaListActiveDirectoriesParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) WithHTTPClient(client *http.Client) *V1betaListActiveDirectoriesParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithLocationID adds the locationID to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) WithLocationID(locationID string) *V1betaListActiveDirectoriesParams {
	o.SetLocationID(locationID)
	return o
}

// SetLocationID adds the locationId to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) SetLocationID(locationID string) {
	o.LocationID = locationID
}

// WithProjectNumber adds the projectNumber to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) WithProjectNumber(projectNumber string) *V1betaListActiveDirectoriesParams {
	o.SetProjectNumber(projectNumber)
	return o
}

// SetProjectNumber adds the projectNumber to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) SetProjectNumber(projectNumber string) {
	o.ProjectNumber = projectNumber
}

// WithXCorrelationID adds the xCorrelationID to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) WithXCorrelationID(xCorrelationID *string) *V1betaListActiveDirectoriesParams {
	o.SetXCorrelationID(xCorrelationID)
	return o
}

// SetXCorrelationID adds the xCorrelationId to the v1beta list active directories params
func (o *V1betaListActiveDirectoriesParams) SetXCorrelationID(xCorrelationID *string) {
	o.XCorrelationID = xCorrelationID
}

// WriteToRequest writes these params to a swagger request
func (o *V1betaListActiveDirectoriesParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	// path param locationId
	if err := r.SetPathParam("locationId", o.LocationID); err != nil {
		return err
	}

	// path param projectNumber
	if err := r.SetPathParam("projectNumber", o.ProjectNumber); err != nil {
		return err
	}

	if o.XCorrelationID != nil {

		// header param x-correlation-id
		if err := r.SetHeaderParam("x-correlation-id", *o.XCorrelationID); err != nil {
			return err
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
