// Code generated by go-swagger; DO NOT EDIT.

package migration_internal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp/models"
)

// V1betaTenantMigratePreMigrationCheckReader is a Reader for the V1betaTenantMigratePreMigrationCheck structure.
type V1betaTenantMigratePreMigrationCheckReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1betaTenantMigratePreMigrationCheckReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1betaTenantMigratePreMigrationCheckOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1betaTenantMigratePreMigrationCheckBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewV1betaTenantMigratePreMigrationCheckUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV1betaTenantMigratePreMigrationCheckForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1betaTenantMigratePreMigrationCheckNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewV1betaTenantMigratePreMigrationCheckTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV1betaTenantMigratePreMigrationCheckInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 501:
		result := NewV1betaTenantMigratePreMigrationCheckNotImplemented()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewV1betaTenantMigratePreMigrationCheckDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV1betaTenantMigratePreMigrationCheckOK creates a V1betaTenantMigratePreMigrationCheckOK with default headers values
func NewV1betaTenantMigratePreMigrationCheckOK() *V1betaTenantMigratePreMigrationCheckOK {
	return &V1betaTenantMigratePreMigrationCheckOK{}
}

/*
V1betaTenantMigratePreMigrationCheckOK describes a response with status code 200, with default header values.

OK
*/
type V1betaTenantMigratePreMigrationCheckOK struct {
	Payload *models.PreMigrationCheckStatusV1beta
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check o k response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check o k response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta tenant migrate pre migration check o k response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1beta tenant migrate pre migration check o k response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta tenant migrate pre migration check o k response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1beta tenant migrate pre migration check o k response
func (o *V1betaTenantMigratePreMigrationCheckOK) Code() int {
	return 200
}

func (o *V1betaTenantMigratePreMigrationCheckOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckOK %s", 200, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckOK %s", 200, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckOK) GetPayload() *models.PreMigrationCheckStatusV1beta {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.PreMigrationCheckStatusV1beta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaTenantMigratePreMigrationCheckBadRequest creates a V1betaTenantMigratePreMigrationCheckBadRequest with default headers values
func NewV1betaTenantMigratePreMigrationCheckBadRequest() *V1betaTenantMigratePreMigrationCheckBadRequest {
	return &V1betaTenantMigratePreMigrationCheckBadRequest{}
}

/*
V1betaTenantMigratePreMigrationCheckBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type V1betaTenantMigratePreMigrationCheckBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check bad request response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check bad request response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta tenant migrate pre migration check bad request response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta tenant migrate pre migration check bad request response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta tenant migrate pre migration check bad request response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the v1beta tenant migrate pre migration check bad request response
func (o *V1betaTenantMigratePreMigrationCheckBadRequest) Code() int {
	return 400
}

func (o *V1betaTenantMigratePreMigrationCheckBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckBadRequest %s", 400, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckBadRequest %s", 400, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaTenantMigratePreMigrationCheckUnauthorized creates a V1betaTenantMigratePreMigrationCheckUnauthorized with default headers values
func NewV1betaTenantMigratePreMigrationCheckUnauthorized() *V1betaTenantMigratePreMigrationCheckUnauthorized {
	return &V1betaTenantMigratePreMigrationCheckUnauthorized{}
}

/*
V1betaTenantMigratePreMigrationCheckUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type V1betaTenantMigratePreMigrationCheckUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check unauthorized response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check unauthorized response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta tenant migrate pre migration check unauthorized response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta tenant migrate pre migration check unauthorized response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta tenant migrate pre migration check unauthorized response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the v1beta tenant migrate pre migration check unauthorized response
func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) Code() int {
	return 401
}

func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckUnauthorized %s", 401, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckUnauthorized %s", 401, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaTenantMigratePreMigrationCheckForbidden creates a V1betaTenantMigratePreMigrationCheckForbidden with default headers values
func NewV1betaTenantMigratePreMigrationCheckForbidden() *V1betaTenantMigratePreMigrationCheckForbidden {
	return &V1betaTenantMigratePreMigrationCheckForbidden{}
}

/*
V1betaTenantMigratePreMigrationCheckForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type V1betaTenantMigratePreMigrationCheckForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check forbidden response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check forbidden response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta tenant migrate pre migration check forbidden response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta tenant migrate pre migration check forbidden response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta tenant migrate pre migration check forbidden response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the v1beta tenant migrate pre migration check forbidden response
func (o *V1betaTenantMigratePreMigrationCheckForbidden) Code() int {
	return 403
}

func (o *V1betaTenantMigratePreMigrationCheckForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckForbidden %s", 403, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckForbidden %s", 403, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaTenantMigratePreMigrationCheckNotFound creates a V1betaTenantMigratePreMigrationCheckNotFound with default headers values
func NewV1betaTenantMigratePreMigrationCheckNotFound() *V1betaTenantMigratePreMigrationCheckNotFound {
	return &V1betaTenantMigratePreMigrationCheckNotFound{}
}

/*
V1betaTenantMigratePreMigrationCheckNotFound describes a response with status code 404, with default header values.

Not found
*/
type V1betaTenantMigratePreMigrationCheckNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check not found response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check not found response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta tenant migrate pre migration check not found response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta tenant migrate pre migration check not found response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta tenant migrate pre migration check not found response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v1beta tenant migrate pre migration check not found response
func (o *V1betaTenantMigratePreMigrationCheckNotFound) Code() int {
	return 404
}

func (o *V1betaTenantMigratePreMigrationCheckNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckNotFound %s", 404, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckNotFound %s", 404, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaTenantMigratePreMigrationCheckTooManyRequests creates a V1betaTenantMigratePreMigrationCheckTooManyRequests with default headers values
func NewV1betaTenantMigratePreMigrationCheckTooManyRequests() *V1betaTenantMigratePreMigrationCheckTooManyRequests {
	return &V1betaTenantMigratePreMigrationCheckTooManyRequests{}
}

/*
V1betaTenantMigratePreMigrationCheckTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type V1betaTenantMigratePreMigrationCheckTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check too many requests response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check too many requests response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta tenant migrate pre migration check too many requests response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta tenant migrate pre migration check too many requests response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta tenant migrate pre migration check too many requests response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the v1beta tenant migrate pre migration check too many requests response
func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) Code() int {
	return 429
}

func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckTooManyRequests %s", 429, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckTooManyRequests %s", 429, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaTenantMigratePreMigrationCheckInternalServerError creates a V1betaTenantMigratePreMigrationCheckInternalServerError with default headers values
func NewV1betaTenantMigratePreMigrationCheckInternalServerError() *V1betaTenantMigratePreMigrationCheckInternalServerError {
	return &V1betaTenantMigratePreMigrationCheckInternalServerError{}
}

/*
V1betaTenantMigratePreMigrationCheckInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type V1betaTenantMigratePreMigrationCheckInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check internal server error response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check internal server error response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta tenant migrate pre migration check internal server error response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1beta tenant migrate pre migration check internal server error response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this v1beta tenant migrate pre migration check internal server error response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the v1beta tenant migrate pre migration check internal server error response
func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) Code() int {
	return 500
}

func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckInternalServerError %s", 500, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckInternalServerError %s", 500, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaTenantMigratePreMigrationCheckNotImplemented creates a V1betaTenantMigratePreMigrationCheckNotImplemented with default headers values
func NewV1betaTenantMigratePreMigrationCheckNotImplemented() *V1betaTenantMigratePreMigrationCheckNotImplemented {
	return &V1betaTenantMigratePreMigrationCheckNotImplemented{}
}

/*
V1betaTenantMigratePreMigrationCheckNotImplemented describes a response with status code 501, with default header values.

Not implemented
*/
type V1betaTenantMigratePreMigrationCheckNotImplemented struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check not implemented response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check not implemented response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta tenant migrate pre migration check not implemented response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1beta tenant migrate pre migration check not implemented response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) IsServerError() bool {
	return true
}

// IsCode returns true when this v1beta tenant migrate pre migration check not implemented response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) IsCode(code int) bool {
	return code == 501
}

// Code gets the status code for the v1beta tenant migrate pre migration check not implemented response
func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) Code() int {
	return 501
}

func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckNotImplemented %s", 501, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1betaTenantMigratePreMigrationCheckNotImplemented %s", 501, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckNotImplemented) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaTenantMigratePreMigrationCheckDefault creates a V1betaTenantMigratePreMigrationCheckDefault with default headers values
func NewV1betaTenantMigratePreMigrationCheckDefault(code int) *V1betaTenantMigratePreMigrationCheckDefault {
	return &V1betaTenantMigratePreMigrationCheckDefault{
		_statusCode: code,
	}
}

/*
V1betaTenantMigratePreMigrationCheckDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type V1betaTenantMigratePreMigrationCheckDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this v1beta tenant migrate pre migration check default response has a 2xx status code
func (o *V1betaTenantMigratePreMigrationCheckDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this v1beta tenant migrate pre migration check default response has a 3xx status code
func (o *V1betaTenantMigratePreMigrationCheckDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this v1beta tenant migrate pre migration check default response has a 4xx status code
func (o *V1betaTenantMigratePreMigrationCheckDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this v1beta tenant migrate pre migration check default response has a 5xx status code
func (o *V1betaTenantMigratePreMigrationCheckDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this v1beta tenant migrate pre migration check default response a status code equal to that given
func (o *V1betaTenantMigratePreMigrationCheckDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the v1beta tenant migrate pre migration check default response
func (o *V1betaTenantMigratePreMigrationCheckDefault) Code() int {
	return o._statusCode
}

func (o *V1betaTenantMigratePreMigrationCheckDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1beta_TenantMigratePreMigrationCheck default %s", o._statusCode, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate/PreMigrateCheck][%d] v1beta_TenantMigratePreMigrationCheck default %s", o._statusCode, payload)
}

func (o *V1betaTenantMigratePreMigrationCheckDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaTenantMigratePreMigrationCheckDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
