// Code generated by go-swagger; DO NOT EDIT.

package migration_internal

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp/models"
)

// V1betaCreateTenantMigrationJobReader is a Reader for the V1betaCreateTenantMigrationJob structure.
type V1betaCreateTenantMigrationJobReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1betaCreateTenantMigrationJobReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewV1betaCreateTenantMigrationJobAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1betaCreateTenantMigrationJobBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewV1betaCreateTenantMigrationJobUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV1betaCreateTenantMigrationJobForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewV1betaCreateTenantMigrationJobConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV1betaCreateTenantMigrationJobUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewV1betaCreateTenantMigrationJobTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV1betaCreateTenantMigrationJobInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewV1betaCreateTenantMigrationJobDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV1betaCreateTenantMigrationJobAccepted creates a V1betaCreateTenantMigrationJobAccepted with default headers values
func NewV1betaCreateTenantMigrationJobAccepted() *V1betaCreateTenantMigrationJobAccepted {
	return &V1betaCreateTenantMigrationJobAccepted{}
}

/*
V1betaCreateTenantMigrationJobAccepted describes a response with status code 202, with default header values.

Creating tenant migration job
*/
type V1betaCreateTenantMigrationJobAccepted struct {
	Payload *models.OperationV1beta
}

// IsSuccess returns true when this v1beta create tenant migration job accepted response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobAccepted) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1beta create tenant migration job accepted response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobAccepted) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta create tenant migration job accepted response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobAccepted) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1beta create tenant migration job accepted response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobAccepted) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta create tenant migration job accepted response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobAccepted) IsCode(code int) bool {
	return code == 202
}

// Code gets the status code for the v1beta create tenant migration job accepted response
func (o *V1betaCreateTenantMigrationJobAccepted) Code() int {
	return 202
}

func (o *V1betaCreateTenantMigrationJobAccepted) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobAccepted %s", 202, payload)
}

func (o *V1betaCreateTenantMigrationJobAccepted) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobAccepted %s", 202, payload)
}

func (o *V1betaCreateTenantMigrationJobAccepted) GetPayload() *models.OperationV1beta {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OperationV1beta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaCreateTenantMigrationJobBadRequest creates a V1betaCreateTenantMigrationJobBadRequest with default headers values
func NewV1betaCreateTenantMigrationJobBadRequest() *V1betaCreateTenantMigrationJobBadRequest {
	return &V1betaCreateTenantMigrationJobBadRequest{}
}

/*
V1betaCreateTenantMigrationJobBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type V1betaCreateTenantMigrationJobBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta create tenant migration job bad request response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta create tenant migration job bad request response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta create tenant migration job bad request response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta create tenant migration job bad request response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta create tenant migration job bad request response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the v1beta create tenant migration job bad request response
func (o *V1betaCreateTenantMigrationJobBadRequest) Code() int {
	return 400
}

func (o *V1betaCreateTenantMigrationJobBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobBadRequest %s", 400, payload)
}

func (o *V1betaCreateTenantMigrationJobBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobBadRequest %s", 400, payload)
}

func (o *V1betaCreateTenantMigrationJobBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaCreateTenantMigrationJobUnauthorized creates a V1betaCreateTenantMigrationJobUnauthorized with default headers values
func NewV1betaCreateTenantMigrationJobUnauthorized() *V1betaCreateTenantMigrationJobUnauthorized {
	return &V1betaCreateTenantMigrationJobUnauthorized{}
}

/*
V1betaCreateTenantMigrationJobUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type V1betaCreateTenantMigrationJobUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta create tenant migration job unauthorized response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta create tenant migration job unauthorized response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta create tenant migration job unauthorized response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta create tenant migration job unauthorized response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta create tenant migration job unauthorized response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the v1beta create tenant migration job unauthorized response
func (o *V1betaCreateTenantMigrationJobUnauthorized) Code() int {
	return 401
}

func (o *V1betaCreateTenantMigrationJobUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobUnauthorized %s", 401, payload)
}

func (o *V1betaCreateTenantMigrationJobUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobUnauthorized %s", 401, payload)
}

func (o *V1betaCreateTenantMigrationJobUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaCreateTenantMigrationJobForbidden creates a V1betaCreateTenantMigrationJobForbidden with default headers values
func NewV1betaCreateTenantMigrationJobForbidden() *V1betaCreateTenantMigrationJobForbidden {
	return &V1betaCreateTenantMigrationJobForbidden{}
}

/*
V1betaCreateTenantMigrationJobForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type V1betaCreateTenantMigrationJobForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta create tenant migration job forbidden response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta create tenant migration job forbidden response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta create tenant migration job forbidden response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta create tenant migration job forbidden response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta create tenant migration job forbidden response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the v1beta create tenant migration job forbidden response
func (o *V1betaCreateTenantMigrationJobForbidden) Code() int {
	return 403
}

func (o *V1betaCreateTenantMigrationJobForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobForbidden %s", 403, payload)
}

func (o *V1betaCreateTenantMigrationJobForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobForbidden %s", 403, payload)
}

func (o *V1betaCreateTenantMigrationJobForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaCreateTenantMigrationJobConflict creates a V1betaCreateTenantMigrationJobConflict with default headers values
func NewV1betaCreateTenantMigrationJobConflict() *V1betaCreateTenantMigrationJobConflict {
	return &V1betaCreateTenantMigrationJobConflict{}
}

/*
V1betaCreateTenantMigrationJobConflict describes a response with status code 409, with default header values.

Conflict
*/
type V1betaCreateTenantMigrationJobConflict struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta create tenant migration job conflict response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobConflict) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta create tenant migration job conflict response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobConflict) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta create tenant migration job conflict response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobConflict) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta create tenant migration job conflict response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobConflict) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta create tenant migration job conflict response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobConflict) IsCode(code int) bool {
	return code == 409
}

// Code gets the status code for the v1beta create tenant migration job conflict response
func (o *V1betaCreateTenantMigrationJobConflict) Code() int {
	return 409
}

func (o *V1betaCreateTenantMigrationJobConflict) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobConflict %s", 409, payload)
}

func (o *V1betaCreateTenantMigrationJobConflict) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobConflict %s", 409, payload)
}

func (o *V1betaCreateTenantMigrationJobConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaCreateTenantMigrationJobUnprocessableEntity creates a V1betaCreateTenantMigrationJobUnprocessableEntity with default headers values
func NewV1betaCreateTenantMigrationJobUnprocessableEntity() *V1betaCreateTenantMigrationJobUnprocessableEntity {
	return &V1betaCreateTenantMigrationJobUnprocessableEntity{}
}

/*
V1betaCreateTenantMigrationJobUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable entity
*/
type V1betaCreateTenantMigrationJobUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta create tenant migration job unprocessable entity response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta create tenant migration job unprocessable entity response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta create tenant migration job unprocessable entity response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta create tenant migration job unprocessable entity response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta create tenant migration job unprocessable entity response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the v1beta create tenant migration job unprocessable entity response
func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) Code() int {
	return 422
}

func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobUnprocessableEntity %s", 422, payload)
}

func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobUnprocessableEntity %s", 422, payload)
}

func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaCreateTenantMigrationJobTooManyRequests creates a V1betaCreateTenantMigrationJobTooManyRequests with default headers values
func NewV1betaCreateTenantMigrationJobTooManyRequests() *V1betaCreateTenantMigrationJobTooManyRequests {
	return &V1betaCreateTenantMigrationJobTooManyRequests{}
}

/*
V1betaCreateTenantMigrationJobTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type V1betaCreateTenantMigrationJobTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta create tenant migration job too many requests response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta create tenant migration job too many requests response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta create tenant migration job too many requests response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta create tenant migration job too many requests response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta create tenant migration job too many requests response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the v1beta create tenant migration job too many requests response
func (o *V1betaCreateTenantMigrationJobTooManyRequests) Code() int {
	return 429
}

func (o *V1betaCreateTenantMigrationJobTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobTooManyRequests %s", 429, payload)
}

func (o *V1betaCreateTenantMigrationJobTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobTooManyRequests %s", 429, payload)
}

func (o *V1betaCreateTenantMigrationJobTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaCreateTenantMigrationJobInternalServerError creates a V1betaCreateTenantMigrationJobInternalServerError with default headers values
func NewV1betaCreateTenantMigrationJobInternalServerError() *V1betaCreateTenantMigrationJobInternalServerError {
	return &V1betaCreateTenantMigrationJobInternalServerError{}
}

/*
V1betaCreateTenantMigrationJobInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type V1betaCreateTenantMigrationJobInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta create tenant migration job internal server error response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta create tenant migration job internal server error response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta create tenant migration job internal server error response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1beta create tenant migration job internal server error response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this v1beta create tenant migration job internal server error response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the v1beta create tenant migration job internal server error response
func (o *V1betaCreateTenantMigrationJobInternalServerError) Code() int {
	return 500
}

func (o *V1betaCreateTenantMigrationJobInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobInternalServerError %s", 500, payload)
}

func (o *V1betaCreateTenantMigrationJobInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1betaCreateTenantMigrationJobInternalServerError %s", 500, payload)
}

func (o *V1betaCreateTenantMigrationJobInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaCreateTenantMigrationJobDefault creates a V1betaCreateTenantMigrationJobDefault with default headers values
func NewV1betaCreateTenantMigrationJobDefault(code int) *V1betaCreateTenantMigrationJobDefault {
	return &V1betaCreateTenantMigrationJobDefault{
		_statusCode: code,
	}
}

/*
V1betaCreateTenantMigrationJobDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type V1betaCreateTenantMigrationJobDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this v1beta create tenant migration job default response has a 2xx status code
func (o *V1betaCreateTenantMigrationJobDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this v1beta create tenant migration job default response has a 3xx status code
func (o *V1betaCreateTenantMigrationJobDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this v1beta create tenant migration job default response has a 4xx status code
func (o *V1betaCreateTenantMigrationJobDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this v1beta create tenant migration job default response has a 5xx status code
func (o *V1betaCreateTenantMigrationJobDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this v1beta create tenant migration job default response a status code equal to that given
func (o *V1betaCreateTenantMigrationJobDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the v1beta create tenant migration job default response
func (o *V1betaCreateTenantMigrationJobDefault) Code() int {
	return o._statusCode
}

func (o *V1betaCreateTenantMigrationJobDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1beta_createTenantMigrationJob default %s", o._statusCode, payload)
}

func (o *V1betaCreateTenantMigrationJobDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[POST /v1beta/internal/projects/{projectNumber}/locations/{locationId}/TenantMigrate][%d] v1beta_createTenantMigrationJob default %s", o._statusCode, payload)
}

func (o *V1betaCreateTenantMigrationJobDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaCreateTenantMigrationJobDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
