apiVersion: v2
appVersion: 11.0.0
description: The leading tool for querying and visualizing time series and metrics.
keywords:
  - monitoring
  - metric
kubeVersion: ^1.8.0-0
name: grafana
type: application
version: 8.0.2
