# Global values - these are typically overridden by parent chart
global:
  primaryImageRegistry: "ghcr.io"
  primaryImageRegistryPath: ""
  chartPrimaryImageRegistry: ""
  secondaryImageRegistry: ""
  secondaryImageRegistryPath: ""
  chartSecondaryImageRegistry: ""
  useTags: false

externalSecretManager: false
hyperscaler: "gcp"

images:
  cloudBackupAdcGCP:
    name: cloud-backup-adc
    tag: "3.0" #NOTE: Please also update the tag for "cloud-backup-adc" in the blackduck scan CI job in release.yaml in case of a tag update here if useTags is set to true in global values.yaml
    digest: "sha256:c3b5aff7b291e8517aa76a0daad526d0fc6edf321e1c8727c3939d8e67118225" #Update digest here if useTags is set to false in global values.yaml
    secondary: true
    pullPolicy: IfNotPresent

# Enabled
enabled: true

# Naming
serviceAccount: adc
nameOverride: adc

# Configuration
replicas: 2
adcport: 8085
threshold: 50
disableVerifySSL: "0"

# Secret configuration
secret:
  googlecomchain: ""

adc_info:
  adcMountBackupSleepInterval: "6"
  adcProvider: ""
  adcMountDir: ""
  adcEndPoint: ""
  adcCertName: ""
  adcCertDir: ""
  adcLogDir: "/home/vsa/adcLogPath"
  adcNumOfCpus: "1"
  adcNumOfFuseDevices: "1"
  adcConfigMemory: "256M"
  adcBrowseMemory: "4G"
  adcNodeSelector: "vsacp-nodes"
  adcCertSecretName: "adc-secret"
  adcPodPollMaxRetryCount: "15"
  adcPodPollSleepInterval: "1"
  adcPodPollDeleteRetryCount: "12"
  adcPodPollDeleteSleepInterval: "5"

# Add support to turn off separate nodes for VSA (tolerations + labels)
nodes: 
  tolerations: true
  nodeSelector: false

# Secret Manager config (used with external-secrets chart)
secretManager:
  apiVersion: external-secrets.io/v1beta1
  clusterSecretStoreName: "main-cluster-secret-store"
  refreshInterval: 24h
  # Name of secret(s) in external Secret Manager
  googleComChain: "vsa-google-chain"

workloadIdentity:
  azureClientId: ""
  gcpServiceAccount: ""

# Annotations
statefulSetAnnotations: {}
podAnnotations:
  container.apparmor.security.beta.kubernetes.io/adc: unconfined
serviceAnnotations: {}
configmapAnnotations: {}
secretAnnotations: {}
serviceAccountAnnotations:
  "iam.gke.io/gcp-service-account": ""
commonAnnotations: {}

# Labels
statefulSetLabels: {}
podLabels: {}
serviceLabels: {}
configmapLabels: {}
secretLabels: {}
serviceAccountLabels: {}
commonLabels: {}

