{{- if .Values.ingress.enabled }}
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: oci-proxy-service-ingress
  annotations:
    {{- with .Values.ingress.annotations }}
    {{- toYaml . | nindent 4 }}
    {{- end }}
    {{- include "oci_proxy.kubernetes.annotations" . | nindent 4 }}
    {{- include "oci_proxy.helmchart.annotations" . | nindent 4 }}
  labels:
    {{- include "oci_proxy.kubernetes.labels" . | nindent 4 }}
    {{- include "oci_proxy.helmchart.labels" . | nindent 4 }}
spec:
  {{- if .Values.ingress.className }}
  ingressClassName: {{ .Values.ingress.className }}
  {{- end }}
  rules:
    {{- if .Values.ingress.host }}
    - host: {{ .Values.ingress.host }}
      http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oci-proxy-service
                port:
                  number: 80
    {{- else }}
    - http:
        paths:
          - path: /
            pathType: Prefix
            backend:
              service:
                name: oci-proxy-service
                port:
                  number: 80
    {{- end }}
  {{- if .Values.ingress.tls }}
  tls:
    {{- toYaml .Values.ingress.tls | nindent 4 }}
  {{- end }}
{{- end }}
