apiVersion: v1
kind: ServiceAccount
metadata:
  name: {{ .Values.serviceAccountName }}
  namespace: {{ .Release.Namespace }}
  annotations:
    "helm.sh/hook": pre-install,pre-upgrade
    {{- include "oci_proxy.kubernetes.annotations" . | nindent 4 }}
    {{- include "oci_proxy.helmchart.annotations" . | nindent 4 }}
    {{- include "oci_proxy.serviceAccountAnnotations" . | nindent 4 }}
  labels:
    {{- include "oci_proxy.kubernetes.labels" . | nindent 4 }}
    {{- include "oci_proxy.helmchart.labels" . | nindent 4 }}
{{- if .Values.imagePullSecrets }}
imagePullSecrets:
  {{- range .Values.imagePullSecrets }}
  {{- if .name }}
  - name: {{ .name | quote }}
  {{- end }}
  {{- end }}
{{- end }}
