// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"encoding/json"
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp/models"
)

// V1betaGetLatestBackupStatusOnVolumeReader is a Reader for the V1betaGetLatestBackupStatusOnVolume structure.
type V1betaGetLatestBackupStatusOnVolumeReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1betaGetLatestBackupStatusOnVolumeReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewV1betaGetLatestBackupStatusOnVolumeOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1betaGetLatestBackupStatusOnVolumeBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewV1betaGetLatestBackupStatusOnVolumeUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV1betaGetLatestBackupStatusOnVolumeForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1betaGetLatestBackupStatusOnVolumeNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV1betaGetLatestBackupStatusOnVolumeUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewV1betaGetLatestBackupStatusOnVolumeTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV1betaGetLatestBackupStatusOnVolumeInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewV1betaGetLatestBackupStatusOnVolumeDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV1betaGetLatestBackupStatusOnVolumeOK creates a V1betaGetLatestBackupStatusOnVolumeOK with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeOK() *V1betaGetLatestBackupStatusOnVolumeOK {
	return &V1betaGetLatestBackupStatusOnVolumeOK{}
}

/*
V1betaGetLatestBackupStatusOnVolumeOK describes a response with status code 200, with default header values.

OK
*/
type V1betaGetLatestBackupStatusOnVolumeOK struct {
	Payload *models.LatestBackupStatusV1beta
}

// IsSuccess returns true when this v1beta get latest backup status on volume o k response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this v1beta get latest backup status on volume o k response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta get latest backup status on volume o k response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1beta get latest backup status on volume o k response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeOK) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta get latest backup status on volume o k response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the v1beta get latest backup status on volume o k response
func (o *V1betaGetLatestBackupStatusOnVolumeOK) Code() int {
	return 200
}

func (o *V1betaGetLatestBackupStatusOnVolumeOK) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeOK %s", 200, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeOK) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeOK %s", 200, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeOK) GetPayload() *models.LatestBackupStatusV1beta {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.LatestBackupStatusV1beta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaGetLatestBackupStatusOnVolumeBadRequest creates a V1betaGetLatestBackupStatusOnVolumeBadRequest with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeBadRequest() *V1betaGetLatestBackupStatusOnVolumeBadRequest {
	return &V1betaGetLatestBackupStatusOnVolumeBadRequest{}
}

/*
V1betaGetLatestBackupStatusOnVolumeBadRequest describes a response with status code 400, with default header values.

Bad request
*/
type V1betaGetLatestBackupStatusOnVolumeBadRequest struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta get latest backup status on volume bad request response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta get latest backup status on volume bad request response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta get latest backup status on volume bad request response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta get latest backup status on volume bad request response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta get latest backup status on volume bad request response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) IsCode(code int) bool {
	return code == 400
}

// Code gets the status code for the v1beta get latest backup status on volume bad request response
func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) Code() int {
	return 400
}

func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeBadRequest %s", 400, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeBadRequest %s", 400, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaGetLatestBackupStatusOnVolumeUnauthorized creates a V1betaGetLatestBackupStatusOnVolumeUnauthorized with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeUnauthorized() *V1betaGetLatestBackupStatusOnVolumeUnauthorized {
	return &V1betaGetLatestBackupStatusOnVolumeUnauthorized{}
}

/*
V1betaGetLatestBackupStatusOnVolumeUnauthorized describes a response with status code 401, with default header values.

Unauthorized
*/
type V1betaGetLatestBackupStatusOnVolumeUnauthorized struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta get latest backup status on volume unauthorized response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta get latest backup status on volume unauthorized response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta get latest backup status on volume unauthorized response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta get latest backup status on volume unauthorized response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta get latest backup status on volume unauthorized response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) IsCode(code int) bool {
	return code == 401
}

// Code gets the status code for the v1beta get latest backup status on volume unauthorized response
func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) Code() int {
	return 401
}

func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeUnauthorized %s", 401, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeUnauthorized %s", 401, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaGetLatestBackupStatusOnVolumeForbidden creates a V1betaGetLatestBackupStatusOnVolumeForbidden with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeForbidden() *V1betaGetLatestBackupStatusOnVolumeForbidden {
	return &V1betaGetLatestBackupStatusOnVolumeForbidden{}
}

/*
V1betaGetLatestBackupStatusOnVolumeForbidden describes a response with status code 403, with default header values.

Forbidden
*/
type V1betaGetLatestBackupStatusOnVolumeForbidden struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta get latest backup status on volume forbidden response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta get latest backup status on volume forbidden response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta get latest backup status on volume forbidden response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta get latest backup status on volume forbidden response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta get latest backup status on volume forbidden response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) IsCode(code int) bool {
	return code == 403
}

// Code gets the status code for the v1beta get latest backup status on volume forbidden response
func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) Code() int {
	return 403
}

func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeForbidden %s", 403, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeForbidden %s", 403, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaGetLatestBackupStatusOnVolumeNotFound creates a V1betaGetLatestBackupStatusOnVolumeNotFound with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeNotFound() *V1betaGetLatestBackupStatusOnVolumeNotFound {
	return &V1betaGetLatestBackupStatusOnVolumeNotFound{}
}

/*
V1betaGetLatestBackupStatusOnVolumeNotFound describes a response with status code 404, with default header values.

Not found
*/
type V1betaGetLatestBackupStatusOnVolumeNotFound struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta get latest backup status on volume not found response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta get latest backup status on volume not found response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta get latest backup status on volume not found response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta get latest backup status on volume not found response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta get latest backup status on volume not found response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) IsCode(code int) bool {
	return code == 404
}

// Code gets the status code for the v1beta get latest backup status on volume not found response
func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) Code() int {
	return 404
}

func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeNotFound %s", 404, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeNotFound %s", 404, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaGetLatestBackupStatusOnVolumeUnprocessableEntity creates a V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeUnprocessableEntity() *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity {
	return &V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity{}
}

/*
V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity describes a response with status code 422, with default header values.

Unprocessable entity
*/
type V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta get latest backup status on volume unprocessable entity response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta get latest backup status on volume unprocessable entity response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta get latest backup status on volume unprocessable entity response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta get latest backup status on volume unprocessable entity response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta get latest backup status on volume unprocessable entity response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) IsCode(code int) bool {
	return code == 422
}

// Code gets the status code for the v1beta get latest backup status on volume unprocessable entity response
func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) Code() int {
	return 422
}

func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeUnprocessableEntity %s", 422, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeUnprocessableEntity %s", 422, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaGetLatestBackupStatusOnVolumeTooManyRequests creates a V1betaGetLatestBackupStatusOnVolumeTooManyRequests with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeTooManyRequests() *V1betaGetLatestBackupStatusOnVolumeTooManyRequests {
	return &V1betaGetLatestBackupStatusOnVolumeTooManyRequests{}
}

/*
V1betaGetLatestBackupStatusOnVolumeTooManyRequests describes a response with status code 429, with default header values.

Too many requests
*/
type V1betaGetLatestBackupStatusOnVolumeTooManyRequests struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta get latest backup status on volume too many requests response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta get latest backup status on volume too many requests response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta get latest backup status on volume too many requests response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) IsClientError() bool {
	return true
}

// IsServerError returns true when this v1beta get latest backup status on volume too many requests response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) IsServerError() bool {
	return false
}

// IsCode returns true when this v1beta get latest backup status on volume too many requests response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) IsCode(code int) bool {
	return code == 429
}

// Code gets the status code for the v1beta get latest backup status on volume too many requests response
func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) Code() int {
	return 429
}

func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeTooManyRequests %s", 429, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeTooManyRequests %s", 429, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaGetLatestBackupStatusOnVolumeInternalServerError creates a V1betaGetLatestBackupStatusOnVolumeInternalServerError with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeInternalServerError() *V1betaGetLatestBackupStatusOnVolumeInternalServerError {
	return &V1betaGetLatestBackupStatusOnVolumeInternalServerError{}
}

/*
V1betaGetLatestBackupStatusOnVolumeInternalServerError describes a response with status code 500, with default header values.

Internal server error
*/
type V1betaGetLatestBackupStatusOnVolumeInternalServerError struct {
	Payload *models.Error
}

// IsSuccess returns true when this v1beta get latest backup status on volume internal server error response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) IsSuccess() bool {
	return false
}

// IsRedirect returns true when this v1beta get latest backup status on volume internal server error response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) IsRedirect() bool {
	return false
}

// IsClientError returns true when this v1beta get latest backup status on volume internal server error response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) IsClientError() bool {
	return false
}

// IsServerError returns true when this v1beta get latest backup status on volume internal server error response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) IsServerError() bool {
	return true
}

// IsCode returns true when this v1beta get latest backup status on volume internal server error response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) IsCode(code int) bool {
	return code == 500
}

// Code gets the status code for the v1beta get latest backup status on volume internal server error response
func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) Code() int {
	return 500
}

func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeInternalServerError %s", 500, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1betaGetLatestBackupStatusOnVolumeInternalServerError %s", 500, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaGetLatestBackupStatusOnVolumeDefault creates a V1betaGetLatestBackupStatusOnVolumeDefault with default headers values
func NewV1betaGetLatestBackupStatusOnVolumeDefault(code int) *V1betaGetLatestBackupStatusOnVolumeDefault {
	return &V1betaGetLatestBackupStatusOnVolumeDefault{
		_statusCode: code,
	}
}

/*
V1betaGetLatestBackupStatusOnVolumeDefault describes a response with status code -1, with default header values.

Unexpected error
*/
type V1betaGetLatestBackupStatusOnVolumeDefault struct {
	_statusCode int

	Payload *models.Error
}

// IsSuccess returns true when this v1beta get latest backup status on volume default response has a 2xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this v1beta get latest backup status on volume default response has a 3xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this v1beta get latest backup status on volume default response has a 4xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this v1beta get latest backup status on volume default response has a 5xx status code
func (o *V1betaGetLatestBackupStatusOnVolumeDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this v1beta get latest backup status on volume default response a status code equal to that given
func (o *V1betaGetLatestBackupStatusOnVolumeDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the v1beta get latest backup status on volume default response
func (o *V1betaGetLatestBackupStatusOnVolumeDefault) Code() int {
	return o._statusCode
}

func (o *V1betaGetLatestBackupStatusOnVolumeDefault) Error() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1beta_getLatestBackupStatusOnVolume default %s", o._statusCode, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeDefault) String() string {
	payload, _ := json.Marshal(o.Payload)
	return fmt.Sprintf("[GET /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeId}/latestBackupStatus][%d] v1beta_getLatestBackupStatusOnVolume default %s", o._statusCode, payload)
}

func (o *V1betaGetLatestBackupStatusOnVolumeDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaGetLatestBackupStatusOnVolumeDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
