// Code generated by go-swagger; DO NOT EDIT.

package volumes

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/cvp/models"
)

// V1betaEstablishVolumePeeringReader is a Reader for the V1betaEstablishVolumePeering structure.
type V1betaEstablishVolumePeeringReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *V1betaEstablishVolumePeeringReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 202:
		result := NewV1betaEstablishVolumePeeringAccepted()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	case 400:
		result := NewV1betaEstablishVolumePeeringBadRequest()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 401:
		result := NewV1betaEstablishVolumePeeringUnauthorized()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 403:
		result := NewV1betaEstablishVolumePeeringForbidden()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 404:
		result := NewV1betaEstablishVolumePeeringNotFound()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 409:
		result := NewV1betaEstablishVolumePeeringConflict()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 422:
		result := NewV1betaEstablishVolumePeeringUnprocessableEntity()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 429:
		result := NewV1betaEstablishVolumePeeringTooManyRequests()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	case 500:
		result := NewV1betaEstablishVolumePeeringInternalServerError()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return nil, result
	default:
		result := NewV1betaEstablishVolumePeeringDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewV1betaEstablishVolumePeeringAccepted creates a V1betaEstablishVolumePeeringAccepted with default headers values
func NewV1betaEstablishVolumePeeringAccepted() *V1betaEstablishVolumePeeringAccepted {
	return &V1betaEstablishVolumePeeringAccepted{}
}

/*
V1betaEstablishVolumePeeringAccepted handles this case with default header values.

Peering is being established
*/
type V1betaEstablishVolumePeeringAccepted struct {
	Payload *models.OperationV1beta
}

func (o *V1betaEstablishVolumePeeringAccepted) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringAccepted  %+v", 202, o.Payload)
}

func (o *V1betaEstablishVolumePeeringAccepted) GetPayload() *models.OperationV1beta {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringAccepted) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.OperationV1beta)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringBadRequest creates a V1betaEstablishVolumePeeringBadRequest with default headers values
func NewV1betaEstablishVolumePeeringBadRequest() *V1betaEstablishVolumePeeringBadRequest {
	return &V1betaEstablishVolumePeeringBadRequest{}
}

/*
V1betaEstablishVolumePeeringBadRequest handles this case with default header values.

Bad request
*/
type V1betaEstablishVolumePeeringBadRequest struct {
	Payload *models.Error
}

func (o *V1betaEstablishVolumePeeringBadRequest) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringBadRequest  %+v", 400, o.Payload)
}

func (o *V1betaEstablishVolumePeeringBadRequest) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringBadRequest) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringUnauthorized creates a V1betaEstablishVolumePeeringUnauthorized with default headers values
func NewV1betaEstablishVolumePeeringUnauthorized() *V1betaEstablishVolumePeeringUnauthorized {
	return &V1betaEstablishVolumePeeringUnauthorized{}
}

/*
V1betaEstablishVolumePeeringUnauthorized handles this case with default header values.

Unauthorized
*/
type V1betaEstablishVolumePeeringUnauthorized struct {
	Payload *models.Error
}

func (o *V1betaEstablishVolumePeeringUnauthorized) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringUnauthorized  %+v", 401, o.Payload)
}

func (o *V1betaEstablishVolumePeeringUnauthorized) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringUnauthorized) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringForbidden creates a V1betaEstablishVolumePeeringForbidden with default headers values
func NewV1betaEstablishVolumePeeringForbidden() *V1betaEstablishVolumePeeringForbidden {
	return &V1betaEstablishVolumePeeringForbidden{}
}

/*
V1betaEstablishVolumePeeringForbidden handles this case with default header values.

Forbidden
*/
type V1betaEstablishVolumePeeringForbidden struct {
	Payload *models.Error
}

func (o *V1betaEstablishVolumePeeringForbidden) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringForbidden  %+v", 403, o.Payload)
}

func (o *V1betaEstablishVolumePeeringForbidden) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringForbidden) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringNotFound creates a V1betaEstablishVolumePeeringNotFound with default headers values
func NewV1betaEstablishVolumePeeringNotFound() *V1betaEstablishVolumePeeringNotFound {
	return &V1betaEstablishVolumePeeringNotFound{}
}

/*
V1betaEstablishVolumePeeringNotFound handles this case with default header values.

Not found
*/
type V1betaEstablishVolumePeeringNotFound struct {
	Payload *models.Error
}

func (o *V1betaEstablishVolumePeeringNotFound) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringNotFound  %+v", 404, o.Payload)
}

func (o *V1betaEstablishVolumePeeringNotFound) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringNotFound) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringConflict creates a V1betaEstablishVolumePeeringConflict with default headers values
func NewV1betaEstablishVolumePeeringConflict() *V1betaEstablishVolumePeeringConflict {
	return &V1betaEstablishVolumePeeringConflict{}
}

/*
V1betaEstablishVolumePeeringConflict handles this case with default header values.

Conflict
*/
type V1betaEstablishVolumePeeringConflict struct {
	Payload *models.Error
}

func (o *V1betaEstablishVolumePeeringConflict) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringConflict  %+v", 409, o.Payload)
}

func (o *V1betaEstablishVolumePeeringConflict) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringConflict) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringUnprocessableEntity creates a V1betaEstablishVolumePeeringUnprocessableEntity with default headers values
func NewV1betaEstablishVolumePeeringUnprocessableEntity() *V1betaEstablishVolumePeeringUnprocessableEntity {
	return &V1betaEstablishVolumePeeringUnprocessableEntity{}
}

/*
V1betaEstablishVolumePeeringUnprocessableEntity handles this case with default header values.

Unprocessable entity
*/
type V1betaEstablishVolumePeeringUnprocessableEntity struct {
	Payload *models.Error
}

func (o *V1betaEstablishVolumePeeringUnprocessableEntity) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringUnprocessableEntity  %+v", 422, o.Payload)
}

func (o *V1betaEstablishVolumePeeringUnprocessableEntity) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringUnprocessableEntity) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringTooManyRequests creates a V1betaEstablishVolumePeeringTooManyRequests with default headers values
func NewV1betaEstablishVolumePeeringTooManyRequests() *V1betaEstablishVolumePeeringTooManyRequests {
	return &V1betaEstablishVolumePeeringTooManyRequests{}
}

/*
V1betaEstablishVolumePeeringTooManyRequests handles this case with default header values.

Too many requests
*/
type V1betaEstablishVolumePeeringTooManyRequests struct {
	Payload *models.Error
}

func (o *V1betaEstablishVolumePeeringTooManyRequests) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringTooManyRequests  %+v", 429, o.Payload)
}

func (o *V1betaEstablishVolumePeeringTooManyRequests) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringTooManyRequests) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringInternalServerError creates a V1betaEstablishVolumePeeringInternalServerError with default headers values
func NewV1betaEstablishVolumePeeringInternalServerError() *V1betaEstablishVolumePeeringInternalServerError {
	return &V1betaEstablishVolumePeeringInternalServerError{}
}

/*
V1betaEstablishVolumePeeringInternalServerError handles this case with default header values.

Internal server error
*/
type V1betaEstablishVolumePeeringInternalServerError struct {
	Payload *models.Error
}

func (o *V1betaEstablishVolumePeeringInternalServerError) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1betaEstablishVolumePeeringInternalServerError  %+v", 500, o.Payload)
}

func (o *V1betaEstablishVolumePeeringInternalServerError) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringInternalServerError) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewV1betaEstablishVolumePeeringDefault creates a V1betaEstablishVolumePeeringDefault with default headers values
func NewV1betaEstablishVolumePeeringDefault(code int) *V1betaEstablishVolumePeeringDefault {
	return &V1betaEstablishVolumePeeringDefault{
		_statusCode: code,
	}
}

/*
V1betaEstablishVolumePeeringDefault handles this case with default header values.

Unexpected error
*/
type V1betaEstablishVolumePeeringDefault struct {
	_statusCode int

	Payload *models.Error
}

// Code gets the status code for the v1beta establish volume peering default response
func (o *V1betaEstablishVolumePeeringDefault) Code() int {
	return o._statusCode
}

func (o *V1betaEstablishVolumePeeringDefault) Error() string {
	return fmt.Sprintf("[POST /v1beta/projects/{projectNumber}/locations/{locationId}/volumes/{volumeResourceId}/establishPeering][%d] v1beta_establishVolumePeering default  %+v", o._statusCode, o.Payload)
}

func (o *V1betaEstablishVolumePeeringDefault) GetPayload() *models.Error {
	return o.Payload
}

func (o *V1betaEstablishVolumePeeringDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.Error)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
