ARG BASE
FROM $BASE

# Copy the binary from the builder stage
COPY /artifacts/vcp-worker /app/app
COPY /core/errors/errors.json /app/errors.json
COPY /common/vsa_config/vlm-config.json /app/vlm-config.json
COPY /config/vmrs_gcp.yaml /app/vmrs_gcp.yaml

# # Set ownership and permissions
# USER nonroot:nonroot
