// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"
	"net/http"
	"time"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/runtime"
	cr "github.com/go-openapi/runtime/client"
	"github.com/go-openapi/strfmt"
)

// NewScheduleModifyCollectionParams creates a new ScheduleModifyCollectionParams object,
// with the default timeout for this client.
//
// Default values are not hydrated, since defaults are normally applied by the API server side.
//
// To enforce default values in parameter, use SetDefaults or WithDefaults.
func NewScheduleModifyCollectionParams() *ScheduleModifyCollectionParams {
	return &ScheduleModifyCollectionParams{
		timeout: cr.DefaultTimeout,
	}
}

// NewScheduleModifyCollectionParamsWithTimeout creates a new ScheduleModifyCollectionParams object
// with the ability to set a timeout on a request.
func NewScheduleModifyCollectionParamsWithTimeout(timeout time.Duration) *ScheduleModifyCollectionParams {
	return &ScheduleModifyCollectionParams{
		timeout: timeout,
	}
}

// NewScheduleModifyCollectionParamsWithContext creates a new ScheduleModifyCollectionParams object
// with the ability to set a context for a request.
func NewScheduleModifyCollectionParamsWithContext(ctx context.Context) *ScheduleModifyCollectionParams {
	return &ScheduleModifyCollectionParams{
		Context: ctx,
	}
}

// NewScheduleModifyCollectionParamsWithHTTPClient creates a new ScheduleModifyCollectionParams object
// with the ability to set a custom HTTPClient for a request.
func NewScheduleModifyCollectionParamsWithHTTPClient(client *http.Client) *ScheduleModifyCollectionParams {
	return &ScheduleModifyCollectionParams{
		HTTPClient: client,
	}
}

/*
ScheduleModifyCollectionParams contains all the parameters to send to the API endpoint

	for the schedule modify collection operation.

	Typically these are written to a http.Request.
*/
type ScheduleModifyCollectionParams struct {

	/* ClusterName.

	   Filter by cluster.name

	   Format: string
	*/
	ClusterName *string

	/* ClusterUUID.

	   Filter by cluster.uuid

	   Format: string
	*/
	ClusterUUID *string

	/* ContinueOnFailure.

	   Continue even when the operation fails on one of the records.

	   Format: boolean
	   Default: "\"False\""
	*/
	ContinueOnFailure *string

	/* CronDays.

	   Filter by cron.days

	   Format: integer
	*/
	CronDays *string

	/* CronHours.

	   Filter by cron.hours

	   Format: integer
	*/
	CronHours *string

	/* CronMinutes.

	   Filter by cron.minutes

	   Format: integer
	*/
	CronMinutes *string

	/* CronMonths.

	   Filter by cron.months

	   Format: integer
	*/
	CronMonths *string

	/* CronWeekdays.

	   Filter by cron.weekdays

	   Format: integer
	*/
	CronWeekdays *string

	/* Info.

	   Info specification
	*/
	Info ScheduleModifyCollectionBody

	/* Interval.

	   Filter by interval

	   Format: string
	*/
	Interval *string

	/* Name.

	   Filter by name

	   Format: string
	*/
	Name *string

	/* ReturnRecords.

	   The default is true for GET calls.  When set to false, only the number of records is returned.

	   Format: boolean
	   Default: "\"True\""
	*/
	ReturnRecords *string

	/* ReturnTimeout.

	   The number of seconds to allow the call to execute before returning.  When iterating over a collection, the default is 15 seconds.  ONTAP returns earlier if either max records or the end of the collection is reached.

	   Format: integer
	   Default: "\"15\""
	*/
	ReturnTimeout *string

	/* Scope.

	   Filter by scope

	   Format: string
	*/
	Scope *string

	/* SerialRecords.

	   Perform the operation on the records synchronously.

	   Format: boolean
	   Default: "\"False\""
	*/
	SerialRecords *string

	/* SvmName.

	   Filter by svm.name

	   Format: string
	*/
	SvmName *string

	/* SvmUUID.

	   Filter by svm.uuid

	   Format: string
	*/
	SvmUUID *string

	/* Type.

	   Filter by type

	   Format: string
	*/
	Type *string

	/* UUID.

	   Filter by uuid

	   Format: string
	*/
	UUID *string

	timeout    time.Duration
	Context    context.Context
	HTTPClient *http.Client
}

// WithDefaults hydrates default values in the schedule modify collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScheduleModifyCollectionParams) WithDefaults() *ScheduleModifyCollectionParams {
	o.SetDefaults()
	return o
}

// SetDefaults hydrates default values in the schedule modify collection params (not the query body).
//
// All values with no default are reset to their zero value.
func (o *ScheduleModifyCollectionParams) SetDefaults() {
	var (
		continueOnFailureDefault = string("\"False\"")

		returnRecordsDefault = string("\"True\"")

		returnTimeoutDefault = string("\"15\"")

		serialRecordsDefault = string("\"False\"")
	)

	val := ScheduleModifyCollectionParams{
		ContinueOnFailure: &continueOnFailureDefault,
		ReturnRecords:     &returnRecordsDefault,
		ReturnTimeout:     &returnTimeoutDefault,
		SerialRecords:     &serialRecordsDefault,
	}

	val.timeout = o.timeout
	val.Context = o.Context
	val.HTTPClient = o.HTTPClient
	*o = val
}

// WithTimeout adds the timeout to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithTimeout(timeout time.Duration) *ScheduleModifyCollectionParams {
	o.SetTimeout(timeout)
	return o
}

// SetTimeout adds the timeout to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetTimeout(timeout time.Duration) {
	o.timeout = timeout
}

// WithContext adds the context to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithContext(ctx context.Context) *ScheduleModifyCollectionParams {
	o.SetContext(ctx)
	return o
}

// SetContext adds the context to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetContext(ctx context.Context) {
	o.Context = ctx
}

// WithHTTPClient adds the HTTPClient to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithHTTPClient(client *http.Client) *ScheduleModifyCollectionParams {
	o.SetHTTPClient(client)
	return o
}

// SetHTTPClient adds the HTTPClient to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetHTTPClient(client *http.Client) {
	o.HTTPClient = client
}

// WithClusterName adds the clusterName to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithClusterName(clusterName *string) *ScheduleModifyCollectionParams {
	o.SetClusterName(clusterName)
	return o
}

// SetClusterName adds the clusterName to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetClusterName(clusterName *string) {
	o.ClusterName = clusterName
}

// WithClusterUUID adds the clusterUUID to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithClusterUUID(clusterUUID *string) *ScheduleModifyCollectionParams {
	o.SetClusterUUID(clusterUUID)
	return o
}

// SetClusterUUID adds the clusterUuid to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetClusterUUID(clusterUUID *string) {
	o.ClusterUUID = clusterUUID
}

// WithContinueOnFailure adds the continueOnFailure to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithContinueOnFailure(continueOnFailure *string) *ScheduleModifyCollectionParams {
	o.SetContinueOnFailure(continueOnFailure)
	return o
}

// SetContinueOnFailure adds the continueOnFailure to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetContinueOnFailure(continueOnFailure *string) {
	o.ContinueOnFailure = continueOnFailure
}

// WithCronDays adds the cronDays to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithCronDays(cronDays *string) *ScheduleModifyCollectionParams {
	o.SetCronDays(cronDays)
	return o
}

// SetCronDays adds the cronDays to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetCronDays(cronDays *string) {
	o.CronDays = cronDays
}

// WithCronHours adds the cronHours to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithCronHours(cronHours *string) *ScheduleModifyCollectionParams {
	o.SetCronHours(cronHours)
	return o
}

// SetCronHours adds the cronHours to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetCronHours(cronHours *string) {
	o.CronHours = cronHours
}

// WithCronMinutes adds the cronMinutes to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithCronMinutes(cronMinutes *string) *ScheduleModifyCollectionParams {
	o.SetCronMinutes(cronMinutes)
	return o
}

// SetCronMinutes adds the cronMinutes to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetCronMinutes(cronMinutes *string) {
	o.CronMinutes = cronMinutes
}

// WithCronMonths adds the cronMonths to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithCronMonths(cronMonths *string) *ScheduleModifyCollectionParams {
	o.SetCronMonths(cronMonths)
	return o
}

// SetCronMonths adds the cronMonths to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetCronMonths(cronMonths *string) {
	o.CronMonths = cronMonths
}

// WithCronWeekdays adds the cronWeekdays to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithCronWeekdays(cronWeekdays *string) *ScheduleModifyCollectionParams {
	o.SetCronWeekdays(cronWeekdays)
	return o
}

// SetCronWeekdays adds the cronWeekdays to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetCronWeekdays(cronWeekdays *string) {
	o.CronWeekdays = cronWeekdays
}

// WithInfo adds the info to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithInfo(info ScheduleModifyCollectionBody) *ScheduleModifyCollectionParams {
	o.SetInfo(info)
	return o
}

// SetInfo adds the info to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetInfo(info ScheduleModifyCollectionBody) {
	o.Info = info
}

// WithInterval adds the interval to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithInterval(interval *string) *ScheduleModifyCollectionParams {
	o.SetInterval(interval)
	return o
}

// SetInterval adds the interval to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetInterval(interval *string) {
	o.Interval = interval
}

// WithName adds the name to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithName(name *string) *ScheduleModifyCollectionParams {
	o.SetName(name)
	return o
}

// SetName adds the name to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetName(name *string) {
	o.Name = name
}

// WithReturnRecords adds the returnRecords to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithReturnRecords(returnRecords *string) *ScheduleModifyCollectionParams {
	o.SetReturnRecords(returnRecords)
	return o
}

// SetReturnRecords adds the returnRecords to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetReturnRecords(returnRecords *string) {
	o.ReturnRecords = returnRecords
}

// WithReturnTimeout adds the returnTimeout to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithReturnTimeout(returnTimeout *string) *ScheduleModifyCollectionParams {
	o.SetReturnTimeout(returnTimeout)
	return o
}

// SetReturnTimeout adds the returnTimeout to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetReturnTimeout(returnTimeout *string) {
	o.ReturnTimeout = returnTimeout
}

// WithScope adds the scope to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithScope(scope *string) *ScheduleModifyCollectionParams {
	o.SetScope(scope)
	return o
}

// SetScope adds the scope to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetScope(scope *string) {
	o.Scope = scope
}

// WithSerialRecords adds the serialRecords to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithSerialRecords(serialRecords *string) *ScheduleModifyCollectionParams {
	o.SetSerialRecords(serialRecords)
	return o
}

// SetSerialRecords adds the serialRecords to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetSerialRecords(serialRecords *string) {
	o.SerialRecords = serialRecords
}

// WithSvmName adds the svmName to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithSvmName(svmName *string) *ScheduleModifyCollectionParams {
	o.SetSvmName(svmName)
	return o
}

// SetSvmName adds the svmName to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetSvmName(svmName *string) {
	o.SvmName = svmName
}

// WithSvmUUID adds the svmUUID to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithSvmUUID(svmUUID *string) *ScheduleModifyCollectionParams {
	o.SetSvmUUID(svmUUID)
	return o
}

// SetSvmUUID adds the svmUuid to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetSvmUUID(svmUUID *string) {
	o.SvmUUID = svmUUID
}

// WithType adds the typeVar to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithType(typeVar *string) *ScheduleModifyCollectionParams {
	o.SetType(typeVar)
	return o
}

// SetType adds the type to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetType(typeVar *string) {
	o.Type = typeVar
}

// WithUUID adds the uuid to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) WithUUID(uuid *string) *ScheduleModifyCollectionParams {
	o.SetUUID(uuid)
	return o
}

// SetUUID adds the uuid to the schedule modify collection params
func (o *ScheduleModifyCollectionParams) SetUUID(uuid *string) {
	o.UUID = uuid
}

// WriteToRequest writes these params to a swagger request
func (o *ScheduleModifyCollectionParams) WriteToRequest(r runtime.ClientRequest, reg strfmt.Registry) error {

	if err := r.SetTimeout(o.timeout); err != nil {
		return err
	}
	var res []error

	if o.ClusterName != nil {

		// query param cluster.name
		var qrClusterName string

		if o.ClusterName != nil {
			qrClusterName = *o.ClusterName
		}
		qClusterName := qrClusterName
		if qClusterName != "" {

			if err := r.SetQueryParam("cluster.name", qClusterName); err != nil {
				return err
			}
		}
	}

	if o.ClusterUUID != nil {

		// query param cluster.uuid
		var qrClusterUUID string

		if o.ClusterUUID != nil {
			qrClusterUUID = *o.ClusterUUID
		}
		qClusterUUID := qrClusterUUID
		if qClusterUUID != "" {

			if err := r.SetQueryParam("cluster.uuid", qClusterUUID); err != nil {
				return err
			}
		}
	}

	if o.ContinueOnFailure != nil {

		// query param continue_on_failure
		var qrContinueOnFailure string

		if o.ContinueOnFailure != nil {
			qrContinueOnFailure = *o.ContinueOnFailure
		}
		qContinueOnFailure := qrContinueOnFailure
		if qContinueOnFailure != "" {

			if err := r.SetQueryParam("continue_on_failure", qContinueOnFailure); err != nil {
				return err
			}
		}
	}

	if o.CronDays != nil {

		// query param cron.days
		var qrCronDays string

		if o.CronDays != nil {
			qrCronDays = *o.CronDays
		}
		qCronDays := qrCronDays
		if qCronDays != "" {

			if err := r.SetQueryParam("cron.days", qCronDays); err != nil {
				return err
			}
		}
	}

	if o.CronHours != nil {

		// query param cron.hours
		var qrCronHours string

		if o.CronHours != nil {
			qrCronHours = *o.CronHours
		}
		qCronHours := qrCronHours
		if qCronHours != "" {

			if err := r.SetQueryParam("cron.hours", qCronHours); err != nil {
				return err
			}
		}
	}

	if o.CronMinutes != nil {

		// query param cron.minutes
		var qrCronMinutes string

		if o.CronMinutes != nil {
			qrCronMinutes = *o.CronMinutes
		}
		qCronMinutes := qrCronMinutes
		if qCronMinutes != "" {

			if err := r.SetQueryParam("cron.minutes", qCronMinutes); err != nil {
				return err
			}
		}
	}

	if o.CronMonths != nil {

		// query param cron.months
		var qrCronMonths string

		if o.CronMonths != nil {
			qrCronMonths = *o.CronMonths
		}
		qCronMonths := qrCronMonths
		if qCronMonths != "" {

			if err := r.SetQueryParam("cron.months", qCronMonths); err != nil {
				return err
			}
		}
	}

	if o.CronWeekdays != nil {

		// query param cron.weekdays
		var qrCronWeekdays string

		if o.CronWeekdays != nil {
			qrCronWeekdays = *o.CronWeekdays
		}
		qCronWeekdays := qrCronWeekdays
		if qCronWeekdays != "" {

			if err := r.SetQueryParam("cron.weekdays", qCronWeekdays); err != nil {
				return err
			}
		}
	}
	if err := r.SetBodyParam(o.Info); err != nil {
		return err
	}

	if o.Interval != nil {

		// query param interval
		var qrInterval string

		if o.Interval != nil {
			qrInterval = *o.Interval
		}
		qInterval := qrInterval
		if qInterval != "" {

			if err := r.SetQueryParam("interval", qInterval); err != nil {
				return err
			}
		}
	}

	if o.Name != nil {

		// query param name
		var qrName string

		if o.Name != nil {
			qrName = *o.Name
		}
		qName := qrName
		if qName != "" {

			if err := r.SetQueryParam("name", qName); err != nil {
				return err
			}
		}
	}

	if o.ReturnRecords != nil {

		// query param return_records
		var qrReturnRecords string

		if o.ReturnRecords != nil {
			qrReturnRecords = *o.ReturnRecords
		}
		qReturnRecords := qrReturnRecords
		if qReturnRecords != "" {

			if err := r.SetQueryParam("return_records", qReturnRecords); err != nil {
				return err
			}
		}
	}

	if o.ReturnTimeout != nil {

		// query param return_timeout
		var qrReturnTimeout string

		if o.ReturnTimeout != nil {
			qrReturnTimeout = *o.ReturnTimeout
		}
		qReturnTimeout := qrReturnTimeout
		if qReturnTimeout != "" {

			if err := r.SetQueryParam("return_timeout", qReturnTimeout); err != nil {
				return err
			}
		}
	}

	if o.Scope != nil {

		// query param scope
		var qrScope string

		if o.Scope != nil {
			qrScope = *o.Scope
		}
		qScope := qrScope
		if qScope != "" {

			if err := r.SetQueryParam("scope", qScope); err != nil {
				return err
			}
		}
	}

	if o.SerialRecords != nil {

		// query param serial_records
		var qrSerialRecords string

		if o.SerialRecords != nil {
			qrSerialRecords = *o.SerialRecords
		}
		qSerialRecords := qrSerialRecords
		if qSerialRecords != "" {

			if err := r.SetQueryParam("serial_records", qSerialRecords); err != nil {
				return err
			}
		}
	}

	if o.SvmName != nil {

		// query param svm.name
		var qrSvmName string

		if o.SvmName != nil {
			qrSvmName = *o.SvmName
		}
		qSvmName := qrSvmName
		if qSvmName != "" {

			if err := r.SetQueryParam("svm.name", qSvmName); err != nil {
				return err
			}
		}
	}

	if o.SvmUUID != nil {

		// query param svm.uuid
		var qrSvmUUID string

		if o.SvmUUID != nil {
			qrSvmUUID = *o.SvmUUID
		}
		qSvmUUID := qrSvmUUID
		if qSvmUUID != "" {

			if err := r.SetQueryParam("svm.uuid", qSvmUUID); err != nil {
				return err
			}
		}
	}

	if o.Type != nil {

		// query param type
		var qrType string

		if o.Type != nil {
			qrType = *o.Type
		}
		qType := qrType
		if qType != "" {

			if err := r.SetQueryParam("type", qType); err != nil {
				return err
			}
		}
	}

	if o.UUID != nil {

		// query param uuid
		var qrUUID string

		if o.UUID != nil {
			qrUUID = *o.UUID
		}
		qUUID := qrUUID
		if qUUID != "" {

			if err := r.SetQueryParam("uuid", qUUID); err != nil {
				return err
			}
		}
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}
