// Code generated by go-swagger; DO NOT EDIT.

package cluster

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"fmt"
	"io"

	"github.com/go-openapi/runtime"
	"github.com/go-openapi/strfmt"

	"github.com/vcp-vsa-control-Plane/vsa-control-plane/clients/ontap-rest/models"
)

// WebStatisticsGetReader is a Reader for the WebStatisticsGet structure.
type WebStatisticsGetReader struct {
	formats strfmt.Registry
}

// ReadResponse reads a server response into the received o.
func (o *WebStatisticsGetReader) ReadResponse(response runtime.ClientResponse, consumer runtime.Consumer) (interface{}, error) {
	switch response.Code() {
	case 200:
		result := NewWebStatisticsGetOK()
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		return result, nil
	default:
		result := NewWebStatisticsGetDefault(response.Code())
		if err := result.readResponse(response, consumer, o.formats); err != nil {
			return nil, err
		}
		if response.Code()/100 == 2 {
			return result, nil
		}
		return nil, result
	}
}

// NewWebStatisticsGetOK creates a WebStatisticsGetOK with default headers values
func NewWebStatisticsGetOK() *WebStatisticsGetOK {
	return &WebStatisticsGetOK{}
}

/*
WebStatisticsGetOK describes a response with status code 200, with default header values.

OK
*/
type WebStatisticsGetOK struct {
	Payload *models.WebStatisticsResponse
}

// IsSuccess returns true when this web statistics get o k response has a 2xx status code
func (o *WebStatisticsGetOK) IsSuccess() bool {
	return true
}

// IsRedirect returns true when this web statistics get o k response has a 3xx status code
func (o *WebStatisticsGetOK) IsRedirect() bool {
	return false
}

// IsClientError returns true when this web statistics get o k response has a 4xx status code
func (o *WebStatisticsGetOK) IsClientError() bool {
	return false
}

// IsServerError returns true when this web statistics get o k response has a 5xx status code
func (o *WebStatisticsGetOK) IsServerError() bool {
	return false
}

// IsCode returns true when this web statistics get o k response a status code equal to that given
func (o *WebStatisticsGetOK) IsCode(code int) bool {
	return code == 200
}

// Code gets the status code for the web statistics get o k response
func (o *WebStatisticsGetOK) Code() int {
	return 200
}

func (o *WebStatisticsGetOK) Error() string {
	return fmt.Sprintf("[GET /cluster/web/statistics][%d] webStatisticsGetOK  %+v", 200, o.Payload)
}

func (o *WebStatisticsGetOK) String() string {
	return fmt.Sprintf("[GET /cluster/web/statistics][%d] webStatisticsGetOK  %+v", 200, o.Payload)
}

func (o *WebStatisticsGetOK) GetPayload() *models.WebStatisticsResponse {
	return o.Payload
}

func (o *WebStatisticsGetOK) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.WebStatisticsResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}

// NewWebStatisticsGetDefault creates a WebStatisticsGetDefault with default headers values
func NewWebStatisticsGetDefault(code int) *WebStatisticsGetDefault {
	return &WebStatisticsGetDefault{
		_statusCode: code,
	}
}

/*
WebStatisticsGetDefault describes a response with status code -1, with default header values.

Error
*/
type WebStatisticsGetDefault struct {
	_statusCode int

	Payload *models.ErrorResponse
}

// IsSuccess returns true when this web statistics get default response has a 2xx status code
func (o *WebStatisticsGetDefault) IsSuccess() bool {
	return o._statusCode/100 == 2
}

// IsRedirect returns true when this web statistics get default response has a 3xx status code
func (o *WebStatisticsGetDefault) IsRedirect() bool {
	return o._statusCode/100 == 3
}

// IsClientError returns true when this web statistics get default response has a 4xx status code
func (o *WebStatisticsGetDefault) IsClientError() bool {
	return o._statusCode/100 == 4
}

// IsServerError returns true when this web statistics get default response has a 5xx status code
func (o *WebStatisticsGetDefault) IsServerError() bool {
	return o._statusCode/100 == 5
}

// IsCode returns true when this web statistics get default response a status code equal to that given
func (o *WebStatisticsGetDefault) IsCode(code int) bool {
	return o._statusCode == code
}

// Code gets the status code for the web statistics get default response
func (o *WebStatisticsGetDefault) Code() int {
	return o._statusCode
}

func (o *WebStatisticsGetDefault) Error() string {
	return fmt.Sprintf("[GET /cluster/web/statistics][%d] web_statistics_get default  %+v", o._statusCode, o.Payload)
}

func (o *WebStatisticsGetDefault) String() string {
	return fmt.Sprintf("[GET /cluster/web/statistics][%d] web_statistics_get default  %+v", o._statusCode, o.Payload)
}

func (o *WebStatisticsGetDefault) GetPayload() *models.ErrorResponse {
	return o.Payload
}

func (o *WebStatisticsGetDefault) readResponse(response runtime.ClientResponse, consumer runtime.Consumer, formats strfmt.Registry) error {

	o.Payload = new(models.ErrorResponse)

	// response payload
	if err := consumer.Consume(response.Body(), o.Payload); err != nil && err != io.EOF {
		return err
	}

	return nil
}
