# OCI environment overrides: tenancy, compartment, region, OCIR, DB, custom images.
# Merge with defaults:
#   helm upgrade --install vcp-worker . -n <ns> -f values.yaml -f overrides.yaml

global:
  primaryImageRegistry: iad.ocir.io
  primaryImageRegistryPath: "nmobsa"

workerConfig:
  localRegion: "us-ashburn-1"
  database:
    host: primary.kce5jry3ybj7h5x2ddd5iymauq6vqq.postgresql.us-ashburn-1.oci.oraclecloud.com
  vsaMediatorImageName: "ocid1.image.oc1.iad.aaaaaaaagakcrtyceuuvl6ts7xhqzzrdk3lv4z7tcqif3xpa6qsvppzflaaq"
  vsaImageName: "ocid1.image.oc1.iad.aaaaaaaaef2bc4g6vf4rvsa4vd2e4pnqw2ot2qicxrjo5a3ohglr6i4exdjq"
  ociVaultOcid: "ocid1.vault.oc1.iad.ejuz5r2maafbg.abuwcljrjk75nldjm3s3q32eev46ohilpvpm2xtkgodnxmqewnpo72u26anq"
  ociMasterKeyOcid: "ocid1.key.oc1.iad.ejuz5r2maafbg.abuwcljtjvrlh4wyvjklfteb6sh3cqx7fz3ftgytfznipl7njhikrr6ltl7q"
  ociCompartmentOcid: "ocid1.compartment.oc1..aaaaaaaapat5pvypcyr7xjb33om5j6howstzg2wfztjhbrlxcf2pz2wfen6a"
  #secretUri: "REPLACE_WITH_VAULT_SECRET_OCID"

# Image configuration (OCIR)
images:
  vcpWorker:
    name: test-vcp-worker
    tag: "01042026_02"
    digest: ""
