apiVersion: v1
name: vsa-harvest-otel
description: A Helm chart for deploying Harvest Pollers to GCNV Clusters
home: https://github.com/VCP-VSA-control-Plane/vsa-control-plane
version: "0.0.0"
appVersion: "v0.0.0"
deprecated: false
maintainers:
  - name: "harvest-otel-team"
annotations:
  gcp-component: "true"