global:
  primaryImageRegistry: us-docker.pkg.dev
  primaryImageRegistryPath: gcnv-artifact-registry-nonprod
  primaryImageRegistryPasswordAuth: false
  primaryImagePullSecretName: ""
  secondaryImageRegistry: us-docker.pkg.dev
  secondaryImageRegistryPath: gcnv-artifact-registry-nonprod
  secondaryImageRegistryPasswordAuth: false
  secondaryImagePullSecretName: ""
  imageDigestTags: false
  namespace: "vcp"
configMap:
  create: true

horizontalPodAutoscaling:
  enable: false

images:
  pm2:
    name: vcp-container-images-us/harvest-multi
    tag: 25.09.19-1
    digest: ""
    secondary: false
    primary: true
    pullPolicy: IfNotPresent
  otel:
    name: vcp-open-telemetry-images/opentelemetry-collector-contrib
    tag: 0.118.0
    digest: 'sha256:83ff24727f615c39056d954dd3a5d4ef227a5a9fe2c234a4489199e4351f0ab5'
    secondary: true
    pullPolicy: IfNotPresent

persistentVolumes:
  persistentVolumeBucket: harvest-farm-pv-au-se1
  storage: 25Gi

otel:
  project: "netapp-au-se1-autopush-sde-tst"
  command:
    name: otelcol-contrib
    extraArgs: []
  presets:
    logsCollection:
      enabled: false
      includeCollectorLogs: false
      storeCheckpoints: false

    hostMetrics:
      enabled: false

    kubernetesAttributes:
      enabled: false

    kubernetesEvents:
      enabled: false

    clusterMetrics:
      enabled: false

    kubeletMetrics:
      enabled: false
  secondImageRegistry: ""
  secondImageRegistryPath: ""
  secondImageRegistryPasswordAuth: false

containers:
  harvest: "harvest-pm2"
  otel: "otel-collector"

replicaCount: 2

mode: deployment

harvestConfig:
  enableVolumeOnline: "false"
  enableVolumeMetrics: "false"
  enableBackupMetrics: "false"
  enableBackupBillingMetrics: "false"
  enableReplicationMetrics: "false"
  coreApiBaseUrl: "core-service.vcp.svc.cluster.local"
  coreApiPort: "8080"
  coreApiBatchSize: "1000"
  sendingQueueEnabled: true

lifecycleHooks: {}

nameOverride: ""

fullnameOverride: ""

imagePullPolicy: IfNotPresent

serviceAccount:
  create: true
  automount: true
  gcpServiceAccount: otel-collector-sa@netapp-au-se1-autopush-sde-tst.iam.gserviceaccount.com
  name: "gcnv-harvest-sa"

stackdriverAdapter:
  gcp:
    serviceAccount: custom-metrics-reader@netapp-au-se1-autopush-sde-tst.iam.gserviceaccount.com

secretManager:
  enable: false
  apiVersion: external-secrets.io/v1beta1
  clusterSecretStoreName: "main-cluster-secret-store"
  refreshInterval: "5m"
  registryCredentials: "cvs-autopush-tst-au-se1-registry"

ports:
  otlp:
    enabled: true
    containerPort: 4317
    servicePort: 4317
    hostPort: 4317
    protocol: TCP
  otlp-http:
    enabled: true
    containerPort: 4318
    servicePort: 4318
    hostPort: 4318
    protocol: TCP
  otlp-lb:
    enabled: true
    containerPort: 55681
    servicePort: 55681
    hostPort: 55681
    protocol: TCP
  metrics:
    enabled: true
    containerPort: 8888
    servicePort: 8888
    protocol: TCP

resources:
  requests:
    cpu: 250m
    memory: 1024Mi
  limits:
    cpu: 250m
    memory: 1024Mi

service:
  name: vsa-harvest-farm-service
  type: ClusterIP
  port: 80
  targetPort: 3000
  protocol: TCP
