name: Main Workflow
on:
  push:
    branches:
      - main
  pull_request:
    types: [opened, edited, synchronize]

permissions:
  contents: read
  packages: read
  actions: read

concurrency:
  group: ${{ github.head_ref || github.run_id }}
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version: '1.24.1'

      - name: Configure Git for private modules
        run: |
          git config --global url."https://${{ secrets.GHVSA_PAT }}@github.com/".insteadOf "https://github.com/"

      - name: Install dependencies
        run: go mod tidy

      - name: Cache Go modules
        uses: actions/cache/save@v4
        with:
          path: |
            ~/go/pkg/mod
            ~/.cache/go-build
          key: ${{ runner.os }}-go-${{ hashFiles('**/go.sum') }}

  common:
    runs-on: [ ubuntu-22.04 ]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsacictl:v4
      options: -v /var/run/docker.sock:/var/run/docker.sock --user root

    steps:

      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Fetch token
        uses: actions/create-github-app-token@v1
        id: token
        with:
          owner: ${{ github.repository_owner }}
          app-id: ${{ secrets.VCP_CI_GH_APP_ID }}
          private-key: ${{ secrets.VCP_CI_GH_PRIVATE_KEY }}
          repositories: |
            vsa-control-plane

      - name: Run Jira allow_merge main
        env:
          PR_TITLE: ${{ github.event.pull_request.title }}
          JIRA_API_TOKEN: ${{ secrets.VCP_CI_JIRA_BOT_PAT }}
          GITHUB_TOKEN: ${{ steps.token.outputs.token }}
          PR_USER: ${{ github.event.pull_request.user.login }}
        run: vsacictl jira allow_merge main

  unit_tests:
      runs-on: [ self-hosted,linux ]
      container:
        image: ghcr.io/vcp-vsa-control-plane/vsacictl:v8
        options: --user root

      steps:
        - name: Checkout code
          uses: actions/checkout@v2

        - name: Set up Go
          uses: actions/setup-go@v3
          with:
            go-version-file: go.mod

        - name: Run golang unit tests
          run: vsacictl unit-test

  coverage:
    needs: unit_tests
    runs-on: [ self-hosted,linux ]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsacictl:v8
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Run golang coverage
        env:
          COVERAGE_THRESHOLD: 90
        run: vsacictl unit-test --coverage --filtered

  verify_generated:
    name: Verify Generated
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Verify generated ONTAP Rest client code
        run: |
          # Get the PR branch name
          PR_BRANCH=$(echo $GITHUB_HEAD_REF)
          echo "Pull request branch: $PR_BRANCH"

          # Fetch the PR branch
          git fetch origin $PR_BRANCH

          # Switch to the PR branch
          git checkout $PR_BRANCH

          # Verify ontap rest client code
          cd ./scripts
          ./verify-ontap.sh

  lint:
    runs-on: [self-hosted,linux]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsacictl:v8
      options: --user root

    steps:
      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Run golangci-lint script
        run: vsacictl lint