name: Final Tagging Workflow
on:
  workflow_dispatch:

jobs:
  final_tagging:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: [ self-hosted ,linux ]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsacictl:v28
      options: --user root

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: vcpghsa
          password: ${{ secrets.GHVSA_PAT }}

      - name: Log in to GitHub Container Registry
        uses: docker/login-action@v3
        with:
          registry: ghcr.io
          username: vcpghsa
          password: ${{ secrets.GHVSA_PAT }}

      - name: Run Promotional logic
        id: promotional_logic_binary
        run: |
          git config --global user.name "vcpghsa"
          git config --global user.email "vcpghsa@netapp.com"
          vsacictl tag promotional
        env:
          GH_PAT: ${{ secrets.GHVSA_PAT }}
          GITHUB_OUTPUT: $GITHUB_ENV

      - name: Output printout
        run: |
          echo "FINAL_TAG=${{ steps.promotional_logic_binary.outputs.FINAL_TAG }}"

    outputs:
      finalTag: ${{ steps.promotional_logic_binary.outputs.FINAL_TAG }}
      finalBranch: ${{ steps.promotional_logic_binary.outputs.FINAL_BRANCH }}

  create_release_vsa_promotional:
    needs: final_tagging
    uses: ./.github/workflows/build_common.yaml
    secrets: inherit
    with:
      pre_release: false
      tag: ${{ needs.final_tagging.outputs.finalTag }}
      component_update: false
      pr_base_branch: ${{ needs.final_tagging.outputs.finalBranch }}