name: Build and Publish Images, Charts and Release

on:
  workflow_call:
    inputs:
      tag:
        description: "Tag to use for building and publishing images and charts and release"
        required: true
        type: string

    secrets:
      GHVSA_PAT:
        required: true
      AR_GCP_PROJ_NUM:
        required: true
      AR_WLI_POOL:
        required: true
      AR_WLI_PROV:
        required: true
      AR_GCP_SA:
        required: true
      AR_GCP_PROJ:
        required: true
      AR_GCP_REGION:
        required: true
      AR_PRIVATE_KEY:
        required: true
      GHCR_REPO:
        required: true
      AR_GCP_REPO:
        required: true
      AR_ATTESTOR_NAME:
        required: true
      AR_HELM_REPO:
        required: true

jobs:
  build_and_publish:
    name: Build and Publish Docker Images
    runs-on: [self-hosted, linux]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsacictl:v15
      options: --user root
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Build images
        env:
          IMAGES_TAG: ${{ inputs.tag }}
          GHVSA_PAT: ${{ secrets.GHVSA_PAT }}
        run: |
          skaffold config set default-repo ""
          skaffold build 
          make vcp-db-migrate-image imageVersion=${{ inputs.tag }}

      - name: Check if digest exists in the gcloud or not
        shell: bash -e {0}
        run: |
          ALL_DIGESTS_EXIST=1
          IMAGES=("core" "google-proxy" "vcp-db-migrate" "vcp-worker")
          for IMAGE in "${IMAGES[@]}"; do
              gcpDigest=$(docker inspect "$IMAGE:${{ inputs.tag }}" | jq -r '.[] | .RepoDigests[] | select(contains("-docker.pkg.dev"))')
              echo "gcp digest is $gcpDigest"
              if [[ -n "$gcpDigest" ]]; then
               echo "Digest for image ${IMAGE} exists in Google Artifact Registry."
               echo "${IMAGE}_DIGEST_EXISTS=1" >> $GITHUB_ENV 
              else
                echo "Digest for image ${IMAGE} does not exist in Google Artifact Registry."
                echo "${IMAGE}_DIGEST_EXISTS=0" >> $GITHUB_ENV 
                ALL_DIGESTS_EXIST=0
              fi
          done
          echo "ALL_DIGESTS_EXIST=$ALL_DIGESTS_EXIST" >> $GITHUB_ENV             


      - name: Log in to the Container registry
        run: |
          echo "${{ secrets.GHVSA_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Trim OIDC Requester ENVs
        uses: actions/github-script@v7
        id: script
        timeout-minutes: 10
        with:
          script: |
            const token = process.env['ACTIONS_RUNTIME_TOKEN']
            const runtimeUrl = process.env['ACTIONS_ID_TOKEN_REQUEST_URL']
            core.setOutput('TOKEN', token.trim())
            core.setOutput('IDTOKENURL', runtimeUrl.trim())

      - name: Get Github OIDC Token
        id: tokenid
        shell: bash
        run: |
          IDTOKEN=$(curl -H "Authorization: Bearer ${{steps.script.outputs.TOKEN}}" ${{steps.script.outputs.IDTOKENURL}}  -H "Accept: application/json; api-version=2.0" -H "Content-Type: application/json" -d "{}" | jq -r '.value')
          jwtd() {
              if [[ -x $(command -v jq) ]]; then
                  jq -R 'split(".") | .[0],.[1] | @base64d | fromjson' <<< "${1}"
                  echo "Signature: $(echo "${1}" | awk -F'.' '{print $3}')"
              fi
          }
          echo "idToken=${IDTOKEN}" >> $GITHUB_OUTPUT


      - name: Authenticate to gcloud
        run: |
          echo "${{ steps.tokenid.outputs.idToken }}" > /tmp/github-token.txt
          gcloud iam workload-identity-pools create-cred-config "projects/${{secrets.AR_GCP_PROJ_NUM}}/locations/global/workloadIdentityPools/${{secrets.AR_WLI_POOL}}/providers/${{secrets.AR_WLI_PROV}}" \
            --service-account="${{secrets.AR_GCP_SA}}@${{ secrets.AR_GCP_PROJ }}.iam.gserviceaccount.com" \
            --output-file="/tmp/gcloud-creds.json" \
            --credential-source-file="/tmp/github-token.txt"
          gcloud auth login --cred-file="/tmp/gcloud-creds.json" --quiet

      - name: Configure Docker
        run: |
          gcloud config set project ${{ secrets.AR_GCP_PROJ }} --quiet
          gcloud auth configure-docker ${{secrets.AR_GCP_REGION}}-docker.pkg.dev --quiet
          gcloud secrets versions access latest --secret="${{secrets.AR_PRIVATE_KEY}}" > /tmp/ec_private.pem

      - name: Push images
        env:
          GCP_PROJECT: ${{ secrets.AR_GCP_PROJ }}
          GHCR_REPO: ${{ secrets.GHCR_REPO }}
          GCP_REPO: ${{ secrets.AR_GCP_REPO }}
          IMAGES_TAG: ${{ inputs.tag }}
          GCP_REGION: ${{ secrets.AR_GCP_REGION }}
        run: vsacictl images push

      - name: Get image digest via GitHub API
        id: get-digest
        run: |
          repo="${1:-VCP-VSA-control-Plane/vsa-control-plane}"  
          token=$(curl -s "https://ghcr.io/token?service=ghcr.io&scope=repository:${repo}:pull" \
          -u "${{github.actor}}:${{secrets.GHVSA_PAT}}") 
          
          token_value=$(echo "$token" | jq -r '.token')
          
          IMAGES=("core" "google-proxy" "vcp-db-migrate" "vcp-worker")
          for IMAGE in "${IMAGES[@]}"; do
            digest=$(curl -s -H "Authorization: Bearer $token_value" \
            -H "Accept: application/vnd.oci.image.manifest.v1+json" \
            https://ghcr.io/v2/VCP-VSA-control-Plane/${IMAGE}/manifests/${{ inputs.tag }} | jq -r '.config.digest')
            echo "${IMAGE}-digest=$digest" >> $GITHUB_ENV
          done
        shell: bash -e {0}

      - name: Sign the GHCR Image using cosign
        run: |
          gcloud secrets versions access latest --secret="${{vars.GH_COSIGN_PUB_KEY}}" > /tmp/cosign.pub
          gcloud secrets versions access latest --secret="${{vars.GH_COSIGN_PVT_KEY}}" > /tmp/cosign.key
          IMAGES=("core" "google-proxy" "vcp-db-migrate" "vcp-worker")
          for IMAGE in "${IMAGES[@]}"; do
            digest=$(printenv "${IMAGE}-digest")
            COSIGN_PASSWORD="" cosign sign --key /tmp/cosign.key  ghcr.io/vcp-vsa-control-plane/${IMAGE}@$digest --tlog-upload=false
            cosign verify --key /tmp/cosign.pub  ghcr.io/vcp-vsa-control-plane/${IMAGE}@$digest --insecure-ignore-tlog=true
          done
        shell: bash -e {0}
      - name: Access Private Key
        if: ${{ env.ALL_DIGESTS_EXIST == '0' }}
        run: |
          gcloud secrets versions access latest --secret="${{secrets.AR_PRIVATE_KEY}}" > /tmp/ec_private.pem

      - name: Retrieve Public Key ID
        if: ${{ env.ALL_DIGESTS_EXIST == '0' }}
        id: retrieve_public_key_id
        run: |
          PUBLIC_KEY_ID=$(gcloud container binauthz attestors describe ${{secrets.AR_ATTESTOR_NAME}} --format='value(userOwnedGrafeasNote.publicKeys[0].id)')
          echo "PUBLIC_KEY_ID=${PUBLIC_KEY_ID}" >> $GITHUB_ENV

      - name: Generate Artifact URLs
        if: ${{ env.ALL_DIGESTS_EXIST == '0' }}
        id: generate_artifact_urls
        shell: bash -e {0}
        run: |
          IMAGES=("core" "google-proxy" "vcp-db-migrate" "vcp-worker")
          for IMAGE in "${IMAGES[@]}"; do
            ARTIFACT_URL=$(gcloud artifacts docker images list ${{secrets.AR_GCP_REGION}}-docker.pkg.dev/${{secrets.AR_GCP_PROJ}}/${{secrets.AR_GCP_REPO}}/${IMAGE} \
            --include-tags \
            --format="value(DIGEST)" \
            --filter="TAGS:${{ inputs.tag }}" | awk '{print "${{secrets.AR_GCP_REGION}}-docker.pkg.dev/${{secrets.AR_GCP_PROJ}}/${{secrets.AR_GCP_REPO}}/'${IMAGE}'@" $1}')
            echo "${IMAGE}_ARTIFACT_URL=${ARTIFACT_URL}" >> $GITHUB_ENV
          done

      - name: Generate and Sign Payloads
        if: ${{ env.ALL_DIGESTS_EXIST == '0' }}
        shell: bash -e {0}
        run: |
          IMAGES=("core" "google-proxy" "vcp-db-migrate" "vcp-worker")
          for IMAGE in "${IMAGES[@]}"; do
            ARTIFACT_URL=$(printenv "${IMAGE}_ARTIFACT_URL")
            gcloud container binauthz create-signature-payload \
            --artifact-url=${ARTIFACT_URL} > /tmp/${IMAGE}_payload.json
            openssl dgst -sha256 -sign /tmp/ec_private.pem /tmp/${IMAGE}_payload.json > /tmp/${IMAGE}_signature
          done

      - name: Create Attestations
        if: ${{ env.ALL_DIGESTS_EXIST == '0' }}
        shell: bash -e {0}
        run: |
          IMAGES=("core" "google-proxy" "vcp-db-migrate" "vcp-worker")
          for IMAGE in "${IMAGES[@]}"; do
            if [[ "$(printenv "${IMAGE}_DIGEST_EXISTS")" == "0" ]]; then
              ARTIFACT_URL=$(printenv "${IMAGE}_ARTIFACT_URL")
              gcloud container binauthz attestations create \
              --project="${{secrets.AR_GCP_PROJ}}" \
              --artifact-url="${ARTIFACT_URL}" \
              --attestor="projects/${{secrets.AR_GCP_PROJ}}/attestors/${{secrets.AR_ATTESTOR_NAME}}" \
              --signature-file=/tmp/${IMAGE}_signature \
              --public-key-id="${{ env.PUBLIC_KEY_ID }}" \
              --validate
              echo "Attestation created for image ${IMAGE}."
            else
              echo "Signed Digest for image ${IMAGE} already exists in Google Artifact Registry. Skipping attestation."
            fi
          done

      - name: Helm Login to Artifact Registry
        run: |
          gcloud auth print-access-token | helm registry login -u oauth2accesstoken --password-stdin https://${{secrets.AR_GCP_REGION}}-docker.pkg.dev
          helm registry login ghcr.io -u ${{github.actor}} --password ${{ secrets.GHVSA_PAT }}

      - name: Update Versions of helm charts
        run: |
          ./.github/scripts/updateHelmVersion.sh ${{ inputs.tag }}

      - name: Package Helm Charts
        run: |
          helm package kubernetes/vsa-control-plane --destination ./helm-packages
          helm package kubernetes/vcp-worker --destination ./helm-packages

      - name: Push Helm Charts to GHCR
        run: |
          for CHART in ./helm-packages/*.tgz; do
            helm push $CHART oci://ghcr.io/vcp-vsa-control-plane
          done

      - name: Push Helm Charts to Artifact Registry
        run: |
          for CHART in ./helm-packages/*.tgz; do
            helm push $CHART oci://${{ secrets.AR_GCP_REGION }}-docker.pkg.dev/${{ secrets.AR_GCP_PROJ }}/${{secrets.AR_HELM_REPO}}
          done

      - name: Create a release
        run: gh release create -R https://github.com/${{ github.repository }} --generate-notes --prerelease ${{ inputs.tag }}
        env:
          GH_TOKEN: ${{ secrets.GHVSA_PAT }}
          GITHUB_REPOSITORY: ${{ github.event.repository.name }}
          newTag: ${{ inputs.tag }}

      - name: Generate output urls
        shell: bash -e {0}
        id: generate_output_urls
        run: |
          IMAGES=("core" "google-proxy" "vcp-db-migrate" "vcp-worker")
          for IMAGE in "${IMAGES[@]}"; do
            echo "GHCR_${IMAGE}_URL=ghcr.io/vcp-vsa-control-plane/${IMAGE}:${{ inputs.tag }}" >> $GITHUB_ENV
            echo "GCP_${IMAGE}_URL=${{secrets.AR_GCP_REGION}}-docker.pkg.dev/${{secrets.AR_GCP_PROJ}}/${{secrets.AR_GCP_REPO}}/${IMAGE}:${{ inputs.tag }}" >> $GITHUB_ENV
          done
          CHARTS=("vsa-control-plane" "vcp-worker")
          for CHART in "${CHARTS[@]}"; do
            echo "GHCR_${CHART}_HELM_URL=oci://ghcr.io/vcp-vsa-control-plane/${CHART}:${{ inputs.tag }}" >> $GITHUB_ENV
            echo "GCP_${CHART}_HELM_URL=oci://${{secrets.AR_GCP_REGION}}-docker.pkg.dev/${{secrets.AR_GCP_PROJ}}/${{secrets.AR_HELM_REPO}}/${CHART}:${{ inputs.tag }}" >> $GITHUB_ENV
          done
    outputs:
      GHCR_core_URL: ${{ steps.generate_output_urls.outputs.GHCR_core_URL }}
      GCP_core_URL: ${{ steps.generate_output_urls.outputs.GCP_core_URL }}
      GHCR_google-proxy_URL: ${{ steps.generate_output_urls.outputs.GHCR_google-proxy_URL }}
      GCP_google-proxy_URL: ${{ steps.generate_output_urls.outputs.GCP_google-proxy_URL }}
      GHCR_vcp-db-migrate_URL: ${{ steps.generate_output_urls.outputs.GHCR_vcp-db-migrate_URL }}
      GCP_vcp-db-migrate_URL: ${{ steps.generate_output_urls.outputs.GCP_vcp-db-migrate_URL }}
      GHCR_vcp-worker_URL: ${{ steps.generate_output_urls.outputs.GHCR_vcp-worker_URL }}
      GCP_vcp-worker_URL: ${{ steps.generate_output_urls.outputs.GCP_vcp-worker_URL }}
      GHCR_vsa-control-plane_HELM_URL: ${{ steps.generate_output_urls.outputs.GHCR_vsa-control-plane_HELM_URL }}
      GCP_vsa-control-plane_HELM_URL: ${{ steps.generate_output_urls.outputs.GCP_vsa-control-plane_HELM_URL }}
      GHCR_vcp-worker_HELM_URL: ${{ steps.generate_output_urls.outputs.GHCR_vcp-worker_HELM_URL }}
      GCP_vcp-worker_HELM_URL: ${{ steps.generate_output_urls.outputs.GCP_vcp-worker_HELM_URL }}
