name: Create Pre-Release and Publish Docker images

on:
  push:
    branches:
      - main
      - release/2*


permissions:
  packages: write
  contents: read
  id-token: write
  security-events: write


jobs:
  generate_tag:
    name: Generate Tag
    runs-on: [self-hosted,linux]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsacictl:v22
      options: --user root
    permissions:
      contents: read
      packages: write
      id-token: write

    steps:
      - name: Check out the repo
        uses: actions/checkout@v2

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Fetch PR user and details
        id: fetch_pr_user_and_details
        run: |
          PR_DETAILS=$(curl -sf -H "Authorization: Bearer ${{ secrets.GHVSA_PAT }}" \
          -H "Accept: application/vnd.github+json" \
            "https://api.github.com/repos/VCP-VSA-control-Plane/vsa-control-plane/commits/${{ github.sha }}/pulls")
          echo "PR_DETAILS FETCHED"
          
            # Check if the curl command succeeded
            if [[ $? -ne 0 || -z "$PR_DETAILS" ]]; then
          echo "Error: Failed to fetch PR details or response is empty."
            exit 1
            fi
          
            # Parse the first PR object
            PR_DETAILS=$(echo "$PR_DETAILS" | tr -d '\000-\037' | jq '.[0]')
          
            # Validate the parsed JSON
            if [[ "$PR_DETAILS" == "null" || -z "$PR_DETAILS" ]]; then
          echo "Error: No pull request found for the given commit."
            exit 1
            fi
          
            # Extract PR user and title
            PR_USER=$(echo "$PR_DETAILS" | jq -r '.user.login // empty')
            PR_TITLE=$(echo "$PR_DETAILS" | jq -r '.title // empty')
            PR_BRANCH=$(echo "$PR_DETAILS" | jq -r '.base.ref // empty')
          
            # Validate extracted values
            if [[ -z "$PR_USER" || -z "$PR_TITLE" || -z "$PR_BRANCH" ]]; then
              echo "Error: PR user, title, or branch is empty."
              exit 1
            fi
          
            # Write to GITHUB_ENV
            echo "PR_USER=$PR_USER" >> $GITHUB_ENV
            echo "PR_TITLE=$PR_TITLE" >> $GITHUB_ENV
            echo "PR_BRANCH=$PR_BRANCH" >> $GITHUB_ENV
        shell: bash
        env:
          GITHUB_TOKEN: ${{ secrets.GHVSA_PAT }}

      - name: Fetch new tag
        id: fetch_new_tag
        run: |
          echo "PR_BASE_BRANCH:" ${{ env.PR_BRANCH}}
          echo "newTag=$(go run .github/scripts/fetchLatestBuild.go 2>&1)" >> $GITHUB_OUTPUT
        env:
          GITHUB_BASE: ${{ env.PR_BRANCH}}

    outputs:
      newTag: ${{ steps.fetch_new_tag.outputs.newTag }}
      pr_user: ${{ env.PR_USER }}
      pr_title: ${{ env.PR_TITLE }}
      pr_base_branch: ${{ env.PR_BRANCH }}


  create_pre_release_vsa_control_plane:
    needs: generate_tag
    uses: ./.github/workflows/build_common.yaml
    secrets: inherit
    with:
      pre_release: true
      tag: ${{ needs.generate_tag.outputs.newTag }}
      pr_user: ${{ needs.generate_tag.outputs.pr_user }}
      pr_title: ${{ needs.generate_tag.outputs.pr_title }}
      pr_base_branch: ${{ needs.generate_tag.outputs.pr_base_branch }}
      component_update: true