name: Release Workflow

on:
  schedule:
    - cron: '30 2 * * 5'

jobs:
  release_branch:
    permissions:
      contents: write
      actions: read
      packages: write

    runs-on: [ self-hosted,linux ]
    container:
      image: ghcr.io/vcp-vsa-control-plane/vsacictl:v9
      options: --user root

    steps:
      - name: Checkout codes
        uses: actions/checkout@v2
        with:
          token: ${{ secrets.GHVSA_PAT }}

      - name: Set up Go
        uses: actions/setup-go@v3
        with:
          go-version-file: go.mod

      - name: Configure Git
        run: |
          USERNAME=${{ github.actor }}
          echo "Fetching email for $USERNAME"
          EMAIL=$(curl -s -H "Authorization: token ${{ secrets.GHVSA_PAT }}" https://api.github.com/users/$USERNAME | jq -r '.email')
          if [ "$EMAIL" == "null" ]; then
            EMAIL="$USERNAME@users.noreply.github.com"
          fi
          echo "Using email: $EMAIL"
          echo "Using username: $USERNAME"
          git config --global user.email "$EMAIL"
          git config --global user.name "$USERNAME"

      - name: Run release logic
        id: release_logic_binary
        run: vsacictl tag release
        env:
          GH_PAT: ${{ secrets.GHVSA_PAT }}

      - name: Log in to the Container registry
        run: |
          echo "${{ secrets.GHVSA_PAT }}" | docker login ghcr.io -u "${{ github.actor }}" --password-stdin

      - name: Build and push RC Docker images
        run: skaffold build --filename=.github/scripts/skaffold_ci.yaml -t ${{ steps.promotional_logic_binary.outputs.RC_TAG }}

      - name: Build and push Dev Docker images
        run: skaffold build --filename=.github/scripts/skaffold_ci.yaml -t ${{ steps.promotional_logic_binary.outputs.DEV_TAG }}
