// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"strconv"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// UpdateDstWithSrcQuotaRulesV1beta UpdateDstQuotaRulesWithSrc
//
// # Update the destination volume's quota rules with the source volume's quota rules
//
// swagger:model UpdateDstWithSrcQuotaRules_v1beta
type UpdateDstWithSrcQuotaRulesV1beta struct {

	// dstQuotaRules
	// Required: true
	DstQuotaRules []*QuotaRulesV1beta `json:"dstQuotaRules"`

	// srcQuotaRules
	// Required: true
	SrcQuotaRules []*QuotaRulesV1beta `json:"srcQuotaRules"`
}

// Validate validates this update dst with src quota rules v1beta
func (m *UpdateDstWithSrcQuotaRulesV1beta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateDstQuotaRules(formats); err != nil {
		res = append(res, err)
	}

	if err := m.validateSrcQuotaRules(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *UpdateDstWithSrcQuotaRulesV1beta) validateDstQuotaRules(formats strfmt.Registry) error {

	if err := validate.Required("dstQuotaRules", "body", m.DstQuotaRules); err != nil {
		return err
	}

	for i := 0; i < len(m.DstQuotaRules); i++ {
		if swag.IsZero(m.DstQuotaRules[i]) { // not required
			continue
		}

		if m.DstQuotaRules[i] != nil {
			if err := m.DstQuotaRules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("dstQuotaRules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

func (m *UpdateDstWithSrcQuotaRulesV1beta) validateSrcQuotaRules(formats strfmt.Registry) error {

	if err := validate.Required("srcQuotaRules", "body", m.SrcQuotaRules); err != nil {
		return err
	}

	for i := 0; i < len(m.SrcQuotaRules); i++ {
		if swag.IsZero(m.SrcQuotaRules[i]) { // not required
			continue
		}

		if m.SrcQuotaRules[i] != nil {
			if err := m.SrcQuotaRules[i].Validate(formats); err != nil {
				if ve, ok := err.(*errors.Validation); ok {
					return ve.ValidateName("srcQuotaRules" + "." + strconv.Itoa(i))
				}
				return err
			}
		}

	}

	return nil
}

// MarshalBinary interface implementation
func (m *UpdateDstWithSrcQuotaRulesV1beta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *UpdateDstWithSrcQuotaRulesV1beta) UnmarshalBinary(b []byte) error {
	var res UpdateDstWithSrcQuotaRulesV1beta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
