// Code generated by go-swagger; DO NOT EDIT.

package models

// This file was generated by the swagger tool.
// Editing this file might prove futile when you re-run the swagger generate command

import (
	"context"

	"github.com/go-openapi/errors"
	"github.com/go-openapi/strfmt"
	"github.com/go-openapi/swag"
	"github.com/go-openapi/validate"
)

// VolumeIDV1beta VolumeId
//
// # A required string describing a volume ID
//
// swagger:model VolumeId_v1beta
type VolumeIDV1beta struct {

	// UUID v4 of the volume
	// Example: 9760acf5-4638-11e7-9bdb-020073ca0001
	// Required: true
	// Max Length: 36
	// Min Length: 36
	// Pattern: ^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$
	VolumeID *string `json:"volumeId"`
}

// Validate validates this volume Id v1beta
func (m *VolumeIDV1beta) Validate(formats strfmt.Registry) error {
	var res []error

	if err := m.validateVolumeID(formats); err != nil {
		res = append(res, err)
	}

	if len(res) > 0 {
		return errors.CompositeValidationError(res...)
	}
	return nil
}

func (m *VolumeIDV1beta) validateVolumeID(formats strfmt.Registry) error {

	if err := validate.Required("volumeId", "body", m.VolumeID); err != nil {
		return err
	}

	if err := validate.MinLength("volumeId", "body", *m.VolumeID, 36); err != nil {
		return err
	}

	if err := validate.MaxLength("volumeId", "body", *m.VolumeID, 36); err != nil {
		return err
	}

	if err := validate.Pattern("volumeId", "body", *m.VolumeID, `^[a-fA-F0-9]{8}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{4}-[a-fA-F0-9]{12}$`); err != nil {
		return err
	}

	return nil
}

// ContextValidate validates this volume Id v1beta based on context it is used
func (m *VolumeIDV1beta) ContextValidate(ctx context.Context, formats strfmt.Registry) error {
	return nil
}

// MarshalBinary interface implementation
func (m *VolumeIDV1beta) MarshalBinary() ([]byte, error) {
	if m == nil {
		return nil, nil
	}
	return swag.WriteJSON(m)
}

// UnmarshalBinary interface implementation
func (m *VolumeIDV1beta) UnmarshalBinary(b []byte) error {
	var res VolumeIDV1beta
	if err := swag.ReadJSON(b, &res); err != nil {
		return err
	}
	*m = res
	return nil
}
